force-app/main/default/staticresources/python/Disappear/src/objects/AmgenProduct__c.object
<CustomObject>
    <fields>
        <fullName>Molecule_Name__c</fullName>
        <description>REF_NUMBER_1</description>
        <label>Molecule Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ODS_DrugId__c</fullName>
        <description>NUM_OCCURRENCE</description>
        <label>Drug Id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Old_ProductName__c</fullName>
        <label>Old Product Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Description__c</fullName>
        <label>Product Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SiebelRowId__c</fullName>
        <externalId>true</externalId>
        <label>Siebel RowId</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isEnbrel__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Defect 33 - IFPRC is able to see Enbrel related Pubs</description>
        <label>isEnbrel</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isLogicallyDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>CONFIGURATION_FLG</description>
        <label>Expired</label>
        <type>Checkbox</type>
    </fields>
    <label>Amgen Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/AmgenProductModel.cls
public class AmgenProductModel {

	public static Map<id,AmgenProduct__c> getProductById(set<id> productIds) {
		
		Map<id,AmgenProduct__c> result = new Map<id,AmgenProduct__c> ();
		for(Id productId : productIds) {
			if (AmgenProductMap.containsKey(productId)) {
				result.put(productId, AmgenProductMap.get(productId));
			}
		}
		return result;
	}


	public static AmgenProduct__c getProductByName(string productName) {
		if ( AmgenProductMapByName.containsKey(productName)) {
			return AmgenProductMapByName.get(productName);
		} else {
			AppLogModel.LogError('AmgenProductModel::getProductByName', 'Cannot find product : '+productName);  //cannot add PubId to this log message
			return null;
		}
	}
	
	private static List<AmgenProduct__c> pAllProducts = null;
	public static List<AmgenProduct__c> AllProducts {
		get {
			if (pAllProducts == null ){
				pAllProducts = getAllAmgenProducts();
			}
			return pAllProducts;
		}
	}
	
	private static List<string> pAllProductNames = null;
	public static List<string> AllProductNames {
		get {
			if (pAllProductNames ==null){
				pAllProductNames = new List<string>();
				for(AmgenProduct__c prod : AllProducts) {
					pAllProductNames.add(prod.Name);
				}
			}
			return pAllProductNames;
		}
		
	}
	
	private static Map<id,AmgenProduct__c> pAmgenProductMap = null;
	public static Map<id,AmgenProduct__c> AmgenProductMap {
		get {
			if (pAmgenProductMap == null ) {
				pAmgenProductMap =getAllAmgenProductMap();
			}
			return pAmgenProductMap;
		}
	}

	private static Map<String,AmgenProduct__c> pAmgenProductMapByName = null;
	public static Map<String,AmgenProduct__c> AmgenProductMapByName {
		get {
			if (pAmgenProductMapByName == null ) {
				pAmgenProductMapByName =getAllAmgenProductMapByName();
			}
			return pAmgenProductMapByName;
		}
	}


	public static list<AmgenProduct__c> getAllAmgenProducts() {
		list<AmgenProduct__c> products = [
			Select id, SiebelRowId__c, Old_ProductName__c, Name,
			ODS_DrugId__c, Molecule_Name__c,isEnbrel__c,
			Product_Description__c
			From AmgenProduct__c 
			where isLogicallyDeleted__c = false   //Def 592
			order by Name
		];
		return products;
	}
	
	public static Map<id,AmgenProduct__c> getAllAmgenProductMap() {		
		Map<id,AmgenProduct__c> result = new Map<id,AmgenProduct__c>();
		for(AmgenProduct__c prod : AllProducts) {
			result.put(prod.id, prod);
		}
		return result;
	}
	

	public static Map<string,AmgenProduct__c> getAllAmgenProductMapByName() {		
		Map<string,AmgenProduct__c> result = new Map<string,AmgenProduct__c>();
		for(AmgenProduct__c prod : AllProducts) {
			result.put(prod.Name, prod);
		}
		return result;
	}
	
	
}