force-app/main/default/staticresources/python/Disappear/src/objects/AmgenProduct__c.object
<CustomObject>
    <fields>
        <fullName>isEnbrel__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Defect 33 - IFPRC is able to see Enbrel related Pubs</description>
        <label>isEnbrel</label>
        <type>Checkbox</type>
    </fields>
    <label>Amgen Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/AmgenProductModelTest.cls
@IsTest
public class AmgenProductModelTest {

    @IsTest
    public static void UnitTest() {
        
        AmgenProductModelData.createData();
        
        System.assertNotEquals(null, AmgenProductModel.AllProducts);
        System.assertNotEquals(null, AmgenProductModel.AllProductNames);

        System.assertNotEquals(null, AmgenProductModel.AmgenProductMapByName);
        System.assert(AmgenProductModel.AmgenProductMapByName.size() > 10);
        
        System.assertNotEquals(null, AmgenProductModel.getProductByName('ABP 215'));
        
        AmgenProduct__c enbrel = AmgenProductModel.getProductByName('Enbrel');
        System.assertNotEquals(null, enbrel);
        System.assert(enbrel.isEnbrel__c);
        
         
        System.assertEquals(null, AmgenProductModel.getProductByName('Not a product'));
        
        AmgenProduct__c product = AmgenProductModel.AmgenProductMapByName.get('ABP 215');
        System.assertNotEquals(null, product);
        System.assert('ABP 215' == product.name);
        
        System.assertNotEquals(null, AmgenProductModel.AmgenProductMap);
    
        Set<id> prodIdSet = new Set<Id>();
        prodIdSet.add(product.id);
        System.assertNotEquals(null, AmgenProductModel.getProductById(prodIdSet));
        
    
        System.assertNotEquals(null, AmgenProductModelData.amg103mt103);
    }

}