force-app/main/default/staticresources/python/Disappear/src/objects/AmgenProduct__c.object
<CustomObject>
    <fields>
        <fullName>isLogicallyDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>CONFIGURATION_FLG</description>
        <label>Expired</label>
        <type>Checkbox</type>
    </fields>
    <label>Amgen Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <fields>
        <fullName>Current_SubmissionCycle_Id_Formula__c</fullName>
        <formula>PubStatus__r.Submission_Cycle__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current Submission Cycle Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PubStatus__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Current status of this publication</description>
        <label>PubStatus</label>
        <referenceTo>PubStatus__c</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PubStatus__c.object
<CustomObject>
    <description>List of Status for a Publication - Target Date / Revised Date / Actual Date
Will be used for planning</description>
    <fields>
        <fullName>IsLogicallyDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to logically delete the record.

Release 1.1 Renamed isLogicallyDeleted to Expired</description>
        <label>Expired</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Status</label>
        <referenceTo>Status__c</referenceTo>
        <relationshipName>PubStatuses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Submission_Cycle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Submission Cycle</label>
        <referenceTo>SubmissionCycle__c</referenceTo>
        <relationshipName>Pub_Statuses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publication Status</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>PubStatus Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PubTOV__c.object
<CustomObject>
    <fields>
        <fullName>ContractNumber__c</fullName>
        <label>Contract number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>FormOfPayment__c</fullName>
        <label>Form of Payment</label>
        <picklist>
            <picklistValues>
                <fullName>In Kind</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>InvoiceNumber__c</fullName>
        <label>Invoice number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsLogicallyDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Expired</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NatureOfPayment__c</fullName>
        <label>Nature of Payment</label>
        <picklist>
            <picklistValues>
                <fullName>Research</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PaymentAmount__c</fullName>
        <label>Payment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PaymentDate__c</fullName>
        <label>Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product Name derived from the Publication&apos;s Product Indications.</description>
        <label>Product Name</label>
        <referenceTo>AmgenProduct__c</referenceTo>
        <relationshipLabel>Publication TOV</relationshipLabel>
        <relationshipName>Publication_TOV</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PublicationStatus__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication Status</label>
        <referenceTo>PubStatus__c</referenceTo>
        <relationshipLabel>Publication TOV</relationshipLabel>
        <relationshipName>Publication_TOV</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Publication TOV</relationshipLabel>
        <relationshipName>Publication_TOV</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubmissionCycle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Submission Cycle</label>
        <referenceTo>SubmissionCycle__c</referenceTo>
        <relationshipLabel>Publication TOV</relationshipLabel>
        <relationshipName>Publication_TOV</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publication TOV</label>
    <nameField>
        <label>Publication TOV Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publication TOV</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Status__c.object
<CustomObject>
    <label>Status</label>
    <nameField>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/SubmissionCycle__c.object
<CustomObject>
    <description>record name will be PubId-{0000000}-SubCycle-{00}</description>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Submission Cycles</relationshipLabel>
        <relationshipName>Submission_Cycles</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Submission_Cycle_Num__c</fullName>
        <label>Submission Cycle #</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Submission Cycle</label>
    <nameField>
        <label>Submission Cycle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submission Cycles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/PubTOVModel.cls
public with sharing class PubTOVModel extends AppearBaseModel {

    private id PubId;
    private string ActiveTile;
    private string ActiveSubMenu;
    private AppearPubModel pubModel; 
    public boolean hasEditAccess {get; private set;}
    
    // property for new record creation
    private transient PubTOV__c pNewPubTOV = null;
    public PubTOV__c newPubTOV { //insert from model
        get {
            if (pNewPubTOV == null) {                
                pNewPubTOV = new PubTOV__c();
                pNewPubTOV.Publication__c = PubId;
                pNewPubTOV.PublicationStatus__c  = pubModel.pubRecord.PubStatus__c; 
                pNewPubTOV.SubmissionCycle__c  = pubModel.pubRecord.Current_SubmissionCycle_Id_Formula__c; 
                pNewPubTOV.Product_Name__c  = pubModel.PubProdIndication.KeyProdNameId;
            }
            return pNewPubTOV;
        }
        set {
            pNewPubTOV = value;
        }
    }
    
	// wrapper is used for selection tracking
    public class TOVWrapper{
    	public PubTOV__c pTOV {get;set;}
    	public boolean IsSelected {get;set;}
    	TOVWrapper(PubTOV__c aTov){
    		pTOV = aTOV;
    		IsSelected = false; 
    	}
    	
    }
        
    //constructor
    public PubTOVModel(Id PubId, AppearPubModel pubModel, string tile, string subMenu, boolean hasEditAccess ) {
        this.PubId = PubId; 
        this.PubModel =  pubModel; 
        this.ActiveTile = tile;
        this.ActiveSubMenu = subMenu;
        this.hasEditAccess = hasEditAccess;
    }
     
    //Logical Delete  
    public PageReference deleteSelected() {
        Boolean recordHasDates = false;

        List<PubTOV__c> itemsToDelete = new List<PubTOV__c>();
        for(TOVWrapper p : PubTOVListWrapper){
            if (p.IsSelected) {
                itemsToDelete.add(p.pTOV);
            }
        }
        if (itemsToDelete.size() > 0){
	        database.delete(itemsToDelete, false);  
    	    pPubTOVListWrapper = null;   // force to refresh 		  
        	return new PageReference(AppearUrlModel.AppearPubMenuUrl(ActiveSubMenu, ActiveTile, itemsToDelete[0].publication__c));
        } else {
        	return null;
        }
    }  



    
    public PageReference saveNewPubTOV() {
	       
	       AppLogModel.LogDebug('PubTOVModel::saveNewPubTOV', 'invoking saveNewPubTOV');

		   PubTOV__c aPubTOV = new PubTOV__c();
		   aPubTOV.Publication__c = PubId;
		   aPubTOV.ContractNumber__c = newPubTOV.ContractNumber__c ;
		   aPubTOV.Description__c = newPubTOV.Description__c;  
		   aPubTOV.FormOfPayment__c =  newPubTOV.FormOfPayment__c;
		   aPubTOV.InvoiceNumber__c = newPubTOV.InvoiceNumber__c;
		   aPubTOV.NatureOfPayment__c = newPubTOV.NatureOfPayment__c;
		   aPubTOV.PaymentAmount__c = newPubTOV.PaymentAmount__c;		   
		   aPubTOV.PaymentDate__c = newPubTOV.PaymentDate__c;
		   
		   // to do: get the publication status and submission cycle from active pub
		   aPubTOV.PublicationStatus__c = newPubTOV.PublicationStatus__c;
		   aPubTOV.SubmissionCycle__c = pubModel.PubStatus.PubStatusMap.get(newPubTOV.PublicationStatus__c).Submission_Cycle__c;
		   aPubTOV.Product_Name__c = newPubTOV.Product_Name__c;
		   
		try {
		        insert aPubTOV;
		                   
		        AppLogModel.LogDebug('PubTOVModel::saveNewPubTOV', 'Created new PubTOV record for '+PubId );
		        AppLogModel.flushLogs();
		        return new PageReference( AppearUrlModel.AppearPubMenuUrl(ActiveSubMenu, ActiveTile, PubId));
		 } catch (DMLException e) {
		        AppLogModel.LogError('PubTOVModel::saveNewPubTOV', 'Faile to save: ' + e);
		        AppLogModel.flushLogs();
		}
        
        return new PageReference(AppearUrlModel.AppearPubMenuUrl(ActiveSubMenu, ActiveTile, PubId));
    
    }
    
    
    public boolean canAddDelTOVs {
        get{
            return  hasEditAccess;
        }
    }

    public PageReference saveTOVList() {
                
        database.update(PubTOVList, true);
        pPubTOVListWrapper = null;  //force refresh of new sort order
        
        AppLogModel.flushLogs();
        
        return new PageReference(AppearUrlModel.AppearPubMenuUrl(ActiveSubMenu, ActiveTile, PubId)) ;
        
    }


    public  List<PubTOV__c> PubTOVList{
        get{
			 List<PubTOV__c> aPubTOVList = new   List<PubTOV__c> ();
			 for (TOVWrapper aTOVWrapper: PubTOVListWrapper){
			 	aPubTOVList.add(aTOVWrapper.pTOV);
			 }
			 return aPubTOVList;
        }
    }  

    private  List<TOVWrapper> pPubTOVListWrapper= null;
    public  List<TOVWrapper> PubTOVListWrapper{
        get{
            if(pPubTOVListWrapper== null){
            	pPubTOVListWrapper = new List<TOVWrapper>() ; 
              List <PubTOV__c> aTOVList = getAllPubTOVList(this.PubId);
              for (PubTOV__c aTOV :aTOVList ){
              	pPubTOVListWrapper.add(new TOVWrapper(aTOV)); 
              }
            }               
	        return pPubTOVListWrapper;
        }
        set {
        	pPubTOVListWrapper = value; 
        }
    }  


    
    public static List<PubTOV__c> getAllPubTOVList(Id PubId){
        if ( PubId == null) {
            return null;
        }
        List<PubTOV__c> result = [
            select id, Name, Publication__c, 
            ContractNumber__c, Description__c, FormOfPayment__c, InvoiceNumber__c, 
            NatureOfPayment__c, PaymentAmount__c, PaymentDate__c, 
            PublicationStatus__c,PublicationStatus__r.Status__r.name , 
            SubmissionCycle__c, SubmissionCycle__r.name, SubmissionCycle__r.Submission_Cycle_Num__c, 
            Product_Name__c, Product_Name__r.name
            From PubTOV__c
            where Publication__c = :PubId
            and isLogicallyDeleted__c = false
            order by PaymentDate__c desc 
        ];
        return result;
    }

    
    /////////////// clone ///////////////
/*
    public static void clone(Id origPubId, Id destCloneId) {
        AppLogModel.LogInfo('PubTOVModel::clone', 'starting ' );

        
        List<PubTOV__c> origList = getAllPubTOVList(origPubId);
 
        List<PubTOV__c> destList = new List<PubTOV__c>();
        for(PubTOV__c record : origList){
            if ( record.IsLogicallyDeleted__c == false) {
                PubTOV__c clone = record.clone(false, true, false, false);
                clone.Publication__c = destCloneId;
                destList.add(clone); 
            }
        }
        
        insert destList;
    }

*/

}