force-app/main/default/staticresources/python/Disappear/src/objects/Appear_Role__c.object
<CustomObject>
    <description>All Roles in the Appear System
Will use Record Type to distinguish between different group of roles</description>
    <label>Appear Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appear Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>UserId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/FPR_Only_Answers__c.object
<CustomObject>
    <fields>
        <fullName>Have_Amgen_Author__c</fullName>
        <description>Stores the response for question :
&quot;Are there Amgen Author/s on this Publication ?&quot;</description>
        <label>Have Amgen Author</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Is_ISS_Pub__c</fullName>
        <description>Response for question :
&quot;Is this an Investigator Sponsored Study (ISS) Publication ?&quot;</description>
        <label>Is ISS Pub</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>FPR Only Answers</label>
    <nameField>
        <label>Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FPR Only Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/FPR_Only_Questions__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Answer_Field_Name__c</fullName>
        <label>Answer Field Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Question_Content__c</fullName>
        <label>Question Content</label>
        <type>TextArea</type>
    </fields>
    <label>FPR Only Questions</label>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <fields>
        <fullName>Current_SubmissionCycle_Id_Formula__c</fullName>
        <formula>PubStatus__r.Submission_Cycle__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current Submission Cycle Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Data_Source__c</fullName>
        <label>Data Source</label>
        <picklist>
            <picklistValues>
                <fullName>Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GRAAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FPR_Due_Date__c</fullName>
        <inlineHelpText>As best practice, select an FPR due date that is more than 10 business days from today. If this is a rush request, provide business justification in the Comments for FPR Coordinator section and we will try to facilitate your request.</inlineHelpText>
        <label>FPR Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>GPP_Type__c</fullName>
        <description>Used for Classification of GPP publication and mandatory for if Publication is GPP type.</description>
        <label>Publication Classification</label>
        <picklist>
            <picklistValues>
                <fullName>CSP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSP Encore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Deliverable</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IsComments_Only__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used for data migration</description>
        <inlineHelpText>Intended for comments only review</inlineHelpText>
        <label>Courtesy Review</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Not_Product_Policy__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Not Product / Policy</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Publication_Title__c</fullName>
        <inlineHelpText>This is a succinct but descriptive Title of the Publication</inlineHelpText>
        <label>Publication Title</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Publication_Type__c</fullName>
        <label>Publication Type</label>
        <picklist>
            <picklistValues>
                <fullName>Abstract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ad Board Summary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMCP Dossier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Book Chapter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brief Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CMS/Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Editorial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GVD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HTA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Letter to Editor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manuscript</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting Summary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Newsletter Article</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oral Presentation (Slide Deck)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Poster</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review Article</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supplement Article (Non English Language Only)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Translation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SOP_Exception__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SOP Exception</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SP_Full__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SP Full</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SubGroup_pick__c</fullName>
        <inlineHelpText>Required and depends on Data Source selected</inlineHelpText>
        <label>Data Source Subgroup</label>
        <picklist>
            <controllingField>Data_Source__c</controllingField>
            <picklistValues>
                <fullName>Global Dev - Asia Pac</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global Dev - China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global Dev - EEMEA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global Dev - Europe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global Dev - Intercont</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global Dev - JAPAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global Dev - Japan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global Dev - LACAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global Dev - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global Dev - US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GRAAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ops - Comm Quality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ops - DP&amp;DD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ops - Mfg Sciences &amp; Tech</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ops - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ops - Process Dev</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ops - Quality Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research - CBSS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research - Early Dev</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research - Genome Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research - Hem &amp; Onc</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research - Inflammation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research - Neuroscience</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research - P&amp;PD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research - Pharmaceutics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research - PKDM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research - SMP&amp;PD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research - Therapeutic Discovery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research - Therapeutic Innovation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>isISS__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ISS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>is_MTA__c</fullName>
        <defaultValue>false</defaultValue>
        <label>MTA</label>
        <type>Checkbox</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PubME__c.object
<CustomObject>
    <description>Record all Manuscript Equivalent points award to authors and others for their work on a publication</description>
    <fields>
        <fullName>AppearRole__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The Role that the Pub Team member played in the preparation of this Publication

Will be used to look up Awarded ME in PubTypeME</description>
        <inlineHelpText>APPEAR Roles include: Writing Coordinator, Writer, Editorial Support, GPPL, and Pub Specialist.</inlineHelpText>
        <label>Appear Role</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Appear_Role__c.isWritingRole__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Appear_Role__c</referenceTo>
        <relationshipLabel>Publication MEs</relationshipLabel>
        <relationshipName>Publication_MEs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Publication MEs</relationshipLabel>
        <relationshipName>Publication_MEs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Submission_Cycle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Submission Cycle</label>
        <referenceTo>SubmissionCycle__c</referenceTo>
        <relationshipLabel>Publication MEs</relationshipLabel>
        <relationshipName>Publication_MEs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WritingRoleMember__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Writing Role Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Publication MEs</relationshipLabel>
        <relationshipName>Publication_MEs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publication ME</label>
    <nameField>
        <displayFormat>PME-{000000000}</displayFormat>
        <label>Publication ME Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication MEs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/AppearPubViewModelTest.cls
@IsTest
public class AppearPubViewModelTest {

    @IsTest
    public static void UnitTest() {
        Publication__c pub = UnitTestData.PublicationNew('AppearPubViewModelTest');
        
        List<IdNameDTO>  pubIdNameDtoList = AppearPubViewModel.findPubsByName('AppearPubViewModelTes');
        System.assertEquals(1, pubIdNameDtoList.size());
        
        AppearPubViewModel.RouteForReview(pub.Id);
        AppearPubViewModel.SubmitToTarget(pub.Id);
        AppearPubViewModel.RejectPub(pub.Id);
        
    }


    @IsTest
    public static void UnitTest1a() {
        Publication__c pub = UnitTestData.PublicationNew('AppearPubViewModelTest');
        
        List<IdNameDTO>  pubIdNameDtoList = AppearPubViewModel.findPubsByName('AppearPubViewModelTes');
        System.assertEquals(1, pubIdNameDtoList.size());
        
        AppearPubViewModel.MaterialChangeForCongressJournal(pub.Id);
        
    }
    
    @IsTest
    public static void UnitTest2() {
        Publication__c pub = UnitTestData.PublicationNew('AppearPubViewModelTest');
        List<IdNameDTO>  pubIdNameDtoList = AppearPubViewModel.findPubsByName('AppearPubViewModelTes');
        System.assertEquals(1, pubIdNameDtoList.size());
        
        
        AppearPubViewModel.DeleteThisPublication(pub.Id);
        AppearPubViewModel.DeleteThisPublication(pub.Id); //should fail
        
        AppearPubViewModel.SubmitSuggestion(pub.Id);  //invalid pub
        AppearPubViewModel.SubmitForFPR(pub.Id); //invalid pub
        AppearPubViewModel.AcceptPub(pub.Id); //invalid pub
        
        
    }
     @IsTest
    public static void UnitTest3(){
        Profile profile= [select id, name from Profile where name ='APPEAR External Writer'];
        User externalWriter = new User(alias = 'external',email='externaluser@testorg.com',emailencodingkey='UTF-8',lastname='Testing', languagelocalekey='en_US',localesidkey='en_US', profileid =profile.Id ,timezonesidkey='America/Los_Angeles',username='externaluser@testorg.com');
        insert externalWriter;
        AppearRoleModelData.createData();
        AccountModelData.createData();  
        Contact contact = new Contact(UserId__c=externalWriter.Id,
        LastName= 'user', FirstName='test',
        AccountId=AccountModel.AccountNameMap.get('AMGEN').Id,
        Email='mike@amgen.com');
        insert contact;
        
        System.runAs(externalWriter){
             Publication__c pub = UnitTestData.PublicationNew('TestExternalWriterCreatedPublication');
            
        }
        
    }
    
    @IsTest
   	public static void unitTest4(){
        Profile profile= [select id, name from Profile where name ='APPEAR External Writer'];
        User externalWriter = new User(alias = 'external',email='externaluser@testorg.com',emailencodingkey='UTF-8',lastname='Testing', languagelocalekey='en_US',localesidkey='en_US', profileid =profile.Id ,timezonesidkey='America/Los_Angeles',username='externaluser@testorg.com');
        insert externalWriter;
        AppearRoleModelData.createData();
        AccountModelData.createData();  
        Contact contact = new Contact(UserId__c=externalWriter.Id,
        LastName= 'user', FirstName='test',
        AccountId=AccountModel.AccountNameMap.get('AMGEN').Id,
        Email='mike@amgen.com');
        insert contact;
        System.runAs(externalWriter){
            Publication__c pub = UnitTestData.PublicationNew('TestExternalWriterCreatedPublication');
            Appear_Role__c appearRole=[Select Id from Appear_Role__c where Name='Writing Coordinator'];
            System.Test.startTest();
            PubMe__c pubMe= New PubMe__c(Publication__c=pub.Id,WritingRoleMember__c=externalWriter.Id,AppearRole__c=appearRole.Id,Submission_Cycle__c=pub.Current_SubmissionCycle_Id_Formula__c);
            System.debug('---->>>'+pub);
            CloneResultDTO result = RelatedPubModel.ClonePub(pub.Id);
       		System.Test.stopTest();
        }    
         
    }
    
    //Appear Enhancement R1 & Backlog R4: 2017 : Test Class for FPR Questionnaire 
    @isTest
    public static void fprquestionTest(){
        Publication__c pub = UnitTestData.PublicationNew('AppearPubModelTest123');
        
        FPR_Only_Questions__c fprQTestRec1 = new FPR_Only_Questions__c(Answer_Field_Name__c = 'Is_ISS_Pub__c',Question_Content__c = 'Test Sample for isISS',Name= 'isISSTest');
        insert fprQTestRec1;
        
        FPR_Only_Answers__c fprATest = new FPR_Only_Answers__c(Name='Test Ans Rec1',Is_ISS_Pub__c = 'Yes',Have_Amgen_Author__c = 'No');
        insert fprATest;
        
        AppearPubViewModel appPubViewMod = new AppearPubViewModel();
        AppearPubModel appPubMod = new AppearPubModel(pub.id);
        
        System.Test.startTest();
        	appPubViewMod.getQuestionContent(null, null);
        	appPubViewMod.getReqOptions('Is_ISS_Pub__c');
        
        	appPubViewMod.answerValue = 'Yes';
        	appPubViewMod.parentQuestion = 'Have Amgen Author';
        	FPR_Only_Questions__c fprQTestRec2 = new FPR_Only_Questions__c(Error_Message__c='TestError2', Name= 'Error Message Amgen Author');
        	insert fprQTestRec2;
        	appPubViewMod.FPRQuestionresponse();
        	appPubViewMod.answerValue = 'No';
        	appPubViewMod.FPRQuestionresponse();
        	//coverage for AppearPubModel save FPR Only publication functionality
        	appPubMod.NewFprOnlyPublication.isISS__c = true;
        	appPubMod.SaveNewFprOnlyPublication();
        	
        	/*
        	appPubViewMod.answerValue = 'Yes';
        	appPubViewMod.parentQuestion = 'Does include human study or reasearch';
        	FPR_Only_Questions__c fprQTestRec3 = new FPR_Only_Questions__c(Error_Message__c='TestError3', Name= 'Error Message human study or reasearch');
        	insert fprQTestRec3;
        	appPubViewMod.FPRQuestionresponse();
        	appPubViewMod.answerValue = 'No';
        	appPubViewMod.FPRQuestionresponse();
            //coverage for AppearPubModel save FPR Only publication functionality
        	appPubMod.NewFprOnlyPublication.is_MTA__c = true;
        	appPubMod.SaveNewFprOnlyPublication();
        	*/
        
        	appPubViewMod.answerValue = 'Yes';
        	appPubViewMod.parentQuestion = 'Have Amgen Author DSR';
        	FPR_Only_Questions__c fprQTestRec3 = new FPR_Only_Questions__c(Error_Message__c='TestError3', Name= 'Error Message Amgen Author DSR');
            insert fprQTestRec3;
			System.assertEquals(fprQTestRec3.Error_Message__c, 'TestError3');
        	appPubViewMod.FPRQuestionresponse();
        	appPubViewMod.answerValue = 'No';
        	appPubViewMod.FPRQuestionresponse();
        	//coverage for AppearPubModel save FPR Only publication functionality
        	appPubMod.NewFprOnlyPublication.IsComments_Only__c = true;
        	appPubMod.SaveNewFprOnlyPublication();
        	
        	appPubViewMod.answerValue = 'Yes';
        	appPubViewMod.parentQuestion = 'Is Partner led SOP'; 
        	appPubViewMod.FPRQuestionresponse();
        	//coverage for AppearPubModel save FPR Only publication functionality
        	appPubMod.NewFprOnlyPublication.SOP_Exception__c = true;
        	appPubMod.SaveNewFprOnlyPublication();
        	
        	appPubViewMod.answerValue = 'Yes';
        	appPubViewMod.parentQuestion = 'Is this a CSP';
        	FPR_Only_Questions__c fprQTestRec4 = new FPR_Only_Questions__c(Error_Message__c='TestError4', Name= 'Error Message Is this a CSP');
            insert fprQTestRec4;
			System.assertEquals(fprQTestRec4.Error_Message__c, 'TestError4');
        	appPubViewMod.FPRQuestionresponse();
        	appPubViewMod.answerValue = 'No';
        	appPubViewMod.FPRQuestionresponse();
        	//coverage for AppearPubModel save FPR Only publication functionality
        	appPubMod.NewFprOnlyPublication.SP_Full__c = true;
        	appPubMod.SaveNewFprOnlyPublication();
        
        	/*
        	appPubViewMod.answerValue = 'Yes';
        	appPubViewMod.parentQuestion = 'Have human study or research No SOP';
        	FPR_Only_Questions__c fprQTestRec4 = new FPR_Only_Questions__c(Error_Message__c='TestError4', Name= 'Error Message study or research No SOP');
            insert fprQTestRec4;
        	appPubViewMod.FPRQuestionresponse();
        	
        	appPubViewMod.answerValue = 'Yes';
        	appPubViewMod.parentQuestion = 'Have data or product materials';
        	appPubViewMod.FPRQuestionresponse();
        	//coverage for AppearPubModel save FPR Only publication functionality
        	appPubMod.NewFprOnlyPublication.SP_Full__c = true;
        	appPubMod.SaveNewFprOnlyPublication();
        	appPubMod.closeQuestionModal();
        	
        	appPubViewMod.answerValue = 'No';
        	appPubViewMod.parentQuestion = 'Is self written and no discussion';
        	FPR_Only_Questions__c fprQTestRec5 = new FPR_Only_Questions__c(Error_Message__c='TestError5', Name= 'Error message written no discussion');
        	insert fprQTestRec5;
        	appPubViewMod.FPRQuestionresponse();
        	appPubViewMod.answerValue = 'Yes';
        	appPubViewMod.FPRQuestionresponse();
        	//coverage for AppearPubModel save FPR Only publication functionality
        	appPubMod.NewFprOnlyPublication.Not_Product_Policy__c = true;
        	appPubMod.SaveNewFprOnlyPublication();
        	*/
        
        	AppearPubModel.ansRecIdVal = fprATest.id;
        	System.assertEquals(fprATest.id, AppearPubModel.ansRecIdVal);
        	appPubMod.NewFprOnlyPublication.GPP_Type__c = 'FPR Only';
        	appPubMod.NewFprOnlyPublication.Publication_Title__c = 'Test Pub FPR Only';
        	appPubMod.NewFprOnlyPublication.Publication_Type__c = 'Other';
        	appPubMod.NewFprOnlyPublication.Data_Source__c = 'Development';
        	appPubMod.NewFprOnlyPublication.SubGroup_pick__c = 'Global Dev - US';
        	appPubMod.NewFprOnlyPublication.FPR_Due_Date__c = System.today();
        	appPubMod.SaveNewFprOnlyPublication();
        	appPubMod.updateAnsPubRelate(appPubMod.NewFprOnlyPublication.Id);
        
        System.Test.stopTest();
    }
}