force-app/main/default/staticresources/python/Disappear/src/objects/Appear_Role__c.object
<CustomObject>
    <description>All Roles in the Appear System
Will use Record Type to distinguish between different group of roles</description>
    <label>Appear Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appear Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Review_Team__c.object
<CustomObject>
    <description>Review team for DataSource or SubGroup

A review team can exists for a DataSource without SubGroup</description>
    <label>Review Team</label>
    <nameField>
        <label>Review Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Review Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/ReviewTeamMember__c.object
<CustomObject>
    <fields>
        <fullName>Appear_Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Appear Role</label>
        <referenceTo>Appear_Role__c</referenceTo>
        <relationshipLabel>Review Team Members</relationshipLabel>
        <relationshipName>Review_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReviewTeamMember__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Review Team Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Review Team Members</relationshipLabel>
        <relationshipName>Review_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Review_Team__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Review Team</label>
        <referenceTo>Review_Team__c</referenceTo>
        <relationshipLabel>Review Team Members</relationshipLabel>
        <relationshipName>Review_Team_Members</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReviewerType__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Primary</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Notify</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FPA Approver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FPA Comments Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FPA Copy Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FPA Delegate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FPA Triagee</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reviewer_Role__c</fullName>
        <label>Reviewer Role</label>
        <picklist>
            <picklistValues>
                <fullName>Area VP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EDL/GDL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IML</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US Legal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>International Legal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Biostatistics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IBL International</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global TA Head</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Biosimilars</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Review Team Member</label>
    <nameField>
        <displayFormat>RTM-{00000000}</displayFormat>
        <label>Review Team Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Review Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/ReviewTeamMemberModel.cls
public class ReviewTeamMemberModel {

    public static List<ReviewTeamMember__c> findReviewTeamMembers(List<Review_Team__c> ReviewTeamList) {
        
        List<id> ReviewTeamIdList = new List<id>();
        for(Review_Team__c reviewteam : ReviewTeamList) {
            ReviewTeamIdList.add(reviewteam.id);
        }
        // r.Reviewer_Role__c has been added in below Code for ENHC0011636:- Enhancement 
        List<ReviewTeamMember__c> reviewTeamMembers = [
            select r.ReviewerType__c, r.Review_Team__c, 
            r.ReviewTeamMember__c, r.ReviewTeamMember__r.Name,
            r.Appear_Role__c,r.Reviewer_Role__c
            from ReviewTeamMember__c r
            where Review_Team__c in :ReviewTeamIdList
        ];
        
        return reviewTeamMembers;
    }
    
    private static List<ReviewTeamMember__c> pReviewTeamMemberList = null;
    public static List<ReviewTeamMember__c> ReviewTeamMemberList {
        get {
            if (pReviewTeamMemberList == null){
                pReviewTeamMemberList = getAllReviewTeamMembers();
            }
            return pReviewTeamMemberList;
        }
    }
    
    public static List<ReviewTeamMember__c> getAllReviewTeamMembers() {
        List<ReviewTeamMember__c> result = [
            Select Name, Review_Team__c, Appear_Role__c, Reviewer_Role__c,ReviewerType__c 
            From ReviewTeamMember__c 
            ];
        return result;
    }
     
    
   private static Map<String, ReviewTeamMember__c> pReviewTeamMemberNameMap = null;
   public static Map<String, ReviewTeamMember__c> ReviewTeamMemberNameMap{
     get {
       if (pReviewTeamMemberNameMap== null){
         pReviewTeamMemberNameMap = getReviewTeamMemberMapByName();
       }
       return pReviewTeamMemberNameMap;
     }
   }
   
   public static Map<String, ReviewTeamMember__c> getReviewTeamMemberMapByName() {
    Map<String, ReviewTeamMember__c> result = new Map<String, ReviewTeamMember__c>();
    for(ReviewTeamMember__c pReviewTeamMem : ReviewTeamMemberList){
      result.put(pReviewTeamMem.Name, pReviewTeamMem );
    }

    return result;
  }
}