force-app/main/default/staticresources/python/Disappear/src/objects/Appear_Role__c.object
<CustomObject>
    <description>All Roles in the Appear System
Will use Record Type to distinguish between different group of roles</description>
    <fields>
        <fullName>isWritingRole__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Select this checkbox for system to copy a publication team member to PubME table to award ME</description>
        <label>isWritingRole</label>
        <type>Checkbox</type>
    </fields>
    <label>Appear Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appear Roles</pluralLabel>
    <recordTypes>
        <fullName>ReviewTeamRole</fullName>
        <active>true</active>
        <label>ReviewTeamRole</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>UserId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Journal__c.object
<CustomObject>
    <fields>
        <fullName>Journal_Name__c</fullName>
        <description>Swapnil indicated that the vendor specified 500 as the length of the Journal Name.</description>
        <label>Journal Name</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <label>Journal</label>
    <nameField>
        <displayFormat>Journal-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/ProductIndication__c.object
<CustomObject>
    <label>Product Indication</label>
    <nameField>
        <label>ProductIndication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Indications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <fields>
        <fullName>Current_FPRCycle_Id_Formula__c</fullName>
        <formula>PubStatus__r.FPR_Cycle__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current FPR Cycle Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Status_FormulaField__c</fullName>
        <description>Used to make Current Status a &quot;read only&quot; field</description>
        <formula>PubStatus__r.Status__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_SubmissionCycle_Id_Formula__c</fullName>
        <formula>PubStatus__r.Submission_Cycle__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current Submission Cycle Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Journal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Journal</label>
        <referenceTo>Journal__c</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <recordTypes>
        <fullName>Review</fullName>
        <active>true</active>
        <label>Review</label>
    </recordTypes>
    <recordTypes>
        <fullName>Suggestion</fullName>
        <active>true</active>
        <label>Suggestion</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Review_Team__c.object
<CustomObject>
    <description>Review team for DataSource or SubGroup

A review team can exists for a DataSource without SubGroup</description>
    <label>Review Team</label>
    <nameField>
        <label>Review Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Review Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/ReviewTeamMember__c.object
<CustomObject>
    <fields>
        <fullName>Appear_Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Appear Role</label>
        <referenceTo>Appear_Role__c</referenceTo>
        <relationshipLabel>Review Team Members</relationshipLabel>
        <relationshipName>Review_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReviewTeamMember__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Review Team Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Review Team Members</relationshipLabel>
        <relationshipName>Review_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Review_Team__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Review Team</label>
        <referenceTo>Review_Team__c</referenceTo>
        <relationshipLabel>Review Team Members</relationshipLabel>
        <relationshipName>Review_Team_Members</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReviewerType__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Primary</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Notify</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FPA Approver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FPA Comments Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FPA Copy Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FPA Delegate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FPA Triagee</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Review Team Member</label>
    <nameField>
        <displayFormat>RTM-{00000000}</displayFormat>
        <label>Review Team Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Review Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/PubProdIndModelTest.cls
@IsTest
public class PubProdIndModelTest {

	public static void CreateData() {
		//Creating Product
		AmgenProductModelData.createData();
		System.assertNotEquals(null, AmgenProductModelData.amg103mt103);
		
		//Creating Indication		
		IndicationModelData.createData();
		System.assertNotEquals(null, IndicationModelData.oncologyIndication);
		
		TherapeuticAreaModelData.createData();
		System.assertNotEquals(null, TherapeuticAreaModelData.OncologyTA);
		
		//Creating Prod Indication	
		ProductIndicationModelData.createData();
		System.assertNotEquals(null, ProductIndicationModelData.abarelixOncologyProdInd);
		
		//Creating DataSource		
		DataSourceModelData.createData();
		
		//Creating Subgroup
		SubGroupModelData.createData();
		
		//Review team for Subgroup
		ReviewTeamModelData.createData();
		System.assertNotEquals(null, ReviewTeamModelData.abarelixOncologyDevelopmentSmpReviewTeam);
		
		//self init lazy load for UserModelData
		System.assertNotEquals(null, UserModelData.bschoenUser);
		System.assertNotEquals(null, UserModelData.cruesgaUser);
    	
    	//Account
		AccountModelData.createData();
		
		//Contact
		List<Contact> ConList = new List<Contact>();
		
		ConList.add(new Contact(AccountId=AccountModelData.AmgenAccount.Id ,
			lastname='Ruesga',firstname='Cid',
			userid__c=UserModelData.cruesgaUser.Id));
		ConList.add(new Contact(AccountId=AccountModelData.AmgenAccount.Id ,
			lastname='Schoen',firstname='Brandon',
			userid__c=UserModelData.bschoenUser.Id));
        insert ConList;

		//Appear Role
		RecordType reviewTeamRoleRecType = RecordTypeModel.LookupRecordType('Appear_Role__c','ReviewTeamRole');
		List<Appear_Role__c> roleList = new List<Appear_Role__c>();
        roleList.add( new Appear_Role__c(name= 'FPR Reviewer', isWritingRole__c = false, RecordTypeId = reviewTeamRoleRecType.id));
		insert roleList;        
		
		Appear_Role__c FprReviewRole =AppearRoleModel.AppearRoleMapByName.get('FPR Reviewer');
		System.assertNotEquals(null, FprReviewRole);
		
		//Review Team Member
		Contact cid = AppearContactModel.findContactByName('Cid', 'Ruesga')[0];   
		Contact brandon = AppearContactModel.findContactByName('Brandon', 'Schoen')[0];
		System.assertNotEquals(null, cid);
		System.assertNotEquals(null, brandon);


		List <ReviewTeamMember__c> ReviewTeamMemberList = new List <ReviewTeamMember__c> ();
		ReviewTeamMemberList.add(new ReviewTeamMember__c(Review_Team__c= ReviewTeamModelData.abarelixOncologyDevelopmentSmpReviewTeam.Id ,
			ReviewTeamMember__c=Cid.id, Appear_Role__c=FprReviewRole.Id,ReviewerType__c = 'Primary'));         
		ReviewTeamMemberList.add(new ReviewTeamMember__c(Review_Team__c= ReviewTeamModelData.abarelixOncologyDevelopmentSmpReviewTeam.Id ,
			ReviewTeamMember__c=Brandon.id,ReviewerType__c = 'Notify'));         
		Insert ReviewTeamMemberList;
		
		//Creating Journal
        List<Journal__c> JournalList = new List<Journal__c>();
        JournalList.add( new Journal__c(Journal_Name__c= 'Annuals of Oncology')); 
		insert JournalList;
	}
	
	@IsTest
	public static Publication__c TestSaveProdInd() {
		CreateData();
 
		//Calling Unit test Data to create a Pub       
        Publication__c newPub = UnitTestData.PublicationNew('TestSaveProdInd');
		System.Test.startTest();
        
        
        System.assert(ProductIndicationModel.ProductIndicationList.size() > 0 );
        set<string> prodIndicationStringSet = new set<string>();
        
        for(ProductIndication__c pi : ProductIndicationModel.ProductIndicationList) {
        	prodIndicationStringSet.add(pi.name);
        	if ( prodIndicationStringSet.size() > 5) break;
        }
        
        
        PubProdIndModel.insertPubProdInd(newPub.id, prodIndicationStringSet);
        
        boolean isFprSubmitter = true; 
        PubProdIndModel indModel = new PubProdIndModel(newPub.id, 'menu','tile',isFprSubmitter);
        
        System.assert(indModel.ProdIndListForPub.size() > 0);
        System.assert(indModel.ProdIndIdListForPub.size() > 0);
        System.assert(indModel.PubProdIndicationList.size() > 0);
        System.assert(indModel.getProdIndicationMultiSelect().size() > 0);        
        System.assertNotEquals(indModel.KeyProdIndStr, null);
        System.assertNotEquals(indModel.KeyProdNameId, null);
        indModel.KeyProdIndStr = indModel.SelectedProductIndications[0];
        indModel.savePubProdInd();
        
        
        set<string> prodIndNames = new set<string>();
        for(ProductIndication__c indication : indModel.ProdIndListForPub) {
        	prodIndNames.add(indication.Name);
        } 
        PubProdIndModel.insertPubProdInd(newPub.Id, prodIndNames);
        PubProdIndModel.removePubProdInd(newPub.Id, prodIndNames);
        
        List<ProductIndication__c> prodIndList = ProductIndicationModel.ProductIndicationList;
        System.assert(prodIndList.size()>0); 
        System.Test.stopTest();
        
        pPubQueryId = null;
        
        AppearPubModel checkPub = new AppearPubModel(newPub.Id);
        
        System.assertEquals('Pending Suggestion', checkPub.pubRecord.Current_Status_FormulaField__c);
        System.assertNotEquals(null,  checkPub.pubRecord.Current_SubmissionCycle_Id_Formula__c);
        
        return newPub;
    }
    
    private static Publication__c pPubQuery = null;
    private static id pPubQueryId = null;
    public static Publication__c PubQuery(Id pubId){
    	
    	if ( pPubQueryId == pubId){
    		pPubQueryId = pubId;
			pPubQuery = [
	 			Select Id,
	 				Current_Status_FormulaField__c,
	 				Current_SubmissionCycle_Id_Formula__c,
	 				Current_FPRCycle_Id_Formula__c
				from Publication__c 
				where id =:pubid
			];
    	}
     	return pPubQuery;
    }


}