force-app/main/default/staticresources/python/Disappear/src/objects/AppearLogArchive__c.object
<CustomObject>
    <fields>
        <fullName>CreatedTime__c</fullName>
        <label>CreatedTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>LogType__c</fullName>
        <label>LogType</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MessageType__c</fullName>
        <label>MessageType</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PubId__c</fullName>
        <label>PubId</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Appear Log Archives</relationshipLabel>
        <relationshipName>Appear_Log_Archives</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecordName__c</fullName>
        <label>RecordName</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordURL__c</fullName>
        <label>RecordURL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>logSubjectId__c</fullName>
        <label>logSubjectId</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Appear Log Archive</label>
    <nameField>
        <label>Appear Log Archive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appear Log Archives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/AppLog__c.object
<CustomObject>
    <fields>
        <fullName>CreatedTime__c</fullName>
        <label>CreatedTime</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>LogType__c</fullName>
        <description>Info/Warning/Error</description>
        <inlineHelpText>Info/Warning/Error</inlineHelpText>
        <label>LogType</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MessageType__c</fullName>
        <label>MessageType</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PubId__c</fullName>
        <description>Pub ID - Name of the publication record</description>
        <label>PubId</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Appear Logs</relationshipLabel>
        <relationshipName>Appear_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RecordName__c</fullName>
        <description>Name of Salesforce Record we are debugging</description>
        <label>RecordName</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordURL__c</fullName>
        <description>optional URL to the record we are debugging</description>
        <label>RecordURL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>logSubjectId__c</fullName>
        <description>The salesforce id of the primary sObject of this AppLog Record
For example the id of a Publication that this log record is about.</description>
        <label>logSubjectId</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Appear Log</label>
    <nameField>
        <displayFormat>AL-{000000000}</displayFormat>
        <label>AppLog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appear Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <recordTypes>
        <fullName>Execute</fullName>
        <active>true</active>
        <label>Execute</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/BatchAppLogArchive.cls
global class BatchAppLogArchive extends BatchBase 
	implements Database.Batchable<SObject>,Database.Stateful {
   	public static String SOQL = 'select CreatedTime__c, Description__c, ' +
   		'logSubjectId__c, LogType__c, Message__c, MessageType__c, PubId__c,  ' +
   		'Publication__c, RecordName__c, RecordURL__c '+
   		'from AppLog__c where CreatedTime__c <> LAST_N_DAYS:14'; 
   		
   	//changed archival limit to 2 weeks on 12/6/2013 with confirmation from Swapnil and Sesha
   	
	public BatchAppLogArchive() {
		super();
    	if ( Test.isRunningTest()){
    		SOQL = SOQL + ' limit 10';
    	} else {
    		SOQL = SOQL + ' limit 10000';  //10k per batch max
    	}
    	AddMessage(SOQL);
        system.debug(SOQL);
	}
	
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        batchableContext = BC;
        batchName = 'BatchAppLogArchive';
        System.Debug(SOQL);
        return Database.getQueryLocator(SOQL);
    }

    global void execute(Database.BatchableContext BC, List<AppLog__c> logs){
		archiveAppLog(logs);
    }
    
    private static void archiveAppLog(List<AppLog__c> logs) {
    	
    	List<AppearLogArchive__c> logArchives = new List<AppearLogArchive__c>();
    	for (AppLog__c log : logs) {
    		logArchives.add(log2LogArchive(log));
    	}
    	
		Database.insert (logArchives, false);
    	Database.delete (logs, false);    	
    }
   
   
	public static  AppearLogArchive__c log2LogArchive ( AppLog__c log) {
		AppearLogArchive__c logArchive = new AppearLogArchive__c();
		logArchive.CreatedTime__c = log.CreatedTime__c;
		logArchive.Description__c = log.Description__c;
		logArchive.logSubjectId__c = log.logSubjectId__c;
		logArchive.LogType__c = log.LogType__c;
		logArchive.Message__c = log.Message__c;
		logArchive.MessageType__c = log.MessageType__c;
		logArchive.PubId__c = log.PubId__c;
		logArchive.Publication__c = log.Publication__c;
		logArchive.RecordName__c = log.RecordName__c;
		logArchive.RecordURL__c = log.RecordURL__c;
		
		return logArchive;
	}
   

    global void finish(Database.BatchableContext BC){
		SendBatchCompletionEmail();
	}
	
	//BatchAppLogArchive.runNow();
	public static void runNow(){
    	BatchAppLogArchive batch = new BatchAppLogArchive();
        Database.executeBatch(batch, 1000);
	}	

//////////////////////////////////////////  unit test /////////////////////////////////////
	@isTest( seeAllData = true)
	private static void unitTest() {
		BatchAppLogArchive.runNow();
	} 
}