force-app/main/default/staticresources/python/Disappear/src/objects/Appear_Role__c.object
<CustomObject>
    <description>All Roles in the Appear System
Will use Record Type to distinguish between different group of roles</description>
    <fields>
        <fullName>IsLogicallyDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Expired</label>
        <type>Checkbox</type>
    </fields>
    <label>Appear Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appear Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Isselected__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used for author</description>
        <label>Isselected</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <fields>
        <fullName>Country_pick__c</fullName>
        <description>07/30: Nagaraj Cheelad (CTS): updated the help text</description>
        <inlineHelpText>Country is required if SubGroup selected is Global Dev – Europe, Global Dev – Intercont,Global Dev – JAPAC,Global Dev – US for &apos;Development&apos; Data Source</inlineHelpText>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>United States</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Balkans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia &amp; Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brazil</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brunei</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bulgaria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cambodia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central And Eastern Europe (CEE)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colombia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Costa Rica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Croatia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cyprus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Czech Republic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denmark</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dominican Republic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ecuador</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GPP_Type__c</fullName>
        <description>Used for Classification of GPP publication and mandatory for if Publication is GPP type.</description>
        <label>Publication Classification</label>
        <picklist>
            <picklistValues>
                <fullName>CSP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSP Encore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Deliverable</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IsSelected__c</fullName>
        <defaultValue>false</defaultValue>
        <description>for UI operation - please do not store or migrate data into this field</description>
        <label>IsSelected</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PreFPRReviewers_Not_Found__c</fullName>
        <description>List of the FPR Reviewers that are not found in the system</description>
        <label>Pre-FPR Reviewers Not Found</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Indication__c</fullName>
        <description>A READ ONLY string that list all product Indications for the Publication
The key product indication will be list at the first entry</description>
        <inlineHelpText>Product - Indication is a required field that is available for selection when a publication is first saved. Once saved, the Product Indication may be edited using the Product Indication button.</inlineHelpText>
        <label>Product - Indication</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RAE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Responsible Amgen Employee (RAE)</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SponsorDept_Pick__c</fullName>
        <label>Sponsoring Amgen Department</label>
        <picklist>
            <picklistValues>
                <fullName>Center for Observational Research (CfOR)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clinical Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discovery Research</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global Government Affairs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global Health Economics (GHE)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global Medical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global Regulatory Affairs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global Safety</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global Scientific Affairs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global Value, Access, and Policy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufacturing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Translational Sciences</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SponsorOrg_Pick__c</fullName>
        <label>Sponsoring Organization</label>
        <picklist>
            <picklistValues>
                <fullName>Amgen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Astellas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AstraZeneca/MedImmune</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cytokinetics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daiichi-Sankyo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Genentech, Inc.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GlaxoSmithKline (GSK)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kirin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Novartis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pfizer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Servier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Takeda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UCB Pharma</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PublicationPreFprReviewer__c.object
<CustomObject>
    <fields>
        <fullName>Appear_Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Appear Role</label>
        <referenceTo>Appear_Role__c</referenceTo>
        <relationshipLabel>PublicationPreFprReviewer</relationshipLabel>
        <relationshipName>PublicationPreFprReviewer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsSelected__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsSelected</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PreFprReviewer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Pre FPR Reviewer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>PublicationPreFprReviewer</relationshipLabel>
        <relationshipName>PublicationPreFprReviewer</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Indication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Indication</label>
        <referenceTo>ProductIndication__c</referenceTo>
        <relationshipLabel>PublicationPreFprReviewer</relationshipLabel>
        <relationshipName>PublicationPreFprReviewer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>PublicationPreFprReviewer</relationshipLabel>
        <relationshipName>PublicationPreFprReviewer</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Publication PreFPR Reviewer</label>
    <nameField>
        <displayFormat>PubPreFpr-{00000000}</displayFormat>
        <label>Publication PreFPR Reviewer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication Pre FPR Reviewers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PublicationTeamMember__c.object
<CustomObject>
    <fields>
        <fullName>Appear_Role__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Appear Role</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Appear_Role__c.isWritingRole__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <filterItems>
                <field>Appear_Role__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>PubTeamRole</value>
            </filterItems>
            <filterItems>
                <field>Appear_Role__c.IsLogicallyDeleted__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Appear_Role__c</referenceTo>
        <relationshipLabel>Publication Team Members</relationshipLabel>
        <relationshipName>PublicationTeams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Pub Team Member links to Contact</description>
        <label>Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>PublicationTeams</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Indication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Optonal - to be filled in - if member is added from Prod Indication</description>
        <label>Product Indication</label>
        <referenceTo>ProductIndication__c</referenceTo>
        <relationshipLabel>Publication Team Members</relationshipLabel>
        <relationshipName>Publication_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipName>PublicationTeams</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Publication Team Member</label>
    <nameField>
        <displayFormat>PubT-{00000000}</displayFormat>
        <label>PublicationTeam Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/PubPreFprReviewerModel.cls
public with sharing class PubPreFprReviewerModel {

    ////////  members ////////////////////////
    private id PubId;
    private string ActiveTile;
    private string ActiveSubMenu;
    private AppearPubModel pActivePub;
    private boolean isFprSubmitter;    
    
    public PubPreFprReviewerModel(Id PubId,  string tile, string subMenu, Boolean isFprSubmitter) {
        this.PubId = PubId; 
        this.ActiveTile = tile;
        this.ActiveSubMenu = subMenu;
        this.isFprSubmitter = isFprSubmitter;
        
    }
    
    public AppearPubModel ActivePub {
        get{
            if (pActivePub == null) {
                pActivePub = new AppearPubModel(this.PubId);
            }
            return pActivePub;
        }
    }
    
    public void clearCache() {
        pPubPreFprReviewerList = null; 
    }
    
    private List<PublicationPreFprReviewer__c> pPubPreFprReviewerList = null;
    public List<PublicationPreFprReviewer__c> PubPreFprReviewerList {
        get {
            if (pPubPreFprReviewerList == null) {
                pPubPreFprReviewerList = getPubPreFprReviewers(this.PubId);
            }
            return pPubPreFprReviewerList;
        }
    }
    
    
    //Def 281 - insert Fpr Submitter as a Pre FPR Reviewer
    public static void InsertFprSubmitter(id pubId, string UserId) {
        
        Set<id> contactIds = AppearContactModel.findContactForAppearUser(UserId);

        
        if ( contactIds.size() == 0) {
            AppLogModel.LogError('PubPreFprReviewerModel::InsertFprSubmitter', 
                'Cannot insert FPR Submitter as PreFPR Reviewer.  Cannot find assocated Contact Record', PubId);
            AppLogModel.flushLogs();
            return;
        }
        for(Id contactId : contactIds) {
            PublicationPreFprReviewer__c preFpr = new PublicationPreFprReviewer__c();
            preFpr.isSelected__c = false;
            preFpr.PreFprReviewer__c =contactId;
            preFpr.Publication__c = pubId;
            //preFpr.Product_Indication__c = ptm.Product_Indication__c;
            //preFpr.Appear_Role__c = ptm.Appear_Role__c;
            
            insert preFpr;
            
            AppLogModel.LogInfo('PubPreFprReviewerModel::InsertFprSubmitter', 
                'inserted FPR Submitter ['+ contactId +'] as a preFPR reviewer '+preFpr, PubId);
            break;
        }
    }
    
    public PageReference save() {       
        
        //def 281
        //def 792 - 
        //Changed for Functional Pub Team
        if ( ProfileModel.isAppearPubTeam ||  ProfileModel.isAppearBusinessAdmin || ProfileModel.isSysAdmin || ProfileModel.isAppearGPPL ||  ProfileModel.isAppearReviewers ||
            ProfileModel.isAppearWriting || ProfileModel.isAppearExternalWriter || ProfileModel.isAppearFPRC || ProfileModel.isAppearIntFPRC || ProfileModel.isAppearFprOnlySubmitter || test.isRunningTest() || ProfileModel.isAppearFunctionalPubTeam ) {
                
            //clear checkbox before persisting
            for(PublicationPreFprReviewer__c p : pPubPreFprReviewerList){
                p.IsSelected__c = false;
            }
            
            //Defect 260 CC 12 add the additional check for PreFPRReviewers Not Found
            activePub.PubRecord.PreFPRReviewers_Not_Found__c = getPublicationPreFPRReviewersString(activePub.PubRecord.PreFPRReviewers_Not_Found__c);
            //Appear Enhancement R3: Historical Data Fix for Validation Rule
            try{
            	database.update(activePub.PubRecord, true);
            }catch(DMLException ae){
            	ApexPages.addMessages(ae);
            	return null;
            }
            
            database.update(pPubPreFprReviewerList, true);
            pPubPreFprReviewerList = null;  //clear cache
            
            if ( isFprSubmitter) {
                return new PageReference(AppearUrlModel.AppearFprSubmitterMenuUrl(ActiveSubMenu, ActiveTile, PubId));
            } else {
                return new PageReference(AppearUrlModel.AppearPubMenuUrl(ActiveSubMenu, ActiveTile, PubId));
            }
        } else {
            String errorMsg = 'You do not have permission to change PreFPR Reviewer List';
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.FATAL, errorMsg);
     
            ApexPages.addMessage(myMsg);     
            AppLogModel.LogError('PubPreFprReviewerModel::save', errorMsg, PubId);
            return null;
        }
    }
    
    public string getPublicationPreFPRReviewersString(string PreFPRReviewersNotFound){
        string result='';
        if (PreFPRReviewersNotFound <> null){
            if (result.length() <> 0) {
                result += ',' + PreFPRReviewersNotFound;
            } else {
                result = PreFPRReviewersNotFound;
            }
        }
        return result;
    }
    
    public PageReference deleteSelected() {
        Boolean recordHasDates = false;
          
        List<PublicationPreFprReviewer__c> itemsToLogicallyDelete = new List<PublicationPreFprReviewer__c>();
        for(PublicationPreFprReviewer__c p : pPubPreFprReviewerList){
            if (p.IsSelected__c) {
                itemsToLogicallyDelete.add(p);
            }
        }
        //Appear Enhancement R3: Start - Historical Data Validation fix        
        String message='Please ensure the required field(s):';
        if(ActivePub.pubRecord.SponsorDept_Pick__c == null){
        	message=message +' Sponsoring Amgen Department,';
        } 
        if(ActivePub.pubRecord.SponsorOrg_Pick__c == null){
        	message=message +' Sponsoring Organization,';
        }
        if(ActivePub.pubRecord.RAE__c == null){
        	message=message +' Responsible Amgen Employee,';
        }
        if (ActivePub.pubRecord.Country_pick__c == null){
        	message=message +' Country,';
        }
        //Commented below as part of Appear Enhancment R1:2017
        /*if(ActivePub.pubRecord.GPP_Type__c == null){
        	message=message +' Publication Classification,';
        }*/
        message= message.removeEnd(',');
        message = message + ' are updated on the publication as the publication is Part of GPP.';
        
        if(ActivePub.pubRecord.SponsorDept_Pick__c == null || ActivePub.pubRecord.SponsorOrg_Pick__c == null || ActivePub.pubRecord.RAE__c == null
        	|| ActivePub.pubRecord.Country_pick__c == null){ // removed || ActivePub.pubRecord.GPP_Type__c == null as part of Appear Enhancment R1:2017
        		ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.FATAL, 
                    message);
 
                ApexPages.addMessage(myMsg);
        		return null;
        	}
		//Appear Enhancement R3: End - Historical Data Validation fix
        
        database.delete(itemsToLogicallyDelete);    
        pPubPreFprReviewerList = null;  
        
        activePub.PubRecord.PreFPRReviewers_Not_Found__c = getPublicationPreFPRReviewersString(activePub.PubRecord.PreFPRReviewers_Not_Found__c);
        database.update(activePub.PubRecord,true);
        
        if ( isFprSubmitter) {  
            return new PageReference(AppearUrlModel.AppearFprSubmitterMenuUrl(ActiveSubMenu, ActiveTile, PubId));
        } else {
            return new PageReference(AppearUrlModel.AppearPubMenuUrl(ActiveSubMenu, ActiveTile, PubId));
        }
    }  
    
    private transient PublicationPreFprReviewer__c pNewPubPreFprReviewMember = null;
    public PublicationPreFprReviewer__c NewPubPreFprReviewMember { //insert from model
        get {
            if (pNewPubPreFprReviewMember == null) {                
                pNewPubPreFprReviewMember = new PublicationPreFprReviewer__c();
                pNewPubPreFprReviewMember.Publication__c = PubId;
            }
            return pNewPubPreFprReviewMember;
        }
        set {
            pNewPubPreFprReviewMember = value;
        }
    }
    
    
    public PageReference saveNewPreFprReviewer() {
        //def 281
        //Changed for Functional pub team
        if ( ProfileModel.isAppearBusinessAdmin || ProfileModel.isSysAdmin || ProfileModel.isAppearGPPL || 
            ProfileModel.isAppearWriting || ProfileModel.isAppearExternalWriter || ProfileModel.isAppearFPRC || ProfileModel.isAppearIntFPRC || ProfileModel.isAppearFprOnlySubmitter || ProfileModel.isAppear626 || ProfileModel.isAppearPubTeam || profilemodel.isAppearReviewers || ProfileModel.isAppearFunctionalPubTeam ) {
                
            if ( pNewPubPreFprReviewMember.PreFprReviewer__c == null ){
                //error do not save
                ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.FATAL, 
                    AppearErrorMessages.NeedNewPreFprReviewer);
 
                ApexPages.addMessage(myMsg);     
                AppLogModel.LogError('PubPreFprReviewerModel::saveNewPreFprReviewer', AppearErrorMessages.NeedNewPreFprReviewer, PubId);                                   
                AppLogModel.flushLogs();
                
                return null; //to show error
            }
            insert pNewPubPreFprReviewMember;         
            
            pPubPreFprReviewerList = null;
        } else {
            String errorMsg = 'You do not have permission to edit PreFPR Reviewer List';
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.FATAL, errorMsg);
     
            ApexPages.addMessage(myMsg);     
            AppLogModel.LogError('PubPreFprReviewerModel::saveNewPreFprReviewer', errorMsg, PubId);
            return null;
        }

        if ( isFprSubmitter) {  
            return new PageReference(AppearUrlModel.AppearFprSubmitterMenuUrl(ActiveSubMenu, ActiveTile, PubId));
        } else {
            return new PageReference(AppearUrlModel.AppearPubMenuUrl(ActiveSubMenu, ActiveTile, PubId));
        }
    }
    
    /*** CR 247 03/19/2014 
    public string ValidAppearRoles {
        get {
            return AppearRoleModel.ValidAppearRoles;
        }
    }
    ***/
    @future
    public static void CopyPubTeamMembersAsPreFprReviewerFuture(id pubId) {
        
        AppearPubModel activePub = new AppearPubModel(PubId);
        List<PublicationTeamMember__c> pubTeamMemberList = ActivePub.PubTeamMember.PubTeamMembers;
        CopyPubTeamMembersAsPreFprReviewer(pubTeamMemberList, pubid);
        
    }
    
    public static string CopyPubTeamMembersAsPreFprReviewer( List<PublicationTeamMember__c> pubTeamMemberList, id pubId) {
        AppLogModel.LogInfo('PubPreFprReviewerModel:CopyPubTeamMembersAsPreFprReviewer', 'start', PubId);
        
        List<PublicationPreFprReviewer__c> newPreFprReviewers = new List<PublicationPreFprReviewer__c>();
        for(PublicationTeamMember__c ptm :  pubTeamMemberList) {
            if ( !ptm.IsLogicallyDeleted__c ) {
                
                PublicationPreFprReviewer__c preFpr = new PublicationPreFprReviewer__c();
                // CR 247 03/19/2014 preFpr.Appear_Role__c = ptm.Appear_Role__c;
                preFpr.isSelected__c = false;
                preFpr.PreFprReviewer__c = ptm.Member__c;
                preFpr.Product_Indication__c = ptm.Product_Indication__c;
                preFpr.Publication__c = ptm.Publication__c;
                
                newPreFprReviewers.add(preFpr);
            }
        }
        
        insert newPreFprReviewers;
        
        AppLogModel.LogInfo('PubPreFprReviewerModel:CopyPubTeamMembersAsPreFprReviewer', 'completed', PubId);
        AppLogModel.flushLogs();
        return ''; //no error message to return     
    }
     

    
    
    ////////////// static ///////////////////
    //System.Debug(PubPreFprReviewerModel.getPubPreFprReviewers('a00K0000002CAeL'));
    
    public static List<PublicationPreFprReviewer__c> getPubPreFprReviewers(Id PubId) {
        if ( PubId == null) {
            return null;
        }
        //Defect 260 CC 12 Adding PreFPRReviewersNotFound
        List<PublicationPreFprReviewer__c> pubPreFprReviewerTeamList = [ 
            select id, 
            Publication__c, isSelected__c,
            Product_Indication__c, Product_Indication__r.Name,
            PreFprReviewer__c, PreFprReviewer__r.Name, PreFprReviewer__r.UserId__c,
            Appear_Role__c, Appear_Role__r.Name,Publication__r.PreFPRReviewers_Not_Found__c
            from PublicationPreFprReviewer__c
            where Publication__c = :PubId 
        ];
        
        string msg = 'PublicationPreFprReviewer__c retrieved ' + pubPreFprReviewerTeamList.size()+' records for PubId = '+PubId;
        System.Debug(msg);
        
        
        return pubPreFprReviewerTeamList;
    }
    
}