force-app/main/default/staticresources/python/Disappear/src/objects/Appear_Role__c.object
<CustomObject>
    <description>All Roles in the Appear System
Will use Record Type to distinguish between different group of roles</description>
    <label>Appear Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appear Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PubAttachmentDetails__c.object
<CustomObject>
    <description>Junction object of a Blob [  attachment / Chatter Feed / Document etc ]  &amp; Pub

since we cannot add custom fields to attachment 
and need a unified way to extract a list of all documents related to a pub</description>
    <fields>
        <fullName>AttachmentType__c</fullName>
        <description>Indicate the type of &apos;Blob&apos; this detail record describes</description>
        <label>AttachmentType</label>
        <picklist>
            <picklistValues>
                <fullName>Publication Proposal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kick Off Meeting Minutes/Memo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Author Agreement Letter/Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft - Share with Authors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft Sent for FPR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Added by FPR Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Added by FPR Reviewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final Attachment for Author Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Author Approvals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Author Contribution(s)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted Version</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted Version</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Response to Author Invitation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Substantial Comments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Response to Final Author Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval to Remove Author</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Author Disclosures</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval to Add Author</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RAE Attestation Sec A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RAE Attestation Sec B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RAE Attestation Sec C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monitoring Checklist Part 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monitoring Checklist Part 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monitoring Checklist Part 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monitoring Checklist Part 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Author Limit Justification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change of Pub RAE Form</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monitoring Overrule</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Attachment Details</relationshipLabel>
        <relationshipName>Attachment_Details</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Attachment Detail</label>
    <nameField>
        <displayFormat>AD-{000000000}</displayFormat>
        <label>AttachDetailId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attachment Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PubEmail__c.object
<CustomObject>
    <description>Object is created to store Emails send to Authors</description>
    <fields>
        <fullName>Author__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field is used to store the author record whom the emails are send</description>
        <label>Author</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Publication Emails</relationshipLabel>
        <relationshipName>Publication_Emails</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publication Email</label>
    <nameField>
        <displayFormat>Pub-Email-{000000}</displayFormat>
        <label>Publication Email</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <fields>
        <fullName>Assigned_FPRC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned to FPR Coordinator</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Target__c</fullName>
        <description>The Current Target field will also be used to populate the Target field for a new Submission Cycle.
This field should NEVER be moved to a formula</description>
        <inlineHelpText>This field is populated automatically by using the &quot;Target&quot; button on the Details tile.  If the desired target is NOT found using the Target button, please use the &quot;Target Not Found&quot; field below.</inlineHelpText>
        <label>Current Target</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GPP_Type__c</fullName>
        <description>Used for Classification of GPP publication and mandatory for if Publication is GPP type.</description>
        <label>Publication Classification</label>
        <picklist>
            <picklistValues>
                <fullName>CSP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSP Encore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Deliverable</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Publication_Title__c</fullName>
        <inlineHelpText>This is a succinct but descriptive Title of the Publication</inlineHelpText>
        <label>Publication Title</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>RAE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Responsible Amgen Employee (RAE)</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PubME__c.object
<CustomObject>
    <description>Record all Manuscript Equivalent points award to authors and others for their work on a publication</description>
    <fields>
        <fullName>AppearRole__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The Role that the Pub Team member played in the preparation of this Publication

Will be used to look up Awarded ME in PubTypeME</description>
        <inlineHelpText>APPEAR Roles include: Writing Coordinator, Writer, Editorial Support, GPPL, and Pub Specialist.</inlineHelpText>
        <label>Appear Role</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Appear_Role__c.isWritingRole__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Appear_Role__c</referenceTo>
        <relationshipLabel>Publication MEs</relationshipLabel>
        <relationshipName>Publication_MEs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Publication MEs</relationshipLabel>
        <relationshipName>Publication_MEs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WritingRoleMember__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Writing Role Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Publication MEs</relationshipLabel>
        <relationshipName>Publication_MEs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publication ME</label>
    <nameField>
        <displayFormat>PME-{000000000}</displayFormat>
        <label>Publication ME Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication MEs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/Email_20_RAEChecklist.cls
/*
*** Class Details *** 
Email_20_RAEChecklist class is used to trigger email notification to RAE & WCs. Email will be triggered when Monitoring Checklist Part 1/2/3 type
attachment added.
*/

public class Email_20_RAEChecklist extends AppearEmailBase {
	
	public Email_20_RAEChecklist(){ 
		super();
	}
	
	public Email_20_RAEChecklist(List<Id> aCon,id attachmentId,Id emailTemplateId,User userId,String monitoringDL){
		super();
		replyTo(userId.email); 
		ToAddresses(aCon);
        CcAddress(monitoringDL);
        whatId(attachmentId);
        templateId(emailTemplateId);
        targetObjectId(aCon[0]); 
	}
	
	@future
	public static void Email_20_RAEChecklistBatch(Id attchmentDetailsId,Id pubId){
		EmailTemplate emailTemplateId = [select id,name,Isactive,Folder.Name from EmailTemplate Where IsActive = true And (Folder.Name = 'Monitoring Checklist Folder') order by createdDate desc limit 1];
        
        PubAttachmentDetails__c pubAttachment = [Select Id, AttachmentType__c,Publication__c,Publication__r.Name,Publication__r.Current_Target__c,
        											Publication__r.RAE__c, publication__r.GPP_Type__c,publication__r.Publication_Title__c from
        											PubAttachmentDetails__c where id =:attchmentDetailsId];
        
        User currentUser = [Select email from User where username = :UserInfo.getUserName() limit 1];
        
        Contact monitoringContact=[Select Id,FirstName,LastName,Email from Contact where Name = 'Monitoring Team'];
       
        List<id> receipentIds = new List<Id>();
        if(pubAttachment.Publication__r.RAE__c != null)
        receipentIds.add(pubAttachment.Publication__r.RAE__c); 
        
        //Email will be triggered only to the Writing role members who have Appear Role as Writing Coordinator, GPPL // Appear Enhancement Backlog R4:2017
        //List<PubME__c> writingRoleMember = [SELECT Id,WritingRoleMember__c FROM PubME__c WHERE AppearRole__r.Name ='Writing Coordinator' and Publication__c =:pubId];
        List<PubME__c> writingRoleMember = [SELECT Id,WritingRoleMember__c FROM PubME__c WHERE AppearRole__r.Name in ('Writing Coordinator','GPPL') and Publication__c =:pubId];
        
        for(PubME__c wc : writingRoleMember){
        	receipentIds.add(wc.WritingRoleMember__c);
        }
        
        System.debug('$$$$$$$$$$$'+receipentIds);
        List<PubEmail__c> monitoredEmailNotificationList = new List<PubEmail__c>();
        if(receipentIds.size()>0){
        	
        		try{
	        		Email_20_RAEChecklist email = new Email_20_RAEChecklist(receipentIds,pubAttachment.Id,emailTemplateId.Id,currentUser,monitoringContact.email);
	        		if (!email.sendEmailWithResult()){
                    	System.debug('Email_20_RAEChecklist / failed to deliver to:' + pubAttachment.Id ); 
                	}
        			
        		}catch (AppearException appearEx){
        			
        		}catch (EmailException emailEx) {
                    // ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, 'The invitation email delivery to ' + pubAuthorList[i].author__r.email + ' failed. Please validate if the email address is correct. If the problem persists, please contact the system administrator.' + ' Error Details: ' + emailEx.getMessage()));
                    AppLogModel.LogError('Email_20_RAEChecklistBatch', 'The monitoring email delivery to '+receipentIds);                   
                } catch(DmlException dmlEx) {
                    // ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, 'The invitation email delivery to ' + pubAuthorList[i].author__r.email + ' failed. Please validate if the email address is correct. If the problem persists, please contact the system administrator.' + ' Error Details: ' + dmlEx.getMessage()));
                    AppLogModel.LogError('Email_20_RAEChecklistBatch', 'The monitoring email delivery to ' + receipentIds, pubAttachment.Id);                   
                } finally {
                    AppLogModel.flushLogs();
                }
        		
        	
        }										
         
	}
}