force-app/main/default/staticresources/python/Disappear/src/objects/Appear_Role__c.object
<CustomObject>
    <description>All Roles in the Appear System
Will use Record Type to distinguish between different group of roles</description>
    <fields>
        <fullName>IsLogicallyDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Expired</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isWritingRole__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Select this checkbox for system to copy a publication team member to PubME table to award ME</description>
        <label>isWritingRole</label>
        <type>Checkbox</type>
    </fields>
    <label>Appear Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appear Roles</pluralLabel>
    <recordTypes>
        <fullName>PubTeamRole</fullName>
        <active>true</active>
        <label>PubTeamRole</label>
    </recordTypes>
    <recordTypes>
        <fullName>ReviewTeamRole</fullName>
        <active>true</active>
        <label>ReviewTeamRole</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/ContactDelegate__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Delegates (Delegated To)</relationshipLabel>
        <relationshipName>ContactDelegatedTo</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Delegate__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Delegate To</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Delegates (Delegated By)</relationshipLabel>
        <relationshipName>ContactDelegatedBy1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Contact Delegate</label>
    <nameField>
        <displayFormat>CDEL-{0000000}</displayFormat>
        <label>ContactDelegate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Delegates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/ProdIndTeamMember__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Members of Team</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>ProdInd_Team_Members</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>isLogicallyDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>InActive</label>
        <type>Checkbox</type>
    </fields>
    <label>Product Indication Team Member</label>
    <nameField>
        <displayFormat>PITM-{000000}</displayFormat>
        <label>ProductIndicationTeam Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Indication Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/ProductIndication__c.object
<CustomObject>
    <fields>
        <fullName>isLogicallyDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Expired</label>
        <type>Checkbox</type>
    </fields>
    <label>Product Indication</label>
    <nameField>
        <label>ProductIndication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Indications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <fields>
        <fullName>Assigned_FPRC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned to FPR Coordinator</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FPR_Submitter__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>FPR_Submitter will record the latest person that click on the Submit to FPR button.

DO NOT USE this field to check if a pub is an FPR Only Pub</description>
        <label>FPR Submitter</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Publication (FPR Submitter)</relationshipLabel>
        <relationshipName>FPR_Submitter</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Author__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>First Author</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Publication (First Author)</relationshipLabel>
        <relationshipName>Publication2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PASS__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Related to the associated oublication study/project</description>
        <label>PASS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RAE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Responsible Amgen Employee (RAE)</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <recordTypes>
        <fullName>Review</fullName>
        <active>true</active>
        <label>Review</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PubME__c.object
<CustomObject>
    <description>Record all Manuscript Equivalent points award to authors and others for their work on a publication</description>
    <fields>
        <fullName>AppearRole__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The Role that the Pub Team member played in the preparation of this Publication

Will be used to look up Awarded ME in PubTypeME</description>
        <inlineHelpText>APPEAR Roles include: Writing Coordinator, Writer, Editorial Support, GPPL, and Pub Specialist.</inlineHelpText>
        <label>Appear Role</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Appear_Role__c.isWritingRole__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Appear_Role__c</referenceTo>
        <relationshipLabel>Publication MEs</relationshipLabel>
        <relationshipName>Publication_MEs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Publication MEs</relationshipLabel>
        <relationshipName>Publication_MEs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WritingRoleMember__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Writing Role Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Publication MEs</relationshipLabel>
        <relationshipName>Publication_MEs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publication ME</label>
    <nameField>
        <displayFormat>PME-{000000000}</displayFormat>
        <label>Publication ME Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication MEs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Review_Team__c.object
<CustomObject>
    <description>Review team for DataSource or SubGroup

A review team can exists for a DataSource without SubGroup</description>
    <fields>
        <fullName>IsLogicallyDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Expired</label>
        <type>Checkbox</type>
    </fields>
    <label>Review Team</label>
    <nameField>
        <label>Review Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Review Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/ReviewTeamMember__c.object
<CustomObject>
    <fields>
        <fullName>Appear_Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Appear Role</label>
        <referenceTo>Appear_Role__c</referenceTo>
        <relationshipLabel>Review Team Members</relationshipLabel>
        <relationshipName>Review_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReviewTeamMember__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Review Team Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Review Team Members</relationshipLabel>
        <relationshipName>Review_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Review_Team__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Review Team</label>
        <referenceTo>Review_Team__c</referenceTo>
        <relationshipLabel>Review Team Members</relationshipLabel>
        <relationshipName>Review_Team_Members</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReviewerType__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Primary</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Notify</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FPA Approver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FPA Comments Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FPA Copy Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FPA Delegate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FPA Triagee</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Review Team Member</label>
    <nameField>
        <displayFormat>RTM-{00000000}</displayFormat>
        <label>Review Team Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Review Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Study__c.object
<CustomObject>
    <fields>
        <fullName>Amgen_Ind__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Amgen Indicator</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsLogicallyDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Expired</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PASS__c</fullName>
        <defaultValue>false</defaultValue>
        <description>PASS field/flag for tracking.</description>
        <label>PASS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Posted_on_ClinTrials__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Posted on Clinical Trials</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>StudySponsor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sponsor Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Studies</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Study/Project</label>
    <nameField>
        <label>Study/Project #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Studies/Projects</pluralLabel>
    <recordTypes>
        <fullName>Study</fullName>
        <active>true</active>
        <label>Study</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/ContactReplacementUtilityTest.cls
@IsTest
public with sharing class ContactReplacementUtilityTest {
	
	@IsTest
	public static void unitTest(){
		
		
		//Creating Product
		AmgenProductModelData.createData();
		
		//Creating Indication		
		IndicationModelData.createData();
		
		TherapeuticAreaModelData.createData();
		
		//Creating Prod Indication	
		ProductIndicationModelData.createData();
		
		//Creating DataSource		
		DataSourceModelData.createData();
		
		//Creating Subgroup
		SubGroupModelData.createData();
		
		//Review team for Subgroup
		ReviewTeamModelData.createData();
		
		//Account
		AccountModelData.createData();
		
		//Contact
		List<Contact> ConList = new List<Contact>();
		
		ConList.add(new Contact(AccountId=AccountModelData.AmgenAccount.Id ,
			lastname='Ruesga',firstname='Cid',
			userid__c=UserModelData.cruesgaUser.Id));
		ConList.add(new Contact(AccountId=AccountModelData.AmgenAccount.Id ,
			lastname='Schoen',firstname='Brandon',
			userid__c=UserModelData.bschoenUser.Id));
		ConList.add(new Contact(AccountId=AccountModelData.AmgenAccount.Id ,
			lastname='Delegate',firstname='test',
			userid__c=UserModelData.bschoenUser.Id));
        insert ConList;
        
        //Contact Delegate
        List<ContactDelegate__c> conDelegate= new List<ContactDelegate__c>();
        conDelegate.add(new ContactDelegate__c(Contact__c=ConList[0].Id,Delegate__c=ConList[2].Id,End_Date__c=system.today(),IsActive__c=true,Start_Date__c=system.today()));
		insert conDelegate;
		
		//Appear Role
		RecordType reviewTeamRoleRecType = RecordTypeModel.LookupRecordType('Appear_Role__c','ReviewTeamRole');
		RecordType pubTeamRoleRecType = RecordTypeModel.LookupRecordType('Appear_Role__c','PubTeamRole');
		List<Appear_Role__c> roleList = new List<Appear_Role__c>();
        roleList.add( new Appear_Role__c(name= 'FPR Reviewer', isWritingRole__c = false, RecordTypeId = reviewTeamRoleRecType.id));
        roleList.add( new Appear_Role__c(name= 'Writer', isWritingRole__c = true,RecordTypeId = pubTeamRoleRecType.id));
		insert roleList;        
		
		Appear_Role__c FprReviewRole =AppearRoleModel.AppearRoleMapByName.get('FPR Reviewer');
		System.assertNotEquals(null, FprReviewRole);
		
		//Review Team Member
		List <ReviewTeamMember__c> ReviewTeamMemberList = new List <ReviewTeamMember__c> ();
		ReviewTeamMemberList.add(new ReviewTeamMember__c(Review_Team__c= ReviewTeamModelData.abarelixOncologyDevelopmentSmpReviewTeam.Id ,
			ReviewTeamMember__c=ConList[0].id, Appear_Role__c=FprReviewRole.Id,ReviewerType__c = 'Primary'));         
		       
		Insert ReviewTeamMemberList;
		
		Publication__c newPub = UnitTestData.PublicationNew('TestSaveProdInd');
		
		newPub.Assigned_FPRC__c=ConList[0].Id;
		newPub.First_Author__c=ConList[0].Id;
		newPub.FPR_Submitter__c=ConList[0].Id;
		newPub.RAE__c=ConList[0].Id;
		update newPub;
		
		set<string> prodIndicationStringSet = new set<string>();
        
        for(ProductIndication__c pi : ProductIndicationModel.ProductIndicationList) {
        	prodIndicationStringSet.add(pi.name);
        	if ( prodIndicationStringSet.size() > 5) break;
        }
		PubProdIndModel.insertPubProdInd(newPub.id, prodIndicationStringSet);
		
		List<ProdIndTeamMember__c> pubProdIndMember= new List<ProdIndTeamMember__c>();
		pubProdIndMember.add( new ProdIndTeamMember__c(Contact__c=ConList[0].Id,isLogicallyDeleted__c=false));
		insert pubProdIndMember;
		
		List<study__c> study= new List<Study__c>();
		study.add( new Study__c(Amgen_Ind__c=false,IsLogicallyDeleted__c=false,PASS__c=false,Posted_on_ClinTrials__c=false,StudySponsor__c=ConList[0].Id));
		insert study;
		
		List<PubME__c> pubMes= new List<PubME__c>();
		pubMes.add(new PubME__c(WritingRoleMember__c=ConList[0].Id,Publication__c=newPub.id,AppearRole__c=roleList[1].Id));
		insert pubMes;
		
		ContactReplacementUtility.ReplaceContact(ConList[0].Id, ConList[1].Id);
	
	}		
}