force-app/main/default/staticresources/python/Disappear/src/objects/Appear_Role__c.object
<CustomObject>
    <description>All Roles in the Appear System
Will use Record Type to distinguish between different group of roles</description>
    <fields>
        <fullName>isWritingRole__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Select this checkbox for system to copy a publication team member to PubME table to award ME</description>
        <label>isWritingRole</label>
        <type>Checkbox</type>
    </fields>
    <label>Appear Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appear Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <recordTypes>
        <fullName>Execute</fullName>
        <active>true</active>
        <label>Execute</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PubME__c.object
<CustomObject>
    <description>Record all Manuscript Equivalent points award to authors and others for their work on a publication</description>
    <fields>
        <fullName>ActualME__c</fullName>
        <description>Actual ME = Calculated ME unless a Business Admin enters the Override ME for this record</description>
        <label>Actual Me</label>
        <precision>6</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AppearRole__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The Role that the Pub Team member played in the preparation of this Publication

Will be used to look up Awarded ME in PubTypeME</description>
        <inlineHelpText>APPEAR Roles include: Writing Coordinator, Writer, Editorial Support, GPPL, and Pub Specialist.</inlineHelpText>
        <label>Appear Role</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Appear_Role__c.isWritingRole__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Appear_Role__c</referenceTo>
        <relationshipLabel>Publication MEs</relationshipLabel>
        <relationshipName>Publication_MEs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CalculatedME__c</fullName>
        <description>ME from PubType / Role / Scope of Work calculation</description>
        <label>Calculated ME</label>
        <precision>6</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OverrideME__c</fullName>
        <description>Available for Business Admin to override the calculated ME</description>
        <label>Override ME</label>
        <precision>6</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Publication MEs</relationshipLabel>
        <relationshipName>Publication_MEs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReasonForMEChange__c</fullName>
        <label>Reason For ME Change</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Siebel_Actual__c</fullName>
        <description>This field contains the Actual Pub ME Migrated from Siebel system.
Appear WILL NOT be writing into this field after data migration has been completed
it can be used to create reports to make sure Actual ME for Legacy pub did not get change by accident.</description>
        <label>Siebel_Actual</label>
        <precision>6</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <label>Publication ME</label>
    <nameField>
        <displayFormat>PME-{000000000}</displayFormat>
        <label>Publication ME Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication MEs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/BatchSwitchPubMeCalcAndActual.cls
global class BatchSwitchPubMeCalcAndActual extends BatchBase 
    implements Database.Batchable<SObject>,Database.Stateful {

    public String SOQL = 'select ReasonForMEChange__c,Siebel_Actual__c, ActualME__c, CalculatedME__c, OverrideME__c from PubME__c where CreatedBy.Name = \'Amgen DataMigration\' and ActualME__c <> null';
    
    public BatchSwitchPubMeCalcAndActual() {
        super();
        if ( Test.isRunningTest()){
            SOQL = SOQL + ' limit 10';
        }
        AddMessage(SOQL);
        system.debug(SOQL);
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        batchableContext = BC;
        batchName = 'BatchSwitchPubMeCalcAndActual';
        System.Debug(SOQL);
        return Database.getQueryLocator(SOQL);
    }
    

    global void execute(Database.BatchableContext BC, List<PubME__c> PubMeList){
        doIt(PubMeList);
    }
    
    global static void doIt(List<PubME__c> PubMeList) {
        List<PubME__c> updateList = new List<PubME__c>();
        for(PubME__c pubME : PubMeList) {
            if ( pubME.ActualME__c <> null) {
                pubME.CalculatedME__c = pubME.ActualME__c;
                pubME.OverrideME__c = pubME.ActualME__c;
                pubME.Siebel_Actual__c = pubME.ActualME__c;
                pubME.ReasonForMEChange__c = 'Adjusted ME of '+pubME.ActualME__c+ ' migrated from Siebel System';
                updateList.add(pubME);
            }
        }
        
        update updateList;

        AppLogModel.flushLogs();    
    }
    

    global void finish(Database.BatchableContext BC){
        SendBatchCompletionEmail();
    }
    
    //BatchSwitchPubMeCalcAndActual.runNow();
    public static void runNow(){
        BatchSwitchPubMeCalcAndActual batch = new BatchSwitchPubMeCalcAndActual();
        Database.executeBatch(batch, 1000);
    }
    
    //BatchSwitchPubMeCalcAndActual.runOne('Pub-Id-000019');
    public static void runOne(string PubId){
        if ( pubID == '')return;
        
        List<PubME__c> pubs = [
            Select ActualME__c, CalculatedME__c, OverrideME__c from PubME__c 
            where publication__r.name = :PubId
        ]; 
        doIt(pubs);
        
    }

//////////////////////////////////////////  unit test /////////////////////////////////////
    
    private static testMethod void unitTest() {
        Publication__c pub = CreateData();
        
        BatchSwitchPubMeCalcAndActual.runNow();
        
        // code changes as per CHG0049014: make APPEAR ROLE lookup field rquired in publication ME  
        List<Appear_Role__c> ARList=AppearRoleModel.AppearRoleList.clone();
        List<Appear_Role__c> RoleList=new List<Appear_Role__c>();
        
        for(Appear_Role__c AR:ARList){
            if(AR.isWritingRole__c==true){
               RoleList.add(AR);
            }
        }
       //CHG0049014: end
        
        PubME__c pme = new PubME__c();
        pme.ActualME__c = 1.0;
        pme.Publication__c = pub.Id;
        //pme.AppearRole__c = AppearRoleModel.AppearRoleList[0].id;
        pme.AppearRole__c=RoleList[0].id;
        insert pme;
        
        List<PubME__c> pubMeList = new List<PubME__c>();
        pubMeList.add(pme);
        System.assertEquals(1.0, pme.ActualME__c);
        System.assertEquals(null, pme.CalculatedME__c);
                
        BatchSwitchPubMeCalcAndActual.doIt(pubMeList);
        System.assertEquals(1.0, pme.ActualME__c);
        System.assertEquals(1.0, pme.CalculatedME__c);
    } 
    
    public static Publication__c CreateData() {
        AppearRoleModelData.createData();
        Publication__c pub = UnitTestData.PublicationNew('switchME');
        return pub;
    }
}