force-app/main/default/staticresources/python/Disappear/src/objects/Appear_Role__c.object
<CustomObject>
    <description>All Roles in the Appear System
Will use Record Type to distinguish between different group of roles</description>
    <label>Appear Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Appear Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Review_Team__c.object
<CustomObject>
    <description>Review team for DataSource or SubGroup

A review team can exists for a DataSource without SubGroup</description>
    <label>Review Team</label>
    <nameField>
        <label>Review Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Review Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/ReviewTeamMember__c.object
<CustomObject>
    <fields>
        <fullName>Appear_Role__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Appear Role</label>
        <referenceTo>Appear_Role__c</referenceTo>
        <relationshipLabel>Review Team Members</relationshipLabel>
        <relationshipName>Review_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReviewTeamMember__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Review Team Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Review Team Members</relationshipLabel>
        <relationshipName>Review_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Review_Team__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Review Team</label>
        <referenceTo>Review_Team__c</referenceTo>
        <relationshipLabel>Review Team Members</relationshipLabel>
        <relationshipName>Review_Team_Members</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Review Team Member</label>
    <nameField>
        <displayFormat>RTM-{00000000}</displayFormat>
        <label>Review Team Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Review Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/ReviewTeamMemberModelData.cls
public  class ReviewTeamMemberModelData {

    /*public static void createData() {
    
        integer dataCount = [select count() from ReviewTeamMember__c];
        if ( dataCount <> 0) return;
        
        List<ReviewTeamMember__c> ReviewTeamMemberList = new List<ReviewTeamMember__c>();
                   
                   
            string RT1 = 'Aranesp - CKD Not Dialysis - Global Dev - LACAN';
            string RT2 = 'Aranesp - CKD Not Dialysis - Development - NAMT';
            string RT3 = 'Aranesp - CKD Not Dialysis - Development - GRAAS';       
            
           	Contact solange = AppearContactModel.findContactByName('Solange', 'Weiss')[0];    
			Contact melissa = AppearContactModel.findContactByName('Melissa', 'Seal')[0]; 
                   
            ReviewTeamMemberList.add(new ReviewTeamMember__c(Review_Team__c= ReviewTeamModel.ReviewTeamNameMap.get(RT1).Id ,
            	ReviewTeamMember__c=solange.id, Appear_Role__c=AppearRoleModel.AppearRoleMapByName.get('GPPL').Id));         
            ReviewTeamMemberList.add(new ReviewTeamMember__c(Review_Team__c= ReviewTeamModel.ReviewTeamNameMap.get(RT2).Id ,
            	ReviewTeamMember__c=melissa.id, Appear_Role__c=AppearRoleModel.AppearRoleMapByName.get('Medical Writer').Id));         
            ReviewTeamMemberList.add(new ReviewTeamMember__c(Review_Team__c= ReviewTeamModel.ReviewTeamNameMap.get(RT3).Id ,
            	ReviewTeamMember__c=solange.id, Appear_Role__c=AppearRoleModel.AppearRoleMapByName.get('GPPL').Id));         
            ReviewTeamMemberList.add(new ReviewTeamMember__c(Review_Team__c= ReviewTeamModel.ReviewTeamNameMap.get(RT3).Id ,
            	ReviewTeamMember__c=melissa.id, Appear_Role__c=AppearRoleModel.AppearRoleMapByName.get('Medical Writer').Id));         
      
            Insert ReviewTeamMemberList;
                
     }*/
    
}