force-app/main/default/staticresources/python/Disappear/src/objects/AppLog__c.object
<CustomObject>
    <fields>
        <fullName>PubId__c</fullName>
        <description>Pub ID - Name of the publication record</description>
        <label>PubId</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Appear Logs</relationshipLabel>
        <relationshipName>Appear_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>logSubjectId__c</fullName>
        <description>The salesforce id of the primary sObject of this AppLog Record
For example the id of a Publication that this log record is about.</description>
        <label>logSubjectId</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Appear Log</label>
    <nameField>
        <displayFormat>AL-{000000000}</displayFormat>
        <label>AppLog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appear Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <recordTypes>
        <fullName>Execute</fullName>
        <active>true</active>
        <label>Execute</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/BatchAppLogPubId.cls
global class BatchAppLogPubId extends BatchBase
	implements Database.Batchable<SObject>,Database.Stateful {
   	public static String SOQL = 'select logSubjectId__c, pubId__c ' +
   		'from AppLog__c  ';
   	
	public BatchAppLogPubId() {
		super();
    	if ( Test.isRunningTest()){
    		SOQL = SOQL + ' limit 10';
    	} else {
    		//BL made change during rel 2.0 rollout to avoid scanning 8M rows of AppLog
    		SOQL = SOQL + ' where pubId__c = null order by createdDate desc ' 
    			+ 'limit 1000000';  //100k max per batch max
    	}
    	AddMessage(SOQL);
        system.debug(SOQL);
	}
	
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        batchableContext = BC;
        batchName = 'BatchAppLogPubId';
        System.Debug(SOQL);
        return Database.getQueryLocator(SOQL);
    }

    global void execute(Database.BatchableContext BC, List<AppLog__c> logs){
		updatelog(logs);
    }  
    
    private static void updateLog(List<AppLog__c> logs) {
    	set<id> pubIds = new set<id>();
    	for (AppLog__c log : logs){
    		pubIds.add(log.logSubjectId__c);
    	}
		List<publication__c> pubs = [select id, Name from Publication__c where id in :pubIds];
		
		Map<id,string> pubIdMap = new Map<id,string>();
		for(publication__c pub : pubs) {
			pubIdMap.put(pub.id, pub.name);
		}
		
		for (AppLog__c log : logs){
    		if (pubIdMap.containsKey(log.logSubjectId__c) ) {
    			log.pubId__c = pubIdMap.get(log.logSubjectId__c);
    		} else {
    			log.pubId__c = 'N/A';
    		}
    	}
    	database.update(logs, false);    	
    }
    
    //BatchAppLogPubId.updatePubIdNow();    
    global static void updatePubIdNow() {
    	String onDemandSOQL = SOQL + ' limit 10000 ';
		List<AppLog__c> logs = Database.query(onDemandSOQL); 
		updateLog(logs);	
    }

    global void finish(Database.BatchableContext BC){
		SendBatchCompletionEmail();
		BatchAppLogArchive.runNow();
	}
	
	//BatchAppLogPubId.runNow();
	public static void runNow(){
    	BatchAppLogPubId batch = new BatchAppLogPubId();
        Database.executeBatch(batch, 1000);
	}	

//////////////////////////////////////////  unit test /////////////////////////////////////
	@isTest( seeAllData = true)
	private static void unitTest() {
		BatchAppLogPubId.updatePubIdNow();
		BatchAppLogPubId.runNow();
	} 
}