force-app/main/default/staticresources/python/Disappear/src/objects/AppLog__c.object
<CustomObject>
    <fields>
        <fullName>MessageType__c</fullName>
        <label>MessageType</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Appear Logs</relationshipLabel>
        <relationshipName>Appear_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Appear Log</label>
    <nameField>
        <displayFormat>AL-{000000000}</displayFormat>
        <label>AppLog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appear Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/FPR_Cycle__c.object
<CustomObject>
    <description>record name will be PubId-{0000000}-FPRCycle-{00}</description>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>FPR Cycles</relationshipLabel>
        <relationshipName>FPR_Cycles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>FPR Cycle</label>
    <nameField>
        <label>FPR_Cycle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FPR Cycles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <fields>
        <fullName>Current_FPRCycle_Id_Formula__c</fullName>
        <formula>PubStatus__r.FPR_Cycle__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current FPR Cycle Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_SubmissionCycle_Id_Formula__c</fullName>
        <formula>PubStatus__r.Submission_Cycle__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current Submission Cycle Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PubStatus__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Current status of this publication</description>
        <label>PubStatus</label>
        <referenceTo>PubStatus__c</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PubStatus__c.object
<CustomObject>
    <description>List of Status for a Publication - Target Date / Revised Date / Actual Date
Will be used for planning</description>
    <fields>
        <fullName>FPR_Cycle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FPR Cycle</label>
        <referenceTo>FPR_Cycle__c</referenceTo>
        <relationshipName>Pub_Statuses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publication Status</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>PubStatus Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/SubmissionCycle__c.object
<CustomObject>
    <description>record name will be PubId-{0000000}-SubCycle-{00}</description>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Submission Cycles</relationshipLabel>
        <relationshipName>Submission_Cycles</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Submission Cycle</label>
    <nameField>
        <label>Submission Cycle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submission Cycles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/AppearDataTest.cls
public class AppearDataTest {

    public static void checkPub(List<Publication__c> pubListBatch) {
        //find all pub without a pubStatus or  submission Cycle
        For(Publication__c p : pubListBatch) {
            if ( p.PubStatus__c == null) {
                AppLogModel.LogError('AppearDataTest::checkPub', 'Pub - '+p.name+' missing PubStatus__c');
            }
            if ( p.Current_SubmissionCycle_Id_Formula__c == null) {
                AppLogModel.LogError('AppearDataTest::checkPub', 'Pub - '+p.name+' missing Current_SubmissionCycle_Id_Formula__c');
            }
        }
        
        AppLogModel.flushLogs();
    }


    public static void checkPubStatus(List<Publication__c> pubListBatch, boolean reportCorrectlyLinked) {
        //find all pubStatus that does not belong to a publication
        
        //find all pub that links to PubStatus with wrong pub id
    
    }
        
    

    public static void checkSubmissionCycle(List<Publication__c> pubListBatch, boolean reportCorrectlyLinked) {
        //find all submission Cycle that does not belong to a publication
        
        //find all pub that links to SubmissionCycle with wrong pub id      
        
        //1 find a set of id for Current_SubmissionCycle_Id_Formula__c
        Set<id> subIds = new set<id>();
        for(Publication__c p : pubListBatch) {
            subIds.add(p.Current_SubmissionCycle_Id_Formula__c);
        }
        
        List<SubmissionCycle__c> subCycles = [
            select id, publication__c 
            from SubmissionCycle__c
            where id in :subIds
            order by name
        ];
        
        map<id,SubmissionCycle__c> SubPubIdMap = new map<id,SubmissionCycle__c>();
        for(SubmissionCycle__c sc : subCycles){
            SubPubIdMap.put(sc.id, sc);
        }
        
        for(publication__c p : pubListBatch){
            if ( SubPubIdMap.containsKey(p.Current_SubmissionCycle_Id_Formula__c)) {
                SubmissionCycle__c sc = SubPubIdMap.get(p.Current_SubmissionCycle_Id_Formula__c);
                Id subPubId = sc.publication__c;
                if ( subPubId == p.id) {
                    if ( reportCorrectlyLinked) {
                        AppLogModel.LogInfo('AppearDataTest::checkSubmissionCycle', 'Pub - '+p.name+' ['+p.id+'] links to Current_SubmissionCycle_Id_Formula__c ['+p.Current_SubmissionCycle_Id_Formula__c+'] correctly.',
                            p.id);
                    } 
                } else {
                    AppLogModel.LogError('AppearDataTest::checkSubmissionCycle', 'Pub - '+p.name+' ['+p.id+'] Current_SubmissionCycle_Id_Formula__c ['+p.Current_SubmissionCycle_Id_Formula__c+'] in SubmissionCycle__c link to another pub  ' +subPubId,
                        p.id);
                }
                
            } else {
                AppLogModel.LogError('AppearDataTest::checkSubmissionCycle', 'Pub - '+p.name+' ['+p.id+'] Current_SubmissionCycle_Id_Formula__c ['+p.Current_SubmissionCycle_Id_Formula__c+'] does not exists in SubmissionCycle__c');
            }
        }
        
        AppLogModel.flushLogs();
        
    }

    public static void checkFprCycle(List<Publication__c> pubListBatch, boolean reportCorrectlyLinked) {
        //find all FPR Cycle that does not belong to a publication  
        
        //find all pub that links to FPR Cycle with wrong pub id    
        
        //1 find a set of id for Current_FPRCycle_Id_Formula__c
        Set<id> FcIds = new set<id>();
        for(Publication__c p : pubListBatch) {
            FcIds.add(p.Current_FPRCycle_Id_Formula__c);
        }
        
        List<FPR_Cycle__c> fcCycles = [
            select id, publication__c 
            from FPR_Cycle__c
            where id in :FcIds
            order by Name
        ];  
        
        map<id,FPR_Cycle__c> FcPubIdMap = new map<id,FPR_Cycle__c>();
        for(FPR_Cycle__c fc : fcCycles){
            FcPubIdMap.put(fc.id, fc);
        }
        
        for(publication__c p : pubListBatch){
            if (  p.Current_FPRCycle_Id_Formula__c <> null  && FcPubIdMap.containsKey(p.Current_FPRCycle_Id_Formula__c)) {
                
                FPR_Cycle__c fc = FcPubIdMap.get(p.Current_FPRCycle_Id_Formula__c);
                Id fcPubId = fc.publication__c;

                if ( fcPubId == p.id) {
                    if ( reportCorrectlyLinked){
                        AppLogModel.LogInfo('AppearDataTest::checkFprCycle', 'Pub - '+p.name+' ['+p.id+'] links to Current_FPRCycle_Id_Formula__c ['+p.Current_FPRCycle_Id_Formula__c+'] correctly.');
                    }
                } else {
                    AppLogModel.LogError('AppearDataTest::checkFprCycle', 'Pub - '+p.name+' ['+p.id+'] Current_FPRCycle_Id_Formula__c ['+p.Current_FPRCycle_Id_Formula__c+'] in FPR_Cycle__c link to another pub  ' +fcPubId);
                }
                
            } else if (p.Current_FPRCycle_Id_Formula__c <> null) {
                AppLogModel.LogError('AppearDataTest::checkFprCycle', 'Pub - '+p.name+' ['+p.id+'] Current_FPRCycle_Id_Formula__c ['+p.Current_FPRCycle_Id_Formula__c+'] does not exists in FPR_Cycle__c');
            }
        }
        
        AppLogModel.flushLogs();    
    }
    
    private static set<Id> pPubIds = null;
    public static set<id> PubIds {
        get {
            if ( pPubIds == null) {
                pPubIds = new Set<id>();
                for(Publication__c p : PubList) {
                    pPubIds.add(p.id);
                }
            }
            return pPubIds;
        }
    }
    
    private static List<Publication__c>  pPubList = null;
    public static List<Publication__c> PubList {
        get {
            
            if (pPubList == null) {
        
                pPubList = [
                    select id, name, PubStatus__c, Current_SubmissionCycle_Id_Formula__c, Current_FPRCycle_Id_Formula__c
                    
                    from Publication__c
                    order by name
                    limit 500
                ];
            }
            return pPubList;
        }
    }
    
    public static void cleanDataTestLog() {
        List<AppLog__c> logs = [
            select id 
            from AppLog__c
            where MessageType__c like 'AppearDataTest::%'
        ];
        
        Delete logs;        
    }   
    
    
    public static void RunAll() {
        AppearDataTest.cleanDataTestLog();
        
        AppearDataTest.checkPub(PubList);
        AppearDataTest.checkSubmissionCycle(PubList, true);
        AppearDataTest.checkFprCycle(PubList, true);
    }
    
    
    @IsTest
    public static void UnitTest() {
        
        AppearDataTest.RunAll();
        Set<Id> PubId = new Set<Id>();
        Publication__c  newPub = UnitTestData.PublicationNew('Fpr Controller Pub');
        pubId.add(newPub.Id);
        //AppearDataTest.PubIds = pubId;
        
    }
    
}