force-app/main/default/staticresources/python/Disappear/src/objects/Author_Identity__c.object
<CustomObject>
    <fields>
        <fullName>Author_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Contact</description>
        <label>Author Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Author_Identities</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Identity_Number__c</fullName>
        <description>ID Number which can be a alphanumeric value</description>
        <inlineHelpText>Identifier Value</inlineHelpText>
        <label>Identity Number</label>
        <length>15</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Identity_Type__c</fullName>
        <description>Type of the identifier allowed for the Author/Contact</description>
        <inlineHelpText>Provide the Identifier Type for the Contact</inlineHelpText>
        <label>Identity Type</label>
        <picklist>
            <picklistValues>
                <fullName>National Provider Identifier (NPI)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Identifier</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Contact Identifier</label>
    <nameField>
        <displayFormat>CI-{0000000}</displayFormat>
        <label>Contact Identifier Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Identifiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/ContactIdentifierTriggerLogicTest.cls
@IsTest
public class ContactIdentifierTriggerLogicTest{
    
    @IsTest
    public static void unitTest1(){
        List<Contact> contactList=new List<Contact>();
        AccountModelData.createData();  
        contactList.add(new Contact(LastName= 'CI', FirstName='test1',AccountId=AccountModel.AccountNameMap.get('AMGEN').Id, Email='test1@amgen.com'));
        contactList.add(new Contact(LastName= 'CI', FirstName='test2',AccountId=AccountModel.AccountNameMap.get('AMGEN').Id, Email='test2@amgen.com'));
        contactList.add(new Contact(LastName= 'CI', FirstName='test3',AccountId=AccountModel.AccountNameMap.get('AMGEN').Id, Email='test3@amgen.com'));
        insert contactList;
        
        Author_Identity__c authIdentity= new Author_Identity__c();
        authIdentity.Author_Contact__c=contactList[0].Id;
        authIdentity.Identity_Number__c='CI001';
        authIdentity.Identity_Type__c='National Provider Identifier (NPI)';
        insert authIdentity;
        
        Author_Identity__c authIdentity2= new Author_Identity__c();
        authIdentity2.Author_Contact__c=contactList[0].Id;
        authIdentity2.Identity_Number__c='CI0003';
        authIdentity2.Identity_Type__c='National Provider Identifier (NPI)';
        insert authIdentity2;
        
        
        Author_Identity__c authIdentity3= new Author_Identity__c();
        authIdentity3.Author_Contact__c=contactList[0].Id;
        authIdentity3.Identity_Number__c='ABC123';
        authIdentity3.Identity_Type__c='Others';
        insert authIdentity3;
        
        authIdentity.Identity_Type__c='Others';
        authIdentity.Identity_Number__c='CI002';
        authIdentity2.Identity_Type__c='Others';
        authIdentity2.Identity_Number__c='CI003';

        update authIdentity;
        update authIdentity2;
        authIdentity2.Identity_Type__c='National Provider Identifier (NPI)';
        authIdentity2.Identity_Number__c='123ABC2';
        update authIdentity2;
        
        delete authIdentity;
        delete authIdentity2; 
        delete authIdentity3;
    }
}