force-app/main/default/staticresources/python/Disappear/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>UserId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PubAttachmentDetails__c.object
<CustomObject>
    <description>Junction object of a Blob [  attachment / Chatter Feed / Document etc ]  &amp; Pub

since we cannot add custom fields to attachment 
and need a unified way to extract a list of all documents related to a pub</description>
    <fields>
        <fullName>AttachmentType__c</fullName>
        <description>Indicate the type of &apos;Blob&apos; this detail record describes</description>
        <label>AttachmentType</label>
        <picklist>
            <picklistValues>
                <fullName>Publication Proposal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kick Off Meeting Minutes/Memo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Author Agreement Letter/Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft - Share with Authors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft Sent for FPR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Added by FPR Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Added by FPR Reviewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final Attachment for Author Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Author Approvals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Author Contribution(s)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted Version</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted Version</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Response to Author Invitation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Substantial Comments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Response to Final Author Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval to Remove Author</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Author Disclosures</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval to Add Author</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RAE Attestation Sec A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RAE Attestation Sec B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RAE Attestation Sec C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monitoring Checklist Part 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monitoring Checklist Part 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monitoring Checklist Part 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monitoring Checklist Part 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Author Limit Justification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change of Pub RAE Form</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monitoring Overrule</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Attachment_URL__c</fullName>
        <label>Attachment URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Attachment Details</relationshipLabel>
        <relationshipName>Attachment_Details</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>isLogicallyDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isLogicallyDeleted</label>
        <type>Checkbox</type>
    </fields>
    <label>Attachment Detail</label>
    <nameField>
        <displayFormat>AD-{000000000}</displayFormat>
        <label>AttachDetailId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attachment Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/pubAuthor__c.object
<CustomObject>
    <fields>
        <fullName>Author__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Author</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Publication Authors</relationshipLabel>
        <relationshipName>Publication_Authors</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CommentReceivedDate__c</fullName>
        <description>Stores the author comment received date</description>
        <label>CommentReceivedDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Publication Authors</relationshipLabel>
        <relationshipName>Publication_Authors</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>isLogicallyDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used for logical deletion or soft deletion of Pub Authors.</description>
        <label>isLogicallyDeleted</label>
        <type>Checkbox</type>
    </fields>
    <label>Publication Author</label>
    <nameField>
        <displayFormat>PA-{0000000}</displayFormat>
        <label>Publication Author Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/ContentVersionTriggerLogic.cls
public with sharing class ContentVersionTriggerLogic {
    
    public static void contentVersionAfterInsertLogic(List<ContentVersion> conVersList){        
        
        set<id> contentDocumentSet = new set<Id>();
        for(ContentVersion conVer : conVersList){
            contentDocumentSet.add(conVer.ContentDocumentId);
        }
        
        /*Fetching the First Content Version ID of all the content version documents inserted*/
        List<ContentVersion> firstVersionIdList = [Select Id, ContentDocumentId from contentversion where contentdocumentId in :contentDocumentSet
                                                    and VersionNumber = '1'];
        // Fetching the ORG URL
        String baseURL = KeyValueSettingsModel.GetKey('ChatterFeedItem_BaseDomain').value__c;
        
        Map<Id,Id> attachmentDetailMap = new Map<Id,Id>();
        Map<String,Id> attchmntURLMap = new Map<String,Id>();
        List<string> attachmentURLList = new List<string>();
        for(ContentVersion cv : firstVersionIdList){
            attachmentURLList.add(baseURL + '/' +cv.Id);
            attchmntURLMap.put(baseURL + '/' +cv.Id,cv.ContentDocumentId);
        }
        List<PubAttachmentDetails__c> dsAttachmentList = [Select Id,AttachmentType__c,Attachment_URL__c,Publication__c from PubAttachmentDetails__c where
                                                            AttachmentType__c = 'Draft - Share with Authors' and Attachment_URL__c in :attachmentURLList ];
        
        set<Id> publicationIdSet = new set<Id>();
        for(PubAttachmentDetails__c pad : dsAttachmentList){
            publicationIdSet.add(pad.Publication__c);
            attachmentDetailMap.put(attchmntURLMap.get(pad.Attachment_URL__c),pad.Id);
        }
        
        Map<id,PubAuthor__c> authorUserIdAuthorMap =  new Map<id,pubAuthor__c>(); //Appear Enhancement R5 : Update CommentReceivedDate__c on new content version upload
        
        List<pubAuthor__c> pubAuthorList = [Select Id, Author__c,Author__r.UserId__c,CommentReceivedDate__c from pubAuthor__c where Publication__c in :publicationIdSet and isLogicallyDeleted__c = false]; //Appear Enhancement R5 : CommentReceivedDate__c added in the query
        set<Id> authorUserIdSet = new set<Id>();
        if(!pubAuthorList.isEmpty()){
            for(pubAuthor__c pubAuth : pubAuthorList){
                authorUserIdSet.add(pubAuth.Author__r.UserId__c);
                 authorUserIdAuthorMap.put(pubAuth.Author__r.UserId__c,pubAuth);//Appear Enhancement R5 : Update CommentReceivedDate__c on new content version upload
            }
        }
        
        /* Inserting comments in Feed Item*/
        List<FeedItem> feedItemList = new List<FeedItem>();
        
        PubAuthor__c authorCommentUpdate ;//Appear Enhancement R5 : Update CommentReceivedDate__c on new content version upload
        Boolean check = false;//Appear Enhancement R5 : Update CommentReceivedDate__c on new content version upload
        List<Database.Saveresult> sr;//Appear Enhancement R5 : Update CommentReceivedDate__c on new content version upload
        
        for(ContentVersion contentVersion : conVersList){
            if(contentVersion.VersionNumber != '1' && attachmentDetailMap.get(contentVersion.ContentDocumentId)!= null && authorUserIdSet.contains(contentVersion.CreatedById)){
                feedItemList.add(new FeedItem(parentid = attachmentDetailMap.get(contentVersion.ContentDocumentId), RelatedRecordId =contentVersion.Id, 
                                          createdbyid =contentVersion.CreatedById, CreatedDate= contentVersion.CreatedDate,  
                                          Body= 'Please See Attached',
                                          Type= 'TextPost', Visibility= 'AllUsers'));
              
	             //Appear Enhancement R5 : Update CommentReceivedDate__c on new content version upload : start//
	             authorCommentUpdate =  authorUserIdAuthorMap.get(contentVersion.CreatedById); 
	             if(authorCommentUpdate.CommentReceivedDate__c == null){
	             authorCommentUpdate.CommentReceivedDate__c= System.Now();
	             check = true;
	             }
	             //Appear Enhancement R5 : Update CommentReceivedDate__c on new content version upload : end//
            }
        }
        try{
            //insert feedItemList;
            sr = database.insert(feedItemList, true);//Appear Enhancement R5 : Update CommentReceivedDate__c on new content version upload
            //Appear Enhancement R5 : Update CommentReceivedDate__c on new content version upload : start//
            if (authorCommentUpdate != null && check == true && sr[0].isSuccess() ){
               update authorCommentUpdate;
            }
            //Appear Enhancement R5 : Update CommentReceivedDate__c on new content version upload : end//
        }catch(DMLException de){
            system.debug('DML Exception caught'+de);
        }
        
    }
}