force-app/main/default/staticresources/python/Disappear/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Isselected__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used for author</description>
        <label>Isselected</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <fields>
        <fullName>IsSelected__c</fullName>
        <defaultValue>false</defaultValue>
        <description>for UI operation - please do not store or migrate data into this field</description>
        <label>IsSelected</label>
        <type>Checkbox</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PublicationTeamMember__c.object
<CustomObject>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Pub Team Member links to Contact</description>
        <label>Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>PublicationTeams</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipName>PublicationTeams</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Publication Team Member</label>
    <nameField>
        <displayFormat>PubT-{00000000}</displayFormat>
        <label>PublicationTeam Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/PubPreFprReviewerModelTest.cls
@IsTest
public with sharing class PubPreFprReviewerModelTest {
	
	private static AppearPubModel createData() {
        Publication__c pub = UnitTestData.PublicationNew('PubPreFprReviewerModelTest');
        
        System.assertNotEquals(null, pub);
        System.assertNotEquals(null, pub.id);
        
        System.Debug('*** PubId = '+Pub.id);    
        
        AppearPubModel pubModel = new AppearPubModel(Pub.Id, '', '', true);
        return pubModel;
	}
	
	@IsTest
	public static void UnitTest() {
		AppearPubModel pubModel = createData();
        Id userId = userInfo.getUserId();
		
		
        PubPreFprReviewerModel.InsertFprSubmitter(pubModel.PubId, userId);//fail with no assoc. contact
		
        Contact contact1 = new Contact(lastname='testing',firstname='contact1',userid__c=userId);
        insert contact1;
        
        pubModel.PreFprReviewer.NewPubPreFprReviewMember.PreFprReviewer__c = contact1.id;
        pubModel.PreFprReviewer.saveNewPreFprReviewer();
        
        PubPreFprReviewerModel.InsertFprSubmitter(pubModel.PubId, userId);
        
        Contact contact2 = new Contact(lastname='testing',firstname='contact2',userid__c=userId);
        insert contact2;
        
        List<PublicationTeamMember__c> mockMembers = new List<PublicationTeamMember__c>();
        PublicationTeamMember__c mockMember1 = new PublicationTeamMember__c();
        mockMember1.Publication__c = pubModel.PubId;
        mockMember1.Member__c = contact2.id;        
        mockMembers.add(mockMember1);
        
        System.assertEquals(2, pubModel.PreFprReviewer.PubPreFprReviewerList.size());
        
        
        PubPreFprReviewerModel.CopyPubTeamMembersAsPreFprReviewer(mockMembers, pubModel.PubId);
        pubModel.PreFprReviewer.clearCache(); 
        
        System.assertEquals(3, pubModel.PreFprReviewer.PubPreFprReviewerList.size());
        
        pubModel.PreFprReviewer.Save();
        
        pubModel.PreFprReviewer.PubPreFprReviewerList[1].IsSelected__c = true;
        pubModel.PreFprReviewer.deleteSelected();
        
        PubPreFprReviewerModel.InsertFprSubmitter(pubModel.PubId, userId);//fail with too many assoc. contact
        
        PubPreFprReviewerModel.CopyPubTeamMembersAsPreFprReviewerFuture(pubModel.PubId);
	}
	
	@IsTest
	public static void FailCases() {
		 Publication__c pub = UnitTestData.PublicationNew('PubPreFprReviewerModelTestFailCases');
        
        AppearPubModel pubModel = new AppearPubModel(Pub.Id);
        System.AssertNotEquals(null,pubModel.PreFprReviewer.NewPubPreFprReviewMember); //lazy-load for fail cases
        pubModel.PreFprReviewer.saveNewPreFprReviewer(); //cycling error cases
        
	}
}