force-app/main/default/staticresources/python/Disappear/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Emp_Type__c</fullName>
        <description>This field is used to identify Amgen Internal or External Contact.</description>
        <label>Employee Type</label>
        <picklist>
            <picklistValues>
                <fullName>Contingent Worker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ext Bus Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Intern</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temporary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vendor</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Department__c.object
<CustomObject>
    <fields>
        <fullName>isLogicallyDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Expired</label>
        <type>Checkbox</type>
    </fields>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/FPR_Cycle__c.object
<CustomObject>
    <description>record name will be PubId-{0000000}-FPRCycle-{00}</description>
    <fields>
        <fullName>FPR_Cycle_Num__c</fullName>
        <label>FPR Cycle Num</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>FPR Cycles</relationshipLabel>
        <relationshipName>FPR_Cycles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>FPR Cycle</label>
    <nameField>
        <label>FPR_Cycle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FPR Cycles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Organization__c.object
<CustomObject>
    <fields>
        <fullName>isLogicallyDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Expired</label>
        <type>Checkbox</type>
    </fields>
    <label>Organization</label>
    <nameField>
        <label>Organization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <fields>
        <fullName>Department__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Department</label>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization</label>
        <referenceTo>Organization__c</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PubStatus__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Current status of this publication</description>
        <label>PubStatus</label>
        <referenceTo>PubStatus__c</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PubME__c.object
<CustomObject>
    <description>Record all Manuscript Equivalent points award to authors and others for their work on a publication</description>
    <fields>
        <fullName>ActualME__c</fullName>
        <description>Actual ME = Calculated ME unless a Business Admin enters the Override ME for this record</description>
        <label>Actual Me</label>
        <precision>6</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AppearRole__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The Role that the Pub Team member played in the preparation of this Publication

Will be used to look up Awarded ME in PubTypeME</description>
        <inlineHelpText>APPEAR Roles include: Writing Coordinator, Writer, Editorial Support, GPPL, and Pub Specialist.</inlineHelpText>
        <label>Appear Role</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Appear_Role__c.isWritingRole__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Appear_Role__c</referenceTo>
        <relationshipLabel>Publication MEs</relationshipLabel>
        <relationshipName>Publication_MEs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CalculatedME__c</fullName>
        <description>ME from PubType / Role / Scope of Work calculation</description>
        <label>Calculated ME</label>
        <precision>6</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Department</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Department__c.isLogicallyDeleted__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <infoMessage>Please do not select [EXPIRED] Department values</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>Publication MEs</relationshipLabel>
        <relationshipName>Publication_MEs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Emp_Type__c</fullName>
        <description>This field indicates whether the Writing Role Member is Amgen Full Time Employee or Outsourced</description>
        <label>Emp. Type</label>
        <picklist>
            <picklistValues>
                <fullName>Contingent Worker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ext Bus Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Intern</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temporary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vendor</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FPR_Cycle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FPR Cycle</label>
        <referenceTo>FPR_Cycle__c</referenceTo>
        <relationshipLabel>Publication MEs</relationshipLabel>
        <relationshipName>Publication_MEs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LegacyPrior_ActualME__c</fullName>
        <label>LegacyPrior ActualME</label>
        <precision>6</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MeCycleNum__c</fullName>
        <defaultValue>0</defaultValue>
        <description>ME Cycle Num - starts at 0 for new records.</description>
        <inlineHelpText>Used to differentiate between Non-Material-Changes within an FPR cycle.  
if no NMC - then ME cycle # = FPR Cycle #.</inlineHelpText>
        <label>ME Cycle #</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field to identify the Organization of the Writing Role Member</description>
        <label>Company</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Organization__c.isLogicallyDeleted__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <infoMessage>Please do not select [EXPIRED] Company values</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Organization__c</referenceTo>
        <relationshipLabel>Publication MEs</relationshipLabel>
        <relationshipName>Publication_MEs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OverrideME__c</fullName>
        <description>Available for Business Admin to override the calculated ME</description>
        <label>Override ME</label>
        <precision>6</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PubStatus__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication Status</label>
        <referenceTo>PubStatus__c</referenceTo>
        <relationshipLabel>Publication MEs</relationshipLabel>
        <relationshipName>Publication_MEs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Publication MEs</relationshipLabel>
        <relationshipName>Publication_MEs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReasonForMEChange__c</fullName>
        <label>Reason For ME Change</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Submission_Cycle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Submission Cycle</label>
        <referenceTo>SubmissionCycle__c</referenceTo>
        <relationshipLabel>Publication MEs</relationshipLabel>
        <relationshipName>Publication_MEs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WritingRoleMember__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Writing Role Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Publication MEs</relationshipLabel>
        <relationshipName>Publication_MEs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publication ME</label>
    <nameField>
        <displayFormat>PME-{000000000}</displayFormat>
        <label>Publication ME Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication MEs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PubStatus__c.object
<CustomObject>
    <description>List of Status for a Publication - Target Date / Revised Date / Actual Date
Will be used for planning</description>
    <fields>
        <fullName>FPR_Cycle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FPR Cycle</label>
        <referenceTo>FPR_Cycle__c</referenceTo>
        <relationshipName>Pub_Statuses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsLogicallyDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to logically delete the record.

Release 1.1 Renamed isLogicallyDeleted to Expired</description>
        <label>Expired</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Submission_Cycle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Submission Cycle</label>
        <referenceTo>SubmissionCycle__c</referenceTo>
        <relationshipName>Pub_Statuses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publication Status</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>PubStatus Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/SubmissionCycle__c.object
<CustomObject>
    <description>record name will be PubId-{0000000}-SubCycle-{00}</description>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Submission Cycles</relationshipLabel>
        <relationshipName>Submission_Cycles</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Submission_Cycle_Num__c</fullName>
        <label>Submission Cycle #</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Submission Cycle</label>
    <nameField>
        <label>Submission Cycle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submission Cycles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/PubMeModelNoSharing.cls
public without sharing class PubMeModelNoSharing {

	public static void PersistPubMeList( List<sObject> pubMeList) {
		
		//All Or Nothing - should be set to true - and generate error if any row failed to persist
		database.update(pubMeList, true);
	}
	
	// pubMeList includes all Writing roles from the ALL submission cycleS - need to filter to only current cycle
	// it must be sorted in order of created date for this function to work....
	// we will order it by name - which is an autonumber in the SOQL retrieval
	
	/*
	public static List<PubME__C> copyMEforResent(List<PubMe__c> PubMeList, id PubId, SubmissionCycle__c CurrentSubmissionCycle, FPR_Cycle__c fromFprCycle, FPR_Cycle__c toFprCycle) {
		AppLogModel.LogInfo('PubMeModelNoSharing::copyMEforResent', 'invoking copyMEforResent');
		return copyME(PubMeList, PubId, CurrentSubmissionCycle, fromFprCycle, CurrentSubmissionCycle, toFprCycle);
	}
	*/
	
	public static List<PubME__C> copyMEforNewSubmissionCycle(List<PubMe__c> PubMeList, id PubId, SubmissionCycle__c CurrentSubmissionCycle, 
		SubmissionCycle__c nextSubCycle, FPR_Cycle__c nextFprCycle, Id resentPubStatusId) {
			
		AppLogModel.LogInfo('PubMeModelNoSharing::copyMEforNewSubmissionCycle', 'invoking copyMEforNewSubmissionCycle', PubId);
		return copyME(PubMeList, PubId, CurrentSubmissionCycle, null, nextSubCycle,  nextFprCycle, resentPubStatusId);
	}	
	
	//same SC - New FC / MC
	public static 	List<PubME__C> copyMEforMaterialChange (List<PubMe__c> PubMeList, id PubId, SubmissionCycle__c fromSubmissionCycle, FPR_Cycle__c fromFprCycle,
		SubmissionCycle__c toSubCycle, FPR_Cycle__c toFprCycle, Id resentPubStatusId) {
			
		AppLogModel.LogInfo('PubMeModelNoSharing::copyMEforNewSubmissionCycle', 'invoking copyMEforNewSubmissionCycle', PubId);
		return copyME(PubMeList, PubId, fromSubmissionCycle, fromFprCycle, toSubCycle,  toFprCycle, resentPubStatusId);
	}
	
	public static 	List<PubME__C> copyMEforNonMaterialChange (List<PubMe__c> PubMeList, id PubId, id recentPubStatusId) {
		AppLogModel.LogInfo('PubMeModelNoSharing::copyMEforNonMaterialChange', 
			'invoking copyMEforNonMaterialChange with PubMeList.size() = '+PubMeList.size(), PubId);
		
		//Find Max ME
		integer MaxtMeCycleNum = 0;
		for(PubMe__c pubme : PubMeList){
			if (pubme.MeCycleNum__c > MaxtMeCycleNum) {
				MaxtMeCycleNum = Integer.valueOf(pubme.MeCycleNum__c);
			}
		}
		
		AppLogModel.LogDebug('PubMeModelNoSharing::copyMEforNonMaterialChange', 
			'MaxMeCycleNum = '+MaxtMeCycleNum, PubId);
		
		//make a copy of all PubME
		PubME__c pubMeFirstWC = null; 
		List<PubME__c> pubMeOtherList = new List<PubME__c>();
		boolean foundFirstWC = false; 
		integer NextMeCycleNum = MaxtMeCycleNum + 1;
		
		for(PubME__C pubme : PubMeList) {
			if ( pubme.MeCycleNum__c == MaxtMeCycleNum) {
				boolean isWritingCoordinatorRole = AppearRoleModel.isWritingCoordinatorRole(pubMe.AppearRole__c);
				if (!foundFirstWC && isWritingCoordinatorRole) {
					AppLogModel.LogInfo('PubMeModelNoSharing::copyMEforNonMaterialChange', 'Found PubME - first WC - '+pubme, PubId);			
					
					foundFirstWC = true;
					
					pubMeFirstWC = new PubME__c();
					pubMeFirstWC.AppearRole__c = pubMe.AppearRole__c;
					pubMeFirstWC.WritingRoleMember__c = pubMe.WritingRoleMember__c;
					pubMeFirstWC.Publication__c = PubId;
					pubMeFirstWC.Submission_Cycle__c = pubMe.Submission_Cycle__c;
					pubMeFirstWC.FPR_Cycle__c = pubMe.FPR_Cycle__c; 
					pubMeFirstWC.MeCycleNum__c = NextMeCycleNum;
					pubMeFirstWC.ActualME__c = 0.0;
					pubMeFirstWC.CalculatedME__c = 0.0;
					pubMeFirstWC.LegacyPrior_ActualME__c = 0.0;
					pubMeFirstWC.OverrideME__c = 0.0;
					pubMeFirstWC.ReasonForMEChange__c = '';
					pubMeFirstWC.Department__c = (pubME.Department__c != null && pubME.Department__r.isLogicallyDeleted__c == true) ? null : pubME.Department__c;
        			pubMeFirstWC.Organization__c = (pubME.Organization__c != null && pubME.Organization__r.isLogicallyDeleted__c == true) ? null : pubME.Organization__c;
					pubMeFirstWC.Emp_Type__c = pubME.Emp_Type__c;
					pubMeFirstWC.PubStatus__c = recentPubStatusId;
					insert pubMeFirstWC;  
					
					AppLogModel.LogInfo('PubMeModel::copyMEforNonMaterialChange', 'inserted - First WC - ' + pubMeFirstWC, PubId );
				} else {
					
					//now just duplicate the rest of ME record
					PubME__c pubOtherMe = new PubME__c();
					pubOtherMe.AppearRole__c = pubMe.AppearRole__c;
					pubOtherMe.WritingRoleMember__c = pubMe.WritingRoleMember__c;
					pubOtherMe.Publication__c = PubId;
					pubOtherMe.Submission_Cycle__c = pubMe.Submission_Cycle__c;
					pubOtherMe.FPR_Cycle__c = pubMe.FPR_Cycle__c;
					pubOtherMe.MeCycleNum__c = NextMeCycleNum;
					pubOtherMe.ActualME__c = 0.0;
					pubOtherMe.CalculatedME__c = 0.0;
					pubOtherMe.LegacyPrior_ActualME__c = 0.0;
					pubOtherMe.OverrideME__c = 0.0;
					pubOtherMe.ReasonForMEChange__c = '';	
					pubOtherMe.Department__c = (pubME.Department__c != null && pubME.Department__r.isLogicallyDeleted__c == true) ? null : pubME.Department__c;
        			pubOtherMe.Organization__c = (pubME.Organization__c != null && pubME.Organization__r.isLogicallyDeleted__c == true) ? null : pubME.Organization__c;
					pubOtherMe.Emp_Type__c = pubME.Emp_Type__c;
					pubOtherMe.PubStatus__c = recentPubStatusId;
					
					pubMeOtherList.add(pubOtherMe);		
				}				
			} else {
				AppLogModel.LogInfo('PubMeModel::copyMEforNonMaterialChange', 'skipped - pubME.MeCycleNum__c <> ' + MaxtMeCycleNum, pubId);
			}
		}
		
		insert pubMeOtherList;
		AppLogModel.LogInfo('PubMeModel::copyMEforNonMaterialChange', 'inserted - pubMeOtherList. size= ' + pubMeOtherList.size(), PubId );
		if (pubMeFirstWC <> null ) {
			pubMeOtherList.add(pubMeFirstWC);
		}
		AppLogModel.flushLogs();
		return pubMeOtherList;
	}
	

	//overload created just for deployment - to be deleted
	public static 	List<PubME__C> copyME (List<PubMe__c> PubMeList, id PubId, SubmissionCycle__c fromSubmissionCycle, FPR_Cycle__c fromFprCycle,
		SubmissionCycle__c toSubCycle, FPR_Cycle__c toFprCycle) {
		return null;
	}

	public static 	List<PubME__C> copyME (List<PubMe__c> PubMeList, id PubId, SubmissionCycle__c fromSubmissionCycle, FPR_Cycle__c fromFprCycle,
		SubmissionCycle__c toSubCycle, FPR_Cycle__c toFprCycle, Id PubStatusId) {
	
		String paramMsg = '';
		AppLogModel.LogInfo('PubMeModelNoSharing::copyME', 'invoking copyME ' + paramMsg, PubId);
		
		//only copy the first WC and mark new record as isResend
		PubME__c pubMeFirstWC = null;
		List<PubME__c> pubMeOtherList = new List<PubME__c>();
		
		boolean copyAllFprCycle = false;
		Id previousFprCycleId = null;
		Fpr_Cycle__c prevFC;
		
		if ( fromFprCycle == null) {
			copyAllFprCycle = true;
			AppLogModel.LogInfo('PubMeModelNoSharing::copyME', ' copyAllFprCycle = '+copyAllFprCycle, PubId );
		} else {
			AppLogModel.LogInfo('PubMeModelNoSharing::copyME', ' prev FC.num = ' + fromFprCycle.FPR_Cycle_Num__c, PubId);
		}
		
		
		Decimal lastMeCycleNum = 0.0;
		for(PubMe__c pubme : PubMeList){
			if (pubme.MeCycleNum__c > lastMeCycleNum) {
				lastMeCycleNum = pubme.MeCycleNum__c;		
			}
		}
		integer NextMeCycleNum = Integer.valueOf(lastMeCycleNum) + 1;
		
		boolean foundFirstWC = false;  
		for(PubME__C pubme : PubMeList) {
			if ( pubMe.Submission_Cycle__c == fromSubmissionCycle.Id && (copyAllFprCycle || pubME.MeCycleNum__c == lastMeCycleNum) ) {
				//post release 2.0 change - use ME to differentiate for legacy records -  pubMe.FPR_Cycle__c == fromFprCycle.Id
				
				boolean isWritingCoordinatorRole = AppearRoleModel.isWritingCoordinatorRole(pubMe.AppearRole__c);
				if (!foundFirstWC && isWritingCoordinatorRole) {
					AppLogModel.LogInfo('PubMeModelNoSharing::copyME', 'Found PubME - first WC -  '+pubme, PubId);			
					
					foundFirstWC = true;
					
					pubMeFirstWC = new PubME__c();
					pubMeFirstWC.AppearRole__c = pubMe.AppearRole__c;
					pubMeFirstWC.WritingRoleMember__c = pubMe.WritingRoleMember__c;
					pubMeFirstWC.Publication__c = PubId;
					pubMeFirstWC.Submission_Cycle__c = toSubCycle.id;
					pubMeFirstWC.FPR_Cycle__c = toFprCycle.Id;
					pubMeFirstWC.MeCycleNum__c = NextMeCycleNum;
					pubMeFirstWC.ActualME__c = 0.0;
					pubMeFirstWC.CalculatedME__c = 0.0;
					pubMeFirstWC.LegacyPrior_ActualME__c = 0.0;
					pubMeFirstWC.OverrideME__c = 0.0;
					pubMeFirstWC.ReasonForMEChange__c = '';
					pubMeFirstWC.Department__c = (pubME.Department__c != null && pubME.Department__r.isLogicallyDeleted__c == true) ? null : pubME.Department__c;
        			pubMeFirstWC.Organization__c = (pubME.Organization__c != null && pubME.Organization__r.isLogicallyDeleted__c == true) ? null : pubME.Organization__c;
					pubMeFirstWC.Emp_Type__c = pubME.Emp_Type__c;
					pubMeFirstWC.PubStatus__c = PubStatusId;

					insert pubMeFirstWC;  
					
					AppLogModel.LogInfo('PubMeModel::copyME', 'inserted - First WC - ' + pubMeFirstWC, PubId );
				} else {
					
					//now just duplicate the rest of ME record
					PubME__c pubOtherMe = new PubME__c();
					pubOtherMe.AppearRole__c = pubMe.AppearRole__c;
					pubOtherMe.WritingRoleMember__c = pubMe.WritingRoleMember__c;
					pubOtherMe.Publication__c = PubId;
					pubOtherMe.Submission_Cycle__c = toSubCycle.Id;
					pubOtherMe.FPR_Cycle__c = toFprCycle.Id;
					pubOtherMe.MeCycleNum__c = NextMeCycleNum;
					pubOtherMe.ActualME__c = 0.0;
					pubOtherMe.CalculatedME__c = 0.0;
					pubOtherMe.LegacyPrior_ActualME__c = 0.0;
					pubOtherMe.OverrideME__c = 0.0;
					pubOtherMe.ReasonForMEChange__c = '';	
					pubOtherMe.Department__c = (pubME.Department__c != null && pubME.Department__r.isLogicallyDeleted__c == true) ? null : pubME.Department__c;
        			pubOtherMe.Organization__c = (pubME.Organization__c != null && pubME.Organization__r.isLogicallyDeleted__c == true) ? null : pubME.Organization__c;
					pubOtherMe.Emp_Type__c = pubME.Emp_Type__c;
					pubOtherMe.PubStatus__c = PubStatusId;
					
					pubMeOtherList.add(pubOtherMe);		
				}
			} else {
				
				string msg = '';
				if (pubMe.Submission_Cycle__c != fromSubmissionCycle.Id  ) {
					msg +=' skipped due to non current SC. ';
				}
				
				//if (pubMe.FPR_Cycle__c == fromFprCycle.Id  ) {
					//msg +=' skipped due to non different FprCycleId '+pubMe.FPR_Cycle__c + ' '+ fromFprCycle.Id ;
				if (pubME.MeCycleNum__c == lastMeCycleNum) {
					msg +=' skipped due to non different pubME.MeCycleNum__c '+pubME.MeCycleNum__c + ' '+ lastMeCycleNum;
				}
				
				AppLogModel.LogInfo('PubMeModelNoSharing::copyME', 
					'skip PubME - '+pubme.WritingRoleMember__r.name + 
					' SC = '+ pubme.Submission_Cycle__r.Submission_Cycle_Num__c +
					' FC = '+ pubme.FPR_Cycle__r.FPR_Cycle_Num__c, PubId);	
			}
		}	
		
		//de-dupe - priority given to WC
		//de-dupe by wc + Role
		
		Set<String> pubMeIdSet = new Set<string>();
		if ( pubMeFirstWc <> null) {
			string firstKey = pubMeFirstWC.WritingRoleMember__c + ' ' + pubMeFirstWC.Department__C + ' ' + pubMeFirstWC.Organization__C + ' ' + pubMeFirstWC.AppearRole__c;
			pubMeIdSet.add(firstKey);
		}
		
		List<PubME__C> pubMeNoDupe = new List<PubMe__c>();
		for(PubME__C pubMe : pubMeOtherList) {
			string key = pubMe.WritingRoleMember__c + ' ' + pubMe.Department__C + ' ' + pubMe.Organization__C + ' ' + pubMe.AppearRole__c;
			if ( pubMeIdSet.contains(key)) {
				//dupe - ignore
			} else {
				pubMeNoDupe.add(pubme);
				pubMeIdSet.add(key);
			}
		}
		
		//now insert the rest - that will give the first WC the lowest autonumber in the name field
		insert pubMeNoDupe;

		if (pubMeFirstWC <> null ) {
			pubMeNoDupe.add(pubMeFirstWC);
		}
				
		AppLogModel.flushLogs();
		return pubMeNoDupe;
	}
}