force-app/main/default/staticresources/python/Disappear/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <description>Country Picklist</description>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Balkans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia &amp; Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brazil</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brunei</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bulgaria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cambodia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central And Eastern Europe (CEE)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colombia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Costa Rica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Croatia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cyprus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Czech Republic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denmark</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dominican Republic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ecuador</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Egypt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>United States</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Emp_Type__c</fullName>
        <description>This field is used to identify Amgen Internal or External Contact.</description>
        <label>Employee Type</label>
        <picklist>
            <picklistValues>
                <fullName>Contingent Worker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ext Bus Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Intern</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temporary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vendor</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SponsoringDept__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>An external contact&apos;s sponsoring department</description>
        <inlineHelpText>An external contact&apos;s sponsoring department</inlineHelpText>
        <label>Sponsoring Dept</label>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>Sponsored Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Country__c.object
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/AppearContactModelData.cls
public class AppearContactModelData extends AppearBaseData {

    public static void createData() {
    
        integer dataCount = [select count() from Contact];
        if ( dataCount <> 0) return;
        
        List<Contact> ContactList = new List<Contact>();
        
        ContactList.add( new Contact(LastName= 'Dorner', FirstName='Michael', Country__c='United States', 
        	AccountId=AccountModelData.AmgenAccount.Id, 
            SponsoringDept__c=DepartmentModelData.GlobalHealthEconomicDept.Id,
            Emp_Type__c = 'Staff',
            Email='mike@amgen.com'));
        ContactList.add( new Contact(LastName= 'Weiss', FirstName='Solange', 
        	AccountId=AccountModelData.AmgenAccount.Id, 
            SponsoringDept__c=DepartmentModelData.GlobalMedicalWritingDept.Id,
            Emp_Type__c = 'Staff',
            Department='Global Medical Writing'));
        ContactList.add( new Contact(LastName= 'Maxwell', FirstName='Michelle', 
        	AccountId=AccountModelData.AmgenAccount.Id, 
            SponsoringDept__c=DepartmentModelData.GlobalMedicalWritingDept.Id,
            Emp_Type__c = 'Contigent',
            Department='Global Medical Writing'));
        ContactList.add( new Contact(LastName= 'Seal', FirstName='Melissa', 
        	AccountId=AccountModelData.AmgenAccount.Id, 
            SponsoringDept__c=DepartmentModelData.MedicalCommunicationsDept.Id,
            Emp_Type__c = 'Staff',
            Department='A new department'));
        ContactList.add( new Contact(LastName= 'Mahon', FirstName='Kelly', 
        	AccountId=AccountModelData.AmgenAccount.Id,
        	Emp_Type__c = 'Temp', 
            SponsoringDept__c=DepartmentModelData.MedicalCommunicationsDept.Id));
        
        insert ContactList;
                
     }
    
}