force-app/main/default/staticresources/python/Disappear/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Proxy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Proxy</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Proxy (Contact)</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/ProvisionDocumentVersion__c.object
<CustomObject>
    <fields>
        <fullName>ProvisionDocumentContent__c</fullName>
        <label>ProvisionDocumentContent</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <label>ProvisionDocumentVersion</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ProvisionDocumentVersion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ProvisionDocumentVersions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PubAttachmentDetails__c.object
<CustomObject>
    <description>Junction object of a Blob [  attachment / Chatter Feed / Document etc ]  &amp; Pub

since we cannot add custom fields to attachment 
and need a unified way to extract a list of all documents related to a pub</description>
    <fields>
        <fullName>AttachmentName__c</fullName>
        <label>AttachmentName</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AttachmentType__c</fullName>
        <description>Indicate the type of &apos;Blob&apos; this detail record describes</description>
        <label>AttachmentType</label>
        <picklist>
            <picklistValues>
                <fullName>Publication Proposal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kick Off Meeting Minutes/Memo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Author Agreement Letter/Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft - Share with Authors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft Sent for FPR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Added by FPR Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Added by FPR Reviewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final Attachment for Author Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Author Approvals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Author Contribution(s)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted Version</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted Version</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Response to Author Invitation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Substantial Comments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Response to Final Author Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval to Remove Author</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Author Disclosures</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval to Add Author</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RAE Attestation Sec A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RAE Attestation Sec B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RAE Attestation Sec C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monitoring Checklist Part 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monitoring Checklist Part 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monitoring Checklist Part 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monitoring Checklist Part 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Author Limit Justification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change of Pub RAE Form</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monitoring Overrule</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Attachment_URL__c</fullName>
        <label>Attachment URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Attachment Details</relationshipLabel>
        <relationshipName>Attachment_Details</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>What__c</fullName>
        <description>similar to WhatId in Activities - the what field stored the salesforce Id of the Blob
Can be Attachment, Content or Item Feed

Stored id as text since we cannot relates to Attachment, Content or ItemFeed</description>
        <label>What</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Attachment Detail</label>
    <nameField>
        <displayFormat>AD-{000000000}</displayFormat>
        <label>AttachDetailId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attachment Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/pubAuthor__c.object
<CustomObject>
    <fields>
        <fullName>ApprovalAcceptedDate__c</fullName>
        <description>The date the Approval Notice has been accepted</description>
        <label>Approval Accepted Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ApprovalSentDate__c</fullName>
        <description>The date the Approval notice has been sent out</description>
        <label>Approval Sent Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Approval_Disclaimer_ID__c</fullName>
        <description>Contains the ID of the approval disclaimer used</description>
        <label>Approval Disclaimer ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AuthorStatus__c</fullName>
        <label>AuthorStatus</label>
        <picklist>
            <picklistValues>
                <fullName>Pending Invite Delivery</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Invite Acceptance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invite Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invitation Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Publication Review by Authors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Author Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed Author Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Author__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Author</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Publication Authors</relationshipLabel>
        <relationshipName>Publication_Authors</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Disclaimer_ID__c</fullName>
        <description>Contains the ID of the invite disclaimer used</description>
        <label>Invite Disclaimer ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InviteAcceptedDate__c</fullName>
        <description>The date when the Author  has accepted the Invitation</description>
        <label>Invite Accepted Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>InviteSentDate__c</fullName>
        <description>The date the Invitation was sent out.</description>
        <label>Invite Sent Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Publication Authors</relationshipLabel>
        <relationshipName>Publication_Authors</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Publication Author</label>
    <nameField>
        <displayFormat>PA-{0000000}</displayFormat>
        <label>Publication Author Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <recordTypes>
        <fullName>Review</fullName>
        <active>true</active>
        <label>Review</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/PubAuthorModelNoSharingTest.cls
@IsTest
public class PubAuthorModelNoSharingTest {

    private static void createData() {
        OrganizationModelData.createData();
        DepartmentModelData.createData();
        AccountModelData.createData();
        AppearContactModelData.createData();
    }
    

    @IsTest
    public static void UnitTest() {     

        // test dat prep
        //createData();//Appear Enhancement R2
        Publication__c pub = UnitTestData.PublicationNew('SelectDeselectAuthorsTest');  
        Publication__c clonePub = UnitTestData.newPublication('SelectDeselectAuthorsTest2');
        AppearPubModel pubModel = new AppearPubModel(Pub.Id);

        // createPubAttachmentData(pubModel); 

        Id userId = userInfo.getUserId();              
        List<Contact> contactsToAdd = new List<Contact>();        
        Contact proxyContact = new Contact(lastname='testing',firstname='proxy',userid__c=userId);
        contactsToAdd.add(proxyContact);
        Contact newContact = new Contact(lastname='testing',firstname='apex',userid__c=userId,Proxy__c=proxyContact.id);
        contactsToAdd.add(newContact);
        Contact triageContact = new Contact(lastname='testing',firstname='triage',userid__c=userId);
        contactsToAdd.add(triageContact);
        Contact triageContact2 = new Contact(lastname='testing',firstname='triage2',userid__c=userId);
        contactsToAdd.add(triageContact2);
        Contact delegateContact = new Contact(lastname='testing',firstname='delegate',userid__c=userId);
        contactsToAdd.add(delegateContact);
        insert contactsToAdd;

        ProvisionDocumentVersion__c comp = new ProvisionDocumentVersion__c ();
        comp.ProvisionDocumentContent__c = 'testing123';   
        insert comp;        

        List<Contact> appearContacts = [Select id, FirstName from Contact limit 3];

         PageReference pageRef = new PageReference('/apex/AppearPub?sfdc.tabName=01ri00000004OaA'); 
         Test.setCurrentPage(pageRef);
        
        PubAuthorModelNoSharing aPubAuthorNoSharing = pubModel.PubAuthorNoSharing; 
        
        PubAuthor__c PubAuthInvite = new PubAuthor__c();
        PubAuthInvite.Publication__c = Pub.Id;
        PubAuthInvite.Author__c = appearContacts[0].Id;
        PubAuthInvite.InviteSentDate__c = date.today();
        PubAuthInvite.AuthorStatus__c='Pending Invite Acceptance';
        PubAuthInvite.Disclaimer_ID__c = comp.id;
        PubAuthInvite.InviteAccepteddate__c=null;
        insert PubAuthInvite;
        PubAuthor__c PubAuthReview = new PubAuthor__c();
        PubAuthReview.Publication__c = Pub.Id;
        PubAuthReview.Author__c = appearContacts[1].Id;
        PubAuthReview.InviteSentDate__c = date.today();
        PubAuthReview.AuthorStatus__c='Publication Review by Authors';
        PubAuthReview.Disclaimer_ID__c =comp.id;
        PubAuthReview.InviteAccepteddate__c = date.today();
        insert PubAuthReview;        
        PubAuthor__c PubAuthApprove = new PubAuthor__c();
        PubAuthApprove.Publication__c = Pub.Id;
        PubAuthApprove.Author__c = appearContacts[2].Id;
        PubAuthApprove.ApprovalSentDate__c = date.today();
        PubAuthApprove.AuthorStatus__c='Pending Author Approval';
        PubAuthApprove.Approval_Disclaimer_ID__c =   PubAuthorModelNoSharing.getLatestPubAuthorAttachmentId(Pub.Id); 
        PubAuthApprove.ApprovalAcceptedDate__c =null;
        System.Test.startTest();  //Appear Enhancement R2
        insert PubAuthApprove;     
        //System.Test.stopTest();
              
        Id aPubId = aPubAuthorNoSharing.PubId; 
        aPubAuthorNoSharing.PubId = aPubId;
        
        Id aPubAuthorId = aPubAuthorNoSharing.PubAuthorId; 
         aPubAuthorNoSharing.PubAuthorId = aPubAuthorId;
        
        pubAuthor__c aPubAuthorRecord = aPubAuthorNoSharing.PubAuthorRecord; 
        
        boolean aIsAuthorComm= PubAuthorModelNoSharing.IsAuthorComm; 
        
        id inviteId = PubAuthorModelNoSharing.getLatestInviteDisclaimerId();
        
        map<id, string> aApprovePubAuthorAttachmentMap = aPubAuthorNoSharing.ApprovePubAuthorAttachmentMap; 
        
        aPubAuthorNoSharing.pubIdForAttachment =  PubAuthorModelNoSharing.getLatestPubAuthorAttachmentId(Pub.Id); 
        Id aPubIdForAttachment = aPubAuthorNoSharing.pubIdForAttachment; 
        
        aPubAuthorNoSharing.remoteSetPubIdForAttachment(); 
        
        id   aCurrentPubAuthorAttachmentId =  aPubAuthorNoSharing.currentPubAuthorAttachmentId;
        
        pagereference aRef = aPubAuthorNoSharing.getInviteDisclaimerVersionPage();
        
        string approvalURL = aPubAuthorNoSharing.getApproveAttachmentURL();
        
        pubAuthor__c apubAuthorc =  PubAuthorModelNoSharing.findPubAuthorRecord(Pub.Id, userId);  

        Set<Id>  aSetId =  PubAuthorModelNoSharing.findContactForAppearUser(userId); 
        
        List<PubAuthor__c> aPubAuthorList = aPubAuthorNoSharing.PubAuthorList;
        
        List<PubAuthor__c> aAuthorList = PubAuthorModelNoSharing.getPubAuthors(pub.id);

        List<Publication__c> acheckPublicationId = PubAuthorModelNoSharing.checkPublicationId(pub.id); 

        Publication__c aPubRecord = aPubAuthorNoSharing.PubRecord;

        string CommentsByAuthors = aPubAuthorNoSharing.CommentsByAuthors; 
        aPubAuthorNoSharing.CommentsByAuthors = 'abc'; 

        Id aCurrentSubmissionCycleId =  aPubAuthorNoSharing.CurrentSubmissionCycleId;
        Id CurrentFprCycleId = aPubAuthorNoSharing.CurrentFprCycleId; 
        integer aCurrentFprCycleNum =  aPubAuthorNoSharing.CurrentFprCycleNum;

        List<SelectOption> aOption = aPubAuthorNoSharing.getAuthorMyRequestOptions();
        aPubAuthorNoSharing.SelectedAuthorMyRequestOption = 'all'; 
        string SelectedAuthorMyRequestOption    =  aPubAuthorNoSharing.SelectedAuthorMyRequestOption;
        boolean aIsSelectedAuthorRequestMainDetail =     aPubAuthorNoSharing.IsSelectedAuthorRequestMainDetail; 
        boolean aIsSelectedAuthorRequestCollaboration = aPubAuthorNoSharing.IsSelectedAuthorRequestCollaboration;
           
        List<pubAuthor__c> aMyAuthorPubStatusList = aPubAuthorNoSharing.MyAuthorPubStatusList;
        List<pubAuthor__c> aMyAuthorPubPendingAccessList = aPubAuthorNoSharing.MyAuthorPubPendingAccessList;        
        decimal aMyAuthorPubPendingAccessListCount = aPubAuthorNoSharing.MyAuthorPubPendingAccessListCount;
        List<pubAuthor__c> MyAuthorPubInviteList = aPubAuthorNoSharing.MyAuthorPubInviteList;
        decimal aMyAuthorPubInviteListCount = aPubAuthorNoSharing.MyAuthorPubInviteListCount;
        List<pubAuthor__c> MyAuthorPubApproveList = aPubAuthorNoSharing.MyAuthorPubApproveList;
        decimal aMyAuthorPubApproveListCount  = aPubAuthorNoSharing.MyAuthorPubApproveListCount;
        List<pubAuthor__c> MyAuthorPubReviewList = aPubAuthorNoSharing.MyAuthorPubReviewList;
        decimal aMyAuthorPubReviewListCount  = aPubAuthorNoSharing.MyAuthorPubReviewListCount;        
        List<pubAuthor__c> MyAuthorPubStatusFullList = aPubAuthorNoSharing.MyAuthorPubStatusFullList;


        Map<id, boolean> aPendingAuthorApprovalMap = aPubAuthorNoSharing.PendingAuthorApprovalMap;
        Map<id, boolean> aAuthorInviteAccepetedMap = aPubAuthorNoSharing.AuthorInviteAccepetedMap;        
        Map<id, boolean> aAuthorApprovedMap = aPubAuthorNoSharing.AuthorApprovedMap;

        boolean isAuthorInvite = PubAuthorModelNoSharing.IsAuthorAcceptedInvite ('');     
        boolean IsAuthorApproved = PubAuthorModelNoSharing.IsAuthorApproved('');
        
        PageReference saveRef = aPubAuthorNoSharing.saveCommentsByAuthors(); 
        
        aPubAuthorNoSharing.newRejectApprovalReason = 'test';
        aPubAuthorNoSharing.authorApprovePub(); 
        aPubAuthorNoSharing.authorAcceptInvitePub();
        
        aPubAuthorNoSharing.pubAuthorIdForInviteAccept = PubAuthInvite.Id; 
        aPubAuthorNoSharing.acceptInviteSF1(); 
        
        aPubAuthorNoSharing.pubAuthorIdForApprove = PubAuthInvite.Id; 
        aPubAuthorNoSharing.approvePubSF1();
        
        aPubAuthorNoSharing.pubAuthorIdForReject  = PubAuthInvite.Id; 
        aPubAuthorNoSharing.authorRejectPubSF1();    

        aPubAuthorNoSharing.updatePubAuthorStatusAndInvitedDate(PubAuthInvite.Id);
        
        List<FeedItem> aListFeedItem = PubAuthorModelNoSharing.GetFeedItems(userId, Pub.Id);  

        
        aPubAuthorNoSharing.updatePubAuthorStatus(PubAuthInvite.Id, 'Pending Author Approval' ); 
        
        
        id apubAuthorIdForViewProvision = aPubAuthorNoSharing.pubAuthorIdForViewProvision;
        aPubAuthorNoSharing.RemoteSetPubAuthorIdForViewProvision();  
         string pubAuthorViewProvision = aPubAuthorNoSharing.pubAuthorViewProvision; 

        aPubAuthorNoSharing.activeOpr = 'update';
        aPubAuthorNoSharing.RemoteSetActiveOpr(); 

        decimal activePubAuthorOprTabSF1 = aPubAuthorNoSharing.activePubAuthorOprTabSF1; 
        Map<id, boolean> ActivePubAuthorMapSF1 = aPubAuthorNoSharing.ActivePubAuthorMapSF1;
        
        Map<id, PubAuthorPubDTO> PubAuthorPubMap = aPubAuthorNoSharing.PubAuthorPubMap;
        Map<id, List<PubAuthorPubDraftAttachCommentDTO>> PubAuthorCommentMap = aPubAuthorNoSharing.PubAuthorCommentMap;
        Map<id, decimal> PubAuthorCommentCountMap =  aPubAuthorNoSharing.PubAuthorCommentCountMap;
        
        aPubAuthorNoSharing.RemoteSetPubAttachmentIdForComment(); 
        List<PubAuthorPubDraftAttachCommentDTO> AuthorCommentbyAttachment = aPubAuthorNoSharing.AuthorCommentbyAttachment;
        aPubAuthorNoSharing.CommentAuthorStatusForDelete = 'Approval Rejected';
        aPubAuthorNoSharing.deletecomment() ;
        aPubAuthorNoSharing.CommentAuthorStatusForDelete = '';
        aPubAuthorNoSharing.deletecomment() ;       
        
       List<PubAuthorPubDTO>  PubAuthorPubsDraftsAttachments = aPubAuthorNoSharing.PubAuthorPubsDraftsAttachments;
        
        
        
        
        
                                                
        // ------ 
        
        String aParamPubAuthorId = aPubAuthorNoSharing.ParamPubAuthorId; 
        id puAuthorId = aPubAuthorNoSharing.PubAuthorId;         
        

        System.assertNotEquals(null, aPubAuthorNoSharing.PubId);






        string aSelectedOption = aPubAuthorNoSharing.SelectedAuthorMyRequestOption;


        PageReference apageReference =  aPubAuthorNoSharing.saveCommentsByAuthors();
        apageReference =  aPubAuthorNoSharing.authorApprovePub();        
        apageReference =  aPubAuthorNoSharing.authorAcceptInvitePub();
        
        System.Test.stopTest();
    }




    @IsTest
    public static void UnitTest2() {        

         PageReference pageRef = new PageReference('/apex/AppearPub?sfdc.tabName=01ri00000004OaA'); 
         Test.setCurrentPage(pageRef);
         
        // test dat prep
        //createData(); //Appear Enhancement R2
        
        Publication__c pub = UnitTestData.PublicationNew('SelectDeselectAuthorsTest');  
        Publication__c clonePub = UnitTestData.newPublication('SelectDeselectAuthorsTest2');
        AppearPubModel pubModel = new AppearPubModel(Pub.Id);

        CollaborationGroup myGroup = new CollaborationGroup();
        myGroup.Name='Author Attachments';
        myGroup.CollaborationType='Public'; //can be 'Public' or 'Private'     
         
        insert myGroup;    
        FeedItem NewFeedItem1 = new FeedItem(); 
        NewFeedItem1.ContentFileName = 'mockFile.txt';
        NewFeedItem1.ParentId = pubModel.PubAttachments.AuthorAttachmentGroupId; 
        NewFeedItem1.ContentData = EncodingUtil.base64Decode('mockContent');        
        insert NewFeedItem1; 
        
        PubAttachmentDetails__c aPubAttachmentDetail = new PubAttachmentDetails__c(); 
        aPubAttachmentDetail.Publication__c = pubModel.pubId; 
        aPubAttachmentDetail.AttachmentType__c = 'Draft - Share with Authors';      
        aPubAttachmentDetail.AttachmentName__c = 'test1';   
        aPubAttachmentDetail.What__c = NewFeedItem1.Id;
        aPubAttachmentDetail.Attachment_URL__c   = AppearUrlModel.ChatterFeedIdToUrl(aPubAttachmentDetail.what__c);
        insert aPubAttachmentDetail;         

        FeedItem NewFeedItem2 = new FeedItem(); 
        NewFeedItem2.ContentFileName = 'mockFile.txt';
        NewFeedItem2.ParentId = aPubAttachmentDetail.Id; 
        NewFeedItem2.ContentData = EncodingUtil.base64Decode('mockContent');        
        insert NewFeedItem2;        

        Id userId = userInfo.getUserId();              
        List<Contact> contactsToAdd = new List<Contact>();        
        Contact triageContact = new Contact(lastname='testing',firstname='triage',userid__c=userId);
        contactsToAdd.add(triageContact);
        Contact triageContact2 = new Contact(lastname='testing',firstname='triage2',userid__c=userId);
        contactsToAdd.add(triageContact2);
        Contact delegateContact = new Contact(lastname='testing',firstname='delegate',userid__c=userId);
        contactsToAdd.add(delegateContact);
        insert contactsToAdd;

        List<Contact> appearContacts = [Select id, FirstName from Contact limit 3];
        Set<Id> contactSet =  new Set<Id>();
        for (Contact aContact: contactsToAdd){
            contactSet.add(aContact.Id);
        }

        
        PubAuthorModelNoSharing aPubAuthorNoSharing = pubModel.PubAuthorNoSharing; 
        
        PubAuthor__c PubAuthApprove = new PubAuthor__c();
        PubAuthApprove.Publication__c = Pub.Id;
        PubAuthApprove.Author__c = appearContacts[2].Id;
        PubAuthApprove.ApprovalSentDate__c = date.today();
        PubAuthApprove.AuthorStatus__c='Pending Author Approval';
        PubAuthApprove.Approval_Disclaimer_ID__c =   PubAuthorModelNoSharing.getLatestPubAuthorAttachmentId(Pub.Id); 
        PubAuthApprove.ApprovalAcceptedDate__c =null;
        
        insert PubAuthApprove;        
        

        System.Test.startTest();
        aPubAuthorNoSharing.PubAuthorId = PubAuthApprove.Id; 
        map<id, string> ApprovePubAuthorAttachmentMap =       aPubAuthorNoSharing.ApprovePubAuthorAttachmentMap;
        string approvalURL = aPubAuthorNoSharing.getApproveAttachmentURL();
         List<FeedItem> aFeedItemLIst = PubAuthorModelNoSharing.GetFeedItems(userId, Pub.Id); 
         Map< id, List<FeedItem>> aFeedMap =   PubAuthorModelNoSharing.GetFeedItemCountByAuthor( contactSet, Pub.Id); 
        aPubAuthorNoSharing.NewDraftComment.body = 'test comments 1'; 
        aPubAuthorNoSharing.NewDraftComment.parentId = aPubAttachmentDetail.id; 
        aPubAuthorNoSharing.AddDraftComment(); 
        aPubAuthorNoSharing.NewDraftComment.body = 'test comments 2'; 
        aPubAuthorNoSharing.NewDraftComment.parentId = aPubAttachmentDetail.id; 
        aPubAuthorNoSharing.AddDraftComment2(); 

        Map<id, PubAuthorPubDTO> PubAuthorPubMap = aPubAuthorNoSharing.PubAuthorPubMap;
        Map<id, List<PubAuthorPubDraftAttachCommentDTO>> PubAuthorCommentMap = aPubAuthorNoSharing.PubAuthorCommentMap;
        Map<id, decimal> PubAuthorCommentCountMap =  aPubAuthorNoSharing.PubAuthorCommentCountMap;
        
        aPubAuthorNoSharing.pubAttachmentIdForComment =  aPubAttachmentDetail.id; 
        aPubAuthorNoSharing.RemoteSetPubAttachmentIdForComment(); 
        List<PubAuthorPubDraftAttachCommentDTO> AuthorCommentbyAttachment = aPubAuthorNoSharing.AuthorCommentbyAttachment;
        aPubAuthorNoSharing.CommentAuthorStatusForDelete = 'Approval Rejected';
        aPubAuthorNoSharing.deletecomment() ;
        aPubAuthorNoSharing.CommentAuthorStatusForDelete = '';
        aPubAuthorNoSharing.deletecomment() ;       
                
        aPubAuthorNoSharing.updatePubAfterApproval(pub.id);//Appear Enhancement R3
        
        System.Test.stopTest();
    }



}