force-app/main/default/staticresources/python/Disappear/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/ContactDelegate__c.object
<CustomObject>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Delegates (Delegated To)</relationshipLabel>
        <relationshipName>ContactDelegatedTo</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Delegate__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Delegate To</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Delegates (Delegated By)</relationshipLabel>
        <relationshipName>ContactDelegatedBy1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Contact Delegate</label>
    <nameField>
        <displayFormat>CDEL-{0000000}</displayFormat>
        <label>ContactDelegate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Delegates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/ContactDelegateModel.cls
public class ContactDelegateModel {
	//trump order - Delegate > Proxy > Assigned contact

	private static map<Id, ContactDelegate__c> contactIdtoDelegateMap;
	
	public static ContactDelegate__c pubfindPubReviewDelegate(Contact ReviewTeamMember, Date delegationDate) {
		return pubfindPubReviewDelegate(reviewTeamMember.id, delegationDate);
	}
	
	public static ContactDelegate__c pubfindPubReviewDelegate(Id contactId, Date delegationDate) {
		if (contactIdtoDelegateMap == null) {
			List<ContactDelegate__c> allDelegates = [
				select Contact__c, Contact__r.name, Delegate__c, Delegate__r.name,
				start_Date__c, end_Date__c, Comment__c, isActive__c
				from ContactDelegate__c
				where start_Date__c <= :DelegationDate
				and end_Date__c >= :DelegationDate
				and isActive__c = true
			];
			
			contactIdtoDelegateMap = new map<Id, ContactDelegate__c>();
			for(ContactDelegate__c delegate : allDelegates) {
				if (!contactIdtoDelegateMap.containsKey(delegate.contact__c)) { //avoid potential de-duplication errors
					contactIdtoDelegateMap.put(delegate.contact__c, delegate);
				}
			}
		}
		
		if (!contactIdtoDelegateMap.containsKey(contactId)) {
			return null;
		} else {
			return contactIdtoDelegateMap.get(contactId);
		}
	}	
}