force-app/main/default/staticresources/python/Disappear/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <description>Country Picklist</description>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Balkans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia &amp; Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brazil</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brunei</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bulgaria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cambodia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central And Eastern Europe (CEE)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colombia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Costa Rica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Croatia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cyprus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Czech Republic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denmark</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dominican Republic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ecuador</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Egypt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>United States</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Proxy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Proxy</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Proxy (Contact)</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SponsoringDept__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>An external contact&apos;s sponsoring department</description>
        <inlineHelpText>An external contact&apos;s sponsoring department</inlineHelpText>
        <label>Sponsoring Dept</label>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>Sponsored Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Used to distinguish between the different types of contacts that are loaded - via data load vs SAP integration and set up in APPEAR Roles.</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>APPEAR</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>SAP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Siebel</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/ContactDelegate__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Delegates (Delegated To)</relationshipLabel>
        <relationshipName>ContactDelegatedTo</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Delegate__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Delegate To</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Delegates (Delegated By)</relationshipLabel>
        <relationshipName>ContactDelegatedBy1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Contact Delegate</label>
    <nameField>
        <displayFormat>CDEL-{0000000}</displayFormat>
        <label>ContactDelegate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Delegates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Country__c.object
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/FPR_Cycle__c.object
<CustomObject>
    <description>record name will be PubId-{0000000}-FPRCycle-{00}</description>
    <fields>
        <fullName>FPR_Cycle_Num__c</fullName>
        <label>FPR Cycle Num</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Incremental_FPR_Cycle_c__c</fullName>
        <label>Incremental FPR Cycle</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>FPR Cycles</relationshipLabel>
        <relationshipName>FPR_Cycles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>FPR Cycle</label>
    <nameField>
        <label>FPR_Cycle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FPR Cycles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Country is required if SubGroup selected is LACAN, JAPAC, EEMEA for &apos;Global Development&apos; Data Source</inlineHelpText>
        <label>Country Link</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SponsoringDept__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Department from which publication data are generated.</inlineHelpText>
        <label>Sponsoring Amgen Department (Lookup)</label>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>Publication (SponsoringDept)</relationshipLabel>
        <relationshipName>Publication1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PubReviewTeam__c.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <description>Vote Comments</description>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Delivered__c</fullName>
        <label>Delivered</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FPR_Cycle__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>FPR_Cycle</label>
        <referenceTo>FPR_Cycle__c</referenceTo>
        <relationshipName>PubReviewTeams</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HasVoted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>boolean set when a team member has voted</description>
        <label>HasVoted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipName>PubReviewTeams</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reviewer_Status__c</fullName>
        <label>Vote</label>
        <picklist>
            <picklistValues>
                <fullName>Reviewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reviewed With Comments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discussion Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withheld</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Comments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vote Not Available</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reviewer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reviewer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>PubReviewTeams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Primary / Informed</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Notify</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Publication Review Team Member</label>
    <nameField>
        <displayFormat>PRT-{000000000}</displayFormat>
        <label>PubReviewTeamId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication Review Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/ProxyDelegateUtilityTests.cls
@isTest
public with sharing class ProxyDelegateUtilityTests {
	private static void CreateData() {
		OrganizationModelData.createData();
        DepartmentModelData.createData();
        AccountModelData.createData();
        AppearContactModelData.createData();
        AppearTriggerActivationModel.isPubReviewTeamTriggerActive = false;
	}
	
	private static Publication__c pProxyDelegateTestPub;
    public static Publication__c ProxyDelegateTestPub {
        get {
            if (pProxyDelegateTestPub == null) {
                CreateData();
                pProxyDelegateTestPub = UnitTestData.PublicationNew('ProxyDelegateUtilityTests');
            }
            return pProxyDelegateTestPub;
        }
    }
	
	@isTest
	private static void TestSingleProxy() {
		CreateData();
		
		List<Contact> allContacts = [Select id, Name, UserId__c, Proxy__c from Contact];
		System.assert(allContacts.size() > 3);	
			
		Contact contactBeingProxied = allContacts[0];
		Contact proxyContact =  allContacts[1];
		contactBeingProxied.Proxy__c = proxyContact.Id;
		update contactBeingProxied;
		
		AppearPubModel pubModel = new AppearPubModel(ProxyDelegateTestPub.Id);
		
		FPR_Cycle__c fprCycle = new FPR_Cycle__c(FPR_Cycle_Num__c=1, Incremental_FPR_Cycle_c__c=1, Publication__c=pubModel.PubId);
		insert fprCycle;
		
		//Insert Primary Reviewer
		PubReviewTeam__c primaryReviewer = new PubReviewTeam__c( Reviewer__c = contactBeingProxied.Id, Type__c = 'Primary', 
																 Publication__c = pubModel.PubId, FPR_Cycle__c = fprCycle.Id, Delivered__c = Date.today() ); 
		insert primaryReviewer;		 
		 
		ProxyDelegateUtility.ProxyOrDelegatePrimary(primaryReviewer);
		
		primaryReviewer.HasVoted__c = true;
		primaryReviewer.Reviewer_Status__c = 'test';
		primaryReviewer.Comments__c = 'test';
		
		ProxyDelegateUtility.SyncUpdateWithProxies(primaryReviewer);
		
		List<PubReviewTeam__c> allReviewers = PubReviewTeamModel.getReviewTeamMembers(pubModel.PubId, false);
		
		System.AssertEquals(2, allReviewers.size()); //expect 1 additional reviewer to be proxied
		
		for(PubReviewTeam__c reviewer : ProxyDelegateUtility.GetProxiesForAndProxiedBy(primaryReviewer)) { //assert that vote update synced properly
			System.assertEquals(primaryReviewer.HasVoted__c, reviewer.HasVoted__c);
			System.assertEquals(primaryReviewer.Reviewer_Status__c, reviewer.Reviewer_Status__c);
			System.assertEquals(primaryReviewer.Comments__c, reviewer.Comments__c);
		}
	}
	
	
	@isTest
	private static void TestSingleDelegate() {
		CreateData();
		
		List<Contact> allContacts = [Select id, Name, UserId__c, Proxy__c from Contact];
		System.assert(allContacts.size() > 3);
			
		Contact contactBeingDelegated = allContacts[0];
		Contact delegateContact =  allContacts[1];
		
		ContactDelegate__c testDelegate = new ContactDelegate__c(Contact__c = contactBeingDelegated.id, Delegate__c = delegateContact.id, start_Date__c = Date.today().addDays(-7),
																 end_Date__c = Date.today().addDays(7), isActive__c = true);
		insert testDelegate;
		
		AppearPubModel pubModel = new AppearPubModel(ProxyDelegateTestPub.Id);
		
		FPR_Cycle__c fprCycle = new FPR_Cycle__c(FPR_Cycle_Num__c=1, Incremental_FPR_Cycle_c__c=1, Publication__c=pubModel.PubId);
		insert fprCycle;
		
		//Insert Primary Reviewer
		PubReviewTeam__c primaryReviewer = new PubReviewTeam__c( Reviewer__c = contactBeingDelegated.Id, Type__c = 'Primary', 
																 Publication__c = pubModel.PubId, FPR_Cycle__c = fprCycle.Id, Delivered__c = Date.today() ); 
		
		insert primaryReviewer;		 
		 
		system.AssertNotEquals(null, ProxyDelegateUtility.ProxyOrDelegatePrimary(primaryReviewer));
		
		List<PubReviewTeam__c> allReviewers = PubReviewTeamModel.getReviewTeamMembers(pubModel.PubId, false);
		
		System.AssertEquals(2, allReviewers.size()); //expect 1 additional reviewer to be proxied
		
		Integer numOfPrimary = 0;
		Integer numOfNotify = 0;
		for(PubReviewTeam__c reviewer : allReviewers) {
			if (reviewer.Type__c == 'Primary') {
				numOfPrimary++;
			} else if (reviewer.Type__c == 'Notify') {
				numOfNotify++;
			}  
		}
		
		System.AssertEquals(1, numOfPrimary);
		System.AssertEquals(1, numOfNotify);
	}
	
	@isTest
	private static void TestDelegateTopOfProxyChain() {
		CreateData();
		
		List<Contact> allContacts = [Select id, Name, UserId__c, Proxy__c from Contact];
		System.assert(allContacts.size() > 3);	
		
		Contact contactBeingProxied = allContacts[0];
		Contact proxyContactBeingDelegated =  allContacts[1];
		Contact delegateContact =  allContacts[2];
		
		contactBeingProxied.Proxy__c = proxyContactBeingDelegated.Id;
		update contactBeingProxied;
		
		ContactDelegate__c testDelegate = new ContactDelegate__c(Contact__c = proxyContactBeingDelegated.id, Delegate__c = delegateContact.id, start_Date__c = Date.today().addDays(-7),
																 end_Date__c = Date.today().addDays(7), isActive__c = true);
		insert testDelegate;
		
		AppearPubModel pubModel = new AppearPubModel(ProxyDelegateTestPub.Id);
		
		FPR_Cycle__c fprCycle = new FPR_Cycle__c(FPR_Cycle_Num__c=1, Incremental_FPR_Cycle_c__c=1, Publication__c=pubModel.PubId);
		insert fprCycle;
		
		//Insert Primary Reviewer
		PubReviewTeam__c primaryReviewer = new PubReviewTeam__c( Reviewer__c = contactBeingProxied.Id, Type__c = 'Primary', 
																 Publication__c = pubModel.PubId, FPR_Cycle__c = fprCycle.Id, Delivered__c = Date.today() ); 
		
		insert primaryReviewer;		 
		 
		system.AssertNotEquals(null, ProxyDelegateUtility.ProxyOrDelegatePrimary(primaryReviewer));
		
		List<PubReviewTeam__c> allReviewers = PubReviewTeamModel.getReviewTeamMembers(pubModel.PubId, false);
		
		System.AssertEquals(3, allReviewers.size()); //expect 1 additional reviewer to be proxied
		
		Integer numOfPrimary = 0;
		Integer numOfNotify = 0;
		for(PubReviewTeam__c reviewer : allReviewers) {
			if (reviewer.Type__c == 'Primary') {
				numOfPrimary++;
			} else if (reviewer.Type__c == 'Notify') {
				numOfNotify++;
			}  
		}
		
		System.AssertEquals(1, numOfPrimary);
		System.AssertEquals(2, numOfNotify);
	}
	
	@isTest
	private static void TestMaxProxy() {
		CreateData();
		
        List<Contact> additionalContacts = new List<Contact>();
        
        additionalContacts.add( new Contact(LastName= 'Dorner2', FirstName='Michael2', Country__c='United States', 
        	AccountId=AccountModelData.AmgenAccount.Id, 
            SponsoringDept__c=DepartmentModelData.GlobalHealthEconomicDept.Id,
            Email='mike1@amgen.com'));
        additionalContacts.add( new Contact(LastName= 'Weiss2', FirstName='Solange2', 
        	AccountId=AccountModelData.AmgenAccount.Id, 
            SponsoringDept__c=DepartmentModelData.GlobalMedicalWritingDept.Id,
            Department='Global Medical Writing'));
        insert additionalContacts;
		
		List<Contact> allContacts = [Select id, Name, UserId__c, Proxy__c from Contact];
		System.assert(allContacts.size() > ProxyDelegateUtility.MaxProxyDelegateCount + 1);	
		
		for(integer i = 0; i < allContacts.size() - 1; i++) {
			allContacts[i].Proxy__c = allContacts[i + 1].Id;
		}

		update allContacts;
		
		AppearPubModel pubModel = new AppearPubModel(ProxyDelegateTestPub.Id);
		
		FPR_Cycle__c fprCycle = new FPR_Cycle__c(FPR_Cycle_Num__c=1, Incremental_FPR_Cycle_c__c=1, Publication__c=pubModel.PubId);
		insert fprCycle;
		
		//Insert Primary Reviewer
		PubReviewTeam__c primaryReviewer = new PubReviewTeam__c( Reviewer__c = allContacts[0].Id, Type__c = 'Primary', 
																 Publication__c = pubModel.PubId, FPR_Cycle__c = fprCycle.Id ); 
		insert primaryReviewer;		 
		 
		ProxyDelegateUtility.ProxyOrDelegatePrimary(primaryReviewer);
		
		List<PubReviewTeam__c> allReviewers = PubReviewTeamModel.getReviewTeamMembers(pubModel.PubId, false);
		System.AssertEquals(ProxyDelegateUtility.MaxProxyDelegateCount+1, allReviewers.size()); //expect max  additional reviewers to be proxied + initial reviewer
		System.AssertEquals(ProxyDelegateUtility.MaxProxyDelegateCount, ProxyDelegateUtility.GetProxiesForAndProxiedBy(allReviewers[1]).size()); //expect exact # of reviewers to be proxied by and for as max. Testing both directions		
		System.AssertEquals(ProxyDelegateUtility.MaxProxyDelegateCount, ProxyDelegateUtility.GetProxiesForAndProxiedBy(allReviewers[allReviewers.size()-2]).size()); //expect exact # of reviewers to be proxied by and for as max. Testing both directions
	}
}