force-app/main/default/staticresources/python/Disappear/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <description>Country Picklist</description>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Balkans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia &amp; Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brazil</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brunei</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bulgaria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cambodia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central And Eastern Europe (CEE)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colombia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Costa Rica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Croatia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cyprus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Czech Republic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denmark</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dominican Republic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ecuador</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Egypt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>United States</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Country__c.object
<CustomObject>
    <fields>
        <fullName>RegionId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Countries</relationshipLabel>
        <relationshipName>Countries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Country is required if SubGroup selected is LACAN, JAPAC, EEMEA for &apos;Global Development&apos; Data Source</inlineHelpText>
        <label>Country Link</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Data_Source__c</fullName>
        <label>Data Source</label>
        <picklist>
            <picklistValues>
                <fullName>Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GRAAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FPR_Due_Date__c</fullName>
        <inlineHelpText>As best practice, select an FPR due date that is more than 10 business days from today. If this is a rush request, provide business justification in the Comments for FPR Coordinator section and we will try to facilitate your request.</inlineHelpText>
        <label>FPR Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product_Indication__c</fullName>
        <description>A READ ONLY string that list all product Indications for the Publication
The key product indication will be list at the first entry</description>
        <inlineHelpText>Product - Indication is a required field that is available for selection when a publication is first saved. Once saved, the Product Indication may be edited using the Product Indication button.</inlineHelpText>
        <label>Product - Indication</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PubType__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>User will pick a Publication_Type in Picklist
then trigger or code will fill in the proper PubType__c</description>
        <label>PubType Link</label>
        <referenceTo>PubType__c</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publication_Title__c</fullName>
        <inlineHelpText>This is a succinct but descriptive Title of the Publication</inlineHelpText>
        <label>Publication Title</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Publication_Type__c</fullName>
        <label>Publication Type</label>
        <picklist>
            <picklistValues>
                <fullName>Abstract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ad Board Summary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMCP Dossier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Book Chapter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brief Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CMS/Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Editorial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GVD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HTA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Letter to Editor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manuscript</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting Summary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Newsletter Article</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oral Presentation (Slide Deck)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Poster</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review Article</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supplement Article (Non English Language Only)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Translation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PubStatus__c.object
<CustomObject>
    <description>List of Status for a Publication - Target Date / Revised Date / Actual Date
Will be used for planning</description>
    <fields>
        <fullName>Status__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Status</label>
        <referenceTo>Status__c</referenceTo>
        <relationshipName>PubStatuses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publication Status</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>PubStatus Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PubType__c.object
<CustomObject>
    <fields>
        <fullName>DefaultTargetType__c</fullName>
        <label>DefaultTargetType</label>
        <picklist>
            <picklistValues>
                <fullName>Meeting</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Journal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ME_plus__c</fullName>
        <label>ME +</label>
        <precision>6</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MePoint__c</fullName>
        <description>Manuscript Point awarded to Writing Coordinator for this type of publication.</description>
        <label>ME</label>
        <precision>6</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>displayOrder__c</fullName>
        <description>Order to sort the Publication Type in</description>
        <label>displayOrder</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Publication Type</label>
    <nameField>
        <label>PubType Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publication Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Status__c.object
<CustomObject>
    <fields>
        <fullName>displayOrder__c</fullName>
        <description>display order</description>
        <label>displayOrder</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Status</label>
    <nameField>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/SubGroup__c.object
<CustomObject>
    <fields>
        <fullName>Data_Source__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Data Source</label>
        <referenceTo>DataSource__c</referenceTo>
        <relationshipLabel>SubGroups</relationshipLabel>
        <relationshipName>SubGroups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SubGroup</label>
    <nameField>
        <label>SubGroup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SubGroups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/UnitTestData.cls
public class UnitTestData {
	public static void PubTypeTestData() {
		integer pubTypeCount = [select count() from PubType__c ];
		if (pubTypeCount == 0) {
			PubTypeModelData.createData();
			pubTypeCount = [select count() from PubType__c ];
			System.assertNotEquals(0, pubTypeCount);
		}	
	}

	// refence tables
	
	public static void StatusTestData() {
		integer statusCount = [select count() from Status__c ];
		if (statusCount == 0) {
			StatusModelData.createData();
			
			statusCount = [select count() from Status__c ];
			System.assertNotEquals(0, statusCount);
		}
		
	}
	
	// junction tables
	
	
	// transaction tables
	
	public static Publication__c PublicationNew(string title){
		AppLogModel.LogInfo('UnitTestData::PublicationNew', 'Creating pub with title '+title);
			
		StatusTestData();
		Status__c FprOnlyStatus = StatusModel.LookUpStatus('Pending FPR Submission'); 
		System.assertNotEquals(null, FprOnlyStatus,' missing Pending FPR Submission');
		
//		PubTypeTestData();
		List<PubType__c> pubtypes = new List<PubType__c>();
		pubTypes.add( new PubType__c(name='Manuscript', displayOrder__c=120, DefaultTargetType__c= 'Journal',
            MePoint__c = 1.00, ME_plus__c=0.25));
                insert PubTypes;    
		//Appear Enhancement R2
		List<Contact> con= new List<Contact>();
		con.add(new contact(FirstName='Test', LastName='Contact', Email='testcontact@con.com', country__c='United States'));
		insert con;
		//Appear Enhancement R2
		List<Region__c> RegionList = new List<Region__c>();
		RegionList.add( new Region__c(name= 'US'));
		insert RegionList;
		//Appear Enhancement R2
		List<Country__c> CountryList = new List<Country__c>();
		CountryList.add( new Country__c(name= 'United States' , RegionId__c=RegionModel.RegionNameMap.get('US').id));
		insert CountryList;
		
		MEScopeOfWorkModelData.createData();
		DataSourceModelData.createData();
		SubGroupModelData.createData();
		
		Publication__c pub = new Publication__c();
		pub.Publication_Title__c = title; 
		PubType__c ManuscriptType = PubTypeModel.LookupPubType('Manuscript');
		System.assertNotEquals(null, ManuscriptType, ' missing Manuscript PubType');
		pub.Publication_Type__c = 'Manuscript';
		pub.FPR_Due_Date__c = System.today().addDays(30);
		pub.Product_Indication__c = 'Product Indication 1;Product Indication 2';
		pub.Data_Source__c = 'Development';  
		pub.SubGroup_pick__c = 'Development - GRAAS';
		pub.SubGroup__c = SubGroupModelData.DevelopmentSmpSubGroup.Id;
	    pub.Execution_Notes__c = 'this is execution notes test case scenario';
		pub.Execution_Notes_Last_Mod__c = DateTime.valueOf('2014-09-09 20:57:00');
		pub.SponsorDept_Pick__c='Clinical Development';//Appear Enhancement R2
		pub.SponsorOrg_Pick__c='Amgen';//Appear Enhancement R2
		pub.Country_pick__c='United States';//Appear Enhancement R2
		pub.RAE__c=con[0].id;//Appear Enhancement R2
		pub.GPP_Type__c='SP';//Appear Enhancement R3
		
		AppLogModel.LogInfo('UnitTestData::PublicationNew', 'insert new pub records');
		insert pub;

		System.assertNotEquals(null, pub);
		System.assertNotEquals(null, pub.id);
		System.assertNotEquals(null, pub.Data_Source__c);
		System.assertNotEquals(null, pub.SubGroup__c);
		
		Publication__c pubupdated = [Select Id,PubStatus__c from Publication__c where id =:pub.id];
		System.assertNotEquals(null,pubupdated.PubStatus__c );
		
		return pub;
	}
	
	public static Publication__c newPublication(string title){
		AppLogModel.LogInfo('UnitTestData::PublicationNew', 'Creating pub with title '+title);
			
		StatusTestData();
		Status__c FprOnlyStatus = StatusModel.LookUpStatus('Pending FPR Submission'); 
		System.assertNotEquals(null, FprOnlyStatus,' missing Pending FPR Submission');
		
//		PubTypeTestData();
		List<PubType__c> pubtypes = new List<PubType__c>();
		pubTypes.add( new PubType__c(name='Manuscript', displayOrder__c=120, DefaultTargetType__c= 'Journal',
            MePoint__c = 1.00, ME_plus__c=0.25));
                insert PubTypes;    
		//Appear Enhancement R2
		List<Contact> con= new List<Contact>();
		con.add(new contact(FirstName='Test', LastName='Contact', Email='secondcontact@con.com', country__c='United States'));
		insert con;
		//Appear Enhancement R2
		List<Region__c> RegionList = new List<Region__c>();
		RegionList.add( new Region__c(name= 'US'));
		insert RegionList;
		//Appear Enhancement R2
		List<Country__c> CountryList = new List<Country__c>();
		CountryList.add( new Country__c(name= 'United States' , RegionId__c=RegionModel.RegionNameMap.get('US').id));
		insert CountryList;
		
		MEScopeOfWorkModelData.createData();
		DataSourceModelData.createData();
		SubGroupModelData.createData();
		
		Publication__c pub = new Publication__c();
		pub.Publication_Title__c = title; 
		PubType__c ManuscriptType = PubTypeModel.LookupPubType('Manuscript');
		System.assertNotEquals(null, ManuscriptType, ' missing Manuscript PubType');
		pub.Publication_Type__c = 'Manuscript';
		pub.FPR_Due_Date__c = System.today().addDays(30);
		pub.Product_Indication__c = 'Product Indication 1;Product Indication 2';
		pub.Data_Source__c = 'Development';  
		pub.SubGroup_pick__c = 'Development - GRAAS';
		pub.SubGroup__c = SubGroupModelData.DevelopmentSmpSubGroup.Id;
	    pub.Execution_Notes__c = 'this is execution notes test case scenario';
		pub.Execution_Notes_Last_Mod__c = DateTime.valueOf('2014-09-09 20:57:00');
		pub.SponsorDept_Pick__c='Clinical Development';//Appear Enhancement R2
		pub.SponsorOrg_Pick__c='Amgen';//Appear Enhancement R2
		pub.Country_pick__c='United States';//Appear Enhancement R2
		pub.RAE__c=con[0].id;//Appear Enhancement R2
		pub.GPP_Type__c='SP';//Appear Enhancement R3
		
		AppLogModel.LogInfo('UnitTestData::PublicationNew', 'insert new pub records');
		insert pub;

		System.assertNotEquals(null, pub);
		System.assertNotEquals(null, pub.id);
		System.assertNotEquals(null, pub.Data_Source__c);
		System.assertNotEquals(null, pub.SubGroup__c);
		
		Publication__c pubupdated = [Select Id,PubStatus__c from Publication__c where id =:pub.id];
		System.assertNotEquals(null,pubupdated.PubStatus__c );
		
		return pub;
	}
	
	// transaction junction tables
	
	// attachments

}