force-app/main/default/staticresources/python/Disappear/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <description>Country Picklist</description>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Balkans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia &amp; Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brazil</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brunei</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bulgaria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cambodia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central And Eastern Europe (CEE)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colombia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Costa Rica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Croatia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cyprus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Czech Republic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denmark</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dominican Republic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ecuador</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Egypt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>United States</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SponsoringDept__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>An external contact&apos;s sponsoring department</description>
        <inlineHelpText>An external contact&apos;s sponsoring department</inlineHelpText>
        <label>Sponsoring Dept</label>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>Sponsored Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Country__c.object
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/KeyValueSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Key__c</fullName>
        <label>Key</label>
        <length>150</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>KeyValueSettings</label>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/pubAuthor__c.object
<CustomObject>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Publication Authors</relationshipLabel>
        <relationshipName>Publication_Authors</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Publication Author</label>
    <nameField>
        <displayFormat>PA-{0000000}</displayFormat>
        <label>Publication Author Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Country is required if SubGroup selected is LACAN, JAPAC, EEMEA for &apos;Global Development&apos; Data Source</inlineHelpText>
        <label>Country Link</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HasUSAuthors__c</fullName>
        <defaultValue>false</defaultValue>
        <description>boolean to indicate whether pub has one or more US authors. Kept in sync by author trigger.</description>
        <label>Has US Authors</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SponsoringDept__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Department from which publication data are generated.</inlineHelpText>
        <label>Sponsoring Amgen Department (Lookup)</label>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>Publication (SponsoringDept)</relationshipLabel>
        <relationshipName>Publication1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SponsoringOrg__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Company from which publication is generated.  (e.g. Amgen, Pfizer, etc.)</inlineHelpText>
        <label>Sponsoring Organization (Lookup)</label>
        <referenceTo>Organization__c</referenceTo>
        <relationshipLabel>Publication (SponsoringOrg)</relationshipLabel>
        <relationshipName>Publication2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PubStudy__c.object
<CustomObject>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipName>PubStudies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Study__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Study</label>
        <referenceTo>Study__c</referenceTo>
        <relationshipName>PubStudies</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publication Study/Project</label>
    <nameField>
        <label>PubStudy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publication Studies/Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Study__c.object
<CustomObject>
    <label>Study/Project</label>
    <nameField>
        <label>Study/Project #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Studies/Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/PubAuthorTriggerLogicTest.cls
@IsTest
public with sharing class PubAuthorTriggerLogicTest {
    private static Publication__c pPubAuthorTestPub = null;
    public static Publication__c PubAuthorTestPub {
        get {
            if (pPubAuthorTestPub == null) {
                CreateData();
                pPubAuthorTestPub = UnitTestData.PublicationNew('PubAuthorTriggerLogicTest');
            }
            return pPubAuthorTestPub;
        }
    }
    
    private static void CreateData() {
		OrganizationModelData.createData();
        DepartmentModelData.createData();
        AccountModelData.createData();
        AppearContactModelData.createData();
        //R1:2017 - max author count data
        KeyValueSettings__c kvs = new KeyValueSettings__c(Name='CSP Pub Author Count',Key__c='Max_Author_Count',Value__c='10');
		insert kvs;
    }
    
    @IsTest
    private static void TestPubAuthorTriggerLogic() {
    	System.assert(PubAuthorTestPub != null);
    	PubStudy__c pubstudy = new PubStudy__c();
    	Pubstudy.Publication__c = PubAuthorTestPub.Id;
    	PubStudy.Study__c = null;
    	insert Pubstudy;
    	
    	list<pubstudy__c> pslist = new list<PubStudy__c>();
    	pslist.add(PubSTudy);
    	//PubAuthorTestPub.SponsoringDept__c ='test';
    	//PubAuthorTestPub.SponsoringOrg__c='test';
    	//update PubAuthorTestPub;
    	list<Publication__c> publist = new List<Publication__c>();
    	publist.add(PubAuthorTestPub);
    	PubAuthorTriggerLogic.PubProjectStudyUpdate(pslist, publist);
    	List<Contact> testContacts = [Select id From Contact Where Country__c =:'United States' Limit 5];
    	
    	PubAuthorModel authorModel = new PubAuthorModel(PubAuthorTestPub.Id, '','', PubAuthorTestPub, false);    	
    	
    	for(Contact author : testContacts) {
    		authorModel.NewAuthorId = author.Id;
    		System.assertNotEquals(null, authorModel.save());    		
    	}    	
    	
    	List<PubAuthor__c> pubAuthors = authorModel.PubAuthorList;    	
    	System.assertNotEquals(0, pubAuthors.size());
    	
    	PubAuthorTriggerLogic.PubAuthorTriggerInsertOrDeleteLogic(pubAuthors);    	
    	
    	//Publication__c refreshedPub = [Select id, HasUSAuthors__c from Publication__c where id = :PubAUthorTestPub.Id];
    	//System.assertequals(true,PubAUthorTestPub.HasUSAuthors__c); //Has US Authors On Pub
    	
    	//Contact usContact = [Select id, Country__c from Contact Where Country__c =:'United States'];
    	contact uscontact = testContacts[0];
    	usContact.Country__c = null;
    	update usContact;
    	
    	PubAuthorTriggerLogic.PubAuthorTriggerInsertOrDeleteLogic(pubAuthors);
    	
    	//refreshedPub = [Select id, HasUSAuthors__c from Publication__c where id = :PubAUthorTestPub.Id];
    	System.assertEquals(false,PubAUthorTestPub.HasUSAuthors__c); //No Longer US Authors On Pub
    	
    	PubAuthorTriggerLogic.PubAuthorTriggerInsertOrDeleteLogic(null);
    }
}