force-app/main/default/staticresources/python/Disappear/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <description>Used to distinguish between the different types of contacts that are loaded - via data load vs SAP integration and set up in APPEAR Roles.</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>APPEAR</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>SAP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Siebel</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <fields>
        <fullName>Assigned_FPRC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned to FPR Coordinator</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Status_FormulaField__c</fullName>
        <description>Used to make Current Status a &quot;read only&quot; field</description>
        <formula>PubStatus__r.Status__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FPR_Due_Date__c</fullName>
        <inlineHelpText>As best practice, select an FPR due date that is more than 10 business days from today. If this is a rush request, provide business justification in the Comments for FPR Coordinator section and we will try to facilitate your request.</inlineHelpText>
        <label>FPR Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IsComments_Only__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used for data migration</description>
        <inlineHelpText>Intended for comments only review</inlineHelpText>
        <label>Courtesy Review</label>
        <type>Checkbox</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <recordTypes>
        <fullName>Execute</fullName>
        <active>true</active>
        <label>Execute</label>
    </recordTypes>
    <recordTypes>
        <fullName>Review</fullName>
        <active>true</active>
        <label>Review</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PubReviewTeam__c.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <description>Vote Comments</description>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Delivered__c</fullName>
        <label>Delivered</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>HasVoted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>boolean set when a team member has voted</description>
        <label>HasVoted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipName>PubReviewTeams</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Returned__c</fullName>
        <label>Returned</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Reviewer_Status__c</fullName>
        <label>Vote</label>
        <picklist>
            <picklistValues>
                <fullName>Reviewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reviewed With Comments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discussion Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withheld</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Comments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vote Not Available</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reviewer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reviewer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>PubReviewTeams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Primary / Informed</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Notify</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Publication Review Team Member</label>
    <nameField>
        <displayFormat>PRT-{000000000}</displayFormat>
        <label>PubReviewTeamId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication Review Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/BatchCloseReviewCycles.cls
//BatchCloseReviewCycles 
global class BatchCloseReviewCycles extends BatchBase implements Database.Batchable<SObject>,Database.Stateful {
    public String SOQL = 'SELECT Id, Name, Reviewer__r.Name, Publication__c, Publication__r.Name FROM PubReviewTeam__c where HasVoted__c = FALSE '+
        'and Delivered__c != null and Returned__c = null and Type__c = \'Primary\' and Publication__c IN (select id from Publication__c where '+
        'IsComments_Only__c = TRUE and Current_Status_FormulaField__c = \'Routed\' and FPR_Due_Date__c < LAST_N_DAYS:0)';
    
    public BatchCloseReviewCycles() {
        super();
        if ( Test.isRunningTest()){
            SOQL = SOQL + ' limit 10';
        }
        AddMessage(SOQL);
        system.debug(SOQL);
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        batchableContext = BC;
        batchName = 'BatchCloseReviewCycles ';
        System.Debug(SOQL);
        return Database.getQueryLocator(SOQL);
    }

    global void execute(Database.BatchableContext BC, List<PubReviewTeam__c> pubReviewTeam){
        ActionforpubReviewTeam(pubReviewTeam);
        System.Debug('Here is the list of records to be updated' + pubReviewTeam);
    }

    global void finish(Database.BatchableContext BC){
        AppearTriggerActivationModel.activateTriggersAfterDataMigration();
    
        SendBatchCompletionEmail();
    }
    
    //BatchCloseReviewCycles.runNow();
    public static void runNow(){
        BatchCloseReviewCycles  batch = new BatchCloseReviewCycles ();
        Database.executeBatch(batch, 200);
    }
    
    public static void ActionforpubReviewTeam(List<PubReviewTeam__c> pubReviewTeam) {
            AppearTriggerActivationModel.deactivateTriggersForDataMigration();
            Set <Id> pubIds = new Set<Id>();
            
        for (PubReviewTeam__c pubRteam :  pubReviewTeam) {
            pubRteam.HasVoted__c = true;
			pubRteam.Reviewer_Status__c  = 'No Comments';
			pubRteam.Returned__c = Date.Today();
            pubRteam.Comments__c = 'No Response Received - system updated to "No Comments" on ' + DateTime.now();
            pubIds.add(pubRteam.publication__c);
        }
        
        AppLogModel.LogInfo('BatchCloseReviewCycles', 'updating Review Team '+pubReviewTeam.size());
        database.update(pubReviewTeam, true);
        
        //Code to Recount the Vote and Update the Current Status of the Publication 
        Iterator<Id> iteratorPub = pubIds.iterator();
	    while(iteratorPub.hasNext()) {
	        Id setPubId = iteratorPub.next();
	        PubReviewTeamTriggerLogic.ReCountVoteByPubId(setPubId);
	    }
        
        AppLogModel.flushLogs();        
    }
}