force-app/main/default/staticresources/python/Disappear/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>UserId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/ProvisionDocumentVersion__c.object
<CustomObject>
    <fields>
        <fullName>ProvisionDocumentContent__c</fullName>
        <label>ProvisionDocumentContent</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <label>ProvisionDocumentVersion</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ProvisionDocumentVersion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ProvisionDocumentVersions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/pubAuthor__c.object
<CustomObject>
    <fields>
        <fullName>AuthorStatus__c</fullName>
        <label>AuthorStatus</label>
        <picklist>
            <picklistValues>
                <fullName>Pending Invite Delivery</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Invite Acceptance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invite Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invitation Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Publication Review by Authors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Author Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed Author Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Author__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Author</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Publication Authors</relationshipLabel>
        <relationshipName>Publication_Authors</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Disclaimer_ID__c</fullName>
        <description>Contains the ID of the invite disclaimer used</description>
        <label>Invite Disclaimer ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InviteAcceptedDate__c</fullName>
        <description>The date when the Author  has accepted the Invitation</description>
        <label>Invite Accepted Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Publication Authors</relationshipLabel>
        <relationshipName>Publication_Authors</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>isLogicallyDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used for logical deletion or soft deletion of Pub Authors.</description>
        <label>isLogicallyDeleted</label>
        <type>Checkbox</type>
    </fields>
    <label>Publication Author</label>
    <nameField>
        <displayFormat>PA-{0000000}</displayFormat>
        <label>Publication Author Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <fields>
        <fullName>Assigned_FPRC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned to FPR Coordinator</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <recordTypes>
        <fullName>Plan</fullName>
        <active>true</active>
        <label>Plan</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/AuthorInvitationLandingPageController.cls
public without sharing class AuthorInvitationLandingPageController  {
    // public Static Id PubId;
    public Boolean haserror{get;set;}
    public id PubAuthorId{get;set;}
    public pubAuthor__c PubAuth{get;set;}
    public Id AuthorId {get;set;}
    public ProvisionDocumentVersion__c comp{get;set;}
    public String compType{get;set;}
    public id docid{get;set;}
    public id publicationId {get;set;}
    public Boolean hasUserAssociated{get;set;} //Appear Enhancement R2
    //Constructor to get the required values from the page
    public AuthorInvitationLandingPageController(){
        PubAuthorId= ApexPages.currentpage().getParameters().get('PubAuthorId');
        if(PubAuthorId != null ){
            PubAuth = [select id,author__r.id,publication__r.id,AuthorStatus__c,publication__c,InviteAcceptedDate__c,Disclaimer_ID__c from pubAuthor__c where Id =:PubAuthorId
                      	AND isLogicallyDeleted__c = false //Appear Enhancement R3 : Soft Delete Author functionality
                      ];
            // Pubid = Pubauth.publication__c;
            publicationId = Pubauth.publication__c;
            AuthorId = PubAuth.author__r.Id; 
            DocId = PubAuth.Disclaimer_ID__c;
            
        }
        comp=[SELECT id, ProvisionDocumentContent__c, Name
                      FROM ProvisionDocumentVersion__c ORDER BY createddate Desc limit 1]; 
            System.debug('---------------'+comp); 
        //Appear Enhancement R2, Checking if user present for redirection logic 
        Contact con=[select UserId__c from contact where id=:AuthorId];
            //hasuser=false;
            hasUserAssociated = false;
        if(con.UserId__c!=null){
            hasUserAssociated = true;
        }
    }
    
    //Appear Enhancement R2
    Public Pagereference RedirecttoPage(){       
        if(hasUserAssociated==false) {
	        PageReference page = new pagereference('/apex/CommunitiesSelfReg?'+'&ContactId='+AuthorId+'&Id='+publicationId);
	        return page;  
        }
        else{
             PageReference page = new pagereference('/apex/appearpubauthordashboard?Id='+publicationId+'&sfdc.tabName=01ri00000004OaA&submenu=Plan&tile=Pub%20Details' + '&ContactId=' + AuthorId ); 
             return page;   
        }           
      
    }
    //logic if the author accepts the disclaimer
    Public Pagereference AppearPubAuthor(){
        AppearPubModel pubModel = new AppearPubModel(publicationId); // new AppearPubModel(pubid);
        PubAuthorModelNoSharing aPubAuthorNoSharing = pubModel.PubAuthorNoSharing; 
        aPubAuthorNoSharing.updatePubAuthorStatusAndInvitedDate(PubAuthorId);
        PageReference page = new pagereference('/apex/appearpubauthordashboard?Id='+publicationId+'&activeopr=update&sfdc.tabName=01ri00000004OaA&submenu=Plan&tile=Pub%20Details' + '&ContactId=' + AuthorId );
        return page;
    }
    //getting the disclaimer associated with the Pub Author record
    public pagereference getContentVersionPage(){
        if(docid!=null){
            // Document cv = [select id from Document Where id =: DocId ];
            Id Cvid =  docid; // cv.id;
            pagereference pageref = new Pagereference((AppearURLModel.IsAuthorComm? '/PubAuthor': '')+ '/servlet/servlet.FileDownload?file='+Cvid);
            return pageref;
        }
        else{
            return null;
        }
   } 
   public void setCompType(String s){
          compType = s;
      }
        
      public String getCompType(){
          return compType;
      }
   
   //Logic for cancel button
   Public PageReference CancelAppearPubAuthor(){
        Pagereference Pageref;
        list<user> users =[select id from user where contactid =: AuthorID];
        if(Users.Isempty()){
            haserror = false;   
        }
        else{
            haserror = true;
            Pageref = new pagereference('/apex/appearpubauthordashboard?sfdc.tabName=01rZ00000000bbN');
        }
        return Pageref;
        
    }
}