force-app/main/default/staticresources/python/Disappear/src/objects/ContactDelegate__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Delegates (Delegated To)</relationshipLabel>
        <relationshipName>ContactDelegatedTo</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Delegate__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Delegate To</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Delegates (Delegated By)</relationshipLabel>
        <relationshipName>ContactDelegatedBy1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Contact Delegate</label>
    <nameField>
        <displayFormat>CDEL-{0000000}</displayFormat>
        <label>ContactDelegate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Delegates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/ProdIndTeamMember__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Members of Team</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>ProdInd_Team_Members</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Product Indication Team Member</label>
    <nameField>
        <displayFormat>PITM-{000000}</displayFormat>
        <label>ProductIndicationTeam Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Indication Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/ProductTeamContact__c.object
<CustomObject>
    <fields>
        <fullName>ProductTeamContactName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ProductTeamContactName</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>ProductTeamContacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Team Contact</label>
    <nameField>
        <label>ProductTeamContact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Team Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/pubAuthor__c.object
<CustomObject>
    <fields>
        <fullName>Author__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Author</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Publication Authors</relationshipLabel>
        <relationshipName>Publication_Authors</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Publication Authors</relationshipLabel>
        <relationshipName>Publication_Authors</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Publication Author</label>
    <nameField>
        <displayFormat>PA-{0000000}</displayFormat>
        <label>Publication Author Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <fields>
        <fullName>Assigned_FPRC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned to FPR Coordinator</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FPR_Submitter__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>FPR_Submitter will record the latest person that click on the Submit to FPR button.

DO NOT USE this field to check if a pub is an FPR Only Pub</description>
        <label>FPR Submitter</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Publication (FPR Submitter)</relationshipLabel>
        <relationshipName>FPR_Submitter</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Author__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>First Author</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Publication (First Author)</relationshipLabel>
        <relationshipName>Publication2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RAE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Responsible Amgen Employee (RAE)</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PublicationPreFprReviewer__c.object
<CustomObject>
    <fields>
        <fullName>PreFprReviewer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Pre FPR Reviewer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>PublicationPreFprReviewer</relationshipLabel>
        <relationshipName>PublicationPreFprReviewer</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>PublicationPreFprReviewer</relationshipLabel>
        <relationshipName>PublicationPreFprReviewer</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Publication PreFPR Reviewer</label>
    <nameField>
        <displayFormat>PubPreFpr-{00000000}</displayFormat>
        <label>Publication PreFPR Reviewer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication Pre FPR Reviewers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PublicationTeamMember__c.object
<CustomObject>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Pub Team Member links to Contact</description>
        <label>Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>PublicationTeams</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipName>PublicationTeams</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Publication Team Member</label>
    <nameField>
        <displayFormat>PubT-{00000000}</displayFormat>
        <label>PublicationTeam Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PubME__c.object
<CustomObject>
    <description>Record all Manuscript Equivalent points award to authors and others for their work on a publication</description>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Publication MEs</relationshipLabel>
        <relationshipName>Publication_MEs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WritingRoleMember__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Writing Role Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Publication MEs</relationshipLabel>
        <relationshipName>Publication_MEs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publication ME</label>
    <nameField>
        <displayFormat>PME-{000000000}</displayFormat>
        <label>Publication ME Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication MEs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PubReviewTeam__c.object
<CustomObject>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipName>PubReviewTeams</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reviewer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reviewer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>PubReviewTeams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TriageDelegatedBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TriageDelegatedBy</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>PubReviewTeams1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publication Review Team Member</label>
    <nameField>
        <displayFormat>PRT-{000000000}</displayFormat>
        <label>PubReviewTeamId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication Review Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/ReviewTeamMember__c.object
<CustomObject>
    <fields>
        <fullName>ReviewTeamMember__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Review Team Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Review Team Members</relationshipLabel>
        <relationshipName>Review_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Review Team Member</label>
    <nameField>
        <displayFormat>RTM-{00000000}</displayFormat>
        <label>Review Team Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Review Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Study__c.object
<CustomObject>
    <fields>
        <fullName>StudySponsor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sponsor Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Studies</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Study/Project</label>
    <nameField>
        <label>Study/Project #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Studies/Projects</pluralLabel>
    <recordTypes>
        <fullName>Study</fullName>
        <active>true</active>
        <label>Study</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/ContactReplacementUtility.cls
public with sharing class ContactReplacementUtility {
    //This method will read the ID from the fromContact. With the exclusion of the User object, which is handled before this function, It will look for *ALL* references to that contact (lookups) and replace *ALL* existing references with the id of toContact. fromContact will then later be deleted by a different function.
    

    
    //@future
    public static void ReplaceContact(Id fromContactId, Id toContactId) {
        //so far, brandon notices to exclude Asset, Case, CaseContactRole, Contact, Lead
        //expect: one query and one update DML statement per object type. Update List<SObject>.
        
        //ReviewTeamMember
        List<ReviewTeamMember__c> reviewTeamMembers = [Select ReviewTeamMember__c, id FROM ReviewTeamMember__c WHERE ReviewTeamMember__c =: fromContactid];
        if (reviewTeamMembers.size() > 0) {
            for(ReviewTeamMember__c reviewTeamMember : reviewTeamMembers) {
                reviewTeamMember.ReviewTeamMember__c = toContactId;
            }
            update reviewTeamMembers;
        }
        //ContactDelegate
        List<ContactDelegate__c> contactDelegates = [Select Contact__c,Delegate__c, id FROM ContactDelegate__c WHERE (Contact__c =: fromContactid Or Delegate__c =: fromContactid)];
        if (contactDelegates .size() > 0) {
            for(ContactDelegate__c contactDelegate : contactDelegates) {
                if(contactDelegate.Contact__c == FromContactId) {
                    contactDelegate.Contact__c = toContactId;
                }
                if(contactDelegate.Delegate__c == FromContactId) {
                    contactDelegate.Delegate__c = toContactId;
                }
            }
            update contactDelegates;
        }
        //ProdIndTeamMember
        List<ProdIndTeamMember__c> ProdIndTeamMembers = [Select Contact__c, id FROM ProdIndTeamMember__c WHERE Contact__c =: fromContactid];
        if (ProdIndTeamMembers.size() > 0) {
            for(ProdIndTeamMember__c ProdIndTeamMember : ProdIndTeamMembers) {
                ProdIndTeamMember.Contact__c= toContactId;
            }
            update ProdIndTeamMembers;
        }
        //ProductTeamContact
        List<ProductTeamContact__c> ProdTeamContacts = [Select ProductTeamContactName__c, id FROM ProductTeamContact__c WHERE ProductTeamContactName__c=: fromContactid];
        if (ProdTeamContacts.size() > 0) {
            for(ProductTeamContact__c ProdTeamContact : ProdTeamContacts ) {
                ProdTeamContact.ProductTeamContactName__c = toContactId;
            }
            update ProdTeamContacts;
        }
        //PublicationAuthor
        List<pubAuthor__c> PubAuthors = [Select Author__c , id FROM pubAuthor__c WHERE Author__c =: fromContactid];
        if (PubAuthors.size() > 0) {
            for(pubAuthor__c PubAuthor : PubAuthors) {
                PubAuthor.Author__c= toContactId;
            }
            update PubAuthors ;
        }
        //Publication
        List<Publication__c> Publications = [Select Assigned_FPRC__c,First_Author__c,FPR_Submitter__c,RAE__c, id FROM Publication__c WHERE (Assigned_FPRC__c =: fromContactid Or First_Author__c =: fromContactid Or FPR_Submitter__c =: fromContactid Or RAE__c =: fromContactid)];
        if (Publications.size() > 0) {
            for(Publication__c Publication : Publications ) {
                if(Publication.Assigned_FPRC__c == FromContactId) {
                    Publication.Assigned_FPRC__c = toContactId;
                }
                if(Publication.First_Author__c == FromContactId) {
                    Publication.First_Author__c = toContactId;
                }
                if(Publication.FPR_Submitter__c == FromContactId) {
                    Publication.FPR_Submitter__c= toContactId;
                }
                if(Publication.RAE__c == FromContactId) {
                    Publication.RAE__c = toContactId;
                }
            }
            update Publications ;
        }
        //PublicationPreFprReviewer
        List<PublicationPreFprReviewer__c> FprReviewers = [Select PreFprReviewer__c, id FROM PublicationPreFprReviewer__c WHERE PreFprReviewer__c=: fromContactid];
        if (FprReviewers.size() > 0) {
            for(PublicationPreFprReviewer__c FprReviewer: FprReviewers ) {
                FprReviewer.PreFprReviewer__c = toContactId;
            }
            update FprReviewers ;
        }
       //PublicationTeamMember
        List<PublicationTeamMember__c> pubTeamMembers = [Select Member__c, id FROM PublicationTeamMember__c WHERE Member__c =: fromContactid];
        if (pubTeamMembers.size() > 0) {
            for(PublicationTeamMember__c pubTeamMember : pubTeamMembers) {
                pubTeamMember.Member__c= toContactId;
            }
            update pubTeamMembers;
        }
       //PublicationMe 
        List<PubME__c> PubMes = [Select WritingRoleMember__c , id FROM PubME__c WHERE WritingRoleMember__c =: fromContactid];
        if (Pubmes.size() > 0) {
            for(PubME__c PubME : PubMes ) {
                PubME.WritingRoleMember__c = toContactId;
            }
            update PubMes ;
        }
        //Study
        List<Study__c> Studies= [Select StudySponsor__c, id FROM Study__c WHERE StudySponsor__c=: fromContactid];
        if (Studies.size() > 0) {
            for(Study__c Study: Studies) {
                Study.StudySponsor__c= toContactId;
            }
            update Studies;
        }
        //PublicationReviewTeam 
        List<PubReviewTeam__c> PubreviewTeams= [Select Reviewer__c,TriageDelegatedBy__c, id FROM PubReviewTeam__c WHERE (Reviewer__c=: fromContactid Or TriageDelegatedBy__c =: fromContactid) ];
        if (PubreviewTeams.size() > 0) {
            for(PubReviewTeam__c PubreviewTeam: PubreviewTeams) {
                if(PubreviewTeam.TriageDelegatedBy__c == FromContactId) {
                    PubreviewTeam.TriageDelegatedBy__c = toContactId;
                }
                if(PubreviewTeam.Reviewer__c== FromContactId) {
                    PubreviewTeam.Reviewer__c = toContactId;
                }
            }
            update PubreviewTeams;
        }
     
    }
}