force-app/main/default/staticresources/python/Disappear/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>SiebelRowId__c</fullName>
        <externalId>true</externalId>
        <label>SiebelRowId</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Used to distinguish between the different types of contacts that are loaded - via data load vs SAP integration and set up in APPEAR Roles.</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>APPEAR</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>SAP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Siebel</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Department__c.object
<CustomObject>
    <fields>
        <fullName>Acronym__c</fullName>
        <label>Acronym</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrganizationId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization</label>
        <referenceTo>Organization__c</referenceTo>
        <relationshipLabel>Departments</relationshipLabel>
        <relationshipName>Departments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SiebelRowId__c</fullName>
        <label>SiebelRowId</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SponsorDept__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sponsor Dept</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Amgen Internal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vendor</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>isLogicallyDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Expired</label>
        <type>Checkbox</type>
    </fields>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/DepartmentModel.cls
public class DepartmentModel {
    
    private static List<Department__c> dDepartmentList= null;
    public static List<Department__c> DepartmentList{
        get{
            if(dDepartmentList== null){
              dDepartmentList= getAllDepartmentList();
            }               
        return dDepartmentList;
        }
    }  

    public static List<Department__c> SponsoringDepartmentList{
        get{             
        	return getSponsoringDepartmentList();
        }
    }
    
	public static Department__c lookupDept(string dept) {
		if (DepartmentNameMap.containsKey(dept)) {
			return DepartmentNameMap.get(dept);
		} else {
			return null;
		}   
	} 
    
   private static Map<String, Department__c> dDepartmentNameMap = null;
   public static Map<String, Department__c> DepartmentNameMap{
     get {
       if (dDepartmentNameMap == null){
         dDepartmentNameMap = getDepartmentMapByName();
       }
       	
       return dDepartmentNameMap;
     }
   }
   
   
	//get Department will be used to insert Contact into PubME
	//if a Contact's Department does not exist in Department table
	//a new row will be inserted
	public static Department__c getDepartment(string DeptName) {
   		if (DepartmentNameMap.containsKey(DeptName)) {
   			return DepartmentNameMap.get(DeptName);
   		}
   		
   		Department__c newDept = new Department__c();
   		newDept.Name = DeptName;
   		newDept.OrganizationId__c = null;
   		newDept.Acronym__c = null;
   		
   		insert newDept;
   		
   		DepartmentNameMap.put(DeptName, newDept);
   		
   		return newDept;
	}
   
   
	public static Map<String, Department__c> getDepartmentMapByName() {
	    Map<String, Department__c> result = new Map<String, Department__c>();
	    for(Department__c dDepartment : DepartmentList){
			result.put(dDepartment.Name, dDepartment );
		}
		return result;
	}
    
    public static List<Department__c> getSponsoringDepartmentList(){
    	List<Department__c> result = new List<Department__c>();
    	for(Department__c dept : DepartmentList) {
    		if ( dept.SponsorDept__c) {
    			result.add(dept);
    		}
    	}
    	return result;
    }
      
    public static List<Department__c> getAllDepartmentList(){
        List<Department__c> result = [
          select id, Name, OrganizationId__c, Acronym__c, SiebelRowId__c, Type__c, URL__c, SponsorDept__c
          From Department__c
          where isLogicallyDeleted__c = false
          order by Name  
           ];
           
        return result;
    }
    
    public static List<Department__c> getCompleteDepartmentList(){
        List<Department__c> result = [
          select id, Name, OrganizationId__c, Acronym__c, SiebelRowId__c, Type__c, URL__c, SponsorDept__c,isLogicallyDeleted__c
          From Department__c
          order by Name  
           ];
           
        return result;
    }
    
    public static Department__c getDepartmentById(Id deptId){
        List<Department__c> result = [
	          select id, Name, OrganizationId__c, Acronym__c, SiebelRowId__c, Type__c, URL__c, SponsorDept__c, isLogicallyDeleted__c
	          From Department__c
	          where id =: deptId
           ];
        
        if(result.size() == 0) {
        	return null;
        }   
        
        return result[0];
    }
   
}