force-app/main/default/staticresources/python/Disappear/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <description>Country Picklist</description>
        <label>Country</label>
        <picklist>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Balkans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia &amp; Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brazil</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brunei</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bulgaria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cambodia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central And Eastern Europe (CEE)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colombia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Costa Rica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Croatia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cyprus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Czech Republic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denmark</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dominican Republic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ecuador</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Egypt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>United States</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Country__c.object
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/pubAuthor__c.object
<CustomObject>
    <fields>
        <fullName>ApprovalSentDate__c</fullName>
        <description>The date the Approval notice has been sent out</description>
        <label>Approval Sent Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AuthorStatus__c</fullName>
        <label>AuthorStatus</label>
        <picklist>
            <picklistValues>
                <fullName>Pending Invite Delivery</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Invite Acceptance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invite Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invitation Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Publication Review by Authors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Author Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed Author Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Author__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Author</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Publication Authors</relationshipLabel>
        <relationshipName>Publication_Authors</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GrantDraftAccess__c</fullName>
        <defaultValue>false</defaultValue>
        <description>used to grant access to the latest draft document related to this publication</description>
        <inlineHelpText>Grant access to the latest draft document related to this publication</inlineHelpText>
        <label>Grant Access</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>InviteAcceptedDate__c</fullName>
        <description>The date when the Author  has accepted the Invitation</description>
        <label>Invite Accepted Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Publication Authors</relationshipLabel>
        <relationshipName>Publication_Authors</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Publication Author</label>
    <nameField>
        <displayFormat>PA-{0000000}</displayFormat>
        <label>Publication Author Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Country is required if SubGroup selected is LACAN, JAPAC, EEMEA for &apos;Global Development&apos; Data Source</inlineHelpText>
        <label>Country Link</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/AppearEmailTest.cls
public class AppearEmailTest extends AppearEmailBase{

    public AppearEmailTest(Contact toContact) {
        super('AppearEmailTest');
 
        subject('AppearEmailTest');
        ToAddress(toContact.Email);

        string htmlBodyStr =
            'AppearEmailTest - this is body';

        htmlBody(htmlBodyStr);
        plainTextBody(htmlBodyStr.replace('<br>', '\\r\\n'));
    }

    //AppearEmailTest.testGoodCase();
    public static void testGoodCase() {
    
        AppearEmailTest email = new AppearEmailTest(EmailPubReviewTeam.contact2);
        email.sendEmail();
    }
    
    //AppearEmailTest.testMaxAddresses();
    public static void testMaxAddresses() {
        AppearEmailTest email = new AppearEmailTest(EmailPubReviewTeam.contact2);
        for(integer x=0; x<99; x++) {
            email.ToAddress('benjamin_lau@hotmail.com');
        }
        for(integer x=0; x<25; x++) {
            email.CcAddress('benjamin_lau@hotmail.com');
            email.BccAddress('benjamin_lau@hotmail.com');
        } 
        email.sendEmail();
    }
     
    //AppearEmailTest.undeliverableEmail();
    public static void undeliverableEmail() {
        AppearEmailTest email = new AppearEmailTest(EmailPubReviewTeam.contact1);
        email.CcAddress('canotbedelivered-bademailaddress@benjaminlau.com');
        email.senderDisplayName('[sender for test undeliverable email]');
        
        //overrode replyTo
        email.replyTo('benjamin_lau@hotmail.com');
        
        email.sendEmail();
    }
    //Appear Enhancement R2
    @isTest(SeeAllData=false) // Appear Enhancement Backlog R2
    public static void authorInvitationReminderApprovalMailTest(){
        Publication__c pub = UnitTestData.PublicationNew('SelectDeselectAuthorsTest');
        User currentUser = [Select email from User where username = :UserInfo.getUserName() limit 1];
        Contact aContact = new Contact(lastname='testing', firstname='test', Email='ranjeet.kumar3@cognizant.com',country__c='United States');
        insert aContact;
        
        List<PubAuthor__c> pubAuthors= new List<PubAuthor__c>();
        pubAuthors.add(new PubAuthor__c(Publication__c = Pub.Id,Author__c = aContact.Id,GrantDraftAccess__c = true,ApprovalSentDate__c = date.today(),AuthorStatus__c='Pending Invite Delivery'));
        insert pubAuthors;      
        List<Id> pubAuthorIds= new List<Id>();
        for(PubAuthor__c pubs: pubAuthors){
            pubAuthorIds.add(pubs.Id);
        }
        
        system.debug('checking the Id set'+pubAuthorIds);
        
        List<EmailTemplate> emailTemplate = new List<EmailTemplate>([Select id from EmailTemplate where Name='Abstract and Scientific Presentations Author Agreement (Lead Author)' limit 1]);
        List<Id> emailTemplateIds= new List<Id>();
        emailTemplateIds.add(emailTemplate[0].Id);
        //Author Invitation part
        Email_16_AuthorInvitation.Email_16_AuthorInvitationBatchLimit(pubAuthorIds, emailTemplateIds);      
        Email_16_AuthorInvitation.Email_16_AuthorInvitationBatch(pubAuthorIds, emailTemplateIds);
        
        //Author Reminder part
        Email_18_AuthorReminder email_18= new Email_18_AuthorReminder(pubAuthors[0],emailTemplateIds[0],currentUser);
        Email_18_AuthorReminder.Email_18_AuthorReminderBatchLimit(pubAuthorIds, emailTemplateIds);
        Email_18_AuthorReminder.Email_18_AuthorReminderBatch(pubAuthorIds, emailTemplateIds);
        
        //Final Author Approval
        Email_17_AuthorApproval email_17= new Email_17_AuthorApproval(pubAuthors[0],emailTemplateIds[0],currentUser);
        Email_17_AuthorApproval.Email_17_AuthorApprovalBatchLimit(pubAuthorIds, emailTemplateIds);
    }
    
    
    
    @IsTest
    public static void EmailUnitTest1() {
        testGoodCase() ;
        testMaxAddresses();
    }
    
    
    @IsTest
    public static void EmailTemplatesUnitTest1(){
        Email_01_FprcConfirmationForSubmitter.testEmail();
        Email_02_RoutedForPrimary.testEmail();
        Email_03_RoutedToDelegate.testEmail();
        Email_04_RoutedToTriagee.testEmail();
        Email_05_PubWithheld.testEmail();
    }
    
    @IsTest
    public static void EmailTemplatesUnitTest2(){
        Email_06_PubWithdrawn.testEmail();
        Email_07_FprDiscussionRequired.testEmail();
        Email_08_IndividualFprReviewerReviewed.testEmail();
        Email_09_IndividualFprReviewerCommented.testEmail();
        Email_10_FullFprReviewComplete.testEmail();
    }

    @IsTest
    public static void EmailTemplatesUnitTest3(){
        Email_11_IndividCourtesyFprRevCommented.testEmail();
        Email_12_IndividCourtesyFprRevReviewed.testEmail();
        Email_13_CourtesyFprReviewComplete.testEmail();
        Email_14_ChangeReviewerTypeOrNewPrimary.testEmail();
        Email_15_FullFprReviewWithCmtsComplete.testEmail();
    }
    
    @IsTest(SeeAllData=false)
    public static void EmailTemplatesUnitTest16_17(){

        /*
        EmailTemplate aTemplate = new EmailTemplate();
        aTemplate.name = 'Author Agreement'; 
        aTemplate.DeveloperName = 'author_agreement'; 
        insert aTemplate; 
        */
    
        Id userId = userInfo.getUserId();              
        

        
        Publication__c pub = UnitTestData.PublicationNew('SelectDeselectAuthorsTest');
        Contact aContact = new Contact(lastname='testing', firstname='test', userid__c=userId, Email='if@test.com.invalid');
        insert aContact;
        
        PubAuthor__c PubAuthApprove = new PubAuthor__c();
        PubAuthApprove.Publication__c = Pub.Id;
        PubAuthApprove.Author__c = aContact.Id;
        PubAuthApprove.GrantDraftAccess__c = true; 
        PubAuthApprove.ApprovalSentDate__c = date.today();
        PubAuthApprove.InviteAcceptedDate__c  = date.today();
        PubAuthApprove.AuthorStatus__c='Pending Author Approval';
        insert PubAuthApprove;
        

        Email_16_AuthorInvitation.testBatchEmails();
        Email_16_AuthorInvitation.testEmail();
        Email_17_AuthorApproval.testBatchEmails();
        Email_17_AuthorApproval.testEmail();        
        Email_18_AuthorReminder.testEmail();
        Email_18_AuthoRreminder.testBatchEmails();
        Email_19_DraftShare.testEmail();
        Email_19_DraftShare.testBatchEmails();      
    }
    
    
    @IsTest(SeeAllData=false)
    private static void TestMultipleBatchEmail16(){       
        AppearTriggerActivationModel.shouldSkipPubAuthorTrigger = true;
        
        Id userId = userInfo.getUserId();       
        Publication__c pub = UnitTestData.PublicationNew('TestMultipleBatchEmail16');
        for(integer i = 0; i < 11; i++) {
            Contact aContact = new Contact(lastname='testing'+i,firstname='test'+i,userid__c=userId, Email=i+'if@test.com.invalid');
            insert aContact;
            
            PubAuthor__c PubAuthApprove = new PubAuthor__c();
            PubAuthApprove.Publication__c = pub.Id;
            PubAuthApprove.Author__c = aContact.Id;
            PubAuthApprove.GrantDraftAccess__c = true; 
            PubAuthApprove.ApprovalSentDate__c = date.today();
            PubAuthApprove.InviteAcceptedDate__c  = date.today();
            PubAuthApprove.AuthorStatus__c='Pending Author Approval';
            insert PubAuthApprove;
        }
        
        Test.startTest();
        Email_16_AuthorInvitation.testBatchEmails();
        Test.stopTest();
        AppearTriggerActivationModel.shouldSkipPubAuthorTrigger = true;
    }
    
}