force-app/main/default/staticresources/python/Disappear/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <description>Used to distinguish between the different types of contacts that are loaded - via data load vs SAP integration and set up in APPEAR Roles.</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>APPEAR</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>SAP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Siebel</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/pubAuthor__c.object
<CustomObject>
    <fields>
        <fullName>ApprovalSentDate__c</fullName>
        <description>The date the Approval notice has been sent out</description>
        <label>Approval Sent Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Approval_Disclaimer_ID__c</fullName>
        <description>Contains the ID of the approval disclaimer used</description>
        <label>Approval Disclaimer ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AuthorOrder__c</fullName>
        <label>Author Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AuthorStatus__c</fullName>
        <label>AuthorStatus</label>
        <picklist>
            <picklistValues>
                <fullName>Pending Invite Delivery</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Invite Acceptance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invite Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Invitation Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Publication Review by Authors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Author Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed Author Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Author__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Author</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Publication Authors</relationshipLabel>
        <relationshipName>Publication_Authors</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CommentReceivedDate__c</fullName>
        <description>Stores the author comment received date</description>
        <label>CommentReceivedDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Disclaimer_ID__c</fullName>
        <description>Contains the ID of the invite disclaimer used</description>
        <label>Invite Disclaimer ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DraftShareDate__c</fullName>
        <description>The date on which Draft Share email was sent</description>
        <label>Draft Share Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>GrantDraftAccess__c</fullName>
        <defaultValue>false</defaultValue>
        <description>used to grant access to the latest draft document related to this publication</description>
        <inlineHelpText>Grant access to the latest draft document related to this publication</inlineHelpText>
        <label>Grant Access</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>InviteAcceptedDate__c</fullName>
        <description>The date when the Author  has accepted the Invitation</description>
        <label>Invite Accepted Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>InviteSentDate__c</fullName>
        <description>The date the Invitation was sent out.</description>
        <label>Invite Sent Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Publication Authors</relationshipLabel>
        <relationshipName>Publication_Authors</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>isLogicallyDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used for logical deletion or soft deletion of Pub Authors.</description>
        <label>isLogicallyDeleted</label>
        <type>Checkbox</type>
    </fields>
    <label>Publication Author</label>
    <nameField>
        <displayFormat>PA-{0000000}</displayFormat>
        <label>Publication Author Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PubEmail__c.object
<CustomObject>
    <description>Object is created to store Emails send to Authors</description>
    <fields>
        <fullName>Author__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Field is used to store the author record whom the emails are send</description>
        <label>Author</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Publication Emails</relationshipLabel>
        <relationshipName>Publication_Emails</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CC__c</fullName>
        <description>Other users who are receiving this mail in CC</description>
        <label>CC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Body__c</fullName>
        <description>field is used to store the Email body which is send to the Authors</description>
        <label>Email Body</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Publication_Author__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Used to store the value of the Junction record between Author and Publication</description>
        <label>Publication Author</label>
        <referenceTo>pubAuthor__c</referenceTo>
        <relationshipLabel>Publication Emails</relationshipLabel>
        <relationshipName>Publication_Emails</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <description>Field is used to store the Subject Line of Email send to Author</description>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>used to store which type of Email send to Author</description>
        <label>Email Type</label>
        <picklist>
            <picklistValues>
                <fullName>Invitation Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reminder Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final Author Approval Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft-Share Email</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Publication Email</label>
    <nameField>
        <displayFormat>Pub-Email-{000000}</displayFormat>
        <label>Publication Email</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/Email_19_DraftShare.cls
public class Email_19_DraftShare extends AppearEmailBase  {


    public Email_19_DraftShare(pubAuthor__c aPub , Id emailTemplateId, User currentUser) {
        super();            
                //List<String> toAddressIds = new List<String> {aPub.author__r.email};
                //ToAddresses(toAddressIds); // SFDC CASE: 11260997 {Sesha: This is not required when using the standard SFDC VF email template as the TARGET OBJECT is already calling the EMAIL Object and working as DESIGNED by SFDC.}
                replyTo(currentUser.email); 
                CcAddress(currentUser.email);
                whatId(aPub.id);
                templateId(emailTemplateId);
                targetObjectId(aPub.author__c);     
    }

    public Email_19_DraftShare() {
        super();
    }
    
    @future
    public static void Email_19_DraftShareBatchLimit(List<id> pubAuthorIds){        
        EmailTemplate emailTemplateId = [select id,name,Isactive,Folder.Name from EmailTemplate Where IsActive = true And (Folder.Name = 'Draft Share Reminder Templates') order by createdDate desc limit 1];
            
        List <pubAuthor__c> pubAuthorList = [select id, InviteAcceptedDate__c, GrantDraftAccess__c, InviteSentDate__c, AuthorStatus__c, publication__c, author__c, author__r.name, author__r.email, AuthorOrder__c, Approval_Disclaimer_ID__c, ApprovalSentDate__c
                                            from PubAuthor__c
                                            where id in :pubAuthorIds
                                            AND isLogicallyDeleted__c = false //Appear Enhancement R3 : Soft Delete Author functionality                                     
                                            ];
        
        User currentUser = [Select email from User where username = :UserInfo.getUserName() limit 1];   
        for (integer i = 0; i < pubAuthorList.size(); i++ ){
            // iy: currently use SingleEmailMessage. Shoud consider bulkifying the code if volume is large
            try {
                Email_19_DraftShare email = new Email_19_DraftShare(pubAuthorList[i], emailTemplateId.id, currentUser);
                if (!email.sendEmailWithResult()){
                    System.debug('Email_19_DraftShare / failed to deliver to:' + pubAuthorList[i].id ); 
                }
            } catch (AppearException appearEx){
                AppLogModel.LogError('Email_19_DraftShareBatchLimit', 'The invitation email delivery to ' + pubAuthorList[i].author__r.email, pubAuthorList[i].id);                         
                // ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, 'The attachment status email delivery to ' + pubAuthorList[i].author__r.email + ' failed. Please validate if the email address is correct. If the problem persists, please contact the system administrator.' ));                       
            } catch (EmailException emailEx) {
                AppLogModel.LogError('Email_19_DraftShareBatchLimit', 'The invitation email delivery to ' + pubAuthorList[i].author__r.email, pubAuthorList[i].id);                     
                // ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, 'The attachment status email delivery to ' + pubAuthorList[i].author__r.email + ' failed. Please validate if the email address is correct. If the problem persists, please contact the system administrator.' + ' Error Details: ' + emailEx.getMessage()));
            } catch(DmlException dmlEx) {
                AppLogModel.LogError('Email_19_DraftShareBatchLimit', 'The invitation email delivery to ' + pubAuthorList[i].author__r.email, pubAuthorList[i].id);                         
                // ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, 'The attachment status email delivery to ' + pubAuthorList[i].author__r.email + ' failed. Please validate if the email address is correct. If the problem persists, please contact the system administrator.' + ' Error Details: ' + dmlEx.getMessage()));
            } finally {
                AppLogModel.flushLogs();
            }
        }         
    }
    
    public static void Email_19_DraftShareBatch(id pubId ){
        List <pubAuthor__c> pubAuthorList = [select id
                                            from PubAuthor__c
                                            where GrantDraftAccess__c = true and InviteAcceptedDate__c != null
                                            and  publication__c = :PubId
                                            and isLogicallyDeleted__c = false //Appear Enhancement R3 : Soft Delete Author functionality                                     
                                            ];    
        
        // the size of pubAuthorIds and emailTemplates should match. Currently, all emailTemplates are the same. 
        Decimal APILimit = 10;  // Total number of sendEmail methods allowed = 10
        Decimal batchCount = 0; 
        List <id> pubAuthorIdsByLimit = new List<id>(); 
        
        for (integer i = 0; i < pubAuthorList.size(); i++ ){

            batchCount++; 
            pubAuthorIdsByLimit.add(pubAuthorList[i].Id);
            
            if (batchCount == APILimit){
                Email_19_DraftShareBatchLimit(pubAuthorIdsByLimit); 
                batchCount = 0; 
                pubAuthorIdsByLimit.clear();  
            }
        }
        if (batchCount > 0){
            Email_19_DraftShareBatchLimit(pubAuthorIdsByLimit);             
            batchCount = 0; 
            pubAuthorIdsByLimit.clear();  
        }
                             
    }
    
    //=====================
 // Appear Enhancment R3
 // =====================
 	
    //Future Method to send the Draft-Share email
      @future 
    public static void Email_19_DraftShareBatchLimit(List <id> pubAuthorIds, List<id> emailTemplateIds ){
            
        // the caller of this method is responsible for grovenor limit. 
               
        List <pubAuthor__c> pubAuthorList = [select id,  AuthorStatus__c, publication__c, author__c, author__r.name, author__r.email, AuthorOrder__c, ApprovalSentDate__c, InviteSentDate__c, Disclaimer_ID__c
                                            from PubAuthor__c
                                            where id in :pubAuthorIds
                                            and isLogicallyDeleted__c = false //Appear Enhancement R3 : Soft Delete Author functionality                                    
                                            ]; 
        User currentUser = [Select email from User where username = :UserInfo.getUserName() limit 1];   
        //Appear Enhancement R2, list is created for Store Author Email functionality
        List<PubEmail__c> authorDraftShareEmailList = new List<PubEmail__c>();
        
        for (integer i = 0; i < pubAuthorList.size(); i++ ){
                // iy: currently use SingleEmailMessage. Shoud consider bulkifying the code if volume is large
                try {
                	id docId = PubAuthorModelNoSharing.getLatestPubAuthorDraftShareId(pubAuthorList[i].publication__c); 
                    Email_19_DraftShare email = new Email_19_DraftShare(pubAuthorList[i], emailTemplateIds[i], currentUser);
                    if (email.sendEmailWithResult()){
                        pubAuthorList[i].DraftShareDate__c = date.today(); 
                        pubAuthorList[i].Disclaimer_ID__c = docId;  
                        // Backlog R2 Req.29 - Appear Enhancement backlog R2 2017 - Remove Nullification of CommentReceiveDate
                        //pubAuthorList[i].CommentReceivedDate__c = null;//Changing the comment received to null once Draft has been shared
                        if (pubAuthorList[i].AuthorStatus__c == null || pubAuthorList[i].AuthorStatus__c == PubAuthorModelNoSharing.sPublicationReviewByAuthors || pubAuthorList[i].AuthorStatus__c =='' ){
                            pubAuthorList[i].AuthorStatus__c = PubAuthorModelNoSharing.sPublicationReviewByAuthors;
                        }
                        pubAuthorList[i].GrantDraftAccess__c = true; //Appear Enhancement R3 Share Draft -Grant Draft Access checked to true
                        //Appear Enhancement R2
                        PubEmail__c draftShareEmail = new PubEmail__c();
                        draftShareEmail.Email_Body__c  = email.getHtmlMailBody();
                        List<String> ccaddresses=email.getCCAddresses();
                        String ccAddressString;
                        for(String ccadd:ccaddresses){
                            ccAddressString=ccadd+';';
                        }
                        draftShareEmail.CC__c=ccAddressString;
                        draftShareEmail.Author__c = pubAuthorList[i].author__c;   
                        draftShareEmail.Subject__c = email.getSubject();   
                        draftShareEmail.Publication_Author__c= pubAuthorList[i].id;  
                        draftShareEmail.Type__c='Draft-Share Email';                        
                        authorDraftShareEmailList.add(draftShareEmail);
                    }
                } catch (AppearException appearEx){
                    // remove message from future all since it is out of VF context
                    // ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, 'The invitation email delivery to ' + pubAuthorList[i].author__r.email + ' failed. Please validate if the email address is correct. If the problem persists, please contact the system administrator.' ));  
                    AppLogModel.LogError('Email_16_AuthorInvitationBatchLimit', 'The invitation email delivery to ' + pubAuthorList[i].author__r.email, pubAuthorList[i].id);                   
               } catch (EmailException emailEx) {
                    // ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, 'The invitation email delivery to ' + pubAuthorList[i].author__r.email + ' failed. Please validate if the email address is correct. If the problem persists, please contact the system administrator.' + ' Error Details: ' + emailEx.getMessage()));
                    AppLogModel.LogError('Email_16_AuthorInvitationBatchLimit', 'The invitation email delivery to ' + pubAuthorList[i].author__r.email, pubAuthorList[i].id);                   
                } catch(DmlException dmlEx) {
                    // ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, 'The invitation email delivery to ' + pubAuthorList[i].author__r.email + ' failed. Please validate if the email address is correct. If the problem persists, please contact the system administrator.' + ' Error Details: ' + dmlEx.getMessage()));
                    AppLogModel.LogError('Email_16_AuthorInvitationBatchLimit', 'The invitation email delivery to ' + pubAuthorList[i].author__r.email, pubAuthorList[i].id);                   
                } finally {
                    AppLogModel.flushLogs();
                }
               
        } 
        //Appear Enhancement R2, inserting the Draft-Share Email Records to Publication Email Object
        insert authorDraftShareEmailList;
        
        AppearTriggerActivationModel.shouldSkipUsAuthorUpdate = true;
        update pubAuthorList; 
        AppearTriggerActivationModel.shouldSkipUsAuthorUpdate = false;
        
    }
    //Future Method to send the Draft-Share email
    
    //Start - New overloaded method written to pass the email template as parameters along with the PubIds
        public static void Email_19_DraftShareBatch(List <id> pubAuthorIds, List<id> emailTemplateIds ){
            
        // the size of pubAuthorIds and emailTemplates should match. Currently, all emailTemplates are the same. 
        Decimal APILimit = 10;  // Total number of sendEmail methods allowed = 10
        Decimal batchCount = 0; 
        List <id> pubAuthorIdsByLimit = new List<id>(); 
        List <id> emailTemplateIdsByLimit = new List <id>(); 
        
        for (integer i = 0; i < pubAuthorIds.size(); i++ ){

            batchCount++; 
            pubAuthorIdsByLimit.add(pubAuthorIds[i]); 
            emailTemplateIdsByLimit.add(emailTemplateIds[i]); 
            
            if (batchCount == APILimit){
                Email_19_DraftShareBatchLimit(pubAuthorIdsByLimit,  emailTemplateIdsByLimit ); 
                batchCount = 0; 
                pubAuthorIdsByLimit.clear();
                emailTemplateIdsByLimit.clear();  
            }
        }
        if (batchCount > 0){
                Email_19_DraftShareBatchLimit(pubAuthorIdsByLimit,  emailTemplateIdsByLimit );
                batchCount = 0; 
                pubAuthorIdsByLimit.clear();
                emailTemplateIdsByLimit.clear();  
        }

        ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.INFO,  'Author Draft Share email(s) are queued for delivery. Please check back after couple minutes to view the system updates.'));    
    }
    //End - New overloaded method written to pass the email template as parameters along with the PubIds
    
    
    //=====================
 // Appear Enhancment R3
 // =====================
    
    
  
    public static void testBatchEmails(){       
        /*EmailTemplate template = New EmailTemplate(Name = 'Author Approval', Body = null, BrandTemplateId=null, DeveloperName='Author_Agreement', FolderId=UserInfo.getUserId(), IsActive=True, Subject='test', TemplateType='Text');
        insert template;*/
        
        List<pubAuthor__c> pubAuthors = [select id, publication__c, author__r.Email, author__c from pubAuthor__c where GrantDraftAccess__c = true and InviteAcceptedDate__c != null and author__r.Email like '%if%' 
            							and isLogicallyDeleted__c = false //Appear Enhancement R3 : Soft Delete Author functionality
                                         limit 1 
                                        ]; // pick any one record 
        
        if (pubAuthors.size() > 0 ) {
            Email_19_DraftShareBatch(pubAuthors[0].publication__c );
        }
    }
    
    
    

    public static void testEmail() {

        // whatId : pub_author__c
        // templateid : Author Invitation 
        // targetObjectId: contact 
        
        // this test method send email to the current user, even though the body of the email is reference to one of the pub author
        List<pubAuthor__c> pubAuthors = [select id,  author__r.Email, author__c from pubAuthor__c 
                                         Where isLogicallyDeleted__c = false //Appear Enhancement R3 : Soft Delete Author functionality
                                         limit 1                                         
                                        ]; // pick any one record 
        if (!pubAuthors.isEmpty()) {
                pubAuthor__c aPubAuthorId = pubAuthors[0]; 
                
                EmailTemplate aTemplate = [SELECT id, Name FROM EmailTemplate where name like '%Author Approval%' limit 1];
                
                if (aTemplate != null){

                    Email_19_DraftShare email = new Email_19_DraftShare(); 
                    //get the current user in context
                    User currentUser = [Select email from User where username = :UserInfo.getUserName() limit 1];   
                    List<String> toAddressIds = new List<String> {currentUser.email};
                    email.replyTo(currentUser.email); 
                    email.ToAddresses(toAddressIds);
                    email.CcAddress(currentUser.email);
                    email.whatId(aPubAuthorId.id);
                    email.templateId(aTemplate.id);
                    email.targetObjectId(aPubAuthorId.author__c); 
                    email.sendEmail();

                } else{
                    AppLogModel.LogDebug('Email_19_DraftShare::testEmail','missing template');                  
                }      
        } else {
                     AppLogModel.LogDebug('Email_19_DraftShare::testEmail','Cannot find contact');                  
        }
        
    }

}