force-app/main/default/staticresources/python/Disappear/src/objects/Country__c.object
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Journal__c.object
<CustomObject>
    <label>Journal</label>
    <nameField>
        <displayFormat>Journal-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Meeting__c.object
<CustomObject>
    <description>Used for the Meeting target and to maintain Meeting related Data</description>
    <label>Meeting</label>
    <nameField>
        <displayFormat>MTG-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Country is required if SubGroup selected is LACAN, JAPAC, EEMEA for &apos;Global Development&apos; Data Source</inlineHelpText>
        <label>Country Link</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Target__c</fullName>
        <description>The Current Target field will also be used to populate the Target field for a new Submission Cycle.
This field should NEVER be moved to a formula</description>
        <inlineHelpText>This field is populated automatically by using the &quot;Target&quot; button on the Details tile.  If the desired target is NOT found using the Target button, please use the &quot;Target Not Found&quot; field below.</inlineHelpText>
        <label>Current Target</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Journal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Journal</label>
        <referenceTo>Journal__c</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Meeting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Meeting</inlineHelpText>
        <label>Meeting</label>
        <referenceTo>Meeting__c</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PubStatus__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Current status of this publication</description>
        <label>PubStatus</label>
        <referenceTo>PubStatus__c</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link Publication to a SubGroup - which we can find the DataSource for the publication.
This link is very important for the auto population of FPR Reviewer.</description>
        <inlineHelpText>For purposes of FPR routing, functional group from which publication content/or data was orignated. Enter one of these selections - Research, Development, Operations - before clicking the Lookup icon.  Then select a SubGroup from the Search Results list.</inlineHelpText>
        <label>SubGroup Link</label>
        <referenceTo>SubGroup__c</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target_Type__c</fullName>
        <description>Default TargetType for the next Submission Cycle</description>
        <label>Target Type</label>
        <picklist>
            <picklistValues>
                <fullName>Journal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <recordTypes>
        <fullName>Execute</fullName>
        <active>true</active>
        <label>Execute</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PubStatus__c.object
<CustomObject>
    <description>List of Status for a Publication - Target Date / Revised Date / Actual Date
Will be used for planning</description>
    <fields>
        <fullName>Journal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Target to which Journal</description>
        <label>Journal</label>
        <referenceTo>Journal__c</referenceTo>
        <relationshipName>PubStatuses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Meeting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Target a Meeting</description>
        <label>Meeting</label>
        <referenceTo>Meeting__c</referenceTo>
        <relationshipName>PubStatuses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publication_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication_id</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipName>PubStatus</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Submission_Cycle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Submission Cycle</label>
        <referenceTo>SubmissionCycle__c</referenceTo>
        <relationshipName>Pub_Statuses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publication Status</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>PubStatus Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/SubGroup__c.object
<CustomObject>
    <label>SubGroup</label>
    <nameField>
        <label>SubGroup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SubGroups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/SubmissionCycle__c.object
<CustomObject>
    <description>record name will be PubId-{0000000}-SubCycle-{00}</description>
    <fields>
        <fullName>Journal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Journal</label>
        <referenceTo>Journal__c</referenceTo>
        <relationshipLabel>Submission Cycles</relationshipLabel>
        <relationshipName>Submission_Cycles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Meeting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Meeting</label>
        <referenceTo>Meeting__c</referenceTo>
        <relationshipLabel>Submission Cycles</relationshipLabel>
        <relationshipName>Submission_Cycles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Submission Cycles</relationshipLabel>
        <relationshipName>Submission_Cycles</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Submission_Cycle_Num__c</fullName>
        <label>Submission Cycle #</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TargetLabelFormula__c</fullName>
        <formula>IF( TEXT(Target_Type__c) = &quot;meeting&quot;,  Meeting__r.MeetingName255__c ,  Journal__r.JournalName255__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Target Label</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Type__c</fullName>
        <label>Target Type</label>
        <picklist>
            <picklistValues>
                <fullName>Journal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Submission Cycle</label>
    <nameField>
        <label>Submission Cycle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submission Cycles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/BatchSyncTargetPubStatusToSC.cls
global class BatchSyncTargetPubStatusToSC extends BatchBase 
	implements Database.Batchable<SObject>,Database.Stateful {
   	public String SOQL = 'select id,name, Current_Target__c from Publication__c ' +
    	' order by name desc ';
	public BatchSyncTargetPubStatusToSC() {
		super();
    	if ( Test.isRunningTest()){
    		SOQL = SOQL + ' limit 10';
    	}
    	AddMessage(SOQL);
        system.debug(SOQL);
	}
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        batchableContext = BC;
        batchName = 'BatchSyncTargetPubStatusToSC';
        System.Debug(SOQL);
        return Database.getQueryLocator(SOQL);
    }

    global void execute(Database.BatchableContext BC, List<publication__c> pubs){
    	syncPubs(pubs);
    }
    
    public static void syncPubs(List<Publication__c> pubs) {
    	//collect id of all pub to grab pubStatus
    	Set<id> pubIdset = new Set<id>();
    	for(Publication__c pub : pubs) {
    		pubIdset.add(pub.id);
    	}
    	
    	List<PubStatus__c> pubStatusList = [
    		select Submission_Cycle__c, Journal__c, Meeting__c, publication_id__r.name
    		from PubStatus__c
    		where Publication_Id__c in :pubIdset  
    	];
    	
    	Map<Id,PubStatus__c> ScPubStatusMap = new Map<Id,PubStatus__c>();
    	Set<Id> ScIdSet = new Set<Id>();
    	for(PubStatus__c pubstatus : pubStatusList) {
    		if (pubStatus.Journal__c <> null || pubStatus.Meeting__c <> null) {
    			ScPubStatusMap.put(pubstatus.Submission_Cycle__c, pubstatus);
    			ScIdSet.add(pubstatus.Submission_Cycle__c);
    		} else {
    			AppLogModel.LogError('BatchSyncTargetPubStatusToSC', 
    				' pubstatus of '+pubstatus.publication_id__r.name+' has no reference to journal or meeting');
    		}
    	}
    	
    	//now get all the Submission Cycles
    	List<SubmissionCycle__c> ScList = [
    		select id,name,Target_Type__c, Journal__c, Meeting__c
    		from SubmissionCycle__c  
    		where id in :ScIdSet
    		order by Submission_Cycle_Num__c  
    	];
    	
    	for(SubmissionCycle__c sc : ScList){
    		if ( ScPubStatusMap.containsKey(sc.id)){
    			PubStatus__c ps = ScPubStatusMap.get(sc.id);
    			sc.Journal__c = ps.Journal__c;
    			sc.Meeting__c = ps.Meeting__c;
    			if ( ps.Meeting__c <> null) {
    				sc.Target_Type__c = 'meeting';
    			} else {
    				sc.Target_type__c = 'journal';
    			}
    		} else {
  				AppLogModel.LogError('BatchSyncTargetPubStatusToSC', 
    				' ScPubStatusMap does not containsKey(sc.id) for '+sc.name);  			
    		}
    	}
    	
    	update ScList;
    	
    	for(id pubId : pubIdset) {
    		PublicationTriggerLogic.UpdateLatestPubStatusById(pubId, true);  
    	}
    	
    	//finally get all the pubs to update Current Target
    	List<Publication__c> pubList2 = [
    		select name, Current_Target__c, PubStatus__c, country__c,SubGroup__c,
    		PubStatus__r.Submission_Cycle__c, PubStatus__r.Submission_Cycle__r.TargetLabelFormula__c
    		from Publication__c
    		where id in :pubIdset
    	];
    	

    	for (Publication__c pub : pubList2) {
    		if (pub.PubStatus__r.Submission_Cycle__c <> null ) {
    			if (pub.PubStatus__r.Submission_Cycle__r.TargetLabelFormula__c <> null) {
					pub.Current_Target__c = pub.PubStatus__r.Submission_Cycle__r.TargetLabelFormula__c;
    			} else {
    				AppLogModel.LogError('BatchSyncTargetPubStatusToSC', 
    					pub.name +' pub.PubStatus__r.Submission_Cycle__r.TargetLabelFormula__c == null');
    			}
    		} else {
 				AppLogModel.LogError('BatchSyncTargetPubStatusToSC', 
					pub.name +' pub.PubStatus__r.Submission_Cycle__c == null');   			
    		}
    		if ( pub.SubGroup__c == SubGroupModelData.DevelopmentIrdSubGroup.id && pub.country__c == null) {
    			pub.country__c = CountryModel.Unknown.id;
    		}
    	}	
		update pubList2;

		AppLogModel.flushLogs();
    }
	
	//BatchSyncTargetPubStatusToSC.syncOnePub('Pub-Id-081125');
	public static void syncOnePub(string pubName){
		List<Publication__c> pubs = [
			select id,name, Current_Target__c
			from Publication__c 
			WHERE name = :pubName  
		];
		
		syncPubs(pubs);
	}
	
	//BatchSyncTargetPubStatusToSC.runNow();
	public static void runNow(){
    	BatchSyncTargetPubStatusToSC batch = new BatchSyncTargetPubStatusToSC();
        Database.executeBatch(batch, 50);
	}
    
    global void finish(Database.BatchableContext BC){
		SendBatchCompletionEmail();
	}

//////////////////////////////////////////  unit test /////////////////////////////////////
	@IsTest
	Public static void unitTest() {
		AppearPubModel activePub = CreateData();
		
		BatchSyncTargetPubStatusToSC.syncOnePub(activePub.pubId);
		BatchSyncTargetPubStatusToSC.runNow();
	} 
	
	public static AppearPubModel CreateData() {
		RegionModelData.createData();
		CountryModelData.createData();
		
		DataSourceModelData.createData();
		SubGroupModelData.createData();
		
		MeetingModelData.createData();
		
		System.assertNotEquals(null, CountryModel.Unknown.id);
		System.assertNotEquals(null, SubGroupModelData.DevelopmentIrdSubGroup.id);
		
		Publication__c pub = UnitTestData.PublicationNew('pubtest');
		AppearPubModel activePub = new AppearPubModel(pub.id);
		activePub.SubmissionCycle.CurrentSubmissionCycle.Target_Type__c = 'meeting';
		activePub.SubmissionCycle.CurrentSubmissionCycle.Meeting__c = MeetingModel.getAllMeetingList()[0].id;
		
		update activePub.SubmissionCycle.CurrentSubmissionCycle;
		
		return activePub;
	}
}