force-app/main/default/staticresources/python/Disappear/src/objects/DataSource__c.object
<CustomObject>
    <label>Data Source</label>
    <nameField>
        <label>DataSource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Sources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Review_Team__c.object
<CustomObject>
    <description>Review team for DataSource or SubGroup

A review team can exists for a DataSource without SubGroup</description>
    <fields>
        <fullName>Data_Source__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Data Source</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>DataSource__c.isLogicallyDeleted__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>DataSource__c</referenceTo>
        <relationshipLabel>Review Teams</relationshipLabel>
        <relationshipName>Review_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Indication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product Indication</label>
        <referenceTo>ProductIndication__c</referenceTo>
        <relationshipLabel>Review Teams</relationshipLabel>
        <relationshipName>Review_Teams</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubGroup__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>SubGroup</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>SubGroup__c.isLogicallyDeleted__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SubGroup__c</referenceTo>
        <relationshipLabel>Review Teams</relationshipLabel>
        <relationshipName>Review_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Review Team</label>
    <nameField>
        <label>Review Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Review Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/SubGroup__c.object
<CustomObject>
    <fields>
        <fullName>Data_Source__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Data Source</label>
        <referenceTo>DataSource__c</referenceTo>
        <relationshipLabel>SubGroups</relationshipLabel>
        <relationshipName>SubGroups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SubGroup</label>
    <nameField>
        <label>SubGroup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SubGroups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/ReviewTeamModel.cls
public class ReviewTeamModel {


    public static List<Review_Team__c> findReviewTeamsBySubGroupProdInd(id SubGroupId, Set<Id> ProdIndList) {
    
        List<Review_Team__c> result = [
            select Name, Data_Source__c, Data_Source__r.name, subGroup__c, subGroup__r.Name
            from Review_Team__c
            where SubGroup__c = :SubGroupId
            and Product_Indication__c in :ProdIndList
        ];
        return result;
        
    }

    public static List<Review_Team__c> findReviewTeamsByDataSourceProdInd(id DataSourceId, Set<Id> ProdIndList) {

        List<Review_Team__c> result = [
            select Name, Data_Source__c, Data_Source__r.name, subGroup__c, subGroup__r.Name
            from Review_Team__c
            where SubGroup__c = :DataSourceId
            and Product_Indication__c in :ProdIndList
        ];
        return result;
        
    }
    
    private static List<Review_Team__c> pReviewTeamList = null;
    public static List<Review_Team__c> ReviewTeamList {
        get {
            if (pReviewTeamList == null){
                pReviewTeamList = getAllReviewTeams();
            }
            return pReviewTeamList;
        }
    }
    
    public static List<Review_Team__c> getAllReviewTeams() {
        List<Review_Team__c> result = [
            Select Name, Data_Source__c, Data_Source__r.name, subGroup__c, subGroup__r.Name, Product_Indication__c 
            From Review_Team__c 
            ];
        return result;
    }
     
    
   private static Map<String, Review_Team__c> pReviewTeamNameMap = null;
   public static Map<String, Review_Team__c> ReviewTeamNameMap{
     get {
       if (pReviewTeamNameMap == null){
         pReviewTeamNameMap = getReviewTeamMapByName();
       }
       return pReviewTeamNameMap;
     }
   }
   
   public static Map<String, Review_Team__c> getReviewTeamMapByName() {
    Map<String, Review_Team__c> result = new Map<String, Review_Team__c>();
    for(Review_Team__c pReviewTeam : ReviewTeamList){
      result.put(pReviewTeam.Name, pReviewTeam );
    }

    return result;
  }
    
   private static Map<Id, Review_Team__c> pReviewTeamMap = null;
   public static Map<Id, Review_Team__c> ReviewTeamMap{
     get {
       if (pReviewTeamMap == null){
         pReviewTeamMap = getReviewTeamMap();
       }
       return pReviewTeamMap;
     }
   }
   
   public static Map<Id, Review_Team__c> getReviewTeamMap() {
    Map<Id, Review_Team__c> result = new Map<Id, Review_Team__c>();
    for(Review_Team__c pReviewTeam : ReviewTeamList){
      result.put(pReviewTeam.Id, pReviewTeam );
    }

    return result;
  }


}