force-app/main/default/staticresources/python/Disappear/src/objects/DataSource__c.object
<CustomObject>
    <label>Data Source</label>
    <nameField>
        <label>DataSource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Sources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/ProductIndication__c.object
<CustomObject>
    <label>Product Indication</label>
    <nameField>
        <label>ProductIndication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Indications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Review_Team__c.object
<CustomObject>
    <description>Review team for DataSource or SubGroup

A review team can exists for a DataSource without SubGroup</description>
    <fields>
        <fullName>Data_Source__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Data Source</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>DataSource__c.isLogicallyDeleted__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>DataSource__c</referenceTo>
        <relationshipLabel>Review Teams</relationshipLabel>
        <relationshipName>Review_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Indication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product Indication</label>
        <referenceTo>ProductIndication__c</referenceTo>
        <relationshipLabel>Review Teams</relationshipLabel>
        <relationshipName>Review_Teams</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubGroup__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>SubGroup</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>SubGroup__c.isLogicallyDeleted__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SubGroup__c</referenceTo>
        <relationshipLabel>Review Teams</relationshipLabel>
        <relationshipName>Review_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Review Team</label>
    <nameField>
        <label>Review Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Review Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/SubGroup__c.object
<CustomObject>
    <fields>
        <fullName>Data_Source__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Data Source</label>
        <referenceTo>DataSource__c</referenceTo>
        <relationshipLabel>SubGroups</relationshipLabel>
        <relationshipName>SubGroups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SubGroup</label>
    <nameField>
        <label>SubGroup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SubGroups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/ReviewTeamModelData.cls
public  class ReviewTeamModelData {

	public static Review_Team__c abarelixOncologyDevelopmentSmpReviewTeam {
		get {
			return ReviewTeamModel.ReviewTeamNameMap.get('Epogen - Dialysis - GRAAS - GRAAS');
		}
	}

	public static Review_Team__c aranespCkdNotDialysisDevelopmentIrdReviewTeam {
		get {
			return ReviewTeamModel.ReviewTeamNameMap.get('Aranesp - CKD Not Dialysis - Development - Global Dev - LACAN');
		}
	}
	
	public static Review_Team__c aranespCkdNotDialysisOperationCommericalQualityReviewTeam {
		get {
			return ReviewTeamModel.ReviewTeamNameMap.get('Aranesp - CKD Not Dialysis - Operations - Ops - Comm Quality');
		}
	}
	 
	
    public static void createData() {
    
        integer dataCount = [select count() from Review_Team__c];
        if ( dataCount <> 0) {
        	return;
        }
        
        List<Review_Team__c> ReviewTeamList = new List<Review_Team__c>();
        
        
        	DataSource__c developmentDataSource = DataSourceModelData.Development;
        	System.assertNotEquals(null, developmentDataSource);
        	
        	ProductIndication__c abarelixOncologyProdInd = ProductIndicationModelData.abarelixOncologyProdInd; 
        	System.assertNotEquals(null, abarelixOncologyProdInd);

			//abarelixOncologyDevelopmentSmpReviewTeam
            ReviewTeamList.add( new Review_Team__c(Name='RT0', Data_Source__c=developmentDataSource.Id, 
            	subGroup__c=SubGroupModelData.DevelopmentSmpSubGroup.Id,
            	Product_Indication__c=ProductIndicationModelData.abarelixOncologyProdInd.Id));    
        
        	//aranespCkdNotDialysisDevelopmentIrdReviewTeam
            ReviewTeamList.add( new Review_Team__c(Name='RT1', Data_Source__c=developmentDataSource.Id, 
            	subGroup__c=SubGroupModelData.DevelopmentIrdSubGroup.Id,
            	Product_Indication__c=ProductIndicationModel.ProductIndicationNameMap.get('Aranesp - CKD Not Dialysis').Id));         
            	
            ReviewTeamList.add( new Review_Team__c(Name='RT2', Data_Source__c= DataSourceModel.DataSourceMapByName.get('Development').Id, 
            	subGroup__c=SubGroupModel.SubGroupNameMap.get('Global Dev - LACAN').Id, 
            	Product_Indication__c=ProductIndicationModel.ProductIndicationNameMap.get('Aranesp - CKD Not Dialysis').Id));
            ReviewTeamList.add( new Review_Team__c(Name='RT3', Data_Source__c= DataSourceModel.DataSourceMapByName.get('Development').Id, 
            	subGroup__c=SubGroupModel.SubGroupNameMap.get('Global Dev - US').Id, 
            	Product_Indication__c=ProductIndicationModel.ProductIndicationNameMap.get('Aranesp - CKD Not Dialysis').Id));       
            	  
            ReviewTeamList.add( new Review_Team__c(Name='RT4', Data_Source__c= DataSourceModel.DataSourceMapByName.get('Operations').Id, 
            	subGroup__c=SubGroupModel.SubGroupNameMap.get('Ops - Comm Quality').Id, 
            	Product_Indication__c=ProductIndicationModel.ProductIndicationNameMap.get('Aranesp - CKD Not Dialysis').Id));         
            ReviewTeamList.add( new Review_Team__c(Name='RT5', Data_Source__c= DataSourceModel.DataSourceMapByName.get('Operations').Id, 
            	subGroup__c=SubGroupModel.SubGroupNameMap.get('Ops - DP&DD').Id, 
            	Product_Indication__c=ProductIndicationModel.ProductIndicationNameMap.get('Aranesp - CKD Not Dialysis').Id));         
            ReviewTeamList.add( new Review_Team__c(Name='RT6', Data_Source__c= DataSourceModel.DataSourceMapByName.get('Operations').Id, 
            	subGroup__c=SubGroupModel.SubGroupNameMap.get('Ops - Mfg Sciences & Tech').Id, 
            	Product_Indication__c=ProductIndicationModel.ProductIndicationNameMap.get('Aranesp - CKD Not Dialysis').Id));         
            ReviewTeamList.add( new Review_Team__c(Name='RT7', Data_Source__c= DataSourceModel.DataSourceMapByName.get('Operations').Id, 
            	subGroup__c=SubGroupModel.SubGroupNameMap.get('Ops - Other').Id, 
            	Product_Indication__c=ProductIndicationModel.ProductIndicationNameMap.get('Aranesp - Dialysis').Id));         
            ReviewTeamList.add( new Review_Team__c(Name='RT8', Data_Source__c= DataSourceModel.DataSourceMapByName.get('Operations').Id, 
            	subGroup__c=SubGroupModel.SubGroupNameMap.get('Ops - Quality Admin').Id, 
            	Product_Indication__c=ProductIndicationModel.ProductIndicationNameMap.get('Aranesp - Dialysis').Id));         
            	
            	
            ReviewTeamList.add( new Review_Team__c(Name='RT9', Data_Source__c= DataSourceModel.DataSourceMapByName.get('Research').Id, 
				subGroup__c=SubGroupModel.SubGroupNameMap.get('Research - CBSS').Id, 
				Product_Indication__c=ProductIndicationModel.ProductIndicationNameMap.get('Aranesp - Dialysis').Id));         
			ReviewTeamList.add( new Review_Team__c(Name='RT11', Data_Source__c= DataSourceModel.DataSourceMapByName.get('Research').Id, 
				subGroup__c=SubGroupModel.SubGroupNameMap.get('Research - Early Dev').Id, 
				Product_Indication__c=ProductIndicationModel.ProductIndicationNameMap.get('Aranesp - Dialysis').Id));         
			ReviewTeamList.add( new Review_Team__c(Name='RT10', Data_Source__c= DataSourceModel.DataSourceMapByName.get('Research').Id, 
				subGroup__c=SubGroupModel.SubGroupNameMap.get('Research - Genome Analysis').Id, 
				Product_Indication__c=ProductIndicationModel.ProductIndicationNameMap.get('Aranesp - Dialysis').Id));         
			ReviewTeamList.add( new Review_Team__c(Name='RT12', Data_Source__c= DataSourceModel.DataSourceMapByName.get('Research').Id, 
				subGroup__c=SubGroupModel.SubGroupNameMap.get('Research - Hem & Onc').Id, 
				Product_Indication__c=ProductIndicationModel.ProductIndicationNameMap.get('Aranesp - Dialysis').Id));         
			ReviewTeamList.add( new Review_Team__c(Name='RT13', Data_Source__c= DataSourceModel.DataSourceMapByName.get('Research').Id, 
				subGroup__c=SubGroupModel.SubGroupNameMap.get('Research - Inflammation').Id, 
				Product_Indication__c=ProductIndicationModel.ProductIndicationNameMap.get('Aranesp - Dialysis').Id));         
			ReviewTeamList.add( new Review_Team__c(Name='RT14', Data_Source__c= DataSourceModel.DataSourceMapByName.get('Research').Id, 
				subGroup__c=SubGroupModel.SubGroupNameMap.get('Research - Met. Disorders').Id, 
				Product_Indication__c=ProductIndicationModel.ProductIndicationNameMap.get('Epogen - Dialysis').Id));         
			ReviewTeamList.add( new Review_Team__c(Name='RT15', Data_Source__c= DataSourceModel.DataSourceMapByName.get('Research').Id, 
				subGroup__c=SubGroupModel.SubGroupNameMap.get('Research - Neuroscience').Id, 
				Product_Indication__c=ProductIndicationModel.ProductIndicationNameMap.get('Epogen - Dialysis').Id));         
			ReviewTeamList.add( new Review_Team__c(Name='RT16', Data_Source__c= DataSourceModel.DataSourceMapByName.get('Research').Id, 
				subGroup__c=SubGroupModel.SubGroupNameMap.get('Research - Other').Id, 
				Product_Indication__c=ProductIndicationModel.ProductIndicationNameMap.get('Epogen - Dialysis').Id));         
			ReviewTeamList.add( new Review_Team__c(Name='RT17', Data_Source__c= DataSourceModel.DataSourceMapByName.get('Research').Id, 
				subGroup__c=SubGroupModel.SubGroupNameMap.get('Research - P&PD').Id, 
				Product_Indication__c=ProductIndicationModel.ProductIndicationNameMap.get('Epogen - Dialysis').Id));         
			ReviewTeamList.add( new Review_Team__c(Name='RT19', Data_Source__c= DataSourceModel.DataSourceMapByName.get('Research').Id, 
				subGroup__c=SubGroupModel.SubGroupNameMap.get('Research - Pharmaceutics').Id, 
				Product_Indication__c=ProductIndicationModel.ProductIndicationNameMap.get('Epogen - Dialysis').Id));         
			ReviewTeamList.add( new Review_Team__c(Name='RT18', Data_Source__c= DataSourceModel.DataSourceMapByName.get('Research').Id, 
				subGroup__c=SubGroupModel.SubGroupNameMap.get('Research - PKDM').Id, 
				Product_Indication__c=ProductIndicationModel.ProductIndicationNameMap.get('Epogen - Dialysis').Id));         
			ReviewTeamList.add( new Review_Team__c(Name='RT20', Data_Source__c= DataSourceModel.DataSourceMapByName.get('Research').Id, 
				subGroup__c=SubGroupModel.SubGroupNameMap.get('Research - SMP&PD').Id, 
				Product_Indication__c=ProductIndicationModel.ProductIndicationNameMap.get('Epogen - Dialysis').Id));
			ReviewTeamList.add( new Review_Team__c(Name='RT21', Data_Source__c= DataSourceModel.DataSourceMapByName.get('Research').Id, 
				subGroup__c=SubGroupModel.SubGroupNameMap.get('Research - Therapeutic Discovery').Id, 
				Product_Indication__c=ProductIndicationModel.ProductIndicationNameMap.get('Epogen - Dialysis').Id));
			ReviewTeamList.add( new Review_Team__c(Name='RT22', Data_Source__c= DataSourceModel.DataSourceMapByName.get('Research').Id, 
				subGroup__c=SubGroupModel.SubGroupNameMap.get('Research - Therapeutic Innovation').Id, 
				Product_Indication__c=ProductIndicationModel.ProductIndicationNameMap.get('Epogen - Dialysis').Id));         
            
            
            ReviewTeamList.add( new Review_Team__c(Name='RT23', Data_Source__c= DataSourceModel.DataSourceMapByName.get('GRAAS').Id, 
				subGroup__c=SubGroupModel.SubGroupNameMap.get('GRAAS').Id, 
				Product_Indication__c=ProductIndicationModel.ProductIndicationNameMap.get('Epogen - Dialysis').Id));         
                    
         insert ReviewTeamList;
                
     }
    
}