force-app/main/default/staticresources/python/Disappear/src/objects/Deadline__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Meeting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Meeting</label>
        <referenceTo>Meeting__c</referenceTo>
        <relationshipLabel>Deadlines</relationshipLabel>
        <relationshipName>Deadlines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deadline</label>
    <nameField>
        <displayFormat>DL-{000000}</displayFormat>
        <label>Deadline Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deadlines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Meeting__c.object
<CustomObject>
    <description>Used for the Meeting target and to maintain Meeting related Data</description>
    <label>Meeting</label>
    <nameField>
        <displayFormat>MTG-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/DeadlineModel.cls
public class DeadlineModel {
    
    private static List<Deadline__c> dDeadlineList = null;
    public static List<Deadline__c> DeadlineList{
        get{
            if(dDeadlineList == null){
              dDeadlineList = getAllDeadlineList();
            }               
        return dDeadlineList;
        }
    }  
    
   private static Map<String, Deadline__c> dDeadlineNameMap = null;
   public static Map<String, Deadline__c> DeadlineNameMap{
     get {
       if (dDeadlineNameMap == null){
         dDeadlineNameMap = getDeadlineMapByName();
       }
       return dDeadlineNameMap;
     }
   }
   
   public static Map<String, Deadline__c> getDeadlineMapByName() {
    Map<String, Deadline__c> result = new Map<String, Deadline__c>();
    for(Deadline__c dDeadline : DeadlineList){
      result.put(dDeadline.Name, dDeadline );
    }

    return result;
  }
      
    public static List<Deadline__c> getAllDeadlineList(){
        List<Deadline__c> result = [
          select id, Name, Date__c, Meeting__c
          From Deadline__c
          order by Name  
           ];
        return result;
    } 
}