force-app/main/default/staticresources/python/Disappear/src/objects/Deadline__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DeadLine_Type__c</fullName>
        <description>Different type of deadLine</description>
        <label>DeadLine Type</label>
        <picklist>
            <picklistValues>
                <fullName>2nd yr fellow Abst. Deadline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Abstract Notifications Mailed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Abstract Withdrawal Date</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Abstracts Available On-Line</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Abstracts and Programs Mailed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advance Registration Deadline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Call For Abstracts Available</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporate Symposia Deadline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electronic Abstract Deadline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final Program Available</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final Registration Deadline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Housing Deadline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Late Breaker Submission Opens</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paper Abstract Deadline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Abstract Deadline Online Close</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Abstract Deadline Notification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Abstract Deadline Late Breaker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Preliminary Program Available</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Meeting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Meeting</label>
        <referenceTo>Meeting__c</referenceTo>
        <relationshipLabel>Deadlines</relationshipLabel>
        <relationshipName>Deadlines</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Deadline</label>
    <nameField>
        <displayFormat>DL-{000000}</displayFormat>
        <label>Deadline Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deadlines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Meeting__c.object
<CustomObject>
    <description>Used for the Meeting target and to maintain Meeting related Data</description>
    <label>Meeting</label>
    <nameField>
        <displayFormat>MTG-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/DeadlineModelData.cls
public  class DeadlineModelData {

  /*@IsTest
    public static void UnitTest() {
        MeetingModelData.createData();
        DeadlineModelData.createData();
    }*/

    public static void createData() {
    
		integer dataCount = [select count() from Deadline__c];
		if ( dataCount <> 0) return;
		
		List<Deadline__c> DeadlineList = new List<Deadline__c>();
		 
		DeadlineList.add( new Deadline__c(DeadLine_Type__c='2nd yr fellow Abst. Deadline',Date__c=null, Meeting__c=MeetingModel.MeetingNameMap.get('Annual Viral Hepatitis Congress').Id));
		DeadlineList.add( new Deadline__c(DeadLine_Type__c='Abstract Notifications Mailed',Date__c=null, Meeting__c=MeetingModel.MeetingNameMap.get('World Conference on Lung Cancer').Id));
		DeadlineList.add( new Deadline__c(DeadLine_Type__c='Abstract Withdrawal Date',Date__c=null, Meeting__c=MeetingModel.MeetingNameMap.get('HIV Drug Therapy in the Americas').Id));
		DeadlineList.add( new Deadline__c(DeadLine_Type__c='Abstracts Available On-Line',Date__c=null, Meeting__c=MeetingModel.MeetingNameMap.get('Annual World PGx Summit').Id));
		DeadlineList.add( new Deadline__c(DeadLine_Type__c='Abstracts and Programs Mailed',Date__c=null, Meeting__c=MeetingModel.MeetingNameMap.get('Annual Leipzig Interventional Course').Id));
		DeadlineList.add( new Deadline__c(DeadLine_Type__c='Advance Registration Deadline',Date__c=null, Meeting__c=MeetingModel.MeetingNameMap.get('Annual Human Amyloid Imaging').Id));
		DeadlineList.add( new Deadline__c(DeadLine_Type__c='Call For Abstracts Available',Date__c=null, Meeting__c=MeetingModel.MeetingNameMap.get('Annual CNS Summit').Id));
		DeadlineList.add( new Deadline__c(DeadLine_Type__c='Corporate Symposia Deadline',Date__c=null, Meeting__c=MeetingModel.MeetingNameMap.get('Annual Meeting of the Retina Society').Id));
		DeadlineList.add( new Deadline__c(DeadLine_Type__c='Electronic Abstract Deadline',Date__c=null, Meeting__c=MeetingModel.MeetingNameMap.get('Biennial International Surgical Week').Id));
		DeadlineList.add( new Deadline__c(DeadLine_Type__c='Final Program Available',Date__c=null, Meeting__c=MeetingModel.MeetingNameMap.get('Annual Meeting of the Macula Society').Id));
		DeadlineList.add( new Deadline__c(DeadLine_Type__c='Final Registration Deadline',Date__c=null, Meeting__c=MeetingModel.MeetingNameMap.get('Annual EuroPCR').Id));
		DeadlineList.add( new Deadline__c(DeadLine_Type__c='Housing Deadline',Date__c=null, Meeting__c=MeetingModel.MeetingNameMap.get('Annual EuroHeartCare').Id));
		DeadlineList.add( new Deadline__c(DeadLine_Type__c='Late Breaker Submission Opens',Date__c=null, Meeting__c=MeetingModel.MeetingNameMap.get('Annual Endovascular Summit').Id));
		DeadlineList.add( new Deadline__c(DeadLine_Type__c='Other',Date__c=null, Meeting__c=MeetingModel.MeetingNameMap.get('Annual SECO International').Id));
		DeadlineList.add( new Deadline__c(DeadLine_Type__c='Paper Abstract Deadline',Date__c=null, Meeting__c=MeetingModel.MeetingNameMap.get('Biennial World Glaucoma Congress').Id));
		DeadlineList.add( new Deadline__c(DeadLine_Type__c='Abstract Deadline Online Close',Date__c=null, Meeting__c=MeetingModel.MeetingNameMap.get('Annual Fall Managed Care Forum').Id));
		DeadlineList.add( new Deadline__c(DeadLine_Type__c='Abstract Deadline Notification',Date__c=null, Meeting__c=MeetingModel.MeetingNameMap.get('Annual European Colorectal Congress').Id));
		DeadlineList.add( new Deadline__c(DeadLine_Type__c='Abstract Deadline Late Breaker',Date__c=null, Meeting__c=MeetingModel.MeetingNameMap.get('Annual European Colorectal Congress').Id));
		DeadlineList.add( new Deadline__c(DeadLine_Type__c='Preliminary Program Available',Date__c=null, Meeting__c=MeetingModel.MeetingNameMap.get('World Parkinson Congress').Id));
		           
		insert DeadlineList;
                
     }
    
}