force-app/main/default/staticresources/python/Disappear/src/objects/Department__c.object
<CustomObject>
    <fields>
        <fullName>isLogicallyDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Expired</label>
        <type>Checkbox</type>
    </fields>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/FPR_Cycle__c.object
<CustomObject>
    <description>record name will be PubId-{0000000}-FPRCycle-{00}</description>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>FPR Cycles</relationshipLabel>
        <relationshipName>FPR_Cycles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>FPR Cycle</label>
    <nameField>
        <label>FPR_Cycle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FPR Cycles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <fields>
        <fullName>Department__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Department</label>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsSelected__c</fullName>
        <defaultValue>false</defaultValue>
        <description>for UI operation - please do not store or migrate data into this field</description>
        <label>IsSelected</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PubStatus__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Current status of this publication</description>
        <label>PubStatus</label>
        <referenceTo>PubStatus__c</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <recordTypes>
        <fullName>Submit</fullName>
        <active>true</active>
        <label>Submit</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PubME__c.object
<CustomObject>
    <description>Record all Manuscript Equivalent points award to authors and others for their work on a publication</description>
    <fields>
        <fullName>AppearRole__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The Role that the Pub Team member played in the preparation of this Publication

Will be used to look up Awarded ME in PubTypeME</description>
        <inlineHelpText>APPEAR Roles include: Writing Coordinator, Writer, Editorial Support, GPPL, and Pub Specialist.</inlineHelpText>
        <label>Appear Role</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Appear_Role__c.isWritingRole__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Appear_Role__c</referenceTo>
        <relationshipLabel>Publication MEs</relationshipLabel>
        <relationshipName>Publication_MEs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Department</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Department__c.isLogicallyDeleted__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <infoMessage>Please do not select [EXPIRED] Department values</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>Publication MEs</relationshipLabel>
        <relationshipName>Publication_MEs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Emp_Type__c</fullName>
        <description>This field indicates whether the Writing Role Member is Amgen Full Time Employee or Outsourced</description>
        <label>Emp. Type</label>
        <picklist>
            <picklistValues>
                <fullName>Contingent Worker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ext Bus Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Intern</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Temporary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vendor</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FPR_Cycle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FPR Cycle</label>
        <referenceTo>FPR_Cycle__c</referenceTo>
        <relationshipLabel>Publication MEs</relationshipLabel>
        <relationshipName>Publication_MEs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OverrideME__c</fullName>
        <description>Available for Business Admin to override the calculated ME</description>
        <label>Override ME</label>
        <precision>6</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PubStatus__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication Status</label>
        <referenceTo>PubStatus__c</referenceTo>
        <relationshipLabel>Publication MEs</relationshipLabel>
        <relationshipName>Publication_MEs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Publication MEs</relationshipLabel>
        <relationshipName>Publication_MEs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WritingRoleMember__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Writing Role Member</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Publication MEs</relationshipLabel>
        <relationshipName>Publication_MEs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>isSelected__c</fullName>
        <defaultValue>false</defaultValue>
        <description>UI Operation Only - Do not store or migrate data into this Field</description>
        <label>isSelected</label>
        <type>Checkbox</type>
    </fields>
    <label>Publication ME</label>
    <nameField>
        <displayFormat>PME-{000000000}</displayFormat>
        <label>Publication ME Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication MEs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PubStatus__c.object
<CustomObject>
    <description>List of Status for a Publication - Target Date / Revised Date / Actual Date
Will be used for planning</description>
    <fields>
        <fullName>ActualDate__c</fullName>
        <label>Actual Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>FPR_Cycle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FPR Cycle</label>
        <referenceTo>FPR_Cycle__c</referenceTo>
        <relationshipName>Pub_Statuses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsLogicallyDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to logically delete the record.

Release 1.1 Renamed isLogicallyDeleted to Expired</description>
        <label>Expired</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Publication_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication_id</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipName>PubStatus</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Status</label>
        <referenceTo>Status__c</referenceTo>
        <relationshipName>PubStatuses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publication Status</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>PubStatus Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Status__c.object
<CustomObject>
    <label>Status</label>
    <nameField>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/SubmissionCycle__c.object
<CustomObject>
    <description>record name will be PubId-{0000000}-SubCycle-{00}</description>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Submission Cycles</relationshipLabel>
        <relationshipName>Submission_Cycles</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Submission Cycle</label>
    <nameField>
        <label>Submission Cycle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submission Cycles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/PubMeModelTest.cls
@IsTest
public class PubMeModelTest {

    @IsTest
    public static void UnitTest() {
        //create a Publication
        AppearPubModel activePub = createData();
        
        
        System.test.startTest();
        //add Product Indication
        
        List<String> ProdIndList = new List<String>();
        ProdIndList.add(ProductIndicationModel.ProductIndicationNameMap.get('AMG 108 - Not Applicable').id);
        
        activePub.PubProdIndication.SelectedProductIndications = ProdIndList;
        activePub.PubProdIndication.savePubProdInd();
        //system should copy the Product Indication team over to publication 
    
        PubME__c pubME = activePub.pubMe.NewPubWritingRoleMembers;
        pubMe.WritingRoleMember__c = AppearContactModel.SimilarContacts('Maxwell, Michelle', 10)[0].id;
        pubMe.AppearRole__c = AppearRoleModel.AppearRoleMapByName.get('Writing Coordinator').id;
        pubMe.Emp_Type__c = AppearContactModel.findContactEmployeeType(AppearContactModel.SimilarContacts('Maxwell, Michelle', 10)[0].id);
        activePub.pubMe.saveNewWritingRoleMember();
        
        List<PubME__c> pubMeList = activePub.PubMe.PubMeList;
        System.assertEquals(1, pubMeList.size());
                
        activePub.pubMe.calculateActualMeGUI();
        
        pubMeList[0].isSelected__c = true;
        activePub.pubMe.deleteSelected();
        
        pubMeList = activePub.PubMe.PubMeList;
        System.assertEquals(0, pubMeList.size());
        
        PubME__c pubME2 = activePub.pubMe.NewPubWritingRoleMembers;
        pubME2.WritingRoleMember__c = AppearContactModel.SimilarContacts('mike@amgen', 10)[0].id;
        pubME2.AppearRole__c = AppearRoleModel.AppearRoleMapByName.get('Writer').id;
        pubME2.Emp_Type__c = AppearContactModel.findContactEmployeeType(AppearContactModel.SimilarContacts('mike@amgen', 10)[0].id);
        pubME2.id = null;
        activePub.pubMe.saveNewWritingRoleMember();
    
        pubMeList = activePub.PubMe.PubMeList;
        System.assertEquals(1, pubMeList.size());
        
        pubMeList[0].OverrideME__c = 1.0;
        pubMeList[0].FPR_Cycle__c = activePub.FprCycle.getFprCycleByNum(1).id;
        activePub.pubMe.save();
        
        pubMeList = activePub.PubMe.PubMeList;
        System.assertEquals(1, pubMeList.size());
        
        List<Department__c> departments = DepartmentModel.getCompleteDepartmentList();
        System.assertEquals(14, departments.size());
        
        for(Department__c tmpDept : departments){
            if(tmpDept !=null && tmpDept.Name == 'Abgenix [Expired]' && tmpDept.isLogicallyDeleted__c) {
                pubMeList[0].Department__c = tmpDept.Id;
                break;
            }   
        }
        activePub.pubMe.save();
        
        activePub.pubMe.copyMEforResent(1,2);
        SubmissionCycle__c nextSubmissionCycle = activePub.submissionCycle.getSubmissionCycleByNum(2);
        FPR_Cycle__c nextFprCycle = activePub.FprCycle.getFprCycleByNum(2);
        activePub.pubMe.copyMEforNewSubmissionCycle(nextSubmissionCycle,nextFprCycle);
        
        ////////////////Start:Changes Made By Sudha //////////////
        PubMeModel objPubMeModel = new PubMeModel();
        String strObj =objPubMeModel.RecalculateHelpText;
        Boolean objBLN = objPubMeModel.ShowOverrideColumn;
        objBLN = objPubMeModel.debugFlag;
        objBLN = objPubMeModel.ShowGUIvsDB;
        
        PubStatusModel pubstats = activePub.PubStatus;
        PubStatus__c newSCPubStatus;
        System.debug('Madhurima Hello 1');
        for (PubStatus__c st: pubstats.PubStatusList){
            if (st.Status__c == StatusModel.SubmittedCompleted.Id ){
                st.ActualDate__c = Date.today();
                break;
            }
        }
        pubstats.save();
        pubstats.clearCache();
        
        for (PubStatus__c st: pubstats.PubStatusList){
            if (st.Status__c == StatusModel.SubmittedCompleted.Id && st.ActualDate__c <> null){
                newSCPubStatus = st;
                break;
            }
        }
        
        try{
            objPubMeModel.AwardMeForSubmittedCompleted(activePub, newSCPubStatus);
        }catch(exception ex){
        }
        try{
            objPubMeModel.AwardMeForMaterialChangeCongressJournal(activePub);
        }catch(exception ex){
        }
        try{
            objPubMeModel.recalculateAndPersist();
        }catch(exception ex){
        }       
        //objPubMeModel.AwardMeForSubmittedCompleted(activePub, );
        
        try{
            objPubMeModel.findPubStatusId(pubME);
        }catch(exception ex){
        }
         
        /*Madhurima Added Code*/
        
       
        /////////////////END-of Changes Made By Sudha---///////////////////////////////
        System.test.stopTest();
    
        //Submit the publication    
        //System should copy all Publication Team members with writing roles to the PubME models
        
        //check Submission Cycle
        //check FPR cycle
        //check team member
        //check Department
        //check organization
        //check scope of work
        //check Calculated ME
        
        //Change Scope of Work
        //Check Calculated ME
        
        //Check total Calculated ME
        
        //Add Manual Changes for Actual ME
        
        //check Actual ME
        //check reason for changes
        
        //check total ME included Actual
        
        //perist and check again......
    }
    
    @IsTest
    public static void UnitTest1() {
        AppearPubModel activePub = createData();
        System.Test.startTest();
        activePub.pubMe.copyMEforResent(1,2);
        List<PubME__c> pubMeList = activePub.PubMe.PubMeList;
        
        SubmissionCycle__c nextSubmissionCycle = activePub.submissionCycle.getSubmissionCycleByNum(2);
        FPR_Cycle__c nextFprCycle = activePub.FprCycle.getFprCycleByNum(2);
        activePub.pubMe.copyMEforNewSubmissionCycle(nextSubmissionCycle,nextFprCycle);
        PubMeModel objPubMeModel = new PubMeModel();
        String strObj =objPubMeModel.RecalculateHelpText;
        Boolean objBLN = objPubMeModel.ShowOverrideColumn;
        objBLN = objPubMeModel.debugFlag;
        objBLN = objPubMeModel.ShowGUIvsDB;
        Publication__c pub = UnitTestData.newPublication('PubReviewTeamModelTest');
        
        PubStatus__c ps1 = new PubStatus__c();    
        
        ps1.Publication_id__c = pub.Id;
        ps1.Status__c = StatusModel.DepartmentStatusList[0].id;
        
        
        
        insert ps1;
        /**/
        
        try{
            objPubMeModel.AwardMeForSubmittedCompleted(activePub, ps1);
        }catch(exception ex){
        }        
        
        activePub.pubMe.copyMEforNewSubmissionCycle(nextSubmissionCycle,nextFprCycle, ps1.Id);
        activePub.pubMe.copyMEforMaterialChange(1,1,ps1.Id);
        objPubMeModel.getPubMeSubmitCycles(pub.Id, nextSubmissionCycle.Id);
        activePub.pubMe.copyMEforNonMaterialChange(ps1.id); 
        objPubMeModel.CurrentFprCycle = null;
        objPubMeModel.saveNewWritingRoleMember();
        //Appear Enhancement R2
        
        PubME__c pubME = activePub.pubMe.NewPubWritingRoleMembers;
        pubMe.WritingRoleMember__c = AppearContactModel.SimilarContacts('Maxwell, Michelle', 10)[0].id;
        pubMe.AppearRole__c = AppearRoleModel.AppearRoleMapByName.get('Writing Coordinator').id;
        pubMe.Emp_Type__c = AppearContactModel.findContactEmployeeType(AppearContactModel.SimilarContacts('Maxwell, Michelle', 10)[0].id);
        activePub.pubMe.saveNewWritingRoleMember();
        List<PubME__c> pubMeList1 = activePub.PubMe.PubMeList;
        system.debug('*****'+pubMeList);
        //system.debug('****'+pubMeList[0].Publication__r.Id);Writer
        system.debug('*******'+ps1.id);
        
        PubMeModelNoSharing.copyMEforNonMaterialChange(pubMeList1,pub.Id,ps1.id);
        //List<PubMe__c> PubMeList, id PubId, SubmissionCycle__c fromSubmissionCycle, FPR_Cycle__c fromFprCycle,
        //SubmissionCycle__c toSubCycle, FPR_Cycle__c toFprCycle, Id PubStatusId
        SubmissionCycle__c subcycle= [Select id from SubmissionCycle__c where Publication__c =: pub.Id];
        PubMeModelNoSharing.copyME(pubMeList1,pub.Id,subcycle,nextFprCycle,nextSubmissionCycle,nextFprCycle,ps1.id);
        
        
        
        PubME__c pubMENew = activePub.pubMe.NewPubWritingRoleMembers;
        pubMENew.WritingRoleMember__c = AppearContactModel.SimilarContacts('Maxwell, Michelle', 10)[0].id;
        pubMENew.AppearRole__c = AppearRoleModel.AppearRoleMapByName.get('Writer').id;
        pubMENew.Emp_Type__c = AppearContactModel.findContactEmployeeType(AppearContactModel.SimilarContacts('Maxwell, Michelle', 10)[0].id);
        pubMENew.id = null;
        activePub.pubMe.saveNewWritingRoleMember();
        List<PubME__c> pubMeList2 = activePub.PubMe.PubMeList;
        PubMeModelNoSharing.copyMEforNonMaterialChange(pubMeList2,pub.Id,ps1.id);
        
        // Appear Enhancement Release 2
        strObj =objPubMeModel.AssignedTo;
        List<SelectOption> LSToPTION = objPubMeModel.getassignToOpt();
        
        
        objPubMeModel.CurrentSubmissionCycle = null;
        pubMeList = objPubMeModel.PubMeList;
        
        
        //objPubMeModel.objPubMeModel();
        objPubMeModel.clearPubMeList();
        objPubMeModel.cancel();
        System.Test.stopTest();
    }
   
    public static AppearPubModel createData(){
        
        TherapeuticAreaModelData.createData();
        AmgenProductModelData.createData();
        IndicationModelData.createData();
        ProductIndicationModelData.createData();
        ProdIndiObjectiveModelData.createData();
        MEScopeOfWorkModelData.createData();
        AppearRoleModelData.createData();
        
        OrganizationModelData.createData();
        DepartmentModelData.createData();
        AccountModelData.createData();
        AppearContactModelData.createData();
        StatusModelData.createData();
        
        
        Publication__c pub = UnitTestData.PublicationNew('PubMEUnitTest');
        
        AppearPubModel activePub = new AppearPubModel(pub.id);
        
        return activePub;
    }
    
    

}