force-app/main/default/staticresources/python/Disappear/src/objects/Department__c.object
<CustomObject>
    <fields>
        <fullName>Acronym__c</fullName>
        <label>Acronym</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrganizationId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization</label>
        <referenceTo>Organization__c</referenceTo>
        <relationshipLabel>Departments</relationshipLabel>
        <relationshipName>Departments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SiebelRowId__c</fullName>
        <label>SiebelRowId</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SponsorDept__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sponsor Dept</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Amgen Internal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vendor</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>isLogicallyDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Expired</label>
        <type>Checkbox</type>
    </fields>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/DepartmentModelData.cls
public  class DepartmentModelData {

	public static Department__c GlobalHealthEconomicDept {
		get {
			return DepartmentModel.DepartmentNameMap.get('Global Health Economics (GHE)');
		}
	}

	public static Department__c GlobalMedicalWritingDept {
		get {
			return DepartmentModel.DepartmentNameMap.get('Medical Writing');
		}
	}
	
	public static Department__c MedicalCommunicationsDept {
		get {
			return DepartmentModel.DepartmentNameMap.get('Global Value, Access, and Policy');
		}
	}


    public static void createData() {
    
        integer dataCount = [select count() from Department__c];
        if ( dataCount <> 0) return;
        
        List<Department__c> DepartmentList = new List<Department__c>();
        
        DepartmentList.add( new Department__c(name= 'Center for Observational Research (CfOR)', OrganizationId__c= OrganizationModel.OrganizationNameMap.get('Amgen').Id, 
            		SiebelRowId__c=null,Acronym__c=null, Type__c=null, URL__c=null, SponsorDept__c=true));
		DepartmentList.add( new Department__c(name= 'Clinical Development', OrganizationId__c= OrganizationModel.OrganizationNameMap.get('Amgen').Id, 
		            SiebelRowId__c=null,Acronym__c=null, Type__c=null, URL__c=null, SponsorDept__c=true));
		DepartmentList.add( new Department__c(name= 'Discovery Research', OrganizationId__c= OrganizationModel.OrganizationNameMap.get('Amgen').Id, 
		            SiebelRowId__c=null,Acronym__c=null, Type__c=null, URL__c=null, SponsorDept__c=true));
		DepartmentList.add( new Department__c(name= 'Global Government Affairs', OrganizationId__c= OrganizationModel.OrganizationNameMap.get('Amgen').Id, 
		            SiebelRowId__c=null,Acronym__c=null, Type__c=null, URL__c=null, SponsorDept__c=true));
		DepartmentList.add( new Department__c(name= 'Global Health Economics (GHE)', OrganizationId__c= OrganizationModel.OrganizationNameMap.get('Amgen').Id, 
		            SiebelRowId__c=null,Acronym__c=null, Type__c=null, URL__c=null, SponsorDept__c=true));
		DepartmentList.add( new Department__c(name= 'Global Regulatory Affairs', OrganizationId__c= OrganizationModel.OrganizationNameMap.get('Amgen').Id, 
		            SiebelRowId__c=null,Acronym__c=null, Type__c=null, URL__c=null, SponsorDept__c=true));
		DepartmentList.add( new Department__c(name= 'Global Safety', OrganizationId__c= OrganizationModel.OrganizationNameMap.get('Amgen').Id, 
		            SiebelRowId__c=null,Acronym__c=null, Type__c=null, URL__c=null, SponsorDept__c=true));
		DepartmentList.add( new Department__c(name= 'Global Scientific Affairs', OrganizationId__c= OrganizationModel.OrganizationNameMap.get('Amgen').Id, 
		            SiebelRowId__c=null,Acronym__c=null, Type__c=null, URL__c=null, SponsorDept__c=true));
		DepartmentList.add( new Department__c(name= 'Global Value, Access, and Policy', OrganizationId__c= OrganizationModel.OrganizationNameMap.get('Amgen').Id, 
		            SiebelRowId__c=null,Acronym__c=null, Type__c=null, URL__c=null, SponsorDept__c=true));
		DepartmentList.add( new Department__c(name= 'Manufacturing', OrganizationId__c= OrganizationModel.OrganizationNameMap.get('Amgen').Id, 
		            SiebelRowId__c=null,Acronym__c=null, Type__c=null, URL__c=null, SponsorDept__c=true));
		DepartmentList.add( new Department__c(name= 'Medical Writing', OrganizationId__c= OrganizationModel.OrganizationNameMap.get('Amgen').Id, 
            		SiebelRowId__c=null,Acronym__c=null, Type__c=null, URL__c=null));     
		DepartmentList.add( new Department__c(name= 'Translational Sciences', OrganizationId__c= OrganizationModel.OrganizationNameMap.get('Amgen').Id, 
		            SiebelRowId__c=null,Acronym__c=null, Type__c=null, URL__c=null, SponsorDept__c=true));
        DepartmentList.add( new Department__c(name= 'Abgenix [Expired]', OrganizationId__c= OrganizationModel.OrganizationNameMap.get('Amgen').Id, 
		            SiebelRowId__c=null,Acronym__c=null, Type__c=null, URL__c=null, IsLogicallyDeleted__c=true)); 
        DepartmentList.add( new Department__c(name= 'Medical Research (Phase III-b, IV)', OrganizationId__c= OrganizationModel.OrganizationNameMap.get('Amgen').Id, 
		            SiebelRowId__c=null,Acronym__c=null, Type__c=null, URL__c=null, SponsorDept__c=true));
        insert DepartmentList;
                
     }
    
}