force-app/main/default/staticresources/python/Disappear/src/objects/Department__c.object
<CustomObject>
    <fields>
        <fullName>isLogicallyDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Expired</label>
        <type>Checkbox</type>
    </fields>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Organization__c.object
<CustomObject>
    <fields>
        <fullName>isLogicallyDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Expired</label>
        <type>Checkbox</type>
    </fields>
    <label>Organization</label>
    <nameField>
        <label>Organization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/pubAuthor__c.object
<CustomObject>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Publication Authors</relationshipLabel>
        <relationshipName>Publication_Authors</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>isLogicallyDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used for logical deletion or soft deletion of Pub Authors.</description>
        <label>isLogicallyDeleted</label>
        <type>Checkbox</type>
    </fields>
    <label>Publication Author</label>
    <nameField>
        <displayFormat>PA-{0000000}</displayFormat>
        <label>Publication Author Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <fields>
        <fullName>Project_Ids__c</fullName>
        <description>Used to collect all study Ids, concat in string in trigger</description>
        <label>Project Ids</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SponsorDept_Pick__c</fullName>
        <label>Sponsoring Amgen Department</label>
        <picklist>
            <picklistValues>
                <fullName>Center for Observational Research (CfOR)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clinical Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discovery Research</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global Government Affairs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global Health Economics (GHE)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global Medical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global Regulatory Affairs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global Safety</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global Scientific Affairs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global Value, Access, and Policy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufacturing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Translational Sciences</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SponsorOrg_Pick__c</fullName>
        <label>Sponsoring Organization</label>
        <picklist>
            <picklistValues>
                <fullName>Amgen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Astellas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AstraZeneca/MedImmune</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cytokinetics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daiichi-Sankyo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Genentech, Inc.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GlaxoSmithKline (GSK)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kirin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Novartis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pfizer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Servier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Takeda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UCB Pharma</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SponsoringDept__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Department from which publication data are generated.</inlineHelpText>
        <label>Sponsoring Amgen Department (Lookup)</label>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>Publication (SponsoringDept)</relationshipLabel>
        <relationshipName>Publication1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SponsoringOrg__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Company from which publication is generated.  (e.g. Amgen, Pfizer, etc.)</inlineHelpText>
        <label>Sponsoring Organization (Lookup)</label>
        <referenceTo>Organization__c</referenceTo>
        <relationshipLabel>Publication (SponsoringOrg)</relationshipLabel>
        <relationshipName>Publication2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <recordTypes>
        <fullName>Execute</fullName>
        <active>true</active>
        <label>Execute</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PubStudy__c.object
<CustomObject>
    <fields>
        <fullName>IsLogicallyDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Expired</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipName>PubStudies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Study__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Study</label>
        <referenceTo>Study__c</referenceTo>
        <relationshipName>PubStudies</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publication Study/Project</label>
    <nameField>
        <label>PubStudy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publication Studies/Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Study__c.object
<CustomObject>
    <fields>
        <fullName>IsLogicallyDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Expired</label>
        <type>Checkbox</type>
    </fields>
    <label>Study/Project</label>
    <nameField>
        <label>Study/Project #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Studies/Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/BatchUpdateUsBasedAuthor.cls
global class BatchUpdateUsBasedAuthor extends BatchBase 
	implements Database.Batchable<SObject>,Database.Stateful {
   	public String SOQL = 'select id, Project_Ids__c ,SponsoringDept__c,SponsorDept_Pick__c,SponsoringDept__r.Name,SponsoringOrg__c,SponsorOrg_Pick__c,SponsoringOrg__r.Name from Publication__c ';
   	

   	
	public BatchUpdateUsBasedAuthor() {
		super();
		
    	if ( Test.isRunningTest()){
    		SOQL = SOQL + ' limit 5';
    	} 
    	AddMessage(SOQL);
        system.debug(SOQL);
	}
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        batchableContext = BC;
        batchName = 'BatchContactUpdateCountry';
        System.Debug(SOQL);
        return Database.getQueryLocator(SOQL);
    }

    global void execute(Database.BatchableContext BC, List<Publication__c> pubs){
    	
    	Set<Id> pubIdSet = new Set<Id>();
    	List<Publication__c> Publications = new List<Publication__c>();
    	for(Publication__c pub : pubs) {
    		pubIdSet.add(pub.id);
    		Publications.add(pub);
    	} 
    	
    	List<PubAuthor__c> pubAuthorList = [
    		select id, Publication__c
    		from PubAuthor__c
    		where publication__c in :pubIdSet
            AND isLogicallyDeleted__c = false //Appear Enhancement R3 : Soft Delete Author functionality
    	];
    	 
    	PubAuthorTriggerLogic.PubAuthorTriggerInsertOrDeleteLogic(pubAuthorList);
    	
    	List<PubStudy__c> PubStudies = [ select id, Name, Publication__c, Study__c, Study__r.Name,IsLogicallyDeleted__c,Study__r.RecordType.Name From PubStudy__c
            where Publication__c in :pubIdSet and isLogicallyDeleted__c = false  
        ];
        PubAuthorTriggerLogic.PubProjectStudyUpdate(PubStudies,publications);
    	
		AppLogModel.flushLogs();
    } 

    global void finish(Database.BatchableContext BC){
		SendBatchCompletionEmail();
	}
	
	//BatchUpdateUsBasedAuthor.runNow();
	public static void runNow(){
    	BatchUpdateUsBasedAuthor batch = new BatchUpdateUsBasedAuthor();
        Database.executeBatch(batch, 10);
	}

//////////////////////////////////////////  unit test /////////////////////////////////////
	@isTest
	private static void unitTest() {
		CreateData();
		
		BatchUpdateUsBasedAuthor.runNow();
	} 
	
	public static void CreateData() {

	}
}