force-app/main/default/staticresources/python/Disappear/src/objects/FPR_Cycle__c.object
<CustomObject>
    <description>record name will be PubId-{0000000}-FPRCycle-{00}</description>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>FPR Cycles</relationshipLabel>
        <relationshipName>FPR_Cycles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>FPR Cycle</label>
    <nameField>
        <label>FPR_Cycle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FPR Cycles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <fields>
        <fullName>PubStatus__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Current status of this publication</description>
        <label>PubStatus</label>
        <referenceTo>PubStatus__c</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <recordTypes>
        <fullName>Execute</fullName>
        <active>true</active>
        <label>Execute</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PubStatus__c.object
<CustomObject>
    <description>List of Status for a Publication - Target Date / Revised Date / Actual Date
Will be used for planning</description>
    <fields>
        <fullName>FPR_Cycle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FPR Cycle</label>
        <referenceTo>FPR_Cycle__c</referenceTo>
        <relationshipName>Pub_Statuses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publication_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication_id</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipName>PubStatus</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Submission_Cycle_Num_Formula__c</fullName>
        <formula>Submission_Cycle__r.Submission_Cycle_Num__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Submission Cycle #</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Submission_Cycle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Submission Cycle</label>
        <referenceTo>SubmissionCycle__c</referenceTo>
        <relationshipName>Pub_Statuses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publication Status</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>PubStatus Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/BatchDef542Action3.cls
global class BatchDef542Action3 extends BatchBase 
    implements Database.Batchable<SObject>,Database.Stateful {
    public String SOQL = 'select id, FPR_Cycle__c,Submission_Cycle__c, Submission_Cycle_Num_Formula__c, Publication_id__c from PubStatus__c '+
        'where Submission_Cycle_Num_Formula__c > 1.0 '+
        'and FPR_Cycle__c = null ';
    
    public BatchDef542Action3() {
        super();
        if ( Test.isRunningTest()){
            SOQL = SOQL + ' limit 10';
        }
        AddMessage(SOQL);
        system.debug(SOQL);
    }
    
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        batchableContext = BC;
        batchName = 'BatchDef542Action3';
        System.Debug(SOQL);
        return Database.getQueryLocator(SOQL);
    }

    global void execute(Database.BatchableContext BC, List<PubStatus__c> pubs){
        ActionThreeforPubs(pubs);
    }

    global void finish(Database.BatchableContext BC){
        SendBatchCompletionEmail();
    }
    
    //BatchDef542Action3.runNow();
    public static void runNow(){
        BatchDef542Action3 batch = new BatchDef542Action3();
        Database.executeBatch(batch, 20);
    }
    
    public static void ActionThreeforPubs(List<PubStatus__c> pubStatusList) {
        if ( pubStatusList == null) return;
        
        for(PubStatus__c ps : pubStatusList) {
            AppearPubModel activePub = new AppearPubModel(ps.Publication_id__c);
            if ( activePub <> null && activePub.hasValidPub && activePub.hasEditAccess) {   
                Integer ScCycleNum = Integer.valueOf(ps.Submission_Cycle_Num_Formula__c);
                ps.FPR_Cycle__c = activePub.FprCycle.getFprCycleByNum(ScCycleNum).id;
            }
        }
        update pubStatusList;
        AppLogModel.flushLogs();        
    }
    
    /*
    BatchDef542Action3.ActionThreeForOnePub('Pub-Id-079255');
    */
    public static void ActionThreeForOnePub(string pubName){
        List<PubStatus__c> pubStatusList = [
            select id, FPR_Cycle__c,Submission_Cycle__c, Submission_Cycle_Num_Formula__c, Publication_id__c 
            from PubStatus__c
            where Submission_Cycle_Num_Formula__c > 1.0
            and FPR_Cycle__c = null
            and publication_id__r.name = :pubName
        ];
        
        ActionThreeforPubs(pubStatusList);
        
    }
    
    

//////////////////////////////////////////  unit test /////////////////////////////////////
    @isTest(seeAllData=true)
    private static void unitTest() {
        CreateData();
        Publication__c  newPub = UnitTestData.PublicationNew('Fpr Controller Pub');
        list<PubStatus__c> PubSt = new List<PubStatus__c>();
        BatchDef542Action3.runNow();
        BatchDef542Action3.ActionThreeForOnePub(newPub.Name);
        BatchDef542Action3.ActionThreeForPubs(pubst);
    } 
    
    public static void CreateData() {
        
    }
}