force-app/main/default/staticresources/python/Disappear/src/objects/FPR_Cycle__c.object
<CustomObject>
    <description>record name will be PubId-{0000000}-FPRCycle-{00}</description>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>FPR Cycles</relationshipLabel>
        <relationshipName>FPR_Cycles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>FPR Cycle</label>
    <nameField>
        <label>FPR_Cycle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FPR Cycles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <fields>
        <fullName>Authors__c</fullName>
        <label>Authors</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Current_Status_Date_FormulaField__c</fullName>
        <formula>PubStatus__r.ActualDate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current Status Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Current_Status_FormulaField__c</fullName>
        <description>Used to make Current Status a &quot;read only&quot; field</description>
        <formula>PubStatus__r.Status__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Target__c</fullName>
        <description>The Current Target field will also be used to populate the Target field for a new Submission Cycle.
This field should NEVER be moved to a formula</description>
        <inlineHelpText>This field is populated automatically by using the &quot;Target&quot; button on the Details tile.  If the desired target is NOT found using the Target button, please use the &quot;Target Not Found&quot; field below.</inlineHelpText>
        <label>Current Target</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Data_Source__c</fullName>
        <label>Data Source</label>
        <picklist>
            <picklistValues>
                <fullName>Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GRAAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Research</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FPR_Submitter__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>FPR_Submitter will record the latest person that click on the Submit to FPR button.

DO NOT USE this field to check if a pub is an FPR Only Pub</description>
        <label>FPR Submitter</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Publication (FPR Submitter)</relationshipLabel>
        <relationshipName>FPR_Submitter</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publication_Title__c</fullName>
        <inlineHelpText>This is a succinct but descriptive Title of the Publication</inlineHelpText>
        <label>Publication Title</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Publication_Type__c</fullName>
        <label>Publication Type</label>
        <picklist>
            <picklistValues>
                <fullName>Abstract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ad Board Summary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMCP Dossier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Book Chapter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brief Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CMS/Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Editorial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GVD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HTA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Letter to Editor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manuscript</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting Summary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Newsletter Article</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oral Presentation (Slide Deck)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Poster</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review Article</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supplement Article (Non English Language Only)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Translation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SubGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link Publication to a SubGroup - which we can find the DataSource for the publication.
This link is very important for the auto population of FPR Reviewer.</description>
        <inlineHelpText>For purposes of FPR routing, functional group from which publication content/or data was orignated. Enter one of these selections - Research, Development, Operations - before clicking the Lookup icon.  Then select a SubGroup from the Search Results list.</inlineHelpText>
        <label>SubGroup Link</label>
        <referenceTo>SubGroup__c</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>isEnbrel__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to manage the sharing with those users that should not have access to Enbrel pubs</description>
        <label>isEnbrel</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isPlanning__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Part of GPP</label>
        <type>Checkbox</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <recordTypes>
        <fullName>Review</fullName>
        <active>true</active>
        <label>Review</label>
    </recordTypes>
    <recordTypes>
        <fullName>Suggestion</fullName>
        <active>true</active>
        <label>Suggestion</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PubRelated__c.object
<CustomObject>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipName>PubRelated</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RelatedPub__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipName>RelatedPub</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ToDelete__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Temp field for UI.
User can click on ToDelete Checkbox and backend will physically delete the record.</description>
        <label>ToDelete</label>
        <type>Checkbox</type>
    </fields>
    <label>Publication Related</label>
    <nameField>
        <displayFormat>pr-{0000000}</displayFormat>
        <label>PubRelated Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publications Related</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PubReviewTeam__c.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <description>Vote Comments</description>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FPR_Cycle__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>FPR_Cycle</label>
        <referenceTo>FPR_Cycle__c</referenceTo>
        <relationshipName>PubReviewTeams</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HasVoted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>boolean set when a team member has voted</description>
        <label>HasVoted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsLogicallyDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsLogicallyDeleted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ProxyMember__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>if user has a proxy for this pub, lookup to that proxy team member</description>
        <label>Proxy Member</label>
        <referenceTo>PubReviewTeam__c</referenceTo>
        <relationshipLabel>Publication Review Team Members (Proxy Member)</relationshipLabel>
        <relationshipName>ProxyMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipName>PubReviewTeams</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reviewer_Status__c</fullName>
        <label>Vote</label>
        <picklist>
            <picklistValues>
                <fullName>Reviewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reviewed With Comments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discussion Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withheld</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Comments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vote Not Available</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Reviewer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reviewer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>PubReviewTeams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubType__c</fullName>
        <label>SubType</label>
        <picklist>
            <picklistValues>
                <fullName>Standard</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Delegate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proxy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delegate Exists</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delegate New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Triaged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Triagee</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Primary / Informed</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Notify</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Publication Review Team Member</label>
    <nameField>
        <displayFormat>PRT-{000000000}</displayFormat>
        <label>PubReviewTeamId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication Review Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/SubGroup__c.object
<CustomObject>
    <fields>
        <fullName>Data_Source__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Data Source</label>
        <referenceTo>DataSource__c</referenceTo>
        <relationshipLabel>SubGroups</relationshipLabel>
        <relationshipName>SubGroups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>isLogicallyDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Expired</label>
        <type>Checkbox</type>
    </fields>
    <label>SubGroup</label>
    <nameField>
        <label>SubGroup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SubGroups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/withoutSharingUtil.cls
global without sharing class withoutSharingUtil {


	global static void DelRecords(List<sObject> objects, boolean AllOrNothing) {
		database.delete(objects,AllOrNothing);
	}
	
	global static void MoveToGpp(Publication__c pub) {
		pub.isPlanning__c = true;		
		update pub;
	}
	
	global static void RemoveFromGPP(Publication__c pub) {
		pub.isPlanning__c = false;		
		update pub;
	}
	
	global static void UpdatePub(Publication__c pub) {		
		update pub;
	}
	
	global static void ChangeOwnershipToTemporaryPoolUser(Publication__c pub, boolean updatePubRecord) {
		User temporaryPoolUser;
		string userName = KeyValueSettingsModel.getValue('TemporaryPubOwner'); //Cannot user getKey because userName needs to be unique between login.salesforce.com or test.salesforce.com
		
		List<User> userList = [select id, name from User where Username = :userName and IsActive = true];
		if (userList.size() == 0) {
			AppLogModel.LogError('UserModel::GetTemporaryPoolUser', 
			'No active user found with Username = "'+ userName +'"');
		} else {
			temporaryPoolUser = userList[0];
		}

        if (temporaryPoolUser == null) {
            AppLogModel.LogError('withoutSharingUtil::ChangeOwnershipToTemporaryPoolUser', 'Cannot find Temporary Pool User. Aborting', pub.Id);
            AppLogModel.flushLogs();
            return;
        }
        pub.OwnerId = temporaryPoolUser.Id;
        
        if (updatePubRecord ) {
            update pub;
        }
        AppLogModel.LogInfo('withoutSharingUtil::ChangeOwnershipToTemporaryPoolUser', 
            'Changed ownership for Pub['+pub.Publication_Title__c +'] to user ' + temporaryPoolUser.Name, pub.Id);  
	}
	
	global static void InsertReviewerAsSystem(PubReviewTeam__c reviewTeamMember) {
		insert reviewTeamMember;
	}
	
	global static PubReviewTeam__c getLoggedInTeamMemberForPubFprCycle(Id pubId, Id fprCycleId) {
   		if (pubId == null ||  fprCycleId == null) {
   			return null;
   		}
   		
   		Set<Id> AppearUserContactIdSet = AppearContactModel.findContactForAppearUser(userInfo.getUserId());
   		
   		if (AppearUserContactIdSet.size() > 0) {
   			//Id loggedInContactId = contacts[0].Id;
   		
	   		List<PubReviewTeam__c> teamMembers = [
	   			Select Reviewer_Status__c, Comments__c, HasVoted__c, Type__c, ProxyMember__c, ProxyMember__r.HasVoted__c, SubType__c
	   			From PubReviewTeam__c
	   			Where Publication__c = :pubId 
	   			And Reviewer__c in :AppearUserContactIdSet 
	   			And FPR_Cycle__c= :fprCycleId 
	   			And IsLogicallyDeleted__c = false
	   		];
	   			
   			if (teamMembers.size() > 0) {
   				return teamMembers[0];
   			} else {
   				AppLogModel.LogError('PubReviewTeamModel::getLoggedInTeamMemberForPubFprCycle', 
   					'PubReviewTeam record fround for CurrentUser['+userInfo.getUserName()+'] for this publication['+ pubId +'] ', pubId);
   			}
   		} else {
   			AppLogModel.LogError('PubReviewTeamModel::getLoggedInTeamMemberForPubFprCycle', 
   				'CurrentUser['+userInfo.getUserName()+'] is not a member of the review team of this publication['+ pubId +'] ', pubId);
   		}
		return null;
	}
	
	global static void UpdateReviewerAsSystem(PubReviewTeam__c reviewTeamMember) {
		update reviewTeamMember;
	}
	
    global static void ChangeOwnershipToFprSubmitter(Publication__c pubRecord, boolean updatePubRecord) { //used to remove edit access to a submitted suggestion or in fpr from creator. Sharing criteria will grant redundantly where appropriate
        Id submitterUserId = AppearContactModel.findUserIdForContactId(pubRecord.Fpr_Submitter__c);
        if (submitterUserId == null) {
            AppLogModel.LogError('withoutSharingUtil::ChangeOwnershipToFprSubmitter', 'Cannot find FPR Submitter. Aborting', pubRecord.Id);
            AppLogModel.flushLogs();
            return;
        }
        pubRecord.OwnerId = submitterUserId;
        
        AppearPubModelShare pubShare = new AppearPubModelShare(pubRecord.Id, pubRecord.RecordTypeId, pubRecord.isEnbrel__c);
        pubShare.resetAllApexSharing(); //reset sharing so ownership can be handed back to portal user
        
        if (updatePubRecord ) {
            update pubRecord;
        }
        AppLogModel.LogInfo('withoutSharingUtil::ChangeOwnershipToFprSubmitter', 
            'Changed ownership for Pub['+pubRecord.Publication_Title__c +'] to userId ' + submitterUserId, pubRecord.Id);
    }
    /*Code implemented to check when EW user try to clone a publication whether they have access to all the 
    Related Pubs of Original Pub or NOT*/
    
	  global static List<PubRelated__c> getPubRelatedSystemContext(Id PubId) {
	        if ( PubId == null) {
	            return null;
	        }
	        List<PubRelated__c> pubRelatedList = [ 
	            select id, ToDelete__c,
	            Publication__c, publication__r.Name, publication__r.Publication_Title__c,
	            RelatedPub__c, RelatedPub__r.Name, RelatedPub__r.Publication_Title__c,
	            RelatedPub__r.Publication_Type__c,  RelatedPub__r.Current_Status_FormulaField__c, RelatedPub__r.Authors__c,
	            RelatedPub__r.Current_Status_Date_FormulaField__c, RelatedPub__r.Current_Target__c, RelatedPub__r.isPlanning__c,
	            RelatedPub__r.Data_Source__c, RelatedPub__r.SubGroup_pick__c, RelatedPub__r.Datasourceformulafield__c,
	            RelatedPub__r.Subgroup__c, RelatedPub__r.Is_Tracking_Only__c, RelatedPub__r.Country_Pick__c, RelatedPub__r.Presentation_Type__c,
	            RelatedPub__r.RAE__c, RelatedPub__r.Search_Identifier__c
	            from PubRelated__c
	            where Publication__c = :PubId
	        ];
	        
	        string msg = 'Related Pub Model retrieved from System Context ' + pubRelatedList.size()+' records for PubId = '+PubId;
	        System.Debug(msg);
	        System.debug('Related list fetched'+pubRelatedList);// updated 2/11/15
	        
	        return pubRelatedList;
	    }
    

}