force-app/main/default/staticresources/python/Disappear/src/objects/FPR_Cycle__c.object
<CustomObject>
    <description>record name will be PubId-{0000000}-FPRCycle-{00}</description>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>FPR Cycles</relationshipLabel>
        <relationshipName>FPR_Cycles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>FPR Cycle</label>
    <nameField>
        <label>FPR_Cycle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FPR Cycles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <fields>
        <fullName>Assigned_FPRC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned to FPR Coordinator</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Target__c</fullName>
        <description>The Current Target field will also be used to populate the Target field for a new Submission Cycle.
This field should NEVER be moved to a formula</description>
        <inlineHelpText>This field is populated automatically by using the &quot;Target&quot; button on the Details tile.  If the desired target is NOT found using the Target button, please use the &quot;Target Not Found&quot; field below.</inlineHelpText>
        <label>Current Target</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FPR_Due_Date__c</fullName>
        <inlineHelpText>As best practice, select an FPR due date that is more than 10 business days from today. If this is a rush request, provide business justification in the Comments for FPR Coordinator section and we will try to facilitate your request.</inlineHelpText>
        <label>FPR Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FPR_Submitter__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>FPR_Submitter will record the latest person that click on the Submit to FPR button.

DO NOT USE this field to check if a pub is an FPR Only Pub</description>
        <label>FPR Submitter</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Publication (FPR Submitter)</relationshipLabel>
        <relationshipName>FPR_Submitter</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <description>Related to Pub Product Indication</description>
        <label>Primary Prod Ind Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Indication__c</fullName>
        <description>A READ ONLY string that list all product Indications for the Publication
The key product indication will be list at the first entry</description>
        <inlineHelpText>Product - Indication is a required field that is available for selection when a publication is first saved. Once saved, the Product Indication may be edited using the Product Indication button.</inlineHelpText>
        <label>Product - Indication</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publication_Type__c</fullName>
        <label>Publication Type</label>
        <picklist>
            <picklistValues>
                <fullName>Abstract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ad Board Summary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMCP Dossier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Book Chapter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brief Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CMS/Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Editorial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GVD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HTA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Letter to Editor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manuscript</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting Summary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Newsletter Article</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oral Presentation (Slide Deck)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Poster</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review Article</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supplement Article (Non English Language Only)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Translation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PubReviewTeam__c.object
<CustomObject>
    <fields>
        <fullName>DelegatedTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Publication Review Team Member this pub was delegated to</description>
        <label>Delegated To</label>
        <referenceTo>PubReviewTeam__c</referenceTo>
        <relationshipLabel>Publication Review Team Members (Delegated To)</relationshipLabel>
        <relationshipName>Publication_Review_Team_Members1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Delegation_Justification__c</fullName>
        <label>Delegation Justification</label>
        <picklist>
            <picklistValues>
                <fullName>Reviewer on travel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reviewer on vacation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reviewer on medical leave</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reviewer in office but not available</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FPR_Cycle__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>FPR_Cycle</label>
        <referenceTo>FPR_Cycle__c</referenceTo>
        <relationshipName>PubReviewTeams</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipName>PubReviewTeams</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reviewer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reviewer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>PubReviewTeams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TriageDelegatedBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TriageDelegatedBy</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>PubReviewTeams1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Triage_Justification__c</fullName>
        <label>Triage Justification</label>
        <picklist>
            <picklistValues>
                <fullName>Additional legal expertise required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Additional scientific/medical/statistical expertise required</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Publication Review Team Member</label>
    <nameField>
        <displayFormat>PRT-{000000000}</displayFormat>
        <label>PubReviewTeamId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication Review Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/EmailPubReviewTeam.cls
public class EmailPubReviewTeam{


	private static AppearPubModel pTestPub = null;
	public static AppearPubModel testPub {
		get {  
			if (pTestPub == null) {
				pTestPub = createTestPub();
			}
			return pTestPub;
		}
	}


	private static Contact pContact1 = null;
	public static Contact contact1 {
		get {
			if ( pContact1 <> null) { 
				return pContact1;
			}
			List<Contact> contacts = [
				select id,name,FirstName, Lastname, Email
				from Contact
				where email = 'benjamin_lau@yahoo.com'
			];
			if ( contacts.size() == 1) {
				pContact1 = contacts[0];
			} else {
				Contact myContact = new Contact();
				myContact.FirstName = 'Benjamin';
				myContact.LastName = 'Lau';
				myContact.Email = 'benjamin_lau@yahoo.com';
				insert myContact;	
				pContact1 = myContact;			
			}
			return pContact1;
		}
	}

	private static Contact pContact2 = null;
	public static Contact contact2 {
		get {
			if ( pContact2 <> null) {
				return pContact2;
			}
			List<Contact> contacts = [
				select id,name,FirstName, Lastname, Email
				from Contact
				where email = 'benjamin_lau@hotmail.com'
			];
			if ( contacts.size() == 1) {
				pContact2 = contacts[0];
			} else {
				Contact myContact = new Contact();
				myContact.FirstName = 'Brandon';
				myContact.LastName = 'Schoen';
				myContact.Email = 'benjamin_lau@hotmail.com';
				insert myContact;	
				pContact2 = myContact;			
			}
			return pContact2;
		}
	}


	public static AppearPubModel createTestPub() {

		Publication__c pub = UnitTestData.PublicationNew('test pub');
		pub.Assigned_FPRC__c = contact2.id;
		pub.FPR_Submitter__c = contact1.id;
		pub.FPR_Due_Date__c = Date.today().addDays(30);
		pub.Current_Target__c = '[Current Target Meeting]';
		pub.Primary__c = '[Primary Product]';
		pub.Publication_Type__c ='[Publication Type]';
		pub.Product_Indication__c = 'Product Indication 1; Product Indication2;';
		update pub;		
		
		AppearPubModel activePub = new AppearPubModel(pub.id); 
		PubReviewTeam__c reviewTeamMemberCycle = activePub.PubReviewTeam.NewPubReviewTeamMembers;
		FPR_Cycle__c firstFprCycle = activePub.FprCycle.getFprCycleByNum(1);
		reviewTeamMemberCycle.FPR_Cycle__c = firstFprCycle.id;
		reviewTeamMemberCycle.Reviewer__c = contact1.id;
		reviewTeamMemberCycle.Delegation_Justification__c = '[A good delegation justification]';
		//reviewTeamMemberCycle.DelegatedTo__c = 
		
		reviewTeamMemberCycle.TriageDelegatedBy__c = contact1.id;
		reviewTeamMemberCycle.Triage_Justification__c = '[A good triage justification]';
		
		insert reviewTeamMemberCycle;
		 
		return activePub;
	}

}