force-app/main/default/staticresources/python/Disappear/src/objects/FPR_Cycle__c.object
<CustomObject>
    <description>record name will be PubId-{0000000}-FPRCycle-{00}</description>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>FPR Cycles</relationshipLabel>
        <relationshipName>FPR_Cycles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>FPR Cycle</label>
    <nameField>
        <label>FPR_Cycle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FPR Cycles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <fields>
        <fullName>Current_SubmissionCycle_Id_Formula__c</fullName>
        <formula>PubStatus__r.Submission_Cycle__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current Submission Cycle Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PubStatus__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Current status of this publication</description>
        <label>PubStatus</label>
        <referenceTo>PubStatus__c</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PubStatus__c.object
<CustomObject>
    <description>List of Status for a Publication - Target Date / Revised Date / Actual Date
Will be used for planning</description>
    <fields>
        <fullName>ActualDate__c</fullName>
        <label>Actual Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>FPR_Cycle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FPR Cycle</label>
        <referenceTo>FPR_Cycle__c</referenceTo>
        <relationshipName>Pub_Statuses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publication_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication_id</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipName>PubStatus</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Status</label>
        <referenceTo>Status__c</referenceTo>
        <relationshipName>PubStatuses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Submission_Cycle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Submission Cycle</label>
        <referenceTo>SubmissionCycle__c</referenceTo>
        <relationshipName>Pub_Statuses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publication Status</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>PubStatus Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Status__c.object
<CustomObject>
    <label>Status</label>
    <nameField>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/BatchInsertMissingAcceptedStatus.cls
global class BatchInsertMissingAcceptedStatus{
	public static void test() {
		Map<id, Publication__c> pubMap = new Map<id, Publication__c>( [select id, Current_SubmissionCycle_Id_Formula__c from publication__c where id not in (select Publication_id__c from PubStatus__c where Status__r.Name = 'Accepted') AND id in (select Publication_id__c from PubStatus__c where Status__r.Name = 'Published/Presented')]);

		Map<id, id> pubIdFprCycleIdMap = new Map<id, id>();
		for(PubStatus__c publishedStatus : [select FPR_Cycle__c, Publication_id__c FROM PubStatus__c where Status__r.Name = 'Published/Presented' AND Publication_id__c in : pubMap.keySet()]) {
			pubIdFprCycleIdMap.put(publishedStatus.Publication_id__c,publishedStatus.FPR_Cycle__c);
		}
		
		List<PubStatus__c> statusesToInsert = new List<PubStatus__c>();
		for(Id pubId : pubMap.keyset()) {
		    if (pubIdFprCycleIdMap.containsKey(pubId)) {        
		        Id fprCycleId = pubIdFprCycleIdMap.get(pubId);
		        Id subCycleId = pubMap.get(pubId).Current_SubmissionCycle_Id_Formula__c;
		        
                PubStatus__c newAcceptedPubStatus = new PubStatus__c();
		        newAcceptedPubStatus.Publication_id__c = pubId;   
		        newAcceptedPubStatus.ActualDate__c = null;
		        newAcceptedPubStatus.Status__c = StatusModel.Accepted.id;
		        newAcceptedPubStatus.Submission_Cycle__c = subCycleId;
		        newAcceptedPubStatus.FPR_Cycle__c = fprCycleId;
		        
		        statusesToInsert.add(newAcceptedPubStatus);
		    }
		}
		
		if (statusesToInsert.size() > 0) {
			insert statusesToInsert;
		}
	}
}