force-app/main/default/staticresources/python/Disappear/src/objects/FPR_Cycle__c.object
<CustomObject>
    <description>record name will be PubId-{0000000}-FPRCycle-{00}</description>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>FPR Cycles</relationshipLabel>
        <relationshipName>FPR_Cycles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>FPR Cycle</label>
    <nameField>
        <label>FPR_Cycle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FPR Cycles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <fields>
        <fullName>PubStatus__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Current status of this publication</description>
        <label>PubStatus</label>
        <referenceTo>PubStatus__c</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <recordTypes>
        <fullName>Execute</fullName>
        <active>true</active>
        <label>Execute</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PubStatus__c.object
<CustomObject>
    <description>List of Status for a Publication - Target Date / Revised Date / Actual Date
Will be used for planning</description>
    <fields>
        <fullName>FPR_Cycle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FPR Cycle</label>
        <referenceTo>FPR_Cycle__c</referenceTo>
        <relationshipName>Pub_Statuses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publication_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication_id</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipName>PubStatus</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Status</label>
        <referenceTo>Status__c</referenceTo>
        <relationshipName>PubStatuses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Submission_Cycle_Num_Formula__c</fullName>
        <formula>Submission_Cycle__r.Submission_Cycle_Num__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Submission Cycle #</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Publication Status</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>PubStatus Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Status__c.object
<CustomObject>
    <fields>
        <fullName>displayOrder__c</fullName>
        <description>display order</description>
        <label>displayOrder</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Status</label>
    <nameField>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/BatchDef542Action6.cls
global class BatchDef542Action6 extends BatchBase 
	implements Database.Batchable<SObject>,Database.Stateful {
   	public String SOQL = 'select fpr_cycle__c, status__r.name ' +
		'from PubStatus__c '+
		'where Submission_Cycle_num_Formula__c = 1 ' +
		'and FPR_Cycle__c <> null ' +
		'and Status__r.displayOrder__c < '; // ':StatusModel.InFpr.displayOrder__c';
   	
	public BatchDef542Action6() {
		super();
		SOQL = SOQL + StatusModel.InFpr.displayOrder__c;
    	if ( Test.isRunningTest()){
    		SOQL = SOQL + ' limit 10';
    	}
    	AddMessage(SOQL);
        system.debug(SOQL);
	}
	
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        batchableContext = BC;
        batchName = 'BatchDef542Action6';
        System.Debug(SOQL);
        return Database.getQueryLocator(SOQL);
    }

    global void execute(Database.BatchableContext BC, List<PubStatus__c> pubs){
		ActionSixforPubs(pubs);
    }

    global void finish(Database.BatchableContext BC){
		SendBatchCompletionEmail();
	}
	
	//BatchDef542Action6.runNow();
	public static void runNow(){
    	BatchDef542Action6 batch = new BatchDef542Action6();
        Database.executeBatch(batch, 80);
	}
	
	public static void ActionSixforPubs(List<PubStatus__c> pubStatusList) {
		if ( pubStatusList == null) return;
		
		for(PubStatus__c ps : pubStatusList) {
			ps.Fpr_Cycle__c = null;
			System.Debug('ActionSixforPubs - pubStatus '+ps.status__r.name);
		}
		update pubStatusList;		
		//System.Debug('ActionSixforPubs - pubStatusList Size = '+ pubStatusList.size());	
	}
	
	/*
	BatchDef542Action6.ActionSixForOnePub('Pub-Id-043826');
	*/
	public static void ActionSixForOnePub(string pubName){
		List<PubStatus__c> pubStatusList = [
			select id,fpr_cycle__c,  status__r.name from PubStatus__c
			where publication_id__r.name = :pubName
			and Submission_Cycle_num_Formula__c = 1 
		    and FPR_Cycle__c <> null 
		    and Status__r.displayOrder__c < :StatusModel.InFpr.displayOrder__c
		];
		
		ActionSixforPubs(pubStatusList);
		
	}
	
	

//////////////////////////////////////////  unit test /////////////////////////////////////
	@isTest
	private static void unitTest() {
		CreateData();
		
		BatchDef542Action6.runNow();
	} 
	
	public static void CreateData() {
		
		Publication__c pub = UnitTestData.PublicationNew('BatchDef542Action6');
		
		AppearPubModel activePub = new AppearPubModel( pub.id);
		
		for(PubStatus__c pubStatus : activePub.pubstatus.pubStatusList) {
			pubStatus.FPR_Cycle__c = activePub.FprCycle.getFprCycleByNum(1).id;
		}
		
		update activePub.pubstatus.pubStatusList;
		
		return;
		
	}
}