force-app/main/default/staticresources/python/Disappear/src/objects/FPR_Cycle__c.object
<CustomObject>
    <description>record name will be PubId-{0000000}-FPRCycle-{00}</description>
    <fields>
        <fullName>FPR_Cycle_Num__c</fullName>
        <label>FPR Cycle Num</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>FPR Cycles</relationshipLabel>
        <relationshipName>FPR_Cycles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>FPR Cycle</label>
    <nameField>
        <label>FPR_Cycle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FPR Cycles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <fields>
        <fullName>Current_FPRCycle_Id_Formula__c</fullName>
        <formula>PubStatus__r.FPR_Cycle__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current FPR Cycle Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_FPR_Cycle_Num__c</fullName>
        <description>PubStatus__r.FPR_Cycle_Num_Formula__c</description>
        <formula>PubStatus__r.FPR_Cycle_Num_Formula__c</formula>
        <label>Current FPR Cycle Num</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_SubmissionCycle_Id_Formula__c</fullName>
        <formula>PubStatus__r.Submission_Cycle__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current Submission Cycle Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PubStatus__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Current status of this publication</description>
        <label>PubStatus</label>
        <referenceTo>PubStatus__c</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <recordTypes>
        <fullName>Execute</fullName>
        <active>true</active>
        <label>Execute</label>
    </recordTypes>
    <recordTypes>
        <fullName>Submit</fullName>
        <active>true</active>
        <label>Submit</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PubStatus__c.object
<CustomObject>
    <description>List of Status for a Publication - Target Date / Revised Date / Actual Date
Will be used for planning</description>
    <fields>
        <fullName>FPR_Cycle_Num_Formula__c</fullName>
        <formula>IF(FPR_Cycle__r.FPR_Cycle_Num__c &gt; 0.0, text(FPR_Cycle__r.FPR_Cycle_Num__c), &quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>FPR Cycle #</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FPR_Cycle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>FPR Cycle</label>
        <referenceTo>FPR_Cycle__c</referenceTo>
        <relationshipName>Pub_Statuses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsLogicallyDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to logically delete the record.

Release 1.1 Renamed isLogicallyDeleted to Expired</description>
        <label>Expired</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Publication_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication_id</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipName>PubStatus</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Status</label>
        <referenceTo>Status__c</referenceTo>
        <relationshipName>PubStatuses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Submission_Cycle_Num_Formula__c</fullName>
        <formula>Submission_Cycle__r.Submission_Cycle_Num__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Submission Cycle #</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Submission_Cycle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Submission Cycle</label>
        <referenceTo>SubmissionCycle__c</referenceTo>
        <relationshipName>Pub_Statuses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publication Status</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>PubStatus Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Status__c.object
<CustomObject>
    <fields>
        <fullName>displayOrder__c</fullName>
        <description>display order</description>
        <label>displayOrder</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Status</label>
    <nameField>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/SubmissionCycle__c.object
<CustomObject>
    <description>record name will be PubId-{0000000}-SubCycle-{00}</description>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Submission Cycles</relationshipLabel>
        <relationshipName>Submission_Cycles</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Submission_Cycle_Num__c</fullName>
        <label>Submission Cycle #</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Submission Cycle</label>
    <nameField>
        <label>Submission Cycle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submission Cycles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/BatchSyncLegacyGlobalStatus.cls
global class BatchSyncLegacyGlobalStatus extends BatchBase 
	implements Database.Batchable<SObject>,Database.Stateful {
   	public String SOQL = 'select id,name,Current_SubmissionCycle_Id_Formula__c,Current_FPRCycle_Id_Formula__c, Current_FPR_Cycle_Num__c from Publication__c  order by name desc';
	public BatchSyncLegacyGlobalStatus() {
		super();
    	if ( Test.isRunningTest()){
    		SOQL = SOQL + ' limit 10';
    	}
    	AddMessage(SOQL);
        system.debug(SOQL);
	}
	
   	private static Set<id> createdByIdsToInclude{
   		get{	
			return RecordTypeModel.LegacyInProgressPubRecordIdSet;
   		}
   	}
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        batchableContext = BC;
        batchName = 'BatchSyncLegacyGlobalStatus';
        System.Debug(SOQL);
        return Database.getQueryLocator(SOQL);
    }

    global void execute(Database.BatchableContext BC, List<publication__c> pubs){
		syncPubs(pubs);
    }

    global void finish(Database.BatchableContext BC){
		SendBatchCompletionEmail();
	}
	
	//BatchSyncLegacyGlobalStatus.runNow();
	public static void runNow(){
    	BatchSyncLegacyGlobalStatus batch = new BatchSyncLegacyGlobalStatus();
        Database.executeBatch(batch, 10);
	}
	
	public static void syncPubs(List<publication__c> pubs) {
		List<PubStatus__c> newStatusList = new List<PubStatus__c>();
		
    	for(Publication__c pub : pubs) {
    		checkPubStatus(pub.id);
    	}    		
    		
		AppLogModel.flushLogs();		
	}
	
	public static void checkPubStatus(Id pubId) {
		AppearPubModel activePub = new AppearPubModel(pubid);
		if ( RecordTypeModel.LegacyPubRecordIdSet.contains(activePub.pubRecord.RecordTypeId)) {
			activePub.pubRecord.RecordTypeId = 	RecordTypeModel.PublicationSuggestionRecTypeId;
			//just get out of legacy Type
			update activePub.PubRecord;
		}
		
		List<PubStatus__c> newStatusForPub = new List<PubStatus__c>();
		
		//find all existing status	
		List<PubStatus__c> existingPubStatuses = [ 
				select Status__c, Status__r.id, Status__r.name, 
				Submission_Cycle__c, Submission_Cycle__r.Submission_Cycle_Num__c,Submission_Cycle_Num_Formula__c, 
				FPR_Cycle__c, FPR_Cycle__r.FPR_Cycle_Num__c, FPR_Cycle_Num_Formula__c
				from PubStatus__c
				where Publication_id__c = :pubId 
				and IsLogicallyDeleted__c = false
			];
		
		
		
		//sc1 - fc0
		SubmissionCycle__c firstSubmissionCycle = activePub.SubmissionCycle.getSubmissionCycleByNum(1);
		//create a set 
		Set<String> existingInitialGlobalStatus = new Set<String>();
		for(PubStatus__c ps : existingPubStatuses) {
			if ( ps.FPR_Cycle__c == null && ps.Submission_Cycle__c == firstSubmissionCycle.id ) {
				existingInitialGlobalStatus.add(ps.status__r.name);
			}
		}
		
		for(Status__c status : StatusModel.GlobalStatusList){
			if (status.displayOrder__c < StatusModel.InFpr.displayOrder__c &&  !existingInitialGlobalStatus.contains(status.name) ) {
				PubStatus__c newPubStatus = new PubStatus__c();
				newPubStatus.Publication_id__c = pubId;   
				newPubStatus.Status__c = status.id;
				newPubStatus.Submission_Cycle__c = firstSubmissionCycle.id;
				newPubStatus.Fpr_Cycle__c = null;
				newStatusForPub.add(newPubStatus);
			}
		}	
		
		insert newStatusForPub;

		//reset FPR_Cycle__c to Null - just in case Trigger copy the Current FPR cycle to the newly inserted PubStatus
		List<PubStatus__c> preFprPubStatus = [
			select Fpr_Cycle__c 
			from PubStatus__c 
			where Publication_id__c = :PubId
			and Submission_Cycle__c = :firstSubmissionCycle.id
			and Status__r.displayOrder__c < :StatusModel.InFpr.displayOrder__c
		];
		for(PubStatus__c ps : newStatusForPub) {
			ps.Fpr_Cycle__c = null;
		}
		update newStatusForPub;
		
		
		//reset for lastFC
		newStatusForPub =  new List<PubStatus__c>();
		
		
		//then last SC / last FC
		integer maxSC = 1;
		integer maxFC = 0;
		for(PubStatus__c ps : existingPubStatuses) {
			integer currSC = Integer.ValueOf(ps.Submission_Cycle__r.Submission_Cycle_Num__c);
			if ( currSC > maxSC) {
				maxSC = currSc;
			}
			if ( ps.FPR_Cycle__c  <> null) {
				if ( Integer.valueOf(ps.FPR_Cycle_Num_Formula__c)  > maxFC) {
					maxFC = Integer.valueOf(ps.FPR_Cycle_Num_Formula__c);
				}
			}
		}
		
		if ( maxFC > 0 ) {
			SubmissionCycle__c maxSubmissionCycle = activePub.SubmissionCycle.getSubmissionCycleByNum(maxSC);
			FPR_Cycle__c maxFprCycle = activePub.FprCycle.getFprCycleByNum(maxFC);
			
			//handle the Post Submit To FPR Status
			Set<String> existingPostSubmitGlobalStatus = new Set<String>();
			for(PubStatus__c ps : existingPubStatuses) {
				if ( ps.FPR_Cycle__c <> null && ( Integer.valueOf(ps.FPR_Cycle_Num_Formula__c) == maxFC && ps.Submission_Cycle_Num_Formula__c == maxSC)  ) {
					existingPostSubmitGlobalStatus.add(ps.status__r.name);
				}
			}
			for(Status__c status : StatusModel.GlobalStatusList){
				if (status.displayOrder__c >= StatusModel.InFpr.displayOrder__c &&  !existingPostSubmitGlobalStatus.contains(status.name) ) {
					PubStatus__c newPubStatus = new PubStatus__c();
					newPubStatus.Publication_id__c = pubId;   
					newPubStatus.Status__c = status.id;
					newPubStatus.Submission_Cycle__c = maxSubmissionCycle.id;
					newPubStatus.Fpr_Cycle__c = maxFprCycle.id;
					newStatusForPub.add(newPubStatus);
				}
			}	
			
		}	
		insert newStatusForPub;
		
		//reload
		activePub = new AppearPubModel(pubid);
		PublicationTriggerLogic.UpdateLatestPubStatus(activePub.pubRecord, true); 
	}
	
	/*
	BatchSyncLegacyGlobalStatus.syncOnePub('Pub-Id-079255');
	BatchSyncLegacyGlobalStatus.syncOnePub('Pub-Id-060989');
	*/
	public static void syncOnePub(string pubName){
		List<Publication__c> pubs = [
			select id,name, Current_SubmissionCycle_Id_Formula__c, Current_FPRCycle_Id_Formula__c
			from Publication__c 
			WHERE name = :pubName  
		];
		
		syncPubs(pubs);
		
	}
	
	

//////////////////////////////////////////  unit test /////////////////////////////////////
	@isTest
	private static void unitTest() {
		CreateData();
		
		BatchSyncLegacyGlobalStatus.runNow();
	} 
	
	public static void CreateData() {
		StatusModelData.createData();
		
		UnitTestData.PublicationNew('BatchSyncLegacyGlobalStatus');
	}
}