force-app/main/default/staticresources/python/Disappear/src/objects/Indication__c.object
<CustomObject>
    <fields>
        <fullName>IsLogicallyDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Expired</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SiebelRowId__c</fullName>
        <externalId>true</externalId>
        <label>Siebel RowId</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Indication</label>
    <nameField>
        <label>Indication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Indications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/ProductIndication__c.object
<CustomObject>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>EndDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Indication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Indication</label>
        <referenceTo>Indication__c</referenceTo>
        <relationshipLabel>Product Indications</relationshipLabel>
        <relationshipName>Product_Indications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>AmgenProduct__c</referenceTo>
        <relationshipLabel>Product Indications</relationshipLabel>
        <relationshipName>Product_Indications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SiebelRowId__c</fullName>
        <externalId>true</externalId>
        <label>SiebelRowId</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>StartDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>isLogicallyDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Expired</label>
        <type>Checkbox</type>
    </fields>
    <label>Product Indication</label>
    <nameField>
        <label>ProductIndication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Indications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Review_Team__c.object
<CustomObject>
    <description>Review team for DataSource or SubGroup

A review team can exists for a DataSource without SubGroup</description>
    <fields>
        <fullName>Data_Source__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Data Source</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>DataSource__c.isLogicallyDeleted__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>DataSource__c</referenceTo>
        <relationshipLabel>Review Teams</relationshipLabel>
        <relationshipName>Review_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsLogicallyDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Expired</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Indication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product Indication</label>
        <referenceTo>ProductIndication__c</referenceTo>
        <relationshipLabel>Review Teams</relationshipLabel>
        <relationshipName>Review_Teams</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SiebelRowId__c</fullName>
        <externalId>true</externalId>
        <label>SiebelRowId</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubGroup__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>SubGroup</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>SubGroup__c.isLogicallyDeleted__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SubGroup__c</referenceTo>
        <relationshipLabel>Review Teams</relationshipLabel>
        <relationshipName>Review_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Review Team</label>
    <nameField>
        <label>Review Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Review Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/SubGroup__c.object
<CustomObject>
    <fields>
        <fullName>Data_Source__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Data Source</label>
        <referenceTo>DataSource__c</referenceTo>
        <relationshipLabel>SubGroups</relationshipLabel>
        <relationshipName>SubGroups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SiebelRowId__c</fullName>
        <externalId>true</externalId>
        <label>SiebelRowId</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isLogicallyDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Expired</label>
        <type>Checkbox</type>
    </fields>
    <label>SubGroup</label>
    <nameField>
        <label>SubGroup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SubGroups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/ReviewTeamTriggerLogicTest.cls
/***************************************************************************************************
 * $Id$ : ReviewTeamTriggerLogicTest
 * $Created Date$ : 2014/04/03
 * $Author$ : Sudha
 * $Description$ : This is a Test Class for ReviewTeamCOntroller 
 ***********************************************************************************************/
@isTest(SeeAllData=true)
public class ReviewTeamTriggerLogicTest {
    private static testMethod void TestReviewTeamTriggerLogic(){
        Test.startTest();
        //Creating data of ProductIndication.
        List<ProductIndication__c> ProductIndicationList = new List<ProductIndication__c>();
        ProductIndication__c ProductIndication = new ProductIndication__c(name= 'ABP 215 - Not Applicable' , Product__c=AmgenProductModel.getProductByName('ABP 215').id, 
            Indication__c=IndicationModel.getIndicationByName('Not Applicable').id, StartDate__c = null, EndDate__c = null);
        ProductIndicationList.add(ProductIndication);
        
        ProductIndication__c ProductIndication1 = new ProductIndication__c(name= 'ABP 215 - Not Applicable' , Product__c=AmgenProductModel.getProductByName('ABP 215').id, 
            Indication__c=IndicationModel.getIndicationByName('Not Applicable').id, StartDate__c = null, EndDate__c = null,isLogicallyDeleted__c = true);
        ProductIndicationList.add(ProductIndication1);
        insert ProductIndicationList;
        
        //Creating data for Review Team 
        List<Review_Team__c> reviewTeamList = new List<Review_Team__c>();
        Review_Team__c reviewTeam = new Review_Team__c();
        reviewTeam.Data_Source__c = DataSourceModelData.Development.id;
        reviewTeam.Product_Indication__c = ProductIndication.id;
        reviewTeam.SubGroup__c = SubGroupModelData.DevelopmentSmpSubGroup.id;
        reviewTeam.SiebelRowId__c = '12445567899';
        reviewTeam.IsLogicallyDeleted__c = false;
        reviewTeamList.add(reviewTeam);
        
        //Data Source set null.
        Review_Team__c reviewTeam1 = new Review_Team__c();
        //reviewTeam1.Data_Source__c = DataSourceModelData.Development.id;
        reviewTeam1.Product_Indication__c = ProductIndication.id;
        reviewTeam1.SubGroup__c = SubGroupModelData.DevelopmentSmpSubGroup.id;
        reviewTeam1.SiebelRowId__c = '12445567899';
        reviewTeam1.IsLogicallyDeleted__c = false;
        reviewTeamList.add(reviewTeam1);
        
        //Both Data Source and Sub Group set to null
        Review_Team__c reviewTeam3 = new Review_Team__c();
        //reviewTeam3.Data_Source__c = DataSourceModelData.Development.id;
        reviewTeam3.Product_Indication__c = ProductIndication1.id;
        //reviewTeam3.SubGroup__c = SubGroupModelData.DevelopmentSmpSubGroup.id;
        reviewTeam3.SiebelRowId__c = '12445567899';
        reviewTeam3.IsLogicallyDeleted__c = false;
        reviewTeamList.add(reviewTeam3);    
           
        try{
        insert reviewTeamList;
        }
        catch(Exception ex){
            system.debug('ex--'+ex);
            Boolean expectedExceptionThrown = ex.getMessage().contains('Invalid Review Team') ? true : false;
            System.AssertEquals(expectedExceptionThrown, true);
        }
        
        Test.stopTest();
    }
    
     private static testMethod void TestReviewTeamTriggerLogic1(){
        Test.startTest();
        //Creating data of ProductIndication.
        List<ProductIndication__c> ProductIndicationList = new List<ProductIndication__c>();
        ProductIndication__c ProductIndication = new ProductIndication__c(name= 'ABP 215 - Not Applicable' , Product__c=AmgenProductModel.getProductByName('ABP 215').id, 
            Indication__c=IndicationModel.getIndicationByName('Not Applicable').id, StartDate__c = null, EndDate__c = null);
        ProductIndicationList.add(ProductIndication);
        
        insert ProductIndicationList;
        
        //Creating data for Review Team 
        List<Review_Team__c> reviewTeamList = new List<Review_Team__c>();
        
        //Sub Group set Null
        Review_Team__c reviewTeam2 = new Review_Team__c();
        reviewTeam2.Data_Source__c = DataSourceModelData.Development.id;
        reviewTeam2.Product_Indication__c = ProductIndication.id;
        reviewTeam2.SiebelRowId__c = '12445567899';
        reviewTeam2.IsLogicallyDeleted__c = false;
        reviewTeamList.add(reviewTeam2);
        
        try{
        insert reviewTeamList;
        }
        catch(Exception ex){
            system.debug('ex1111--'+ex);
            Boolean expectedExceptionThrown = ex.getMessage().contains('Invalid Review Team') ? true : false;
            System.AssertEquals(expectedExceptionThrown, true);
        }
        
        Test.stopTest();
    }
    private static testMethod void TestReviewTeamTriggerLogic3(){
        Test.startTest();
        //Creating data of ProductIndication.
        List<ProductIndication__c> ProductIndicationList = new List<ProductIndication__c>();
        ProductIndication__c ProductIndication = new ProductIndication__c(name= 'ABP 215 - Not Applicable' , Product__c=AmgenProductModel.getProductByName('ABP 215').id, 
            Indication__c=IndicationModel.getIndicationByName('Not Applicable').id, StartDate__c = null, EndDate__c = null);
        ProductIndicationList.add(ProductIndication);
        
        insert ProductIndicationList;
        
        //Creating data for Review Team 
        List<Review_Team__c> reviewTeamList = new List<Review_Team__c>();
        
        //Both Data Source and Sub Group set to null
        Review_Team__c reviewTeam2 = new Review_Team__c();
        reviewTeam2.Product_Indication__c = ProductIndication.id;
        reviewTeam2.SiebelRowId__c = '12445567899';
        reviewTeam2.IsLogicallyDeleted__c = false;
        reviewTeamList.add(reviewTeam2);
        
        try{
        insert reviewTeamList;
        }
        catch(Exception ex){
            system.debug('ex2222--'+ex);
            Boolean expectedExceptionThrown = ex.getMessage().contains('invalid Review Team') ? true : false;
            System.AssertEquals(expectedExceptionThrown, true);
        }
        
        Test.stopTest();
    }
}