force-app/main/default/staticresources/python/Disappear/src/objects/Indication__c.object
<CustomObject>
    <fields>
        <fullName>IsLogicallyDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Expired</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SiebelRowId__c</fullName>
        <externalId>true</externalId>
        <label>Siebel RowId</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Indication</label>
    <nameField>
        <label>Indication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Indications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/ProdIndiObjective__c.object
<CustomObject>
    <fields>
        <fullName>End_date__c</fullName>
        <label>End date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IsLogicallyDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Expired</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsSelected__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A checkbox for Salesforce UI to communicate with backend
please do not store any data in this field</description>
        <label>IsSelected</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Indication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Indication</label>
        <referenceTo>ProductIndication__c</referenceTo>
        <relationshipLabel>Product Indication Objectives</relationshipLabel>
        <relationshipName>Product_Indication_Objectives</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SiebelRowId__c</fullName>
        <externalId>true</externalId>
        <label>SiebelRowId</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Product Indication Objective</label>
    <nameField>
        <label>Product Indication Objective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Indication Objectives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/ProductIndication__c.object
<CustomObject>
    <fields>
        <fullName>Indication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Indication</label>
        <referenceTo>Indication__c</referenceTo>
        <relationshipLabel>Product Indications</relationshipLabel>
        <relationshipName>Product_Indications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>AmgenProduct__c</referenceTo>
        <relationshipLabel>Product Indications</relationshipLabel>
        <relationshipName>Product_Indications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SiebelRowId__c</fullName>
        <externalId>true</externalId>
        <label>SiebelRowId</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Therapeutic_Area__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Therapeutic Area</label>
        <referenceTo>TherapeuticArea__c</referenceTo>
        <relationshipLabel>Product Indications</relationshipLabel>
        <relationshipName>Product_Indications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>isLogicallyDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Expired</label>
        <type>Checkbox</type>
    </fields>
    <label>Product Indication</label>
    <nameField>
        <label>ProductIndication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Indications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/ProdIndiObjectiveModel.cls
public class ProdIndiObjectiveModel {

    public static List<ProdIndiObjective__c> FindObjectivesByProductIndication(List<ProductIndication__c> productIndicationList) {
        List<Id> productIndicationIdList = new List<Id>();
        for(ProductIndication__c prodInd : productIndicationList) {
            productIndicationIdList.add(prodInd.id);
        }
        return FindObjectivesByProductIndication(productIndicationIdList);
    }
    
    public static List<ProdIndiObjective__c> FindObjectivesByProductIndication(List<Id> productIndicationIdList) {
        
        List<ProdIndiObjective__c> result = [
            select Name, start_date__c, End_date__c, Product_Indication__c, 
            Product_Indication__r.name, SiebelRowId__c, isSelected__c
            from ProdIndiObjective__c
            where Product_Indication__c in :productIndicationIdList
            and IsLogicallyDeleted__c = false
        ];
        
        return result;
    }
    
   private static Map<String, ProdIndiObjective__c> pProdIndiObjectiveNameMap = null;
     public static Map<String, ProdIndiObjective__c> ProdIndiObjectiveNameMap {
    get {
      if (pProdIndiObjectiveNameMap == null){
        pProdIndiObjectiveNameMap = getProdIndiObjectivMapByName();
      }
      return pProdIndiObjectiveNameMap;
    }
  }
   public static Map<String, ProdIndiObjective__c> getProdIndiObjectivMapByName() {
    Map<String, ProdIndiObjective__c> result = new Map<String, ProdIndiObjective__c>();
    for(ProdIndiObjective__c prodIndO : ProductIndiObjectiveList){
      result.put(prodIndO.Name, prodIndO);
    }
  
    return result;
  }
  private static List<ProdIndiObjective__c> pProductIndiObjectiveList = null;
  public static List<ProdIndiObjective__c> ProductIndiObjectiveList{
      get {
          if(pProductIndiObjectiveList == null){
              pProductIndiObjectiveList=getAllProductIndiObjectives();
          }
      
      return pProductIndiObjectiveList;
    }  
  }
  public static List<ProdIndiObjective__c> getAllProductIndiObjectives(){
      List<ProdIndiObjective__c> result = [
            select Name, start_date__c, End_date__c, Product_Indication__c,
            Product_Indication__r.name, SiebelRowId__c, isSelected__c
            from ProdIndiObjective__c
            where isLogicallyDeleted__c = false
      ];
      return result;
  }
  private static List<ProductIndication__c> pProductIndicationList = null;
  public static List<ProductIndication__c> ProductIndicationList{
    get {
      if ( pProductIndicationList == null){
        pProductIndicationList = getAllProductIndications();
      }
      
      return pProductIndicationList;
    }
  }
   public static List<ProductIndication__c> getAllProductIndications() {
     List<ProductIndication__c>  result = [
       select id, Name, Product__c, Indication__c, Therapeutic_Area__c
       from ProductIndication__c
       where isLogicallyDeleted__c = false
       order by Name
     ];
     system.debug('result:'+result);
     return result;
  }
  
}