force-app/main/default/staticresources/python/Disappear/src/objects/InflightPubsAtGoLive__c.object
<CustomObject>
    <description>List of inflight pub at 1.0 golive
Import data for batch manipulation

should have 32 rows</description>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>InflightPubsAtGoLive</relationshipLabel>
        <relationshipName>InflightPubsAtGoLive</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>InflightPubsAtGoLive</label>
    <nameField>
        <displayFormat>IFPAGL-{000}</displayFormat>
        <label>InflightPubsAtGoLive Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>InflightPubsAtGoLive</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <recordTypes>
        <fullName>Execute</fullName>
        <active>true</active>
        <label>Execute</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PubReviewTeam__c.object
<CustomObject>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipName>PubReviewTeams</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reviewer_Status__c</fullName>
        <label>Vote</label>
        <picklist>
            <picklistValues>
                <fullName>Reviewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reviewed With Comments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discussion Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withheld</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Comments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vote Not Available</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Primary / Informed</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Notify</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Publication Review Team Member</label>
    <nameField>
        <displayFormat>PRT-{000000000}</displayFormat>
        <label>PubReviewTeamId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication Review Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/BatchInflightPubStatusAdj2.cls
global class BatchInflightPubStatusAdj2 extends BatchBase 
    implements Database.Batchable<SObject>,Database.Stateful {
    public String SOQL = 'select Publication__c, Publication__r.name from InflightPubsAtGoLive__c where Publication__r.name <> \'Pub-Id-033625\'  '; 
    
    public BatchInflightPubStatusAdj2() {
        super();
        if ( Test.isRunningTest()){
            SOQL = SOQL + ' limit 1';
        }
        AddMessage(SOQL);
        system.debug(SOQL);
    }
    
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        batchableContext = BC;
        batchName = 'BatchInflightPubStatusAdj2';
        System.Debug(SOQL);
        return Database.getQueryLocator(SOQL);
    }

    global void execute(Database.BatchableContext BC, List<InflightPubsAtGoLive__c> pubs){
        InflightPubAdj2(pubs);
    }

    global void finish(Database.BatchableContext BC){
        SendBatchCompletionEmail();
    }
    
    //BatchInflightPubStatusAdj1.runNow();
    public static void runNow(){
        BatchInflightPubStatusAdj2 batch = new BatchInflightPubStatusAdj2();
        Database.executeBatch(batch, 2);
    }
    
    public static void InflightPubAdj2(List<InflightPubsAtGoLive__c> inflightPubList) {
        for(InflightPubsAtGoLive__c inflightPub : inflightPubList) {
            InflightPubAdj2OnePub(inflightPub.Publication__c);
        }
    }
    

    public static void InflightPubAdj2OnePub(Id pubId){
        AppearPubModel activePub = new AppearPubModel(pubId);
        
        List<PubReviewTeam__c> reviewers = activePub.PubReviewTeam.PubReviewTeamMembers;
        
        List<PubReviewTeam__c> reviewersToUpdate = new List<PubReviewTeam__c> ();
        
        for(PubReviewTeam__c reviewer : reviewers) {
            if ( reviewer.Type__c == 'Primary') {
                if ( reviewer.Reviewer_Status__c == 'Approved') {
                    reviewer.Reviewer_Status__c = 'Reviewed';
                    reviewersToUpdate.add(reviewer);
                } else if ( reviewer.Reviewer_Status__c == 'Approved with Comments') {
                    reviewer.Reviewer_Status__c = 'Reviewed With Comments';
                    reviewersToUpdate.add(reviewer);
                }                   
            }
        }
        if (reviewersToUpdate.size() > 0 ) {
            update reviewersToUpdate;
        }

        
        AppLogModel.flushLogs();
    }
    
     

//////////////////////////////////////////  unit test /////////////////////////////////////
    @isTest(seeAllData=true)
    private static void unitTest() {
        list<InflightPubsAtGoLive__c> ifpb = new list<InflightPubsAtGoLive__c>();
        id pub;
        BatchInflightPubStatusAdj2.InflightPubAdj2(ifpb);
        BatchInflightPubStatusAdj2.InflightPubAdj2onePub(pub);
        BatchInflightPubStatusAdj2.runNow();
        
        
        
        
    } 
    

}