force-app/main/default/staticresources/python/Disappear/src/objects/InflightPubsAtGoLive__c.object
<CustomObject>
    <description>List of inflight pub at 1.0 golive
Import data for batch manipulation

should have 32 rows</description>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>InflightPubsAtGoLive</relationshipLabel>
        <relationshipName>InflightPubsAtGoLive</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>InflightPubsAtGoLive</label>
    <nameField>
        <displayFormat>IFPAGL-{000}</displayFormat>
        <label>InflightPubsAtGoLive Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>InflightPubsAtGoLive</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <fields>
        <fullName>PubStatus__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Current status of this publication</description>
        <label>PubStatus</label>
        <referenceTo>PubStatus__c</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <recordTypes>
        <fullName>Execute</fullName>
        <active>true</active>
        <label>Execute</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PubReviewTeam__c.object
<CustomObject>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipName>PubReviewTeams</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Publication Review Team Member</label>
    <nameField>
        <displayFormat>PRT-{000000000}</displayFormat>
        <label>PubReviewTeamId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication Review Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PubStatus__c.object
<CustomObject>
    <description>List of Status for a Publication - Target Date / Revised Date / Actual Date
Will be used for planning</description>
    <fields>
        <fullName>ActualDate__c</fullName>
        <label>Actual Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Status</label>
        <referenceTo>Status__c</referenceTo>
        <relationshipName>PubStatuses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publication Status</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>PubStatus Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Status__c.object
<CustomObject>
    <label>Status</label>
    <nameField>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/BatchInflightPubStatusAdj1.cls
global class BatchInflightPubStatusAdj1 extends BatchBase 
	implements Database.Batchable<SObject>,Database.Stateful {
   	public String SOQL = 'select Publication__c, Publication__r.name from InflightPubsAtGoLive__c where Publication__r.name <> \'Pub-Id-033625\'  '; 
   	
	public BatchInflightPubStatusAdj1() {
		super();
    	if ( Test.isRunningTest()){
    		SOQL = SOQL + ' limit 1';
    	}
    	AddMessage(SOQL);
        system.debug(SOQL);
	}
	
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        batchableContext = BC;
        batchName = 'BatchInflightPubStatusAdj1';
        System.Debug(SOQL);
        return Database.getQueryLocator(SOQL);
    }

    global void execute(Database.BatchableContext BC, List<InflightPubsAtGoLive__c> pubs){
		InflightPubAdj1(pubs);
    }

    global void finish(Database.BatchableContext BC){
		SendBatchCompletionEmail();
	}
	
	//BatchInflightPubStatusAdj1.runNow();
	public static void runNow(){
    	BatchInflightPubStatusAdj1 batch = new BatchInflightPubStatusAdj1();
        Database.executeBatch(batch, 2);
	}
	
	public static void InflightPubAdj1(List<InflightPubsAtGoLive__c> inflightPubList) {
		for(InflightPubsAtGoLive__c inflightPub : inflightPubList) {
			InflightPubAdj1OnePub(inflightPub.Publication__c);
		}
	}
	

	public static void InflightPubAdj1OnePub(Id pubId){
		AppearPubModel activePub = new AppearPubModel(pubId);
		
		if ( activePub.CurrentStatus == 'Assigned to FPRC') {
			List<PubReviewTeam__c> reviewers = activePub.PubReviewTeam.PubReviewTeamMembers;
			if ( reviewers.size() > 0) {
				AppLogModel.LogINfo('BatchInflightPubStatusAdj1', 'Inserting Routed Status for this Pub '+activePub.PubName);
				
				for(PubStatus__c pubstatus : activePub.PubStatus.PubStatusList) {
				
					if ( pubstatus.status__c == statusModel.InFpr.id) {
						DateTime routeDateTime = pubstatus.ActualDate__c;
						routeDateTime = routeDateTime.addSeconds(1);
						activePub.PubStatus.InsertRoutePubStatus(routeDateTime);
					}
				}
			}
		}
		
		AppLogModel.flushLogs();
	}
	
	 

//////////////////////////////////////////  unit test /////////////////////////////////////
	@isTest(seeAllData=true)
	private static void unitTest() {
		
		BatchInflightPubStatusAdj1.runNow();
	} 
	

}