force-app/main/default/staticresources/python/Disappear/src/objects/Journal__c.object
<CustomObject>
    <fields>
        <fullName>JournalName255__c</fullName>
        <label>JournalName255</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Journal</label>
    <nameField>
        <displayFormat>Journal-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Meeting__c.object
<CustomObject>
    <description>Used for the Meeting target and to maintain Meeting related Data</description>
    <fields>
        <fullName>MeetingName255__c</fullName>
        <label>MeetingName255</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Meeting</label>
    <nameField>
        <displayFormat>MTG-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <fields>
        <fullName>Country__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Country is required if SubGroup selected is LACAN, JAPAC, EEMEA for &apos;Global Development&apos; Data Source</inlineHelpText>
        <label>Country Link</label>
        <referenceTo>Country__c</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Status_FormulaField__c</fullName>
        <description>Used to make Current Status a &quot;read only&quot; field</description>
        <formula>PubStatus__r.Status__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_SubmissionCycle_Id_Formula__c</fullName>
        <formula>PubStatus__r.Submission_Cycle__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current Submission Cycle Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Target__c</fullName>
        <description>The Current Target field will also be used to populate the Target field for a new Submission Cycle.
This field should NEVER be moved to a formula</description>
        <inlineHelpText>This field is populated automatically by using the &quot;Target&quot; button on the Details tile.  If the desired target is NOT found using the Target button, please use the &quot;Target Not Found&quot; field below.</inlineHelpText>
        <label>Current Target</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GPP_Type__c</fullName>
        <description>Used for Classification of GPP publication and mandatory for if Publication is GPP type.</description>
        <label>Publication Classification</label>
        <picklist>
            <picklistValues>
                <fullName>CSP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSP Encore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Deliverable</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Journal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Journal</label>
        <referenceTo>Journal__c</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MTA__c</fullName>
        <label>MTA #</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Meeting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Meeting</inlineHelpText>
        <label>Meeting</label>
        <referenceTo>Meeting__c</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PubStatus__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Current status of this publication</description>
        <label>PubStatus</label>
        <referenceTo>PubStatus__c</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RAE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Responsible Amgen Employee (RAE)</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SponsorDept_Pick__c</fullName>
        <label>Sponsoring Amgen Department</label>
        <picklist>
            <picklistValues>
                <fullName>Center for Observational Research (CfOR)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clinical Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discovery Research</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global Government Affairs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global Health Economics (GHE)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global Medical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global Regulatory Affairs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global Safety</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global Scientific Affairs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Global Value, Access, and Policy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufacturing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Translational Sciences</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SponsorOrg_Pick__c</fullName>
        <label>Sponsoring Organization</label>
        <picklist>
            <picklistValues>
                <fullName>Amgen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Astellas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AstraZeneca/MedImmune</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cytokinetics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Daiichi-Sankyo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Genentech, Inc.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GlaxoSmithKline (GSK)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kirin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Novartis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pfizer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Servier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Takeda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UCB Pharma</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SubGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Link Publication to a SubGroup - which we can find the DataSource for the publication.
This link is very important for the auto population of FPR Reviewer.</description>
        <inlineHelpText>For purposes of FPR routing, functional group from which publication content/or data was orignated. Enter one of these selections - Research, Development, Operations - before clicking the Lookup icon.  Then select a SubGroup from the Search Results list.</inlineHelpText>
        <label>SubGroup Link</label>
        <referenceTo>SubGroup__c</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target_Type__c</fullName>
        <description>Default TargetType for the next Submission Cycle</description>
        <label>Target Type</label>
        <picklist>
            <picklistValues>
                <fullName>Journal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>isISS__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ISS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isISStext__c</fullName>
        <description>Whenever the isISS flag is checked, user will enter value in this field.
Changed to ISS# as per defect 167</description>
        <label>ISS #</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isPlanning__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Part of GPP</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>is_MTA__c</fullName>
        <defaultValue>false</defaultValue>
        <label>MTA</label>
        <type>Checkbox</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <recordTypes>
        <fullName>Execute</fullName>
        <active>true</active>
        <label>Execute</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PubStatus__c.object
<CustomObject>
    <description>List of Status for a Publication - Target Date / Revised Date / Actual Date
Will be used for planning</description>
    <fields>
        <fullName>IsCurrentSubmissionCycleForPub__c</fullName>
        <formula>Publication_id__r.Current_SubmissionCycle_Id_Formula__c = Submission_Cycle__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>IsCurrentSubmissionCycleForPub</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Journal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Target to which Journal</description>
        <label>Journal</label>
        <referenceTo>Journal__c</referenceTo>
        <relationshipName>PubStatuses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Meeting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Target a Meeting</description>
        <label>Meeting</label>
        <referenceTo>Meeting__c</referenceTo>
        <relationshipName>PubStatuses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publication_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication_id</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipName>PubStatus</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Submission_Cycle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Submission Cycle</label>
        <referenceTo>SubmissionCycle__c</referenceTo>
        <relationshipName>Pub_Statuses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publication Status</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>PubStatus Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/SubmissionCycle__c.object
<CustomObject>
    <description>record name will be PubId-{0000000}-SubCycle-{00}</description>
    <fields>
        <fullName>Journal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Journal</label>
        <referenceTo>Journal__c</referenceTo>
        <relationshipLabel>Submission Cycles</relationshipLabel>
        <relationshipName>Submission_Cycles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Meeting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Meeting</label>
        <referenceTo>Meeting__c</referenceTo>
        <relationshipLabel>Submission Cycles</relationshipLabel>
        <relationshipName>Submission_Cycles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TargetLabelFormula__c</fullName>
        <formula>IF( TEXT(Target_Type__c) = &quot;meeting&quot;,  Meeting__r.MeetingName255__c ,  Journal__r.JournalName255__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Target Label</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Type__c</fullName>
        <label>Target Type</label>
        <picklist>
            <picklistValues>
                <fullName>Journal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Submission Cycle</label>
    <nameField>
        <label>Submission Cycle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submission Cycles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/update_PubCurrentTargetBatch.cls
global class update_PubCurrentTargetBatch implements Database.Batchable<SObject>,Database.Stateful {
      public static set<id> idSet= getIdSetforQueryString();
    public static string SOQL = 'SELECT Name,Id,Current_Status_FormulaField__c,Current_SubmissionCycle_Id_Formula__c,isISStext__c,Current_Target__c,isPlanning__c,GPP_Type__c,RAE__c,SponsorDept_Pick__c,SponsorOrg_Pick__c,isISS__c,is_MTA__c ,MTA__c,SubGroup__r.Name,Country__c,PubStatus__r.Submission_Cycle__r.TargetLabelFormula__c,PubStatus__r.Submission_Cycle__c,PubStatus__r.IsCurrentSubmissionCycleForPub__c,PubStatus__r.Submission_Cycle__r.Meeting__r.MeetingName255__c,PubStatus__r.Submission_Cycle__r.Journal__r.JournalName255__c,PubStatus__c,Target_Type__c FROM Publication__C WHERE Id in:idSet';
    
    //public static string str = 'SELECT Current_SubmissionCycle_Id_Formula__c,Id,Current_Target__c,PubStatus__r.Submission_Cycle__r.TargetLabelFormula__c,PubStatus__r.Submission_Cycle__c,PubStatus__r.IsCurrentSubmissionCycleForPub__c,PubStatus__r.Submission_Cycle__r.Meeting__r.MeetingName255__c,PubStatus__r.Submission_Cycle__r.Journal__r.JournalName255__c,PubStatus__c,Target_Type__c FROM Publication__C where gpp_type__c != null and Target_Type__c !=NULL AND Current_Status_FormulaField__c not in ('+'\'Cancelled\''+','+'\'Published/Presented\''+')';
    private static set<id> getIdSetforQueryString() {
        set<id> pubIdSet = new set<id>();
         
        List<Publication__c> pubList = [SELECT Current_SubmissionCycle_Id_Formula__c,Id,Current_Target__c,PubStatus__r.Submission_Cycle__r.TargetLabelFormula__c,PubStatus__r.Submission_Cycle__c,PubStatus__r.IsCurrentSubmissionCycleForPub__c,PubStatus__r.Submission_Cycle__r.Meeting__r.MeetingName255__c,PubStatus__r.Submission_Cycle__r.Journal__r.JournalName255__c,PubStatus__c,Target_Type__c FROM Publication__C WHERE GPP_TYPE__c != null and Target_Type__c !=NULL AND Current_Status_FormulaField__c not in ('Cancelled','Published/Presented')];
        for(publication__c plBU: pubList){
            if(plBU.Target_Type__c == 'Meeting' || plBU.Target_Type__c == 'Journal'){
            if( plBU.Current_Target__c != plBU.PubStatus__r.Submission_Cycle__r.TargetLabelFormula__c
                                   &&
                                   plBU.PubStatus__r.Submission_Cycle__c == plBU.Current_SubmissionCycle_Id_Formula__c
                                   &&
                                   plBU.PubStatus__r.IsCurrentSubmissionCycleForPub__c == true){
                    pubIdSet.add(plBU.Id); 
                                           
                }
            }   
        
          /*  else if(plBU.Target_Type__c == 'Journal'){
                if( plBU.Current_Target__c != plBU.PubStatus__r.Submission_Cycle__r.TargetLabelFormula__c 
                                       &&
                                       plBU.PubStatus__r.Submission_Cycle__c == plBU.Current_SubmissionCycle_Id_Formula__c
                                       &&
                                       plBU.PubStatus__r.IsCurrentSubmissionCycleForPub__c == true){
                 	pubIdSet.add(plBU.Id); 
                }
            }*/
        }
        system.debug('-----'+pubIdSet.size());
        return pubIdSet;
    }
   
    global Database.QueryLocator start(Database.BatchableContext BC) {
        System.Debug('update_PubCurrentTarget :: QueryLocator ' + SOQL);
        return Database.getQueryLocator(SOQL);
    }
    
    
    global void execute(Database.BatchableContext BC, List<Publication__c> pubListBatchUpdate){
    	
        System.debug('update_PubCurrentTarget :: Execute' + pubListBatchUpdate);
        System.debug('update_PubCurrentTarget :: Execute :: pubListBatchUpdateSize' + pubListBatchUpdate.size());
        List<Database.Saveresult> sr;
        List<Publication__c> list2Update = new List<Publication__c>();
        Boolean invalidPubData = false;
        
        for(Publication__c plBU: pubListBatchUpdate){
        System.debug('$$$$PubName$$$$'+plBU.Name);
        //1st Val : Country_Required
        if((plBU.SubGroup__r.Name == 'Global Dev - Europe' || plBU.SubGroup__r.Name == 'Global Dev - Intercont'|| plBU.SubGroup__r.Name == 'Global Dev - JAPAC' || plBU.SubGroup__r.Name == 'Global Dev - US' || plBU.isPlanning__c == true) && plBU.Country__c == NULL ){
            invalidPubData = true;
            System.debug('update_PubCurrentTarget :: 1st Val : Country_Required'+plBU.Name);
        }
        /*    
        //2nd Val : GPP_Type_Required         
        if(plBU.GPP_Type__c == '' || plBU.GPP_Type__c == NULL){
            invalidPubData = true; //second Validation update as part of Appear Enhancement 2017 R1
            System.debug('update_PubCurrentTarget :: 2nd Val : GPP_Type_Required'+plBU.Name);
        }  */        
        
        //3rd val : ISS_Required
        if(plBU.isISS__c == true && plBU.isISStext__c == ''){
            invalidPubData = true;
            System.debug('update_PubCurrentTarget :: 3rd val : ISS_Required'+plBU.Name);
        }
        
        //4th val : MTA_Required
        if(plBU.is_MTA__c == true && plBU.MTA__c == ''){
            invalidPubData = true;
            System.debug('update_PubCurrentTarget :: 4th val : MTA_Required'+plBU.Name);
        }
        
        //5th Val : PST_Approval_Date :not req
        //6th Val : Rejected_publication_is_read_only : not req
        //8th Val : Restrict_Pub_Classification_Field_Update : not required
        
        //7th Val : Responsible_Amgen_Employee        //9th Val : Sponsoring_Amgen_Department_Required        //10th Val : Sponsoring_Organization_required  
        if(plBU.isPlanning__c == true && (plBU.RAE__c == NULL || plBU.SponsorDept_Pick__c == '' || plBU.SponsorOrg_Pick__c == '')){
            invalidPubData = true;
            System.debug('update_PubCurrentTarget :: 7th/8th/9th Val '+plBU.Name);
        }                
        
        if(invalidPubData == false){
        //update logic :: starts
        if(plBU.Target_Type__c == 'Meeting'){
        if( plBU.Current_Target__c != plBU.PubStatus__r.Submission_Cycle__r.TargetLabelFormula__c
                               &&
                               plBU.PubStatus__r.Submission_Cycle__c == plBU.Current_SubmissionCycle_Id_Formula__c
                               &&
                               plBU.PubStatus__r.IsCurrentSubmissionCycleForPub__c == true){
            plBU.Current_Target__c = plBU.PubStatus__r.Submission_Cycle__r.Meeting__r.MeetingName255__c; 
            list2Update.add(plBU); 
        }
        }   
    
        else if(plBU.Target_Type__c == 'Journal'){
        if( plBU.Current_Target__c != plBU.PubStatus__r.Submission_Cycle__r.TargetLabelFormula__c 
                               &&
                               plBU.PubStatus__r.Submission_Cycle__c == plBU.Current_SubmissionCycle_Id_Formula__c
                               &&
                               plBU.PubStatus__r.IsCurrentSubmissionCycleForPub__c == true){
            plBU.Current_Target__c = plBU.PubStatus__r.Submission_Cycle__r.Journal__r.JournalName255__c;
            list2Update.add(plBU);
        }
        }//update logic ends
        
        }//boolean check
        
        
        }   
       System.debug('THE PUBLIST TO UPDATE' + list2Update.size());
       
        try{
        if(!list2Update.isEmpty()){
            sr = database.update(list2Update, false);
          }
        }
        catch(Asyncexception ee){
            System.debug('AsyncException :: Debug' + ee);
            throw ee;
        }
        catch(DMLException dmlE){
            System.debug('DMLExecute :: Debug' + dmlE);
            throw dmlE;
        }
       
    }
    
    
    global void finish(Database.BatchableContext BC){
        System.debug('update_PubCurrentTarget :: Finish');
    }
}