force-app/main/default/staticresources/python/Disappear/src/objects/Journal__c.object
<CustomObject>
    <fields>
        <fullName>JournalName255__c</fullName>
        <label>JournalName255</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Journal</label>
    <nameField>
        <displayFormat>Journal-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Meeting__c.object
<CustomObject>
    <description>Used for the Meeting target and to maintain Meeting related Data</description>
    <fields>
        <fullName>Acronym__c</fullName>
        <label>Acronym</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ends__c</fullName>
        <label>Ends</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MeetingName255__c</fullName>
        <label>MeetingName255</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Starts__c</fullName>
        <label>Starts</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <label>Venue</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>Meeting</label>
    <nameField>
        <displayFormat>MTG-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Status__c.object
<CustomObject>
    <label>Status</label>
    <nameField>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/PubStatusNewViewModel.cls
global class PubStatusNewViewModel {


    ///////////////  JS Remote support //////////////////
    @remoteAction
    global static List<IdNameDTO> findTargetsByName(string targetType, string startWith){       
        List<IdNameDTO> results = new List<IdNameDTO>();
        
        System.debug('TargetType is '+targetType+' and startWith is '+startWith);
        
        if ( targetType == 'journal') {
            List<Journal__c> journals = JournalModel.findJournalsByName( startWith);
            for(Journal__c j : journals) {
                results.add(new IdNameDTO((String)j.id, j.JournalName255__c));
            }
        } else { //targetType == 'meeting'
            List<Meeting__c> meetings = MeetingModel.findMeetingsByName( startWith);
            //boolean shouldCheckMeetings = (!ProfileModel.isSysAdmin && !ProfileModel.isAppearBusinessAdmin);            
            for(Meeting__c m : meetings) {
            	/*if (shouldCheckMeetings && m.Ends__c != null && m.Ends__c < DateTime.now()) { //CR151- only return meeting with end date greater than todays date
        			continue;
            	}*/
            	String uniqueMtgName = MeetingModel.uniqueMeetingName(
            		m.MeetingName255__c,m.Starts__c, m.Ends__c,
            		m.Acronym__c,m.Venue__c );
            	
                results.add(new IdNameDTO((String)m.id, uniqueMtgName));
            }
        } 
        
        return results;     
    }

	@remoteAction
	global static List<IdNameDTO> findDeptStatusByName( string startWith){		
		List<IdNameDTO> results = new List<IdNameDTO>();
		
		List<Status__c> status = StatusModel.findStatusByTypeName(StatusModel.DeptStatus, startWith);
		for(Status__c s : status) {
			results.add(new IdNameDTO((String)s.id, s.name));
		}

		return results;		
	}

}