force-app/main/default/staticresources/python/Disappear/src/objects/Journal__c.object
<CustomObject>
    <fields>
        <fullName>Journal_Name__c</fullName>
        <description>Swapnil indicated that the vendor specified 500 as the length of the Journal Name.</description>
        <label>Journal Name</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <label>Journal</label>
    <nameField>
        <displayFormat>Journal-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Meeting__c.object
<CustomObject>
    <description>Used for the Meeting target and to maintain Meeting related Data</description>
    <fields>
        <fullName>Acronym__c</fullName>
        <label>Acronym</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ends__c</fullName>
        <label>Ends</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MeetingName255__c</fullName>
        <label>MeetingName255</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Meeting_Name__c</fullName>
        <label>Meeting Name</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Starts__c</fullName>
        <label>Starts</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Venue__c</fullName>
        <label>Venue</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>Meeting</label>
    <nameField>
        <displayFormat>MTG-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <fields>
        <fullName>Journal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Journal</label>
        <referenceTo>Journal__c</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Meeting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Meeting</inlineHelpText>
        <label>Meeting</label>
        <referenceTo>Meeting__c</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PubStatus__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Current status of this publication</description>
        <label>PubStatus</label>
        <referenceTo>PubStatus__c</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target_Type__c</fullName>
        <description>Default TargetType for the next Submission Cycle</description>
        <label>Target Type</label>
        <picklist>
            <picklistValues>
                <fullName>Journal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PubStatus__c.object
<CustomObject>
    <description>List of Status for a Publication - Target Date / Revised Date / Actual Date
Will be used for planning</description>
    <fields>
        <fullName>Journal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Target to which Journal</description>
        <label>Journal</label>
        <referenceTo>Journal__c</referenceTo>
        <relationshipName>PubStatuses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Meeting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Target a Meeting</description>
        <label>Meeting</label>
        <referenceTo>Meeting__c</referenceTo>
        <relationshipName>PubStatuses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Submission_Cycle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Submission Cycle</label>
        <referenceTo>SubmissionCycle__c</referenceTo>
        <relationshipName>Pub_Statuses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publication Status</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>PubStatus Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/SubmissionCycle__c.object
<CustomObject>
    <description>record name will be PubId-{0000000}-SubCycle-{00}</description>
    <fields>
        <fullName>Journal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Journal</label>
        <referenceTo>Journal__c</referenceTo>
        <relationshipLabel>Submission Cycles</relationshipLabel>
        <relationshipName>Submission_Cycles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Meeting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Meeting</label>
        <referenceTo>Meeting__c</referenceTo>
        <relationshipLabel>Submission Cycles</relationshipLabel>
        <relationshipName>Submission_Cycles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Submission Cycles</relationshipLabel>
        <relationshipName>Submission_Cycles</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Submission_Cycle_Num__c</fullName>
        <label>Submission Cycle #</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Target_Type__c</fullName>
        <label>Target Type</label>
        <picklist>
            <picklistValues>
                <fullName>Journal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Submission Cycle</label>
    <nameField>
        <label>Submission Cycle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submission Cycles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/SubmissionCycleModel.cls
public with sharing class SubmissionCycleModel {
    ////////  members ////////////////////////
    private Id PubId;
    private PubStatus__c pubStatus;
    
    public void reloadCurrentSubmissionCycle() {
        pCurrentSubmissionCycle = null;
    }
    private SubmissionCycle__c pCurrentSubmissionCycle = null;
    public SubmissionCycle__c CurrentSubmissionCycle{
        get {
            if ( pCurrentSubmissionCycle == null){
                pCurrentSubmissionCycle = FindCurrentSubmissionCycle();
            }
            return pCurrentSubmissionCycle;
        }
        set {
            pCurrentSubmissionCycle = value;
        }
    }
    
    private transient Map<Id, SubmissionCycle__c> pSubmissionCycleMapeById = null;
    public Map<Id, SubmissionCycle__c> SubmissionCycleMapeById {
        get {
            if (pSubmissionCycleMapeById == null){
                pSubmissionCycleMapeById = new Map<Id, SubmissionCycle__c>();
                for(SubmissionCycle__c cycle : SubmissionCycleList) {
                    pSubmissionCycleMapeById.put(cycle.id, cycle);
                }
            }
            return pSubmissionCycleMapeById;
        }
    }
    
    private transient Map<Integer, SubmissionCycle__c> pSubmissionCycleMap = null;
    public Map<integer, SubmissionCycle__c> SubmissionCycleMap {
        get {
            if (pSubmissionCycleMap == null) {
                pSubmissionCycleMap = new Map<Integer,SubmissionCycle__c>();
                for(SubmissionCycle__c s : SubmissionCycleList){
                    pSubmissionCycleMap.put(Integer.ValueOf(s.Submission_Cycle_Num__c),s);
                }
            }
            return pSubmissionCycleMap;
        }
    }

    
    private List<SubmissionCycle__c> pSubmissionCycleList = null;
    public  List<SubmissionCycle__c> SubmissionCycleList {
        get {
            if ( pSubmissionCycleList == null ){
                pSubmissionCycleList = getSubmissionCycleList(PubId);
            }
            return pSubmissionCycleList;
        }
    }
    
   
     public List<SelectOption> SubmissionCycleOptions {
        get {
            List<SelectOption> result = new List<SelectOption>();
            for( SubmissionCycle__c cycle : SubmissionCycleList) {
                result.add(new selectOption(cycle.id, String.ValueOf(cycle.Submission_Cycle_Num__c)));
            }
            return result;
        }
    } 
    
    private string pTargetLabel = null;
    public string TargetLabel {
        get {
            if (pTargetLabel == null) {
                pTargetLabel = getCurrentTargetLabel();
            }
            return pTargetLabel;
        }
    }
    
    public string getCurrentTargetLabel () {
    	if (CurrentSubmissionCycle == null || CurrentSubmissionCycle.Target_Type__c == null) {
    		return '';
    	} else if ( CurrentSubmissionCycle.Target_Type__c == 'Meeting' )  {
            return CurrentSubmissionCycle.Meeting__r.Meeting_Name__c;
        } else if ( CurrentSubmissionCycle.Target_Type__c == 'Journal' )  {
            return CurrentSubmissionCycle.Journal__r.Journal_Name__c;
        } else {
            return 'unknown target for targetType : '+ CurrentSubmissionCycle.Target_Type__c;
        }
    }
    
    /*
        		String uniqueMeetingName = MeetingModel.uniqueMeetingName(
            		CurrentSubmissionCycle.Meeting__r.MeetingName255__c,
            		CurrentSubmissionCycle.Meeting__r.Starts__c, 
            		CurrentSubmissionCycle.Meeting__r.Ends__c,
            		CurrentSubmissionCycle.Meeting__r.Acronym__c,
            		CurrentSubmissionCycle.Meeting__r.Venue__c );
    */
    
    
    ////// constructor ////////////////////

    public SubmissionCycleModel(Id PubId, PubStatus__c pubStatus){
        this.PubId = PubId;
        this.PubStatus = pubStatus;
    }   
    
    ////// public methods ////////////////
    
    public SubmissionCycle__c FindCurrentSubmissionCycle() {
        if ( pubStatus == null || SubmissionCycleList.size() == 0){
            return getSubmissionCycleByNum(1);
        } else {
        	Id currentSubCycleId = pubStatus.Submission_Cycle__c;
        	return SubmissionCycleMapeById.get(currentSubCycleId);
        }
    }
    
    
    public static List<SubmissionCycle__c> getSubmissionCycleList(id PubId){
        List<SubmissionCycle__c> scs = [
            Select s.Submission_Cycle_Num__c, s.Publication__c, s.Name, s.Id,
            target_Type__c, journal__c, journal__r.Journal_Name__c,
            meeting__c, meeting__r.MeetingName255__c, 
            meeting__r.meeting_name__c,
            meeting__r.Starts__c, meeting__r.Ends__c, 
            meeting__r.Acronym__c, meeting__r.Venue__c
            From SubmissionCycle__c s
            where Publication__c = :PubId
            order by s.Name 
        ];
        return scs;
    }
      
    public static Map<id, SubmissionCycle__c> getSubmissionCycleMap(id PubId){
         Map<id, SubmissionCycle__c> submissionCycleMap = new Map<id, SubmissionCycle__c>();
         for(SubmissionCycle__c scs : getSubmissionCycleList(pubId)) {
         	submissionCycleMap.put(scs.id, scs);
         }
         return submissionCycleMap;
    }
    
    //return the SubmissionCycle__c record for the cycle requested
    //if the record does not exists - it will be created on the fly.
    public SubmissionCycle__c getSubmissionCycleByNum( integer SubmissionCycleNum){
        if ( !SubmissionCycleMap.containsKey(SubmissionCycleNum)) {
            SubmissionCycle__c subCycle = new SubmissionCycle__c();
            subCycle.Submission_Cycle_num__c = SubmissionCycleNum;
            subCycle.Publication__c = PubId;
            insert SubCycle;
            
            System.assertNotEquals(null, SubCycle.id);
            System.assertNotEquals(null, SubCycle.Submission_Cycle_Num__c);
            pSubmissionCycleMap.put(SubmissionCycleNum,subCycle);
            return subCycle;
        } else {
            return SubmissionCycleMap.get(SubmissionCycleNum);
        }
    }
 
}