force-app/main/default/staticresources/python/Disappear/src/objects/Journal__c.object
<CustomObject>
    <fields>
        <fullName>JournalName255__c</fullName>
        <label>JournalName255</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Journal_Name__c</fullName>
        <description>Swapnil indicated that the vendor specified 500 as the length of the Journal Name.</description>
        <label>Journal Name</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <label>Journal</label>
    <nameField>
        <displayFormat>Journal-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Meeting__c.object
<CustomObject>
    <description>Used for the Meeting target and to maintain Meeting related Data</description>
    <fields>
        <fullName>MeetingName255__c</fullName>
        <label>MeetingName255</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Meeting_Name__c</fullName>
        <label>Meeting Name</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <label>Meeting</label>
    <nameField>
        <displayFormat>MTG-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Meetings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <fields>
        <fullName>Current_Target__c</fullName>
        <description>The Current Target field will also be used to populate the Target field for a new Submission Cycle.
This field should NEVER be moved to a formula</description>
        <inlineHelpText>This field is populated automatically by using the &quot;Target&quot; button on the Details tile.  If the desired target is NOT found using the Target button, please use the &quot;Target Not Found&quot; field below.</inlineHelpText>
        <label>Current Target</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Journal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Journal</label>
        <referenceTo>Journal__c</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Meeting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Meeting</inlineHelpText>
        <label>Meeting</label>
        <referenceTo>Meeting__c</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PubStatus__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Current status of this publication</description>
        <label>PubStatus</label>
        <referenceTo>PubStatus__c</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target_Type__c</fullName>
        <description>Default TargetType for the next Submission Cycle</description>
        <label>Target Type</label>
        <picklist>
            <picklistValues>
                <fullName>Journal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PubStatus__c.object
<CustomObject>
    <description>List of Status for a Publication - Target Date / Revised Date / Actual Date
Will be used for planning</description>
    <fields>
        <fullName>IsCurrentSubmissionCycleForPub__c</fullName>
        <formula>Publication_id__r.Current_SubmissionCycle_Id_Formula__c = Submission_Cycle__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>IsCurrentSubmissionCycleForPub</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Journal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Target to which Journal</description>
        <label>Journal</label>
        <referenceTo>Journal__c</referenceTo>
        <relationshipName>PubStatuses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Meeting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Target a Meeting</description>
        <label>Meeting</label>
        <referenceTo>Meeting__c</referenceTo>
        <relationshipName>PubStatuses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publication_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication_id</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipName>PubStatus</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Submission_Cycle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Submission Cycle</label>
        <referenceTo>SubmissionCycle__c</referenceTo>
        <relationshipName>Pub_Statuses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publication Status</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>PubStatus Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/SubmissionCycle__c.object
<CustomObject>
    <description>record name will be PubId-{0000000}-SubCycle-{00}</description>
    <fields>
        <fullName>Journal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Journal</label>
        <referenceTo>Journal__c</referenceTo>
        <relationshipLabel>Submission Cycles</relationshipLabel>
        <relationshipName>Submission_Cycles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Meeting__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Meeting</label>
        <referenceTo>Meeting__c</referenceTo>
        <relationshipLabel>Submission Cycles</relationshipLabel>
        <relationshipName>Submission_Cycles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Submission Cycles</relationshipLabel>
        <relationshipName>Submission_Cycles</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Target_Type__c</fullName>
        <label>Target Type</label>
        <picklist>
            <picklistValues>
                <fullName>Journal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Submission Cycle</label>
    <nameField>
        <label>Submission Cycle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submission Cycles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/Update_PubCurrentTargetBatch_Test.cls
@IsTest
public class Update_PubCurrentTargetBatch_Test{
 
    public static testMethod void testMethod_1(){
     Test.startTest();
        
       Publication__c pub1 = UnitTestData.PublicationNew('TestPub ABC');
        
       Meeting__c testMeeting = new Meeting__c(MeetingName255__c = 'testMeetingABC', Meeting_name__c = 'testMeetingABC');
       insert  testMeeting;
       System.assertEquals('testMeetingABC', testMeeting.MeetingName255__c);
        
       PubStatus__c pubStatus = [SELECT Id,Submission_Cycle__c,IsCurrentSubmissionCycleForPub__c  from PubStatus__c WHERE Publication_id__c=:pub1.Id AND IsCurrentSubmissionCycleForPub__c =true limit 1];
       pubStatus.Meeting__c =testMeeting.Id;
       update  pubStatus;
        
       pub1.PubStatus__c = pubStatus.id;
       pub1.Meeting__c =  testMeeting.Id;
       pub1.Current_Target__c =  testMeeting.MeetingName255__c;
       pub1.Target_Type__c = 'Meeting';
       update pub1;
       System.assertEquals('testMeetingABC', pub1.Current_Target__c); 
       
       SubmissionCycle__c subCycle = [SELECT Id FROM SubmissionCycle__c WHERE Id=: pubStatus.Submission_Cycle__c] ;
       subCycle.Target_Type__c = 'Meeting';
       subCycle.Publication__c = pub1.Id;
       subCycle.Meeting__c = testMeeting.Id;
       update subCycle;
        
       testMeeting.Meeting_Name__c = 'abcdeftrt';
       update testMeeting;
       System.assertEquals('abcdeftrt', testMeeting.Meeting_Name__c); 
       
       targetUpdate_SchedulerClass.schedule_Method();
            
    Test.stopTest();
    }
    
    
    public static testMethod void testMethod_2(){
     Test.startTest();
        
       Publication__c pub2 = UnitTestData.PublicationNew('TestPub ABC2'); 
        
       Journal__c testJournal = new Journal__c(Journal_Name__c = 'testJournalABC', JournalName255__c = 'testJournalABC');
       insert  testJournal;
       System.assertEquals('testJournalABC', testJournal.JournalName255__c); 
        
       PubStatus__c pubStatus = [SELECT Id,Submission_Cycle__c,IsCurrentSubmissionCycleForPub__c  from PubStatus__c WHERE Publication_id__c=:pub2.Id AND IsCurrentSubmissionCycleForPub__c =true limit 1];
       pubStatus.Journal__c =testJournal.Id;
       update  pubStatus;
        
       pub2.PubStatus__c = pubStatus.id;
       pub2.Journal__c =  testJournal.Id;
       pub2.Current_Target__c =  testJournal.JournalName255__c;
       pub2.Target_Type__c = 'Journal';
       update pub2;
       System.assertEquals('testJournalABC', pub2.Current_Target__c); 
       
       SubmissionCycle__c subCycle = [SELECT Id FROM SubmissionCycle__c WHERE Id=: pubStatus.Submission_Cycle__c] ;
       subCycle.Target_Type__c = 'Journal';
       subCycle.Publication__c = pub2.Id;
       subCycle.Journal__c = testJournal.Id;
       update subCycle;
        
       testJournal.Journal_Name__c = 'abcdeftrt';
       update testJournal;
       System.assertEquals('abcdeftrt', testJournal.Journal_Name__c); 
       
       targetUpdate_SchedulerClass.schedule_Method();
            
    Test.stopTest();
    }
}