force-app/main/default/staticresources/python/Disappear/src/objects/MEScopeOfWork__c.object
<CustomObject>
    <fields>
        <fullName>Scaling_Factor__c</fullName>
        <label>Scaling Factor</label>
        <precision>6</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <label>MEScopeOfWork</label>
    <nameField>
        <label>MEScopeOfWork Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MEScopeOfWork</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/MEScopeOfWorkModelData.cls
public class MEScopeOfWorkModelData{

    public static void createData() {
    
        integer dataCount = [select count() from MEScopeOfWork__c];
        if ( dataCount <> 0) return;
        
        List<MEScopeOfWork__c> MMEScopeOfWorkModelList = new List<MEScopeOfWork__c>();
        
        MMEScopeOfWorkModelList.add( new MEScopeOfWork__c(name= 'Encore',Scaling_Factor__c=0.5));
        MMEScopeOfWorkModelList.add( new MEScopeOfWork__c(name= 'Editing/Formatting',Scaling_Factor__c=0.5));
        MMEScopeOfWorkModelList.add( new MEScopeOfWork__c(name= 'Writing',Scaling_Factor__c=1));
        MMEScopeOfWorkModelList.add( new MEScopeOfWork__c(name= 'Not Available',Scaling_Factor__c=1));  
        
        insert MMEScopeOfWorkModelList;
      
		MEScopeOfWorkModel.resetCache();          
     }
    
}