force-app/main/default/staticresources/python/Disappear/src/objects/Organization__c.object
<CustomObject>
    <fields>
        <fullName>ParentOrgId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Self Relationship</description>
        <label>Parent Organization</label>
        <referenceTo>Organization__c</referenceTo>
        <relationshipLabel>Related Organisation</relationshipLabel>
        <relationshipName>RelatedOrg</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SiebelRowId__c</fullName>
        <externalId>true</externalId>
        <label>SiebelRowId</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SponsorOrg__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sponsor Org</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vendor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amgen Internal</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Publisher</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>isLogicallyDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Expired</label>
        <type>Checkbox</type>
    </fields>
    <label>Organization</label>
    <nameField>
        <label>Organization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/OrganizationModelData.cls
public  class OrganizationModelData {

    public static void createData() {
    
        integer dataCount = [select count() from Organization__c];
        if ( dataCount <> 0) return;
        
        List<Organization__c> OrganizationList = new List<Organization__c>();
        
        OrganizationList.add( new Organization__c(name= 'Amgen', ParentOrgId__c = null, SiebelRowId__c=null, Type__c='Amgen Internal', URL__c=null, SponsorOrg__c= true));
		OrganizationList.add( new Organization__c(name= 'Astellas', ParentOrgId__c = null, SiebelRowId__c=null, Type__c='Vendor', URL__c=null, SponsorOrg__c= true));
		OrganizationList.add( new Organization__c(name= 'AstraZeneca/MedImmune', ParentOrgId__c = null, SiebelRowId__c=null, Type__c='Vendor', URL__c=null, SponsorOrg__c= true));
		OrganizationList.add( new Organization__c(name= 'Cytokinetics', ParentOrgId__c = null, SiebelRowId__c=null, Type__c='Amgen Internal', URL__c=null, SponsorOrg__c= true));
		OrganizationList.add( new Organization__c(name= 'Daiichi-Sankyo', ParentOrgId__c = null, SiebelRowId__c=null, Type__c='Amgen Internal', URL__c=null, SponsorOrg__c= true));
		OrganizationList.add( new Organization__c(name= 'Genentech, Inc.', ParentOrgId__c = null, SiebelRowId__c=null, Type__c='Amgen Internal', URL__c=null, SponsorOrg__c= true));
		OrganizationList.add( new Organization__c(name= 'GlaxoSmithKline (GSK)', ParentOrgId__c = null, SiebelRowId__c=null, Type__c='Partner', URL__c=null, SponsorOrg__c= true));
		OrganizationList.add( new Organization__c(name= 'Kirin', ParentOrgId__c = null, SiebelRowId__c=null, Type__c='Partner', URL__c=null, SponsorOrg__c= true));
		OrganizationList.add( new Organization__c(name= 'Novartis', ParentOrgId__c = null, SiebelRowId__c=null, Type__c='Partner', URL__c=null, SponsorOrg__c= true));
		OrganizationList.add( new Organization__c(name= 'Pfizer', ParentOrgId__c = null, SiebelRowId__c=null, Type__c='Partner', URL__c=null, SponsorOrg__c= true));
		OrganizationList.add( new Organization__c(name= 'Servier', ParentOrgId__c = null, SiebelRowId__c=null, Type__c='Partner', URL__c=null, SponsorOrg__c= true));
		OrganizationList.add( new Organization__c(name= 'Takeda', ParentOrgId__c = null, SiebelRowId__c=null, Type__c='Vendor', URL__c=null, SponsorOrg__c= true));
		OrganizationList.add( new Organization__c(name= 'UCB Pharma', ParentOrgId__c = null, SiebelRowId__c=null, Type__c='Vendor', URL__c=null, SponsorOrg__c= true));
        OrganizationList.add( new Organization__c(name= 'ANC Study Group [Expired]', ParentOrgId__c = null, SiebelRowId__c=null, Type__c='Vendor', URL__c=null, SponsorOrg__c= true, IsLogicallyDeleted__c = true));
        
        insert OrganizationList;
     }
    
}