force-app/main/default/staticresources/python/Disappear/src/objects/Plan__c.object
<CustomObject>
    <description>Junction table for PlanYear &amp; Product

Used to find all publications for a Plan Year via Production Indication

PlanName =  {PlanYear}-{Product}</description>
    <fields>
        <fullName>PlanDescription__c</fullName>
        <label>Plan Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PlanYear__c</fullName>
        <label>Plan Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/PlanModel.cls
public class PlanModel {
    
    private static List<Plan__c> pPlanList= null;
    public static List<Plan__c> PlanList{
        get{
            if(pPlanList== null){
              pPlanList= getAllPlanList();
            }               
        return pPlanList;
        }
    }  
    
   private static Map<String, Plan__c> pPlanNameMap = null;
   public static Map<String, Plan__c> PlanNameMap{
     get {
       if (pPlanNameMap == null){
         pPlanNameMap = getPlanMapByName();
       }
       return pPlanNameMap;
     }
   }
   
   public static Map<String, Plan__c> getPlanMapByName() {
    Map<String, Plan__c> result = new Map<String, Plan__c>();
    for(Plan__c pPlan : PlanList){
      result.put(pPlan.Name, pPlan );
    }

    return result;
  }
      
    public static List<Plan__c> getAllPlanList(){
        List<Plan__c> result = [
          select id, Name, ProductId__c, PlanYear__c, PlanDescription__c
          From Plan__c
          order by Name  
           ];
        return result;
    }
    
}