force-app/main/default/staticresources/python/Disappear/src/objects/ProdIndiObjective__c.object
<CustomObject>
    <fields>
        <fullName>End_date__c</fullName>
        <label>End date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IsLogicallyDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Expired</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Indication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Indication</label>
        <referenceTo>ProductIndication__c</referenceTo>
        <relationshipLabel>Product Indication Objectives</relationshipLabel>
        <relationshipName>Product_Indication_Objectives</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SiebelRowId__c</fullName>
        <externalId>true</externalId>
        <label>SiebelRowId</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Product Indication Objective</label>
    <nameField>
        <label>Product Indication Objective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Indication Objectives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/ProdIndObjSciStatement__c.object
<CustomObject>
    <fields>
        <fullName>End_date__c</fullName>
        <label>End date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IsLogicallyDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Expired</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Indication_Objective__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Indication Objective</label>
        <referenceTo>ProdIndiObjective__c</referenceTo>
        <relationshipLabel>Scientific Statements</relationshipLabel>
        <relationshipName>Scientific_Statements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ScientificStatement__c</fullName>
        <label>ScientificStatement</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ScientificStatement_no__c</fullName>
        <label>ScientificStatement Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SiebelRowId__c</fullName>
        <label>SiebelRowId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_date__c</fullName>
        <label>Start date</label>
        <type>Date</type>
    </fields>
    <label>Scientific Statement</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>ProdIndObjSciStatement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scientific Statements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/ProdIndObjSciStatementModelData.cls
public with sharing class ProdIndObjSciStatementModelData {
    
    public static void createData() {
         
        integer dataCount = [select count() from ProdIndiObjective__c];   
        List<ProdIndiObjective__c> prod = [Select name, Product_Indication__c from ProdIndiObjective__c];
     //   if ( dataCount <> 0) return;
        
        List<ProdIndObjSciStatement__c> ProdIndObjSciStatementList= new List<ProdIndObjSciStatement__c>();
            
           ProdIndObjSciStatementList.add(new ProdIndObjSciStatement__c( Product_Indication_Objective__c=ProdIndiObjectiveModel.ProdIndiObjectiveNameMap.get('Differentiate from current and new competitors').Id, ScientificStatement__c='Burden of psoriasis, including psychological or social', ScientificStatement_no__c=1, start_date__c=null, End_date__c=null, SiebelRowId__c=null, IsLogicallyDeleted__c = false) );
           ProdIndObjSciStatementList.add(new ProdIndObjSciStatement__c( Product_Indication_Objective__c=ProdIndiObjectiveModel.ProdIndiObjectiveNameMap.get('Differentiate from current and new competitors').Id, ScientificStatement__c='Healthcare-resource utilization or other costs associated with psoriasis', ScientificStatement_no__c=2, start_date__c=null, End_date__c=null, SiebelRowId__c=null, IsLogicallyDeleted__c = false) );
           ProdIndObjSciStatementList.add(new ProdIndObjSciStatement__c( Product_Indication_Objective__c=ProdIndiObjectiveModel.ProdIndiObjectiveNameMap.get('Market expansion—Drive broad acceptance and use in clinical dermatology practice').Id, ScientificStatement__c='Comorbidities associated with Psoriasis', ScientificStatement_no__c=1, start_date__c=null, End_date__c=null, SiebelRowId__c=null, IsLogicallyDeleted__c = false) );
           ProdIndObjSciStatementList.add(new ProdIndObjSciStatement__c( Product_Indication_Objective__c=ProdIndiObjectiveModel.ProdIndiObjectiveNameMap.get('Market expansion—Drive broad acceptance and use in clinical dermatology practice').Id, ScientificStatement__c='Safety of Etanercept in scalp psoriasis', ScientificStatement_no__c=2, start_date__c=null, End_date__c=null, SiebelRowId__c=null, IsLogicallyDeleted__c = false) );
           ProdIndObjSciStatementList.add(new ProdIndObjSciStatement__c( Product_Indication_Objective__c=ProdIndiObjectiveModel.ProdIndiObjectiveNameMap.get('Payors, employers, and benefit consultants').Id, ScientificStatement__c='The safety profile associated with stopping and restarting etanercept', ScientificStatement_no__c=1, start_date__c=null, End_date__c=null, SiebelRowId__c=null, IsLogicallyDeleted__c = false) );
           ProdIndObjSciStatementList.add(new ProdIndObjSciStatement__c( Product_Indication_Objective__c=ProdIndiObjectiveModel.ProdIndiObjectiveNameMap.get('Payors, employers, and benefit consultants').Id, ScientificStatement__c='The long-term safety profile of etanercept in psoriasis.', ScientificStatement_no__c=2, start_date__c=null, End_date__c=null, SiebelRowId__c=null, IsLogicallyDeleted__c = false) );
      //   ProdIndObjSciStatementList.add(new ProdIndObjSciStatement__c( Product_Indication_Objective__c=ProdIndiObjectiveModel.ProdIndiObjectiveNameMap.get('Market Expansion—Encourage compliance and continual use to treat psoriasis as a chronic condition').Id, ScientificStatement__c='Safety of Etanercept in scalp psoriasis', ScientificStatement_no__c=1, start_date__c=null, End_date__c=null, SiebelRowId__c=null, IsLogicallyDeleted__c = false) );
      //   ProdIndObjSciStatementList.add(new ProdIndObjSciStatement__c( Product_Indication_Objective__c=ProdIndiObjectiveModel.ProdIndiObjectiveNameMap.get('Market Expansion—Encourage compliance and continual use to treat psoriasis as a chronic condition').Id, ScientificStatement__c='The safety profile of etanercept in combination with other agents', ScientificStatement_no__c=2, start_date__c=null, End_date__c=null, SiebelRowId__c=null, IsLogicallyDeleted__c = false) );
           
          insert ProdIndObjSciStatementList;
    }


}