force-app/main/default/staticresources/python/Disappear/src/objects/ProdStudy__c.object
<CustomObject>
    <fields>
        <fullName>Prod_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Amgen Product</label>
        <referenceTo>AmgenProduct__c</referenceTo>
        <relationshipName>Product_Studies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Study_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Study/Project</label>
        <referenceTo>Study__c</referenceTo>
        <relationshipLabel>Product Studies/Projects</relationshipLabel>
        <relationshipName>ProductStudy</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Study/Project</label>
    <nameField>
        <label>ProductStudy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Studies/Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/ProdStudyModelData.cls
public  class ProdStudyModelData {

    public static void createData() {
    
        integer dataCount = [select count() from ProdStudy__c];
        if ( dataCount <> 0) return;
        
        List<ProdStudy__c> ProdStudyList = new List<ProdStudy__c>();
        
        ProdStudyList.add( new ProdStudy__c(Name='ProdStudy01', Prod_id__c=AmgenProductModel.getProductByName('Enbrel').id, 
            Study_id__c=StudyModel.StudyMapByTitle.get('Avanti Patient Use Study').Id));         
        ProdStudyList.add( new ProdStudy__c(Name='ProdStudy02', Prod_id__c=AmgenProductModel.getProductByName('Enbrel').id, 
            Study_id__c=StudyModel.StudyMapByTitle.get('Enbrel PsO Inflamm Joints Pilot Study').Id));         
        ProdStudyList.add( new ProdStudy__c(Name='ProdStudy02', Prod_id__c=AmgenProductModel.getProductByName('Enbrel').id, 
            Study_id__c=StudyModel.StudyMapByTitle.get('Enbrel RA Remission Study').Id));         
        ProdStudyList.add( new ProdStudy__c(Name='ProdStudy02', Prod_id__c=AmgenProductModel.getProductByName('Enbrel').id, 
            Study_id__c=StudyModel.StudyMapByTitle.get('Enbrel Pain Study - formulation buffer and needle impact').Id));         
            
        insert ProdStudyList;
                
     }
    
}