force-app/main/default/staticresources/python/Disappear/src/objects/ProdStudy__c.object
<CustomObject>
    <fields>
        <fullName>Prod_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Amgen Product</label>
        <referenceTo>AmgenProduct__c</referenceTo>
        <relationshipName>Product_Studies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Study_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Study/Project</label>
        <referenceTo>Study__c</referenceTo>
        <relationshipLabel>Product Studies/Projects</relationshipLabel>
        <relationshipName>ProductStudy</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Study/Project</label>
    <nameField>
        <label>ProductStudy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Studies/Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/ProdStudyModel.cls
public class ProdStudyModel {
    
    private static List<ProdStudy__c> pProdStudyList = null;
    public static List<ProdStudy__c> ProdStudyList{
        get{
            if(pProdStudyList == null){
              pProdStudyList = getAllProdStudyList();
            }               
        return pProdStudyList;
        }
    }  
    
   private static Map<String, ProdStudy__c> pProdStudyNameMap = null;
   public static Map<String, ProdStudy__c> ProdStudyNameMap{
     get {
       if (pProdStudyNameMap == null){
         pProdStudyNameMap = getProdStudyMapByName();
       }
       return pProdStudyNameMap;
     }
   }
   
   public static Map<String, ProdStudy__c> getProdStudyMapByName() {
    Map<String, ProdStudy__c> result = new Map<String, ProdStudy__c>();
    for(ProdStudy__c pProdStudy: ProdStudyList){
      result.put(pProdStudy.Name, pProdStudy);
    }

    return result;
  }
      
    public static List<ProdStudy__c> getAllProdStudyList(){
        List<ProdStudy__c> result = [
          select id, Name, Prod_id__c, Study_id__c
          From ProdStudy__c
          order by Name  
           ];
        return result;
    }


}