force-app/main/default/staticresources/python/Disappear/src/objects/ProductIndication__c.object
<CustomObject>
    <fields>
        <fullName>isEnbrel__c</fullName>
        <formula>Product__r.isEnbrel__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>isEnbrel</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isLogicallyDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Expired</label>
        <type>Checkbox</type>
    </fields>
    <label>Product Indication</label>
    <nameField>
        <label>ProductIndication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Indications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Pub_Prod_Ind__c.object
<CustomObject>
    <fields>
        <fullName>Product_Indication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product Indication</label>
        <referenceTo>ProductIndication__c</referenceTo>
        <relationshipLabel>Publication Product  Indications</relationshipLabel>
        <relationshipName>Publication_Product_Indications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Publication Product  Indications</relationshipLabel>
        <relationshipName>Publication_Product_Indications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>isEnbrel__c</fullName>
        <formula>Product_Indication__r.isEnbrel__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>isEnbrel</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isLogicallyDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isLogicallyDeleted</label>
        <type>Checkbox</type>
    </fields>
    <label>Publication Product  Indication</label>
    <nameField>
        <label>Publication Product  Indication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publication Product  Indications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <fields>
        <fullName>Product_Indication__c</fullName>
        <description>A READ ONLY string that list all product Indications for the Publication
The key product indication will be list at the first entry</description>
        <inlineHelpText>Product - Indication is a required field that is available for selection when a publication is first saved. Once saved, the Product Indication may be edited using the Product Indication button.</inlineHelpText>
        <label>Product - Indication</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isEnbrel__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to manage the sharing with those users that should not have access to Enbrel pubs</description>
        <label>isEnbrel</label>
        <type>Checkbox</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <recordTypes>
        <fullName>Execute</fullName>
        <active>true</active>
        <label>Execute</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/BatchResetEnbrel.cls
global class BatchResetEnbrel extends BatchBase 
    implements Database.Batchable<SObject>,Database.Stateful {

    public String SOQL = 'select id,name from Publication__c ' +
        ' order by name desc';
    
    public BatchResetEnbrel() {
        super();
        if ( Test.isRunningTest()){
            SOQL = SOQL + ' limit 10';
        }
        AddMessage(SOQL);
        system.debug(SOQL);
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        batchableContext = BC;
        batchName = 'BatchResetEnbrel';  
        System.Debug(SOQL);
        return Database.getQueryLocator(SOQL);
    }
    

    global void execute(Database.BatchableContext BC, List<publication__c> pubs){
        for(publication__c pub : pubs) {
            resetEnbrel(pub.id);
        }

        AppLogModel.flushLogs();
    }
    
    
    public static void resetEnbrel(id PubId) {
        boolean isEnbrelSelected = false;
        for(Pub_Prod_Ind__c pubProdInd : PubProdIndModel.getPubProductIndication(PubId)) {
            
            if (pubProdInd.isLogicallyDeleted__c == false) {
                
                        
                if (pubProdInd.isEnbrel__c) {
                    AppLogModel.LogDebug('BatchResetEnbrel::resetEnbrel', 
                            'product Indication- '+pubProdInd.Product_Indication__r.name +' isEnbrel = '+ pubProdInd.Product_Indication__r.isEnbrel__c, pubProdInd.Product_Indication__r.id);   
                    
                    AppLogModel.LogDebug('BatchResetEnbrel::resetEnbrel', 
                            'pub Prod Indication- '+pubProdInd.name +':'+ pubProdInd.Product_Indication__r.name +' isEnbrel = '+ pubProdInd.isEnbrel__c, pubProdInd.id);    


                    isEnbrelSelected = true;
                } 
            }
        }       
        if (isEnbrelSelected) {
            AppearPubModel activePub = New AppearPubModel(pubId);
            activePub.pubRecord.isEnbrel__c = true;
            update activePub.pubRecord;
        }
    }

    global void finish(Database.BatchableContext BC){
        SendBatchCompletionEmail();
    }
    
    //BatchResetEnbrel.runNow();
    public static void runNow(){
        BatchResetEnbrel batch = new BatchResetEnbrel();
        Database.executeBatch(batch, 20);
    }

//////////////////////////////////////////  unit test /////////////////////////////////////
    
    private static testMethod void unitTest() {
        CreateData();
        
        BatchResetEnbrel.runNow();
        Publication__c  newPub = UnitTestData.PublicationNew('Fpr Controller Pub');
        BatchResetEnbrel.ResetEnbrel(newPub.Id);
        
    } 
    
    public static void CreateData() {
        
    }
}