force-app/main/default/staticresources/python/Disappear/src/objects/ProdIndTeamMember__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Members of Team</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>ProdInd_Team_Members</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Indication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Indication</label>
        <referenceTo>ProductIndication__c</referenceTo>
        <relationshipName>Product_Indication_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Indication Team Member</label>
    <nameField>
        <displayFormat>PITM-{000000}</displayFormat>
        <label>ProductIndicationTeam Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Indication Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/ProdIndTeamMemberModel.cls
public with sharing class ProdIndTeamMemberModel {
	
	public static List<ProdIndTeamMember__c> getProductIndTeamMember(Id ProductIndicationId) {
		List<ProdIndTeamMember__c> result = [
			Select p.Product_Indication__c,
			p.Contact__c, p.Contact__r.name
			From ProdIndTeamMember__c p
			where Product_Indication__c = :ProductIndicationId
		];
		return result;
	}
	
	public static Map<Id,List<ProdIndTeamMember__c>> getProductIndTeamMember(Set<Id> ProductIndcationIds) {
		//bulkify retrival
		List<ProdIndTeamMember__c> pitms = [
			Select p.Product_Indication__c,
			p.Contact__c, p.Contact__r.name
			From ProdIndTeamMember__c p
			where Product_Indication__c in :ProductIndcationIds
		];
		
		Map<Id,List<ProdIndTeamMember__c>> result = new Map<Id,List<ProdIndTeamMember__c>>();
		for(Id prodIndId : ProductIndcationIds) {
			List<ProdIndTeamMember__c> contacts = new List<ProdIndTeamMember__c>();
			for(ProdIndTeamMember__c pitm :pitms ){
				if ( pitm.Product_Indication__c == prodIndId) {
					contacts.add(pitm);
				}
			}
			result.put(prodIndId, contacts);
		}
		
		return result;
	}
}