force-app/main/default/staticresources/python/Disappear/src/objects/ProdIndiObjective__c.object
<CustomObject>
    <fields>
        <fullName>End_date__c</fullName>
        <label>End date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IsLogicallyDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Expired</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Indication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Indication</label>
        <referenceTo>ProductIndication__c</referenceTo>
        <relationshipLabel>Product Indication Objectives</relationshipLabel>
        <relationshipName>Product_Indication_Objectives</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SiebelRowId__c</fullName>
        <externalId>true</externalId>
        <label>SiebelRowId</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Product Indication Objective</label>
    <nameField>
        <label>Product Indication Objective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Indication Objectives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/ProdIndiObjectiveModelData.cls
public with sharing class ProdIndiObjectiveModelData {

    public static void createData() {
         
        integer dataCount = [select count() from ProdIndiObjective__c];
        if ( dataCount <> 0) return;
        
        List<ProdIndiObjective__c> ProductIndiObjectiveList = new List<ProdIndiObjective__c>();
            
		ProductIndiObjectiveList.add(new ProdIndiObjective__c(Name='Differentiate from current and new competitors', 
			Product_Indication__c=ProductIndicationModel.ProductIndicationNameMap.get('Aranesp - CKD Not Dialysis').Id,
			start_date__c=null, End_date__c=null, SiebelRowId__c=null, IsLogicallyDeleted__c=false));
			
		ProductIndiObjectiveList.add(new ProdIndiObjective__c(Name='Market expansion—Drive broad acceptance and use in clinical dermatology practice', 
			Product_Indication__c=ProductIndicationModel.ProductIndicationNameMap.get('Aranesp - Dialysis').Id,
			start_date__c=null, End_date__c=null, SiebelRowId__c=null, IsLogicallyDeleted__c=false));
			
		ProductIndiObjectiveList.add(new ProdIndiObjective__c(Name='Payors, employers, and benefit consultants', 
			Product_Indication__c=ProductIndicationModel.ProductIndicationNameMap.get('Epogen - Dialysis').Id,
			start_date__c=null, End_date__c=null, SiebelRowId__c=null, IsLogicallyDeleted__c=false));
			
         //  ProductIndiObjectiveList.add(new ProdIndiObjective__c(Name='Market Expansion—Encourage compliance and continual use to treat psoriasis as a chronic condition', Product_Indication__c=ProductIndicationModel.ProductIndicationNameMap.get('AMG 108 - Inflammation').Id,start_date__c=null, End_date__c=null, SiebelRowId__c=null, IsLogicallyDeleted__c = false) );
        insert ProductIndiObjectiveList ;
    }

}