force-app/main/default/staticresources/python/Disappear/src/objects/ProdIndTeamMember__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Members of Team</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>ProdInd_Team_Members</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Indication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Indication</label>
        <referenceTo>ProductIndication__c</referenceTo>
        <relationshipName>Product_Indication_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Indication Team Member</label>
    <nameField>
        <displayFormat>PITM-{000000}</displayFormat>
        <label>ProductIndicationTeam Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Indication Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/ProdIndTeamMemberModelData.cls
public with sharing class ProdIndTeamMemberModelData {

   /* public static testMethod void UnitTest() {
        ProductModelData.createData();
        IndicationModelData.createData();
        ProductIndicationModelData.createData();
        ProdIndTeamMemberModelData.createData();
;
    }*/
    
    public static void createData() {
         
        integer dataCount = [select count() from ProdIndTeamMember__c];                
        if ( dataCount <> 0) return;
        
        List<ProdIndTeamMember__c> ProdIndTeamMemberList= new List<ProdIndTeamMember__c>();
            
		Contact mike = AppearContactModel.findContactByName('Michael', 'Dorner')[0];    
		Contact solange = AppearContactModel.findContactByName('Solange', 'Weiss')[0];    
		Contact melissa = AppearContactModel.findContactByName('Melissa', 'Seal')[0];    
            
		ProdIndTeamMemberList.add(new ProdIndTeamMember__c(
			Contact__c=mike.id ,
            Product_Indication__c=ProductIndicationModel.ProductIndicationNameMap.get('Aranesp - CKD Not Dialysis').Id));
            
          ProdIndTeamMemberList.add(new ProdIndTeamMember__c(
            Contact__c=mike.id ,
            Product_Indication__c=ProductIndicationModel.ProductIndicationNameMap.get('Aranesp - Dialysis').Id));
            
          ProdIndTeamMemberList.add(new ProdIndTeamMember__c(
            Contact__c=solange.id ,
            Product_Indication__c=ProductIndicationModel.ProductIndicationNameMap.get('Aranesp - CKD Not Dialysis').Id));
            
          ProdIndTeamMemberList.add(new ProdIndTeamMember__c(
            Contact__c=melissa.id ,
            Product_Indication__c=ProductIndicationModel.ProductIndicationNameMap.get('Epogen - Dialysis').Id));
           
          insert ProdIndTeamMemberList;
    }


}