force-app/main/default/staticresources/python/Disappear/src/objects/ProdIndiObjective__c.object
<CustomObject>
    <fields>
        <fullName>IsLogicallyDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Expired</label>
        <type>Checkbox</type>
    </fields>
    <label>Product Indication Objective</label>
    <nameField>
        <label>Product Indication Objective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Indication Objectives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/ProdIndObjSciStatement__c.object
<CustomObject>
    <fields>
        <fullName>IsLogicallyDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Expired</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Indication_Objective__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Indication Objective</label>
        <referenceTo>ProdIndiObjective__c</referenceTo>
        <relationshipLabel>Scientific Statements</relationshipLabel>
        <relationshipName>Scientific_Statements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ScientificStatement__c</fullName>
        <label>ScientificStatement</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Scientific Statement</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>ProdIndObjSciStatement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scientific Statements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/ProdIndiObjectivesTriggerLogic.cls
/*******************************************************************************************************
 * $Id$ : ProdIndiObjectivesTriggerLogic
 * $Created Date$ : 2014/04/11
 * $Author$ : Sesha Kurmana
 * $Description$ : This class is used to incorporate logic for handling updates on ProdIndiObjective__c.
 *******************************************************************************************************/
public with sharing class ProdIndiObjectivesTriggerLogic {
	
	public static void handleAutomaticExpirationOfSS(List<ProdIndiObjective__c> prodIndObjList)
	{
    	if ( prodIndObjList == null || prodIndObjList.size() == 0) {
			return;
		}
        
        for (ProdIndiObjective__c prodIndObj : prodIndObjList)
		{
			if(prodIndObj.IsLogicallyDeleted__c) {
				List<ProdIndObjSciStatement__c> prodIndObjSS = [SELECT Id, Name, ScientificStatement__c 
																	FROM ProdIndObjSciStatement__c
																	where Product_Indication_Objective__c = :prodIndObj.Id];
				
				for (ProdIndObjSciStatement__c prodIndObjSSLoop : prodIndObjSS)
				{
					prodIndObjSSLoop.IsLogicallyDeleted__c = true;
				}
				
				update prodIndObjSS;
				
				AppLogModel.LogDebug('ProdIndiObjectivesTriggerLogic::AutomaticExpirationOfSS', 'Updated the isExpired Flag successfully on all the Scientific Statements for Objective:: '+ prodIndObj.Name);
        	}
		}
		
        AppLogModel.flushLogs();
    }
}