force-app/main/default/staticresources/python/Disappear/src/objects/ProductIndication__c.object
<CustomObject>
    <label>Product Indication</label>
    <nameField>
        <label>ProductIndication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Indications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Review_Team__c.object
<CustomObject>
    <description>Review team for DataSource or SubGroup

A review team can exists for a DataSource without SubGroup</description>
    <fields>
        <fullName>Data_Source__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Data Source</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>DataSource__c.isLogicallyDeleted__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>DataSource__c</referenceTo>
        <relationshipLabel>Review Teams</relationshipLabel>
        <relationshipName>Review_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Indication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product Indication</label>
        <referenceTo>ProductIndication__c</referenceTo>
        <relationshipLabel>Review Teams</relationshipLabel>
        <relationshipName>Review_Teams</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubGroup__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>SubGroup</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>SubGroup__c.isLogicallyDeleted__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SubGroup__c</referenceTo>
        <relationshipLabel>Review Teams</relationshipLabel>
        <relationshipName>Review_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Review Team</label>
    <nameField>
        <label>Review Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Review Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/SubGroup__c.object
<CustomObject>
    <fields>
        <fullName>Data_Source__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Data Source</label>
        <referenceTo>DataSource__c</referenceTo>
        <relationshipLabel>SubGroups</relationshipLabel>
        <relationshipName>SubGroups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SubGroup</label>
    <nameField>
        <label>SubGroup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SubGroups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/ReviewTeamTriggerLogic.cls
/***************************************************************************************************
 * $Id$ : ReviewTeamTriggerLogic
 * $Created Date$ : 2014/04/03
 * $Author$ : Sudha
 * $Description$ : This class is used to replace logic from Trigger to Apex Class. 
 ***********************************************************************************************/
public class ReviewTeamTriggerLogic {
    public static void validateReviewTeam(List<Review_Team__c> reviewTeamList){
        Set<Id> SetProductIndicationId = New Set<Id>();
        List<Review_Team__c> ListReviewTeam = new List<Review_Team__c>();
        for(Review_Team__c rt : reviewTeamList){
            string ProductIndicationName = 
            ProductIndicationModel.getProductIndicationName(rt.Product_Indication__c);
            SetProductIndicationId.add(rt.Product_Indication__c);
            ListReviewTeam.add(rt);
            /*if (ProductIndicationName == null ) {
            string msg = 'Error : invalid Review Team - Production_Indication ['+
            rt.Product_Indication__c +'] is not valid.';
            rt.addError(msg); 
            AppLogModel.LogError('ReviewTeamTrigger', msg);
            }*/
            if(ProductIndicationName != null) {            
                string DataSourceName = DataSourceModel.getDataSourceName(rt.Data_Source__c);
                string SubGroupName = SubGroupModel.getSubGroupName(rt.SubGroup__c);
                
                if ( DataSourceName == null && SubGroupName == null) {
                    string msg = 'Error : invalid Review Team - need at least one of DataSource or SubGroup';
                    rt.addError(msg); 
                    AppLogModel.LogError('ReviewTeamTrigger', msg);                 
                } 
                else if (DataSourceName == null) {
                    rt.name = string.format('{0} - {1}',
                    new string[]{ProductIndicationName, SubGroupName});
                } 
                else if (SubGroupName == null) {
                    rt.name = string.format('{0} - {1}',
                    new string[]{ProductIndicationName, DataSourceName});
                } 
                else {
                    rt.name = string.format('{0} - {1} - {2}',
                    new string[]{ProductIndicationName, DataSourceName, SubGroupName});
                }
            }
        }
        //Code unit started for CR: #139
        //To show error message for expired product indication.
        Map<Id,String> MapExpiredProdIndication = ProductIndicationModel.getMapAllExpiredProductIndicationName(SetProductIndicationId);
        if(MapExpiredProdIndication.size()!=0){
            for(Review_Team__c rtAll: ListReviewTeam){
                if(MapExpiredProdIndication.containsKey(rtAll.Product_Indication__c)){
                    string msg = 'Invalid Review Team - Production_Indication ['+
                    MapExpiredProdIndication.get(rtAll.Product_Indication__r.Name) +'] has expired.';
                    rtAll.addError(msg); 
                    AppLogModel.LogError('ReviewTeamTrigger', msg); 
                }
            }
        }
        //Code unit Ended for CR: #139
    }
}