force-app/main/default/staticresources/python/Disappear/src/objects/ProfileTab__c.object
<CustomObject>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Profile Tab</label>
    <nameField>
        <label>ProfileTab Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Profile Tabs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/ProfileTabTile__c.object
<CustomObject>
    <label>Profile Tab Tile</label>
    <nameField>
        <label>ProfileTabTile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Profile Tab Tiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/ProfileTabModelData.cls
public  class ProfileTabModelData {
	
	public static void refreshProfilePermission() {
		List<sObject> records = [select id from ProfileTabTile__c];
		delete records;
		
		records = [select id from ProfileTab__c];
		delete records;
		
		ProfileTabModelData.createData();
		ProfileTabTileModelData.createData();
	}

    public static void createData() {
    
        integer dataCount = [select count() from ProfileTab__c];
        if ( dataCount <> 0) return;
        
        List<ProfileTab__c> ProfileTabList = new List<ProfileTab__c>();
        
        ProfileTabList.add( new ProfileTab__c(Name='FPR Tab',Comment__c=null));         
        ProfileTabList.add( new ProfileTab__c(Name='Publication Tab',Comment__c=null));         
               
        insert ProfileTabList;
                
     }
    
}