force-app/main/default/staticresources/python/Disappear/src/objects/ProfileTabTile__c.object
<CustomObject>
    <fields>
        <fullName>APPEAR_626__c</fullName>
        <defaultValue>false</defaultValue>
        <label>APPEAR 626</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APPEAR_Business_Admin__c</fullName>
        <defaultValue>false</defaultValue>
        <label>APPEAR Business Admin</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APPEAR_FPRC__c</fullName>
        <defaultValue>false</defaultValue>
        <label>APPEAR FPRC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APPEAR_FPR_Only_Submitters__c</fullName>
        <defaultValue>false</defaultValue>
        <label>APPEAR FPR Only Submitters</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APPEAR_GPPL__c</fullName>
        <defaultValue>false</defaultValue>
        <label>APPEAR GPPL</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APPEAR_International_FPRC__c</fullName>
        <defaultValue>false</defaultValue>
        <label>APPEAR International FPRC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APPEAR_Pub_Team__c</fullName>
        <defaultValue>false</defaultValue>
        <label>APPEAR Pub Team</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APPEAR_Reviewers__c</fullName>
        <defaultValue>false</defaultValue>
        <label>APPEAR Reviewers</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>APPEAR_Writing__c</fullName>
        <defaultValue>false</defaultValue>
        <label>APPEAR Writing</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Profile_Tab__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Profile Tab</label>
        <referenceTo>ProfileTab__c</referenceTo>
        <relationshipLabel>Profile Tab Tiles</relationshipLabel>
        <relationshipName>Profile_Tab_Tiles</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>System_Admin__c</fullName>
        <defaultValue>false</defaultValue>
        <label>System Admin</label>
        <type>Checkbox</type>
    </fields>
    <label>Profile Tab Tile</label>
    <nameField>
        <label>ProfileTabTile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Profile Tab Tiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/ProfileTabTileModelData.cls
public  class ProfileTabTileModelData {

    public static void createData() {
    
        integer dataCount = [select count() from ProfileTabTile__c];
        if ( dataCount <> 0) return;
        
        List<ProfileTabTile__c> ProfileTabTileList = new List<ProfileTabTile__c>();
        
         ProfileTabTileList.add( new ProfileTabTile__c(Name='Details',Profile_Tab__c=ProfileTabModel.ProfileTabNameMap.get('Publication Tab').Id,
             APPEAR_Pub_Team__c=True,APPEAR_GPPL__c=True,APPEAR_Writing__c=True,APPEAR_Reviewers__c=False,APPEAR_FPR_Only_Submitters__c=False,
             APPEAR_626__c=True,APPEAR_FPRC__c=True,APPEAR_International_FPRC__c=True,APPEAR_Business_Admin__c=True,System_Admin__c=True));         
         ProfileTabTileList.add( new ProfileTabTile__c(Name='Studies/Projects',Profile_Tab__c=ProfileTabModel.ProfileTabNameMap.get('Publication Tab').Id,
             APPEAR_Pub_Team__c=True,APPEAR_GPPL__c=True,APPEAR_Writing__c=True,APPEAR_Reviewers__c=False,APPEAR_FPR_Only_Submitters__c=False,
             APPEAR_626__c=True,APPEAR_FPRC__c=True,APPEAR_International_FPRC__c=True,APPEAR_Business_Admin__c=True,System_Admin__c=True));         
         ProfileTabTileList.add( new ProfileTabTile__c(Name='Scientific Statements',Profile_Tab__c=ProfileTabModel.ProfileTabNameMap.get('Publication Tab').Id,
             APPEAR_Pub_Team__c=True,APPEAR_GPPL__c=True,APPEAR_Writing__c=True,APPEAR_Reviewers__c=False,APPEAR_FPR_Only_Submitters__c=False,
             APPEAR_626__c=False,APPEAR_FPRC__c=True,APPEAR_International_FPRC__c=True,APPEAR_Business_Admin__c=True,System_Admin__c=True));         
         ProfileTabTileList.add( new ProfileTabTile__c(Name='Publication Team',Profile_Tab__c=ProfileTabModel.ProfileTabNameMap.get('Publication Tab').Id,
             APPEAR_Pub_Team__c=True,APPEAR_GPPL__c=True,APPEAR_Writing__c=True,APPEAR_Reviewers__c=False,APPEAR_FPR_Only_Submitters__c=False,
             APPEAR_626__c=False,APPEAR_FPRC__c=True,APPEAR_International_FPRC__c=True,APPEAR_Business_Admin__c=True,System_Admin__c=True));         
         ProfileTabTileList.add( new ProfileTabTile__c(Name='Attachments',Profile_Tab__c=ProfileTabModel.ProfileTabNameMap.get('Publication Tab').Id,
             APPEAR_Pub_Team__c=True,APPEAR_GPPL__c=True,APPEAR_Writing__c=True,APPEAR_Reviewers__c=False,APPEAR_FPR_Only_Submitters__c=False,
             APPEAR_626__c=True,APPEAR_FPRC__c=True,APPEAR_International_FPRC__c=True,APPEAR_Business_Admin__c=True,System_Admin__c=True));         
         ProfileTabTileList.add( new ProfileTabTile__c(Name='Writing Roles',Profile_Tab__c=ProfileTabModel.ProfileTabNameMap.get('Publication Tab').Id,
             APPEAR_Pub_Team__c=True,APPEAR_GPPL__c=True,APPEAR_Writing__c=True,APPEAR_Reviewers__c=False,APPEAR_FPR_Only_Submitters__c=False,
             APPEAR_626__c=False,APPEAR_FPRC__c=True,APPEAR_International_FPRC__c=True,APPEAR_Business_Admin__c=True,System_Admin__c=True));         
         ProfileTabTileList.add( new ProfileTabTile__c(Name='Statuses',Profile_Tab__c=ProfileTabModel.ProfileTabNameMap.get('Publication Tab').Id,
             APPEAR_Pub_Team__c=True,APPEAR_GPPL__c=True,APPEAR_Writing__c=True,APPEAR_Reviewers__c=False,APPEAR_FPR_Only_Submitters__c=False,
             APPEAR_626__c=False,APPEAR_FPRC__c=True,APPEAR_International_FPRC__c=True,APPEAR_Business_Admin__c=True,System_Admin__c=True));         
         ProfileTabTileList.add( new ProfileTabTile__c(Name='Pre-FPR Reviewers',Profile_Tab__c=ProfileTabModel.ProfileTabNameMap.get('Publication Tab').Id,
             APPEAR_Pub_Team__c=False,APPEAR_GPPL__c=False,APPEAR_Writing__c=False,APPEAR_Reviewers__c=False,APPEAR_FPR_Only_Submitters__c=False,
             APPEAR_626__c=True,APPEAR_FPRC__c=True,APPEAR_International_FPRC__c=True,APPEAR_Business_Admin__c=True,System_Admin__c=True));         
         ProfileTabTileList.add( new ProfileTabTile__c(Name='Reviewer Activity',Profile_Tab__c=ProfileTabModel.ProfileTabNameMap.get('Publication Tab').Id,
             APPEAR_Pub_Team__c=True,APPEAR_GPPL__c=True,APPEAR_Writing__c=True,APPEAR_Reviewers__c=False,APPEAR_FPR_Only_Submitters__c=False,
             APPEAR_626__c=True,APPEAR_FPRC__c=True,APPEAR_International_FPRC__c=True,APPEAR_Business_Admin__c=True,System_Admin__c=True));         
         ProfileTabTileList.add( new ProfileTabTile__c(Name='Authors',Profile_Tab__c=ProfileTabModel.ProfileTabNameMap.get('Publication Tab').Id,
             APPEAR_Pub_Team__c=True,APPEAR_GPPL__c=True,APPEAR_Writing__c=True,APPEAR_Reviewers__c=False,APPEAR_FPR_Only_Submitters__c=False,
             APPEAR_626__c=True,APPEAR_FPRC__c=True,APPEAR_International_FPRC__c=True,APPEAR_Business_Admin__c=True,System_Admin__c=True));         
         ProfileTabTileList.add( new ProfileTabTile__c(Name='Related Pubs',Profile_Tab__c=ProfileTabModel.ProfileTabNameMap.get('Publication Tab').Id,
             APPEAR_Pub_Team__c=True,APPEAR_GPPL__c=True,APPEAR_Writing__c=True,APPEAR_Reviewers__c=False,APPEAR_FPR_Only_Submitters__c=False,
             APPEAR_626__c=False,APPEAR_FPRC__c=True,APPEAR_International_FPRC__c=True,APPEAR_Business_Admin__c=True,System_Admin__c=True));         
         ProfileTabTileList.add( new ProfileTabTile__c(Name='Publications Queue',Profile_Tab__c=ProfileTabModel.ProfileTabNameMap.get('Publication Tab').Id,
             APPEAR_Pub_Team__c=False,APPEAR_GPPL__c=False,APPEAR_Writing__c=False,APPEAR_Reviewers__c=False,APPEAR_FPR_Only_Submitters__c=False,
             APPEAR_626__c=False,APPEAR_FPRC__c=True,APPEAR_International_FPRC__c=True,APPEAR_Business_Admin__c=True,System_Admin__c=True));         
         ProfileTabTileList.add( new ProfileTabTile__c(Name='Transfer of Value',Profile_Tab__c=ProfileTabModel.ProfileTabNameMap.get('Publication Tab').Id,
             APPEAR_Pub_Team__c=False,APPEAR_GPPL__c=False,APPEAR_Writing__c=False,APPEAR_Reviewers__c=False,APPEAR_FPR_Only_Submitters__c=False,
             APPEAR_626__c=False,APPEAR_FPRC__c=True,APPEAR_International_FPRC__c=True,APPEAR_Business_Admin__c=True,System_Admin__c=True));                 

         ProfileTabTileList.add( new ProfileTabTile__c(Name='Pub Details',Profile_Tab__c=ProfileTabModel.ProfileTabNameMap.get('FPR Tab').Id,
             APPEAR_Pub_Team__c=False,APPEAR_GPPL__c=True,APPEAR_Writing__c=True,APPEAR_Reviewers__c=True,APPEAR_FPR_Only_Submitters__c=True,
             APPEAR_626__c=False,APPEAR_FPRC__c=True,APPEAR_International_FPRC__c=True,APPEAR_Business_Admin__c=True,System_Admin__c=True));         
         ProfileTabTileList.add( new ProfileTabTile__c(Name=AppearConstants.FprOtherDetailsTile,Profile_Tab__c=ProfileTabModel.ProfileTabNameMap.get('FPR Tab').Id,
             APPEAR_Pub_Team__c=False,APPEAR_GPPL__c=False,APPEAR_Writing__c=False,APPEAR_Reviewers__c=True,APPEAR_FPR_Only_Submitters__c=True,
             APPEAR_626__c=False,APPEAR_FPRC__c=True,APPEAR_International_FPRC__c=True,APPEAR_Business_Admin__c=True,System_Admin__c=True));         
         ProfileTabTileList.add( new ProfileTabTile__c(Name='Publication Content',Profile_Tab__c=ProfileTabModel.ProfileTabNameMap.get('FPR Tab').Id,
             APPEAR_Pub_Team__c=False,APPEAR_GPPL__c=True,APPEAR_Writing__c=True,APPEAR_Reviewers__c=True,APPEAR_FPR_Only_Submitters__c=True,
             APPEAR_626__c=False,APPEAR_FPRC__c=True,APPEAR_International_FPRC__c=True,APPEAR_Business_Admin__c=True,System_Admin__c=True));         
         ProfileTabTileList.add( new ProfileTabTile__c(Name='Publications For Review',Profile_Tab__c=ProfileTabModel.ProfileTabNameMap.get('FPR Tab').Id,
             APPEAR_Pub_Team__c=False,APPEAR_GPPL__c=False,APPEAR_Writing__c=False,APPEAR_Reviewers__c=True,APPEAR_FPR_Only_Submitters__c=False,
             APPEAR_626__c=False,APPEAR_FPRC__c=True,APPEAR_International_FPRC__c=True,APPEAR_Business_Admin__c=True,System_Admin__c=True));         
         ProfileTabTileList.add( new ProfileTabTile__c(Name='Pre-FPR Reviewers',Profile_Tab__c=ProfileTabModel.ProfileTabNameMap.get('FPR Tab').Id,
             APPEAR_Pub_Team__c=False,APPEAR_GPPL__c=False,APPEAR_Writing__c=False,APPEAR_Reviewers__c=True,APPEAR_FPR_Only_Submitters__c=True,
             APPEAR_626__c=False,APPEAR_FPRC__c=True,APPEAR_International_FPRC__c=True,APPEAR_Business_Admin__c=True,System_Admin__c=True));                 

               
        insert ProfileTabTileList;
                
     }
    
}