force-app/main/default/staticresources/python/Disappear/src/objects/ProfileTab__c.object
<CustomObject>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Profile Tab</label>
    <nameField>
        <label>ProfileTab Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Profile Tabs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/ProfileTabModel.cls
public with sharing class ProfileTabModel {
	//with sharing - System Admin RW  / Rest of Profile are RO

	private static Set<string> pPubTileAccessList = null;
    public static Set<string> PubTileAccessList {
        get{
        	if (pPubTileAccessList == null) {
        		pPubTileAccessList = preparePubTileAccessList();
        	}
            return pPubTileAccessList;
        }
    }
    
    public static Set<string> preparePubTileAccessList() {
    	ProfileTab__c pubTab = ProfileTabNameMap.get('Publication Tab');
    	Set<string> pubTabTiles = ProfileTabTileModel.getProfileTabTile(pubTab);
    	
    	return pubTabTiles; 
    }
    
    private static List<ProfileTab__c> pProfileTabList = null;
    public static List<ProfileTab__c> ProfileTabList{
        get{
            if(pProfileTabList == null){
              pProfileTabList = getAllProfileTabList();
            }               
        	return pProfileTabList;
        }
    }  
    
   	private static Map<String, ProfileTab__c> pProfileTabNameMap = null;
   	public static Map<String, ProfileTab__c> ProfileTabNameMap{
		get {
			if (pProfileTabNameMap == null){
         		pProfileTabNameMap = getProfileTabMapByName();
       		}
       		return pProfileTabNameMap;
     	}
   	}
   
	public static Map<String, ProfileTab__c> getProfileTabMapByName() {
 		Map<String, ProfileTab__c> result = new Map<String, ProfileTab__c>();
    	for(ProfileTab__c pProfileTab : ProfileTabList){
      		result.put(pProfileTab.Name, pProfileTab );
    	}
    	return result;
	}
      
    public static List<ProfileTab__c> getAllProfileTabList(){
        List<ProfileTab__c> result = [
			select id, Name, Comment__c
          	From ProfileTab__c
          	order by Name  
		];
        return result;
    }
}