force-app/main/default/staticresources/python/Disappear/src/objects/ProvisionDocumentVersion__c.object
<CustomObject>
    <fields>
        <fullName>ProvisionDocumentContent__c</fullName>
        <label>ProvisionDocumentContent</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <label>ProvisionDocumentVersion</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ProvisionDocumentVersion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ProvisionDocumentVersions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/AppearPubAuthorControllerTest.cls
@IsTest
public class AppearPubAuthorControllerTest {

	@IsTest
	public static void unitTest() {		
		Publication__c  newPub = UnitTestData.PublicationNew('Author Controller Pub');
		
		Test.setCurrentPageReference(new PageReference('Page.appearpubauthordashboard')); 
		System.currentPageReference().getParameters().put(AppearConstants.PUBID, newPub.id);		
		System.currentPageReference().getParameters().put(AppearConstants.TILE, AppearConstants.AuthorPubDetailsTile);
		ProvisionDocumentVersion__c provdoc = new ProvisionDocumentVersion__c();
		Provdoc.ProvisionDocumentContent__c ='testing123';
		insert provdoc;
		AppearPubAuthorController authorController = new AppearPubAuthorController();
		 
		System.assertNotEquals(null, authorController);
		System.assertNotEquals(null, AppearBaseController.AmgenAppearTitle);
		System.assertEquals(true, AppearBaseController.AppearShowChatter);
		authorController.AppearAddErrorMessage('test');
		System.assertNotEquals(null, authorController.RedirectHomeTab());
		
		System.assertNotEquals(null, authorController.ActivePubId);
		System.assertNotEquals(null, authorController.ActivePub);
		System.assertNotEquals(null, authorController.ParamMenu);	
		System.assertNotEquals(null, authorController.PcSubMenus);		
		System.assertNotEquals(null, authorController.PcTiles);
		System.assertNotEquals(null, authorController.TileBar);
		
		authorController.hideAllViews();
		authorController.unSelectAllSubMenus();  
		
	}

}