force-app/main/default/staticresources/python/Disappear/src/objects/ProvisionDocumentVersion__c.object
<CustomObject>
    <fields>
        <fullName>ProvisionDocumentContent__c</fullName>
        <label>ProvisionDocumentContent</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <label>ProvisionDocumentVersion</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ProvisionDocumentVersion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ProvisionDocumentVersions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/ProvisionDocumentVersionTriggerTests.cls
@isTest
public with sharing class ProvisionDocumentVersionTriggerTests {
    @isTest
    private static void TestProvisionUpdateRejection() {
        ProvisionDocumentVersion__c newDoc = new ProvisionDocumentVersion__c();
        newDoc.ProvisionDocumentContent__c = '<p>test</p>';
        insert newDoc;
        
        ProvisionDocumentVersion__c docToUpdate = [select ProvisionDocumentContent__c from ProvisionDocumentVersion__c where id = :newDoc.Id];
        docToUpdate.ProvisionDocumentContent__c = '<p>updated</p>';
        
        try{update docToUpdate;}
        catch(DMLException ex) {
        
        }
    }
}