force-app/main/default/staticresources/python/Disappear/src/objects/ProvisionDocumentVersion__c.object
<CustomObject>
    <fields>
        <fullName>ProvisionDocumentContent__c</fullName>
        <label>ProvisionDocumentContent</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <label>ProvisionDocumentVersion</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>ProvisionDocumentVersion Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ProvisionDocumentVersions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/pubAuthor__c.object
<CustomObject>
    <fields>
        <fullName>Author__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Author</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Publication Authors</relationshipLabel>
        <relationshipName>Publication_Authors</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Disclaimer_ID__c</fullName>
        <description>Contains the ID of the invite disclaimer used</description>
        <label>Invite Disclaimer ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Publication Authors</relationshipLabel>
        <relationshipName>Publication_Authors</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Publication Author</label>
    <nameField>
        <displayFormat>PA-{0000000}</displayFormat>
        <label>Publication Author Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/AuthorLandingPageControllerTest.cls
@IsTest
public class AuthorLandingPageControllerTest {

  private static void createData() {
        OrganizationModelData.createData();
        DepartmentModelData.createData();
        AccountModelData.createData();
        AppearContactModelData.createData();
  }

    @IsTest
    public static void UnitTest() {    
        createData();
        System.Test.startTest();
        document d = new Document();
        d.Name='Author Invitation Disclaimer';
        d.AuthorId = UserInfo.getUserId();
        d.FolderId = UserInfo.getUserId();
        insert d;
 
        ProvisionDocumentVersion__c prov = new ProvisionDocumentVersion__c ();
        prov.ProvisionDocumentContent__c = 'Test';
        insert prov;
        
        Publication__c pub = UnitTestData.PublicationNew('AuthorInvitationLandingPage');  
        Publication__c clonePub = UnitTestData.newPublication('AuthorInvitation');
        List<Contact> appearContacts = [Select id, FirstName from Contact limit 3];
        pubAuthor__c pubauthor = new pubAuthor__c();
        pubauthor.Publication__c  = pub.id;
        pubauthor.author__c= appearContacts[0].id;
        pubauthor.Disclaimer_ID__c = prov.id;
        insert pubauthor;
        
        
        AppearPubModel pubModel = new AppearPubModel(pub.id);
        
        PageReference pageRef = new PageReference('/apex/AuthorInvitationLandingPage');
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('PubAuthorId', pubauthor.id);
        
        AuthorInvitationLandingPageController  AuthorLanding= new AuthorInvitationLandingPageController();
         
        PageReference p= AuthorLanding.getContentVersionPage();
        PageReference p1 = AuthorLanding.AppearPubAuthor();
        PageReference p2 = AuthorLanding.CancelAppearPubAuthor();
        AuthorLanding.getcomptype();
        AuthorLanding.setcomptype('test');
        System.Test.stopTest();
        
        }
    }