force-app/main/default/staticresources/python/Disappear/src/objects/Pub_Prod_Ind__c.object
<CustomObject>
    <fields>
        <fullName>Product_Indication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Product Indication</label>
        <referenceTo>ProductIndication__c</referenceTo>
        <relationshipLabel>Publication Product  Indications</relationshipLabel>
        <relationshipName>Publication_Product_Indications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Publication Product  Indications</relationshipLabel>
        <relationshipName>Publication_Product_Indications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publication Product  Indication</label>
    <nameField>
        <label>Publication Product  Indication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publication Product  Indications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <fields>
        <fullName>IsSelected__c</fullName>
        <defaultValue>false</defaultValue>
        <description>for UI operation - please do not store or migrate data into this field</description>
        <label>IsSelected</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Indication__c</fullName>
        <description>A READ ONLY string that list all product Indications for the Publication
The key product indication will be list at the first entry</description>
        <inlineHelpText>Product - Indication is a required field that is available for selection when a publication is first saved. Once saved, the Product Indication may be edited using the Product Indication button.</inlineHelpText>
        <label>Product - Indication</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/PubScientificStatementModelTest.cls
@IsTest
public class PubScientificStatementModelTest {
    public static void createData() {
        TherapeuticAreaModelData.createData();
        AmgenProductModelData.createData();
        IndicationModelData.createData();
        ProductIndicationModelData.createData();
        ProdIndiObjectiveModelData.createData();        
        ProdIndObjSciStatementModelData.createData();
    }
    
    
    
    
    @IsTest
    public static void TestAddAndRetrieveStatements() {     
        createData();
        
        Publication__c pub = UnitTestData.PublicationNew('PubScientificStatementModelTest');
      
        Pub_Prod_Ind__c pubProdInd = new Pub_Prod_Ind__c(name='PubPI 1', Product_Indication__c=ProductIndicationModel.ProductIndicationNameMap.get('Aranesp - CKD Not Dialysis').Id, Publication__c=pub.Id);
        insert pubProdInd;        
        
        AppearPubModel pubModel = new AppearPubModel(pub.Id);             
        System.Test.startTest();   
        
        System.AssertNotEquals(0, pubModel.PubProdIndication.ProdIndListForPub.size());   
        System.AssertNotEquals(0, pubModel.PubScientificStatement.AllPubObjectives.size());
        
        pubModel.PubScientificStatement.AllPubObjectives[0].IsSelected__c = true;
        System.AssertNotEquals(0, pubModel.PubScientificStatement.AllPubScientificStatements.size());
        
        pubModel.PubScientificStatement.AllPubScientificStatements[0].IsSelected__c = true;
        pubModel.PubScientificStatement.saveSelectedObjectivesSciStatements();
        pubModel.PubScientificStatement.save();
        
        System.AssertNotEquals(0, PubScientificStatementModel.PubSciStmtList.size());
        System.AssertNotEquals(0, PubScientificStatementModel.PubSciStmtNameMap.size());
        pubModel.PubScientificStatement.cancel();
        pubModel.PubScientificStatement.AllPubScientificStatements[0].IsSelected__c = true;
        pubModel.PubScientificStatement.deleteSelected();   
        
        
        System.Test.stopTest(); 
    }
    
    @IsTest
    public static void TestClone() {
        createData();
        
        Publication__c pub = UnitTestData.PublicationNew('PubScientificStatementModelTest');
        Publication__c clonePub = UnitTestData.newPublication('PubScientificStatementModelTest2');
        
        System.Test.startTest();   
        PubScientificStatementModel.clone(pub.Id, clonePub.Id);
        System.Test.stopTest(); 
    }
}