force-app/main/default/staticresources/python/Disappear/src/objects/pubAuthor__c.object
<CustomObject>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Publication Authors</relationshipLabel>
        <relationshipName>Publication_Authors</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Publication Author</label>
    <nameField>
        <displayFormat>PA-{0000000}</displayFormat>
        <label>Publication Author Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <fields>
        <fullName>isEnbrel__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to manage the sharing with those users that should not have access to Enbrel pubs</description>
        <label>isEnbrel</label>
        <type>Checkbox</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PublicationPreFprReviewer__c.object
<CustomObject>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>PublicationPreFprReviewer</relationshipLabel>
        <relationshipName>PublicationPreFprReviewer</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Publication PreFPR Reviewer</label>
    <nameField>
        <displayFormat>PubPreFpr-{00000000}</displayFormat>
        <label>Publication PreFPR Reviewer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication Pre FPR Reviewers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PublicationTeamMember__c.object
<CustomObject>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipName>PublicationTeams</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Publication Team Member</label>
    <nameField>
        <displayFormat>PubT-{00000000}</displayFormat>
        <label>PublicationTeam Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PubME__c.object
<CustomObject>
    <description>Record all Manuscript Equivalent points award to authors and others for their work on a publication</description>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Publication MEs</relationshipLabel>
        <relationshipName>Publication_MEs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Publication ME</label>
    <nameField>
        <displayFormat>PME-{000000000}</displayFormat>
        <label>Publication ME Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication MEs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PubRelated__c.object
<CustomObject>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipName>PubRelated</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Publication Related</label>
    <nameField>
        <displayFormat>pr-{0000000}</displayFormat>
        <label>PubRelated Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publications Related</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PubReviewTeam__c.object
<CustomObject>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipName>PubReviewTeams</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Publication Review Team Member</label>
    <nameField>
        <displayFormat>PRT-{000000000}</displayFormat>
        <label>PubReviewTeamId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication Review Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PubScientificStatement__c.object
<CustomObject>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Publication Scientific Statements</relationshipLabel>
        <relationshipName>Publication_Scientific_Statements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publication Scientific Statement</label>
    <nameField>
        <label>Publication Scientific Statement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publication Scientific Statements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PubStudy__c.object
<CustomObject>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipName>PubStudies</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publication Study/Project</label>
    <nameField>
        <label>PubStudy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publication Studies/Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/MigratePubOwnershipUtil.cls
public with sharing class MigratePubOwnershipUtil {
	
	//@future
	public static void migratePubAndJunctionOwnership(id fromUserId, id toUserId) {
		if (fromuserId == null || toUserId == null) {
			return;
		}
		
		//PubAuthor
		List<pubAuthor__c> ownedPubAuthors = [Select OwnerId, Id from pubAuthor__c where OwnerId =: fromUserId];
		if (ownedPubAuthors.size() > 0) {
			for(pubAuthor__c pubAuthor : ownedPubAuthors) {
				pubAuthor.OwnerId = toUserId;
			}
			update ownedPubAuthors;
		}
		
		//PublicationPreFprReviewer
		List<PublicationPreFprReviewer__c> ownedPreFprReviewers = [Select OwnerId, Id from PublicationPreFprReviewer__c where OwnerId =: fromUserId];
		if (ownedPreFprReviewers.size() > 0) {
			for(PublicationPreFprReviewer__c preFprReviewer : ownedPreFprReviewers) {
				preFprReviewer.OwnerId = toUserId;
			}
			update ownedPreFprReviewers;
		}
		
		//PublicationTeamMember
		List<PublicationTeamMember__c> ownedTeamMembers = [Select OwnerId, Id from PublicationTeamMember__c where OwnerId =: fromUserId];
		if (ownedTeamMembers.size() > 0) {
			for(PublicationTeamMember__c teamMember : ownedTeamMembers) {
				teamMember.OwnerId = toUserId;
			}
			update ownedTeamMembers;
		}
		
		//PubME
		List<PubME__c> ownedPubMEs = [Select OwnerId, Id from PubME__c where OwnerId =: fromUserId];
		if (ownedPubMEs.size() > 0) {
			for(PubME__c pubME : ownedPubMEs) {
				pubME.OwnerId = toUserId;
			}
			update ownedPubMEs;
		}		
		
		//PubRelated
		List<PubRelated__c> ownedPubRelateds = [Select OwnerId, Id from PubRelated__c where OwnerId =: fromUserId];
		if (ownedPubRelateds.size() > 0) {
			for(PubRelated__c pubRelated : ownedPubRelateds) {
				pubRelated.OwnerId = toUserId;
			}
			update ownedPubRelateds;
		}
		
		//PubReviewTeam
		List<PubReviewTeam__c> ownedPubReviewTeams = [Select OwnerId, Id from PubReviewTeam__c where OwnerId =: fromUserId];
		if (ownedPubReviewTeams.size() > 0) {
			for(PubReviewTeam__c pubReviewTeam : ownedPubReviewTeams) {
				pubReviewTeam.OwnerId = toUserId;
			}
			update ownedPubReviewTeams;
		}
		
		//PubScientificStatement
		List<PubScientificStatement__c> ownedPubSciStatements = [Select OwnerId, Id from PubScientificStatement__c where OwnerId =: fromUserId];
		if (ownedPubSciStatements.size() > 0) {
			for(PubScientificStatement__c pubScientificStatement : ownedPubSciStatements) {
				pubScientificStatement.OwnerId = toUserId;
			}
			update ownedPubSciStatements;
		}
		
		//PubStudy
		List<PubStudy__c> ownedPubStudies = [Select OwnerId, Id from PubStudy__c where OwnerId =: fromUserId];
		if (ownedPubStudies.size() > 0) {
			for(PubStudy__c pubStudy : ownedPubStudies) {
				pubStudy.OwnerId = toUserId;
			}
			update ownedPubStudies;
		}
		
		//Publication
		List<Publication__c> ownedPubs = [
			Select OwnerId, RecordTypeId, Id, isEnbrel__c 
			from Publication__c 
			where OwnerId =: fromUserId
		];
		
		if (ownedPubs.size() > 0) {
			for(Publication__c ownedPub : ownedPubs) {
				
				AppearPubModelShare pubShare = new AppearPubModelShare(ownedPub.Id, ownedPub.RecordTypeId, ownedPub.isEnbrel__c);
				pubShare.resetAllApexSharing();
				
				ownedPub.OwnerId = toUserId;
			}
			database.update(ownedPubs, false);

			//for FPR Submitter to merge with platform id
			//reset sharing one more than after owner changed.
			for(Publication__c ownedPub : ownedPubs) {
				AppearPubModel activePub = new AppearPubModel(ownedPub.Id);
				activePub.resetSharing();
			}

		}
	}

}