force-app/main/default/staticresources/python/Disappear/src/objects/PubAttachmentDetails__c.object
<CustomObject>
    <description>Junction object of a Blob [  attachment / Chatter Feed / Document etc ]  &amp; Pub

since we cannot add custom fields to attachment 
and need a unified way to extract a list of all documents related to a pub</description>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Attachment Details</relationshipLabel>
        <relationshipName>Attachment_Details</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>What__c</fullName>
        <description>similar to WhatId in Activities - the what field stored the salesforce Id of the Blob
Can be Attachment, Content or Item Feed

Stored id as text since we cannot relates to Attachment, Content or ItemFeed</description>
        <label>What</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isSharedWithCommunity__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To remove from the batch, to share it with all the community users</description>
        <label>isSharedWithCommunity</label>
        <type>Checkbox</type>
    </fields>
    <label>Attachment Detail</label>
    <nameField>
        <displayFormat>AD-{000000000}</displayFormat>
        <label>AttachDetailId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attachment Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/BatchSharePubAttachmentsTest.cls
@isTest
public class BatchSharePubAttachmentsTest {
    @isTest
    private static void unitTest() {
        CreateData();       
        
        List<FeedItem> allFeedItems = [Select id From FeedItem];
        System.assertEquals(1, allFeedItems.size());
        
        
        List<ContentVersion> allContentVersions = [Select id From ContentVersion];
        System.assertEquals(1, allContentVersions.size());
        
        BatchSharePubAttachments.runNow();
        
        
    } 
    
    private static void CreateData() {
        Publication__c testPub = UnitTestData.PublicationNew('BatchSharePubAttachmentsTestPub');
        
        FeedItem pubFeedItem = new FeedItem();
        pubFeedItem.ContentFileName = 'testFile.txt';
        pubFeedItem.ContentData = blob.valueOf('BatchSharePubAttachmentsTestPub');
        pubFeedItem.ParentId = testPub.Id;
        pubFeedItem.Type = 'ContentPost';       
        insert pubFeedItem;
        
        PubAttachmentDetails__c pubAttachmentDetails = new PubAttachmentDetails__c(What__c = pubFeedItem.Id,issharedwithcommunity__c= false, Publication__c = testPub.Id);
        insert pubAttachmentDetails;
    }
}