force-app/main/default/staticresources/python/Disappear/src/objects/PubAttachmentDetails__c.object
<CustomObject>
    <description>Junction object of a Blob [  attachment / Chatter Feed / Document etc ]  &amp; Pub

since we cannot add custom fields to attachment 
and need a unified way to extract a list of all documents related to a pub</description>
    <fields>
        <fullName>AttachmentType__c</fullName>
        <description>Indicate the type of &apos;Blob&apos; this detail record describes</description>
        <label>AttachmentType</label>
        <picklist>
            <picklistValues>
                <fullName>Publication Proposal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kick Off Meeting Minutes/Memo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Author Agreement Letter/Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft - Share with Authors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft Sent for FPR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Added by FPR Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Added by FPR Reviewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final Attachment for Author Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Author Approvals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Author Contribution(s)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted Version</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted Version</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Response to Author Invitation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Substantial Comments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Response to Final Author Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval to Remove Author</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Author Disclosures</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval to Add Author</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RAE Attestation Sec A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RAE Attestation Sec B</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RAE Attestation Sec C</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monitoring Checklist Part 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monitoring Checklist Part 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monitoring Checklist Part 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monitoring Checklist Part 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Author Limit Justification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Change of Pub RAE Form</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monitoring Overrule</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Attachment Details</relationshipLabel>
        <relationshipName>Attachment_Details</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Attachment Detail</label>
    <nameField>
        <displayFormat>AD-{000000000}</displayFormat>
        <label>AttachDetailId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attachment Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <fields>
        <fullName>Assigned_FPRC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned to FPR Coordinator</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Target__c</fullName>
        <description>The Current Target field will also be used to populate the Target field for a new Submission Cycle.
This field should NEVER be moved to a formula</description>
        <inlineHelpText>This field is populated automatically by using the &quot;Target&quot; button on the Details tile.  If the desired target is NOT found using the Target button, please use the &quot;Target Not Found&quot; field below.</inlineHelpText>
        <label>Current Target</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GPP_Type__c</fullName>
        <description>Used for Classification of GPP publication and mandatory for if Publication is GPP type.</description>
        <label>Publication Classification</label>
        <picklist>
            <picklistValues>
                <fullName>CSP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSP Encore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Deliverable</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Publication_Title__c</fullName>
        <inlineHelpText>This is a succinct but descriptive Title of the Publication</inlineHelpText>
        <label>Publication Title</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/Email_21_MonitoringChecklist.cls
/*
*** Class Details *** 
Email_21_MonitoringChecklist class is used to trigger email notification to Monitoring Team User DL group. Email will be triggered when RAE Checklist Part 1/2/3 type
attachment added.
NOTE** Support and Development Team need to make sure whenever any New Sandbox is created, they should change the Custom Setting value which hold the Monitoring DL 
group. Otherwise Business Users will continuously receiving emails from sandbox during any testing or development. 
*/
public with sharing class Email_21_MonitoringChecklist extends AppearEmailBase{
	
	public Email_21_MonitoringChecklist(){
		super();
	}
	
	public Email_21_MonitoringChecklist(Contact email,pubAttachmentDetails__c attachmentId,Id emailTemplateId,User userId){
		super();
		replyTo(email.email); 
        CcAddress(userId.email);
        whatId(attachmentId.id);
        templateId(emailTemplateId);
        targetObjectId(email.Id); 
	}
	
	
	
	
	@future
    public static void Email_21_MonitoringChecklistBatchLimit(Id attachmentId){        
        EmailTemplate emailTemplateId = [select id,name,Isactive,Folder.Name from EmailTemplate Where IsActive = true And (Folder.Name = 'RAE Checklist Folder') order by createdDate desc limit 1];
            
        Contact monitoringContact=[Select Id,FirstName,LastName,Email from Contact where Name = 'Monitoring Team'];
        
        PubAttachmentDetails__c pubAttachment = [Select Id, AttachmentType__c,Publication__c,Publication__r.Name,Publication__r.Current_Target__c,
        											publication__r.GPP_Type__c,publication__r.Publication_Title__c from
        											PubAttachmentDetails__c where id =:attachmentId];
        
        User currentUser = [Select email from User where username = :UserInfo.getUserName() limit 1];
           
        try {
                system.debug('Reached this place');
                Email_21_MonitoringChecklist email = new  Email_21_MonitoringChecklist(monitoringContact,pubAttachment, emailTemplateId.id, currentUser);
                if (!email.sendEmailWithResult()){
                    System.debug('Email_19_DraftShare / failed to deliver to:' + pubAttachment.Id ); 
                }
            } catch (AppearException appearEx){
                AppLogModel.LogError('Email_21_MonitoringChecklist', 'The monitoring email delivery to ' + monitoringContact.Id, pubAttachment.id);                         
                // ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, 'The attachment status email delivery to ' + pubAttachment + ' failed. Please validate if the email address is correct. If the problem persists, please contact the system administrator.' ));                       
            } catch (EmailException emailEx) {
                AppLogModel.LogError('Email_21_MonitoringChecklist', 'The monitoring email delivery to ' + monitoringContact.Id, pubAttachment.id);                     
                // ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, 'The attachment status email delivery to ' + pubAttachment+ ' failed. Please validate if the email address is correct. If the problem persists, please contact the system administrator.' + ' Error Details: ' + emailEx.getMessage()));
            } catch(DmlException dmlEx) {
                AppLogModel.LogError('Email_21_MonitoringChecklist', 'The monitoring email delivery to ' + monitoringContact.Id, pubAttachment.id);                         
                // ApexPages.addMessage(new ApexPages.Message(ApexPages.severity.ERROR, 'The attachment status email delivery to ' + pubAttachment + ' failed. Please validate if the email address is correct. If the problem persists, please contact the system administrator.' + ' Error Details: ' + dmlEx.getMessage()));
            } finally {
            	system.debug('Email Triggered');
                AppLogModel.flushLogs();
            }
                 
    }
	
}