force-app/main/default/staticresources/python/Disappear/src/objects/PubAttachmentDetails__c.object
<CustomObject>
    <description>Junction object of a Blob [  attachment / Chatter Feed / Document etc ]  &amp; Pub

since we cannot add custom fields to attachment 
and need a unified way to extract a list of all documents related to a pub</description>
    <fields>
        <fullName>AttachmentName__c</fullName>
        <label>AttachmentName</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attachment_URL__c</fullName>
        <label>Attachment URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Attachment Details</relationshipLabel>
        <relationshipName>Attachment_Details</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SiebelRowId__c</fullName>
        <externalId>true</externalId>
        <label>SiebelRowId</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Size__c</fullName>
        <description>Size of attachent in bytes</description>
        <label>Size</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>What__c</fullName>
        <description>similar to WhatId in Activities - the what field stored the salesforce Id of the Blob
Can be Attachment, Content or Item Feed

Stored id as text since we cannot relates to Attachment, Content or ItemFeed</description>
        <label>What</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Attachment Detail</label>
    <nameField>
        <displayFormat>AD-{000000000}</displayFormat>
        <label>AttachDetailId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attachment Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <fields>
        <fullName>SiebelRowId__c</fullName>
        <description>Used for legacy data mapping</description>
        <externalId>true</externalId>
        <label>SiebelRowId</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/PubAttachmentUpdateWhatWebService.cls
@RestResource(urlMapping='/PubAttachmentUpdateWhatWebService/v1/*')
global class PubAttachmentUpdateWhatWebService {

	@httpPost 
	global static string post(String pubId, String pubAttachemntSiebelId, String attachmentId, string fileName) {
		Long startTime = DateTime.now().getTime();
		
		AppLogModel.LogInfo('PubAttachmentUpdateWhatWebService::Post', 
			pubId+' : ' + pubAttachemntSiebelId + ' : '+ attachmentId+' : ' +fileName );
		
		List<PubAttachmentDetails__c> pubAttachDetails = [
			select publication__c, AttachmentName__c, Attachment_URL__c, What__c, size__c
			from PubAttachmentDetails__c
			where SiebelRowId__c = :pubAttachemntSiebelId
		];
		
		
		if ( pubAttachDetails.size() == 1) {
			PubAttachmentDetails__c pubAttch = pubAttachDetails[0];
			pubAttch.what__c = attachmentId;
			pubAttch.AttachmentName__c = fileName;
			pubAttch.Attachment_URL__c = AppearUrlModel.ChatterFeedIdToUrl(attachmentId);
			
			update pubAttch;
		} else {
			AppLogModel.LogInfo('PubAttachmentUpdateWhatWebService::Post', 
				'Cannot locate PubAttachementDetails with siebelId = '+ pubAttachemntSiebelId);
		}
							
		AppLogModel.flushLogs();  
		return 'done';
		

	}
}