force-app/main/default/staticresources/python/Disappear/src/objects/PubAttachmentDetails__c.object
<CustomObject>
    <description>Junction object of a Blob [  attachment / Chatter Feed / Document etc ]  &amp; Pub

since we cannot add custom fields to attachment 
and need a unified way to extract a list of all documents related to a pub</description>
    <fields>
        <fullName>AttachmentName__c</fullName>
        <label>AttachmentName</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attachment_URL__c</fullName>
        <label>Attachment URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Attachment Details</relationshipLabel>
        <relationshipName>Attachment_Details</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SiebelRowId__c</fullName>
        <externalId>true</externalId>
        <label>SiebelRowId</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubmissionCycle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Which Submission Cycle this attachment is from

Optional if there is no submission cycle associated with the pub at upload time</description>
        <label>Submission Cycle</label>
        <referenceTo>SubmissionCycle__c</referenceTo>
        <relationshipLabel>Attachment Details</relationshipLabel>
        <relationshipName>Attachment_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>What__c</fullName>
        <description>similar to WhatId in Activities - the what field stored the salesforce Id of the Blob
Can be Attachment, Content or Item Feed

Stored id as text since we cannot relates to Attachment, Content or ItemFeed</description>
        <label>What</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Attachment Detail</label>
    <nameField>
        <displayFormat>AD-{000000000}</displayFormat>
        <label>AttachDetailId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attachment Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <fields>
        <fullName>SiebelRowId__c</fullName>
        <description>Used for legacy data mapping</description>
        <externalId>true</externalId>
        <label>SiebelRowId</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/SubmissionCycle__c.object
<CustomObject>
    <description>record name will be PubId-{0000000}-SubCycle-{00}</description>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Submission Cycles</relationshipLabel>
        <relationshipName>Submission_Cycles</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SiebelRowId__c</fullName>
        <externalId>true</externalId>
        <label>SiebelRowId</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Submission Cycle</label>
    <nameField>
        <label>Submission Cycle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submission Cycles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/PubAttachmentUpdateWebServiceTest.cls
@IsTest
public class PubAttachmentUpdateWebServiceTest {

    public static final string pubSiebelId = 'TestPubSiebelId';
    public static final string pubAttachmentDetailsSiebelId = 'TestAttachSiebelId';
	public static final string fileName = 'TestFileName';

    @IsTest
  
    public static void UnitTest() {
		createPubWithAttachment();
    }
    
    //PubAttachmentUpdateWebServiceTest.createPubWithAttachment();
    public static void createPubWithAttachment(){
       	id pubId = createData();
    	id feedItemId = createAttachment(pubId);
    	System.assertNotEquals(null, feedItemId);
    	
    	PubAttachmentUpdateWhatWebService.post(pubId, pubAttachmentDetailsSiebelId, feedItemId, fileName); 	
    	
    	List<PubAttachmentDetails__c> details = PubAttachmentModel.getAllPubAttachmentList(Pubid);
		System.assertEquals(1, details.size());
		System.assertEquals(pubAttachmentDetailsSiebelId, details[0].SiebelRowId__c);
    	System.assertEquals(feedItemId, details[0].what__c);
    	System.assertEquals(fileName, details[0].AttachmentName__c);
    	System.assertNotEquals(null, details[0].Attachment_URL__c);
    }
    

    
    //PubAttachmentUpdateWebServiceTest.createData();
    public static id createData() {
    	cleanup();
	
		Publication__c testpub = UnitTestData.PublicationNew('PubAttachmentUpdateWebServiceTest');
		System.assertNotEquals(null, testpub.id);
		testpub.SiebelRowId__c = pubSiebelId;
		update testpub;
		
		AppearPubModel activePub = new AppearPubModel(testPub.id);
		System.assert(activePub.hasValidPub);
		System.assertEquals(pubSiebelId, activePub.pubRecord.SiebelRowId__c);
		
		PubAttachmentDetails__c attachment = activePub.PubAttachments.getNewAttachment();
		attachment.SubmissionCycle__c = activePub.CurrentSubmissionCycleId;
		attachment.SiebelRowId__c = pubAttachmentDetailsSiebelId;
		attachment.What__c = 'missing';
		insert attachment; 
		//activePub.PubAttachments.InsertAttachment(attachment);
		
		List<PubAttachmentDetails__c> details = PubAttachmentModel.getAllPubAttachmentList(testPub.id);
		System.assertEquals(1, details.size());
		System.assertEquals(pubAttachmentDetailsSiebelId, details[0].SiebelRowId__c);
		
		return testpub.id;
    }  
    
    //create a dump attachment 
    public static id createAttachment(id parentId) {
    	
    	FeedItem item = new FeedItem();
    	item.Title = 'test FeedItem';
    	item.Body = 'just a dummy string for a feed item';
    	item.ParentId = ParentId;
    	insert item;
    	
    	return item.id;
    	
    }
    
    
    
    public static void cleanup() {
     	
    	List<PubAttachmentDetails__c> oldDetails= [select id from PubAttachmentDetails__c where SiebelRowId__c = :pubAttachmentDetailsSiebelId];
    	if ( oldDetails.size() > 0 ) {
    		delete oldDetails;
    	}
    	List<Publication__c> oldPubs = [select id from Publication__c where SiebelRowId__c = :pubSiebelId];
    	if ( oldPubs.size() > 0) {
    		for ( Publication__c pub : oldPubs) {
    			AppearPubModel.DeletePub(pub.id);
    		}
    	}   	
    }
}