force-app/main/default/staticresources/python/Disappear/src/objects/PubAttachmentDetails__c.object
<CustomObject>
    <description>Junction object of a Blob [  attachment / Chatter Feed / Document etc ]  &amp; Pub

since we cannot add custom fields to attachment 
and need a unified way to extract a list of all documents related to a pub</description>
    <fields>
        <fullName>Attachment_URL__c</fullName>
        <label>Attachment URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Attachment Details</relationshipLabel>
        <relationshipName>Attachment_Details</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>What__c</fullName>
        <description>similar to WhatId in Activities - the what field stored the salesforce Id of the Blob
Can be Attachment, Content or Item Feed

Stored id as text since we cannot relates to Attachment, Content or ItemFeed</description>
        <label>What</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isSharedWithCommunity__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To remove from the batch, to share it with all the community users</description>
        <label>isSharedWithCommunity</label>
        <type>Checkbox</type>
    </fields>
    <label>Attachment Detail</label>
    <nameField>
        <displayFormat>AD-{000000000}</displayFormat>
        <label>AttachDetailId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attachment Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <recordTypes>
        <fullName>Execute</fullName>
        <active>true</active>
        <label>Execute</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/BatchSharePubAttachments.cls
global class BatchSharePubAttachments extends BatchBase 
    implements Database.Batchable<SObject>,Database.Stateful {
    
    public String SOQL = 'select Publication__c, What__c from PubAttachmentDetails__c where isSharedWithCommunity__c = false and what__c !=\'00-00\' and  Attachment_URL__c != null';
    
    public BatchSharePubAttachments() {
        super();
        if ( Test.isRunningTest()){
            SOQL = SOQL + ' limit 10';
        }
        else {
    		SOQL = SOQL + ' and createdDate < 2014-01-12T00:00:00.00z limit 45000';  //45000 records maximum 
    	}
        AddMessage(SOQL);
        system.debug(SOQL);
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        batchableContext = BC;
        batchName = 'BatchSharePubAttachments';
        System.Debug(SOQL);
        return Database.getQueryLocator(SOQL);
    }
    

    global void execute(Database.BatchableContext BC, List<PubAttachmentDetails__c> attachments){
        Map<Id,Id> feedItemIdToPubIdMap = new Map<Id,Id>();//used for query
        for(PubAttachmentDetails__c attachment : attachments) {
            feedItemIdToPubIdMap.put(attachment.What__c, attachment.Publication__c);
            attachment.isSharedWithCommunity__c = true;
        }
        
        
        
        List<FeedItem> relatedFeedItems = [SELECT Id, RelatedRecordId FROM FeedItem WHERE Id in :feedItemIdToPubIdMap.keySet()];
        List<FeedItem> feedItemsToInsert = new List<FeedItem>();
        for(FeedItem relatedFeedItem : relatedFeedItems) {
            Id pubId = feedItemIdToPubIdMap.get(relatedFeedItem.Id);
            Id contentVersionId = relatedFeedItem.RelatedRecordId;
            if (pubId == null || contentVersionId == null) {
                continue;
            }
            
            FeedItem pubFeedItem = new FeedItem();
            pubFeedItem.RelatedRecordId = contentVersionId;
            pubFeedItem.ParentId = pubId;
            pubFeedItem.Type = 'ContentPost';
            pubFeedItem.Visibility = 'AllUsers';
            feedItemsToInsert.add(pubFeedItem);
        }
        
        if (feedItemsToInsert.size() > 0) {
            insert feedItemsToInsert;
        }
        
        update attachments;
                
        AppLogModel.flushLogs();
    }
    

    global void finish(Database.BatchableContext BC){
        SendBatchCompletionEmail();
    }
    
    public static void runNow(){
        BatchSharePubAttachments batch = new BatchSharePubAttachments();
        Database.executeBatch(batch, 1000);
    }
}