force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <fields>
        <fullName>Assigned_FPRC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned to FPR Coordinator</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FPR_Due_Date__c</fullName>
        <inlineHelpText>As best practice, select an FPR due date that is more than 10 business days from today. If this is a rush request, provide business justification in the Comments for FPR Coordinator section and we will try to facilitate your request.</inlineHelpText>
        <label>FPR Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FPR_Submitter__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>FPR_Submitter will record the latest person that click on the Submit to FPR button.

DO NOT USE this field to check if a pub is an FPR Only Pub</description>
        <label>FPR Submitter</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Publication (FPR Submitter)</relationshipLabel>
        <relationshipName>FPR_Submitter</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/Email_01_FprcConfirmationForSubmitter.cls
public class Email_01_FprcConfirmationForSubmitter  extends AppearEmailBase{

	
	public Email_01_FprcConfirmationForSubmitter(publication__c pub) {
		super(pub, 'Email_01_FprcConfirmationForSubmitter'); 

		subject('FPR '+pub.Name+', Due: '+pub.FPR_Due_Date__c.format() +' has been Assigned to an FPR Coordinator');

		Contact toContact = AppearContactModel.findContactByContactId(pub.FPR_SUBMITTER__C );
		Contact fprcContact = AppearContactModel.findContactByContactId(pub.Assigned_FPRC__c);
		if ( toContact == null) {
			//cannot send email with toContact == null
			AppLogModel.LogError('Email_01_FprcConfirmationForSubmitter', 'ToContact == null.  Cannot send email',pub.id);
			AppLogModel.flushLogs();
			return;
		}
		
		ToAddress(toContact.Email);
  
		string htmlBodyStr =
			'Do not reply to this email message.<br><br>' +
			'FPR '+pub.Name+' has been assigned to ' + fprcContact.Name + ' for processing.' +
			'Contact your assigned FPR Coordinator if you have questions or need support.<br><br>' +
			'Thank you,<br>' +
			'FPR System<br>'; 

		htmlBody(htmlBodyStr);
		plainTextBody(htmlBodyStr.replace('<br>', '\\r\\n'));
	}

	//Email_01_FprcConfirmationForSubmitter.testEmail()
	public static void testEmail() {
		Publication__c pub = EmailPubReviewTeam.testPub.pubRecord;
		
		Email_01_FprcConfirmationForSubmitter email = new Email_01_FprcConfirmationForSubmitter(pub);
		email.sendEmail();
	}  
	

}