force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <fields>
        <fullName>IsSelected__c</fullName>
        <defaultValue>false</defaultValue>
        <description>for UI operation - please do not store or migrate data into this field</description>
        <label>IsSelected</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PASS__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Related to the associated oublication study/project</description>
        <label>PASS</label>
        <type>Checkbox</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PubStudy__c.object
<CustomObject>
    <fields>
        <fullName>IsLogicallyDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Expired</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsSelected__c</fullName>
        <defaultValue>false</defaultValue>
        <description>IsSelected is used for UI Operation - please do not store or migrate data in this field</description>
        <label>IsSelected</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PASS__c</fullName>
        <formula>Study__r.PASS__c</formula>
        <label>PASS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipName>PubStudies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Study__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Study</label>
        <referenceTo>Study__c</referenceTo>
        <relationshipName>PubStudies</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publication Study/Project</label>
    <nameField>
        <label>PubStudy Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publication Studies/Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Study__c.object
<CustomObject>
    <fields>
        <fullName>Acronym__c</fullName>
        <label>Acronym</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IsLogicallyDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Expired</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Latest_Study_status__c</fullName>
        <label>Latest Study/Project Status</label>
        <picklist>
            <picklistValues>
                <fullName>Accrued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSR Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proposed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PASS__c</fullName>
        <defaultValue>false</defaultValue>
        <description>PASS field/flag for tracking.</description>
        <label>PASS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Posted_on_ClinTrials__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Posted on Clinical Trials</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Study_Phase__c</fullName>
        <label>Study/Project Phase</label>
        <picklist>
            <picklistValues>
                <fullName>Investigator Initiated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phase 0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phase 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phase 1a</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phase 1b</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phase 1b/2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phase 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phase 2/3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phase 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phase 3b</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phase 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PreClinical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phase 1/2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Study_Type__c</fullName>
        <label>Study/Project Type</label>
        <picklist>
            <picklistValues>
                <fullName>Analysis of existing Data</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chart Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clinical Trial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cross-sectional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Epidemiology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Follow-up Study</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health Econ Study</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Vitro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MUE/DUE Study</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PK-PD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PreClinical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registry Study</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registry/Observational</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <type>TextArea</type>
    </fields>
    <label>Study/Project</label>
    <nameField>
        <label>Study/Project #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Studies/Projects</pluralLabel>
    <recordTypes>
        <fullName>Study</fullName>
        <active>true</active>
        <label>Study</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/PubStudyModel.cls
public with sharing class PubStudyModel extends AppearBaseModel {
    private id PubId;
    private string ActiveTile;
    private string ActiveSubMenu;
    private boolean isFprSubmitter;
    public boolean hasEditAccess {get; private set;}
    
    
    private  List<PubStudy__c> pPubStudyList= null;
    public  List<PubStudy__c> PubStudyList{
        get{
            if(pPubStudyList== null){
              pPubStudyList= getAllPubStudyList(this.PubId);
            }               
        return pPubStudyList;
        }
    }  
    
    //constructor
    public PubStudyModel(Id PubId, string tile, string subMenu, boolean isFprOnly, boolean hasEditAccess) {
        this.PubId = PubId; 
        this.ActiveTile = tile;
        this.ActiveSubMenu = subMenu;
        this.isFprSubmitter = isFprOnly;
        this.hasEditAccess = hasEditAccess;
    }
     
    //Logical Delete  
    public PageReference deleteSelected() {
        Boolean recordHasDates = false;
        id PubId = pPubStudyList[0].Publication__c;
        List<PubStudy__c> itemsToDelete = new List<PubStudy__c>();
        for(PubStudy__c p : pPubStudyList){
            if (p.isSelected__c) {
                itemsToDelete.add(p);
            }
        }
        database.delete(itemsToDelete, false);  
        pPubStudyList = null;   
        setupMiscFromProdStudy(PubId);
        
        return new PageReference(isFprSubmitter ? AppearUrlModel.AppearFprSubmitterMenuUrl(ActiveSubMenu, ActiveTile, PubId) : AppearUrlModel.AppearPubMenuUrl(ActiveSubMenu, ActiveTile, PubId));
    }  

    private string pStudyProjectId = '';
    public string StudyProjectId{
        get {
            return pStudyProjectId;
        }
        set {
            pStudyProjectId = value;
        }
    }
    public string StudyProjectName{get;set;}
    
    public PageReference saveNewPubStudy() {
        AppLogModel.LogDebug('PubStudyModel::saveNewPubStudy', 'invoking saveNewPubStudy');

        if ( pStudyProjectId <> ''){
            Study__c study = StudyModel.findStudyById(pStudyProjectId);
            
            if ( study == null) {
                //invalid id for study - abort
                AppLogModel.LogError('PubStudyModel::saveNewPubStudy', 'Invalid id for study - abort for '+ pStudyProjectId);
                AppLogModel.flushLogs();
                return new PageReference(isFprSubmitter ? AppearUrlModel.AppearFprSubmitterMenuUrl(ActiveSubMenu, ActiveTile, PubId) : AppearUrlModel.AppearPubMenuUrl(ActiveSubMenu, ActiveTile, PubId));
            }
            
            PubStudy__c pubStudy = new PubStudy__c();
            pubStudy.publication__c = pubId;
            pubStudy.Study__c = study.id;
            
            //insert pubStudy;  //Appear Enhancement R2: Historical Publication fix for Validation Rules
            try{
                insert pubStudy;
            }catch (DmlException err) {
                ApexPages.addMessages(err);
                return null;
            }
            
            /* //Moved logic to PubStudyTrigger+PubStudyTriggerLogic
           Publication__c pubCheckPass  = [select id, Pass__c from Publication__c where id =: pubId];

            
           boolean pstudy = Study.Pass__c;
            pubCheckPass.Pass__c = pstudy;
            update pubCheckPass  ;
         */
            setupMiscFromProdStudy(pubId);
           
            AppLogModel.LogDebug('PubStudyModel::saveNewPubStudy', 'Created new PubStudy record for '+PubId +' '+ study.id);

            AppLogModel.flushLogs();
            return new PageReference(isFprSubmitter ? AppearUrlModel.AppearFprSubmitterMenuUrl(ActiveSubMenu, ActiveTile, PubId) : AppearUrlModel.AppearPubMenuUrl(ActiveSubMenu, ActiveTile, PubId));
        } else {
            AppLogModel.LogError('PubStudyModel::saveNewPubStudy', 'whats going on');
        }
        
        AppLogModel.flushLogs();
        return new PageReference(isFprSubmitter ? AppearUrlModel.AppearFprSubmitterMenuUrl(ActiveSubMenu, ActiveTile, PubId) : AppearUrlModel.AppearPubMenuUrl(ActiveSubMenu, ActiveTile, PubId));
    
    }
    
    public static void setupMiscFromProdStudy(id pubId) {
        list<PubStudy__c> Pubstudies = getAllPubStudyList(PubId);
        set<String> studyids = new set <String>();
        for(PubStudy__c pbs : Pubstudies){
            studyids.add(pbs.Study__r.Name);
        }
        String Projectstudystring='';
        for(String st: studyids){
            Projectstudystring  = (Projectstudystring <> '') ?  Projectstudystring + ', ':'';
            Projectstudystring = Projectstudystring + st;
        } 
        AppearPubModel activePub = new AppearPubModel(PubId);  
        activePub.UpdateProjectstudy(PubId, Projectstudystring);
    }
    
    public static boolean CheckDupStudyForPub(id PubId, Id studyId){
        list<pubStudy__c> ps = [
            select id
            from PubStudy__c
            where publication__c = :pubId 
            and id = :studyId
        ];
        if ( ps.size() == 0) {
            return false;
        } else {
            return true;
        }
    }
    
    public boolean canAddDelStudies {
        get{
            return !(ProfileModel.isAppearReviewers && !isFprSubmitter)  &&  hasEditAccess;
        }
    }
    
    public static List<PubStudy__c> getAllPubStudyList(Id PubId){
        if ( PubId == null) {
            return null;
        }
        List<PubStudy__c> result = [
            select id, Name, Publication__c, IsSelected__c,
            Study__c, Study__r.RecordTypeId, Study__r.Title__c,Study__r.Acronym__c,
            Study__r.Name,Study__r.Latest_Study_status__c,IsLogicallyDeleted__c,
            Study__r.Study_Type__c,Study__r.Study_Phase__c,Study__r.Posted_on_ClinTrials__c,
            Study__r.RecordType.Name
            From PubStudy__c
            where Publication__c = :PubId
            and isLogicallyDeleted__c = false
            order by Study__r.Title__c  
        ];
        return result;
    }
    //
    
    /////////////// clone ///////////////
    public static void clone(Id origPubId, Id destCloneId) {
        AppLogModel.LogInfo('PubStudyModel::clone', 'starting ' );

        
        List<PubStudy__c> origList = getAllPubStudyList(origPubId);
        
        List<PubStudy__c> destList = new List<PubStudy__c>();
        for(PubStudy__c record : origList){
            if ( record.IsLogicallyDeleted__c == false) {
                PubStudy__c clone = record.clone(false, true, false, false);
                clone.Publication__c = destCloneId;
                destList.add(clone); 
            }
        }
        
        insert destList;
    }
}