force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <fields>
        <fullName>PubStatus__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Current status of this publication</description>
        <label>PubStatus</label>
        <referenceTo>PubStatus__c</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <recordTypes>
        <fullName>Assigned_to_FPRC</fullName>
        <active>true</active>
        <label>Assigned to FPRC</label>
    </recordTypes>
    <recordTypes>
        <fullName>In_FPR</fullName>
        <active>true</active>
        <label>In FPR</label>
    </recordTypes>
    <recordTypes>
        <fullName>LegacyFPROnly</fullName>
        <active>true</active>
        <description>Siebel Legacy FPR Only Publication at Terminal Status during cutover to APPEAR</description>
        <label>Legacy FPR Only</label>
    </recordTypes>
    <recordTypes>
        <fullName>LegacyFPROnlyInProgress</fullName>
        <active>true</active>
        <description>Siebel Legacy FPR Only Publication NOT at Terminal Status during cutover to APPEAR</description>
        <label>Legacy FPR Only In Progress</label>
    </recordTypes>
    <recordTypes>
        <fullName>LegacyInProgress</fullName>
        <active>true</active>
        <description>Siebel Legacy publications not reached terminal status at cutover</description>
        <label>Legacy In Progress</label>
    </recordTypes>
    <recordTypes>
        <fullName>Legacy_Publication</fullName>
        <active>true</active>
        <description>Record Type for all migrated Publication from Siebel in terminal state</description>
        <label>Legacy Publication</label>
    </recordTypes>
    <recordTypes>
        <fullName>Plan</fullName>
        <active>true</active>
        <label>Plan</label>
    </recordTypes>
    <recordTypes>
        <fullName>Review</fullName>
        <active>true</active>
        <label>Review</label>
    </recordTypes>
    <recordTypes>
        <fullName>Submit</fullName>
        <active>true</active>
        <label>Submit</label>
    </recordTypes>
    <recordTypes>
        <fullName>Suggestion</fullName>
        <active>true</active>
        <label>Suggestion</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PubReviewTeam__c.object
<CustomObject>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipName>PubReviewTeams</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Publication Review Team Member</label>
    <nameField>
        <displayFormat>PRT-{000000000}</displayFormat>
        <label>PubReviewTeamId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication Review Team Members</pluralLabel>
    <recordTypes>
        <fullName>LegacyPubReviewTeamMemberRecord</fullName>
        <active>true</active>
        <description>Default for Data Migration</description>
        <label>LegacyPubReviewTeamMemberRecord</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PubStatus__c.object
<CustomObject>
    <description>List of Status for a Publication - Target Date / Revised Date / Actual Date
Will be used for planning</description>
    <fields>
        <fullName>Status__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Status</label>
        <referenceTo>Status__c</referenceTo>
        <relationshipName>PubStatuses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publication Status</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>PubStatus Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication Statuses</pluralLabel>
    <recordTypes>
        <fullName>Legacy_Pub_Status</fullName>
        <active>true</active>
        <label>Legacy Pub Status</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Status__c.object
<CustomObject>
    <label>Status</label>
    <nameField>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Statuses</pluralLabel>
    <recordTypes>
        <fullName>Department_Status</fullName>
        <active>true</active>
        <label>Department Status</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/RecordTypeModel.cls
public class RecordTypeModel {
	  
	/////////////////////////////////////////////////////////////////////////
	private static List<RecordType> pRecordTypeList = null;
	public static List<RecordType> RecordTypeList {
		get {
			if (pRecordTypeList == null) {
				pRecordTypeList = [
		            select id, SobjectType,  Name, DeveloperName
		            from RecordType where isActive = true]; 
			}
			return pRecordTypeList;
		} 
	}
	
	private static Map<Id, RecordType> pRecordTypeMapById = null;
	public static Map<Id, RecordType> RecordTypeMapById {
		get {
			if ( pRecordTypeMapById == null) {
				pRecordTypeMapById = new Map<Id, RecordType>();
				for(RecordType rt : RecordTypeList) {
					pRecordTypeMapById.put(rt.id, rt);
				}
			}
			return pRecordTypeMapById;			
		}
	}
	
	public static string findRecordTypeNameById(Id recordTypeId) {
		if (RecordTypeMapById.containsKey(recordTypeId) ) {
			return RecordTypeMapById.get(recordTypeId).DeveloperName;
		} else {
			return 'Unknown RecordTypeId : ' + recordTypeId;
		}
	}
	
	
	
	private static Map<String,RecordType> pRecordTypeMap = null;
	public static Map<String,RecordType> recordTypeMap {
		get {
			if ( pRecordTypeMap == null){
				pRecordTypeMap = new Map<String,RecordType>(); 
		
				for(RecordType rt : RecordTypeList){
					pRecordTypeMap.put(rt.SobjectType+':'+rt.Name, rt);
					//System.Debug(rt.SobjectType+':'+rt.Name);
					if ( rt.Name <> rt.DeveloperName){
						pRecordTypeMap.put(rt.SobjectType+':'+rt.DeveloperName, rt);
						//System.Debug(rt.SobjectType+':'+rt.DeveloperName);
					}
				} 
			}
			return pRecordTypeMap;
		}
	}
    
    public static RecordType LookupRecordType(string sObjectName, string RecordTypeName){
        if(recordTypeMap.containsKey(sObjectName+':'+RecordTypeName)){
        	
        	System.Debug(RecordTypeModel.LegacyPubStatusRecordIdSet);
        	
        	return recordTypeMap.get(sObjectName+':'+RecordTypeName);
        }else { 
            //unable to locate
            System.Debug('RecordTypeModel::LookupRecordType unable to locate '+sObjectName+':'+RecordTypeName);
            return null;
        }
        
        
    }
    
    private static Set<id> pLegacyPubRecordIdSet = null;
    public static Set<id> LegacyPubRecordIdSet {
    	get {
    		if ( pLegacyPubRecordIdSet == null) {
    			pLegacyPubRecordIdSet = new set<id>();
    			
    			pLegacyPubRecordIdSet.add(PublicationLegacyFPROnlyRecTypeId);
    			pLegacyPubRecordIdSet.add(PublicationLegacyFPROnlyInProgressRecTypeId);
    			pLegacyPubRecordIdSet.add(PublicationLegacyInProgressRecTypeId);
    			pLegacyPubRecordIdSet.add(PublicationLegacyPublicationRecTypeId);
    		}
    		return pLegacyPubRecordIdSet;
    	}
    }
    
    private static Set<id> pLegacyInProgressPubRecordIdSet = null;
    public static Set<id> LegacyInProgressPubRecordIdSet {
    	get {
    		if ( pLegacyInProgressPubRecordIdSet == null) {
    			pLegacyInProgressPubRecordIdSet = new set<id>();
    			
    			pLegacyInProgressPubRecordIdSet.add(PublicationLegacyFPROnlyInProgressRecTypeId);
    			pLegacyInProgressPubRecordIdSet.add(PublicationLegacyInProgressRecTypeId);
    		}
    		return pLegacyInProgressPubRecordIdSet;
    	}
    }

    private static Set<id> pLegacyPubStatusRecordIdSet = null;
    public static Set<id> LegacyPubStatusRecordIdSet {
    	get {
    		if ( pLegacyPubStatusRecordIdSet == null) {
    			pLegacyPubStatusRecordIdSet = new set<id>();
    			
    			pLegacyPubStatusRecordIdSet.add(PubStatusLegacyRecTypeId);
    		}
    		return pLegacyPubStatusRecordIdSet;
    	}
    } 
    
    private static Set<id> pLegacyPubReviewTeamRecordIdSet = null;
    public static Set<id> LegacyPubReviewTeamRecordIdSet {
    	get {
    		if ( pLegacyPubReviewTeamRecordIdSet == null) {
    			pLegacyPubReviewTeamRecordIdSet = new set<id>();
    			
    			pLegacyPubReviewTeamRecordIdSet.add(PubReviewTeamLegacyRecTypeId);
    		}
    		return pLegacyPubReviewTeamRecordIdSet;
    	}
    }
	public static Id LookupRecordTypeId(string sObjectName, string RecordTypeName){
        if(recordTypeMap.containsKey(sObjectName+':'+RecordTypeName)){
        	return recordTypeMap.get(sObjectName+':'+RecordTypeName).Id;
        } else { 
            //unable to locate
            System.Debug('RecordTypeModel::LookupRecordType unable to locate '+sObjectName+':'+RecordTypeName);
            return null;
        }
    }
    
    public static id PubReviewTeamLegacyRecTypeId {
    	get {
    		return LookupRecordTypeId('PubReviewTeam__c','LegacyPubReviewTeamMemberRecord');
    	}
    }
    
    
    public static id PubStatusLegacyRecTypeId {
    	get {
    		return LookupRecordTypeId('PubStatus__c','Legacy_Pub_Status');
    	}
    }
    
    public static id StatusDeptStatusRecTypeId {
    	get {
    		return LookupRecordTypeId('Status__c','Department_Status');
    	}
    }
    
    public static id PublicationPlanRecTypeId {
    	get {
    		return LookupRecordTypeId('Publication__c','Plan');
    	}
    }

    public static id PublicationFPROnlyRecTypeId {
    	get {
    		return LookupRecordTypeId('Publication__c','FPR Only');
    	}
    }
    
    public static id PublicationSuggestionRecTypeId {
    	get {
    		return LookupRecordTypeId('Publication__c','Suggestion');
    	}
    }

    public static id PublicationSubmitRecTypeId {
    	get {
    		return LookupRecordTypeId('Publication__c','Submit');
    	}
    }   

    public static id PublicationReviewRecTypeId {
    	get {
    		return LookupRecordTypeId('Publication__c','Review');
    	}
    }    

    public static id PublicationInFPRCTypeId {
    	get {
    		return LookupRecordTypeId('Publication__c','In_FPR');
    	}
    }      

    public static id PublicationAssignedToFPRCTypeId {
    	get {
    		return LookupRecordTypeId('Publication__c','Assigned_to_FPRC');
    	}
    }  

    public static id PublicationLegacyFPROnlyRecTypeId {
    	get {
    		return LookupRecordTypeId('Publication__c','LegacyFPROnly');
    	}
    } 

    public static id PublicationLegacyFPROnlyInProgressRecTypeId {
    	get {
    		return LookupRecordTypeId('Publication__c','LegacyFPROnlyInProgress');
    	}
    } 
    
	public static id PublicationLegacyInProgressRecTypeId {
    	get {
    		return LookupRecordTypeId('Publication__c','LegacyInProgress');
    	}
    } 
    
	public static id PublicationLegacyPublicationRecTypeId {
    	get {
    		return LookupRecordTypeId('Publication__c','Legacy_Publication');
    	}
    } 

}