force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <fields>
        <fullName>Assigned_FPRC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned to FPR Coordinator</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FPR_Due_Date__c</fullName>
        <inlineHelpText>As best practice, select an FPR due date that is more than 10 business days from today. If this is a rush request, provide business justification in the Comments for FPR Coordinator section and we will try to facilitate your request.</inlineHelpText>
        <label>FPR Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FPR_Submitter__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>FPR_Submitter will record the latest person that click on the Submit to FPR button.

DO NOT USE this field to check if a pub is an FPR Only Pub</description>
        <label>FPR Submitter</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Publication (FPR Submitter)</relationshipLabel>
        <relationshipName>FPR_Submitter</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <description>Related to Pub Product Indication</description>
        <label>Primary Prod Ind Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Indication__c</fullName>
        <description>A READ ONLY string that list all product Indications for the Publication
The key product indication will be list at the first entry</description>
        <inlineHelpText>Product - Indication is a required field that is available for selection when a publication is first saved. Once saved, the Product Indication may be edited using the Product Indication button.</inlineHelpText>
        <label>Product - Indication</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publication_Title__c</fullName>
        <inlineHelpText>This is a succinct but descriptive Title of the Publication</inlineHelpText>
        <label>Publication Title</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Publication_Type__c</fullName>
        <label>Publication Type</label>
        <picklist>
            <picklistValues>
                <fullName>Abstract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ad Board Summary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMCP Dossier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Book Chapter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brief Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CMS/Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Editorial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GVD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HTA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Letter to Editor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manuscript</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting Summary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Newsletter Article</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oral Presentation (Slide Deck)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Poster</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review Article</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supplement Article (Non English Language Only)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Translation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <recordTypes>
        <fullName>Review</fullName>
        <active>true</active>
        <label>Review</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PubReviewTeam__c.object
<CustomObject>
    <fields>
        <fullName>AssignedFPRCFF__c</fullName>
        <formula>Publication__r.Assigned_FPRC__r.FirstName &amp; &quot; &quot; &amp; Publication__r.Assigned_FPRC__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AssignedFPRCFF</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipName>PubReviewTeams</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Publication Review Team Member</label>
    <nameField>
        <displayFormat>PRT-{000000000}</displayFormat>
        <label>PubReviewTeamId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication Review Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/Email_15_FullFprReviewWithCmtsComplete.cls
public class Email_15_FullFprReviewWithCmtsComplete extends AppearEmailBase {

	public Email_15_FullFprReviewWithCmtsComplete( List<Id> toAddressIds, List<Id> ccAddressIds, Id reviewTeamMemberCycleId, publication__c pub) {
		super(pub,'Email_15_FullFprReviewWithCmtsComplete');

		PubReviewTeam__c reviewTeamMemberCycle = PubReviewTeamNoSharingModel.loadPubReviewTeamRecord(reviewTeamMemberCycleId);
		if ( reviewTeamMemberCycle == null || reviewTeamMemberCycle.publication__c == null) {
			return;
		}
		if ( pub == null || pub.fpr_Due_Date__c == null) {
			return;
		}
		
		if ( pub.Primary__c == null) {
			if ( pub.Product_Indication__c.contains(';'))  {
				pub.Primary__c = pub.Product_Indication__c.split(';',0)[0];
			} else {
				pub.Primary__c = pub.Product_Indication__c;
			}
		}
	
		subject('FPR '+ pub.name +', Due: ' + 
			pub.fpr_Due_Date__c.format() + ', ' + pub.Primary__c + ', ' +
			pub.Publication_Type__c + ' has been reviewed with comments and is now complete. ');
			
		ToAddresses(toAddressIds);
		CCAddresses(ccAddressIds);

		String htmlBodyStr =
			'Do not reply to this email message.<br><br>' +
			'FPR ' + reviewTeamMemberCycle.publication__r.name + 
			', titled ' + pub.Publication_Title__c + ', has been reviewed with comments and is now complete. Reviewer comments should be ' +
			'addressed prior to external submission or presentation and can be accessed using the link below. ' +
			'Contact the FPR Coordinator, ' + reviewTeamMemberCycle.AssignedFPRCFF__c + ', if you have any questions. <br><br>' +
			'View the status of the FPR record using your bookmarked system URL or through the system launch button from the <a href="' + AppearUrlModel.GetSimpleFprPortalPath() + '" target="_blank">FPR Site</a>.<br><br>' +
			'LEGAL AND COMPLIANCE DISCLAIMER: If an electronic copy of the publication is submitted to external Reviewers or meeting/journal, please ensure the following: <br>' +
			'<ul><li>There are no embedded data (links to data or confidential information). Pay special attention to tables and/or figures generated from underlying Excel spreadsheets that may contain Amgen Confidential Information. </li>' +
			'<li>Remove proprietary information that may appear in the Speaker Notes of oral presentations. </li>' +
			'<li>Set the security on all documents. Note that PDFs are editable unless secured. </li>' +
			'<li>Be aware that Amgen may not wish to disclose AMG numbers for early-phase products. </li>' +
			'<li>Remove "Amgen Confidential" from versions of documents to be publicly disseminated. </li></ul>' +
			'Please note that the FPR process does not fulfill the Amgen requirement for Final Review by All Authors. Refer to the Amgen Publications SOP (014321-7.0) for policy and standard practices across all groups that collaborate with outside Authors.<br><br>' +
			'Thank you,<br>' +
			'FPR System<br>';

		htmlBody(htmlBodyStr);
		plainTextBody(htmlBodyStr.replace('<br>', '\\r\\n').replace('<ul>','-').remove('</ul>').replace('<li>',' --').remove('</li>'));
	}


	//Email_15_FullFprReviewWithCmtsComplete.testEmail();
	public static void testEmail() {
		AppearPubModel activePub = EmailPubReviewTeam.testPub;
		List<Id> ToAddressIds = new List<Id>();
		ToAddressIds.add(activePub.pubRecord.Assigned_FPRC__c);
		ToAddressIds.add(activePub.pubRecord.FPR_Submitter__c);

		Email_15_FullFprReviewWithCmtsComplete email = new Email_15_FullFprReviewWithCmtsComplete(
			ToAddressIds, ToAddressIds, activePub.PubReviewTeam.NewPubReviewTeamMembers.Id, activePub.pubRecord);
		email.sendEmail();

	}
}