force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PubTOV__c.object
<CustomObject>
    <fields>
        <fullName>ContractNumber__c</fullName>
        <label>Contract number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Publication TOV</relationshipLabel>
        <relationshipName>Publication_TOV</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubmissionCycle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Submission Cycle</label>
        <referenceTo>SubmissionCycle__c</referenceTo>
        <relationshipLabel>Publication TOV</relationshipLabel>
        <relationshipName>Publication_TOV</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publication TOV</label>
    <nameField>
        <label>Publication TOV Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publication TOV</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/SubmissionCycle__c.object
<CustomObject>
    <description>record name will be PubId-{0000000}-SubCycle-{00}</description>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipLabel>Submission Cycles</relationshipLabel>
        <relationshipName>Submission_Cycles</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Submission Cycle</label>
    <nameField>
        <label>Submission Cycle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submission Cycles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/PubTOVModelTest.cls
@IsTest
public class PubTOVModelTest {


   	@isTest
	public static void unitTest() {
        //create a test pub
        Publication__c pub = unitTestData.PublicationNew('SubmissionCycleModelTest');
        System.assertNotEquals(null, pub.id);
        
        //load the test pub into AppearPubModel
        AppearPubModel pubModel = new AppearPubModel(pub.id, '', '');
        System.assertNotEquals(null, pubModel);
        System.assertNotEquals(null, pubModel.PubId);
        System.assertNotEquals(null, pubModel.PubName);
        
        //Create a PubTOVModel

        PubTOVModel pubTOV = new PubTOVModel(pubModel.PubId, pubModel, '', '', false);
        pubTOV.deleteSelected();
        boolean canEdit = pubTOV.canAddDelTOVs;
        
        pubTOV.newPubTOV.ContractNumber__c = 'abc';
        pubTOV.saveNewPubTOV();
        pubTOV.saveTOVList();
        List<PubTOV__c>  listPOV = pubTOV.PubTOVList; 
        
        System.assertEquals(pubModel.CurrentSubmissionCycleId, listPOV[0].SubmissionCycle__c);
	
        
        //retrieve SubmissionCycleModel from AppearPubModel
        
    }


}