force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <fields>
        <fullName>IsSelected__c</fullName>
        <defaultValue>false</defaultValue>
        <description>for UI operation - please do not store or migrate data into this field</description>
        <label>IsSelected</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PASS__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Related to the associated oublication study/project</description>
        <label>PASS</label>
        <type>Checkbox</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Study__c.object
<CustomObject>
    <fields>
        <fullName>PASS__c</fullName>
        <defaultValue>false</defaultValue>
        <description>PASS field/flag for tracking.</description>
        <label>PASS</label>
        <type>Checkbox</type>
    </fields>
    <label>Study/Project</label>
    <nameField>
        <label>Study/Project #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Studies/Projects</pluralLabel>
    <recordTypes>
        <fullName>Study</fullName>
        <active>true</active>
        <label>Study</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/PubStudyTriggerLogicTest.cls
@IsTest
public with sharing class PubStudyTriggerLogicTest {
    
    private static void CreateData() {
        OrganizationModelData.createData();
        DepartmentModelData.createData();
        TherapeuticAreaModelData.createData();
        AmgenProductModelData.createData();
		StudyModelData.createData();
    }
    
    private static Publication__c pPubStudyTestPub = null;
    public static Publication__c PubStudyTestPub {
        get {
            if (pPubStudyTestPub == null) {
                CreateData();
                pPubStudyTestPub = UnitTestData.PublicationNew('PubStudyTriggerLogicTest');
            }
            return pPubStudyTestPub;
        }
    }
    
    @IsTest
    private static void TestPubStudyTriggerLogic() {
    	createData();
    	
		Test.startTest();
        AppearPubModel pubModel = new AppearPubModel(PubStudyTestPub.id);
        Study__c studyPass = [Select Id, Name, Pass__c from Study__c where Name = '20119218' limit 1];
          
        PubStudyTriggerLogic.PubStudyTriggerInsertOrDeleteLogic(null); //error case 
         
        System.assertEquals(true,  pubModel.PubStudy.canAddDelStudies);  
        
        //add a study           
        pubModel.PubStudy.StudyProjectId = studyPass.Id;
        System.assertNotEquals(null, pubModel.PubStudy.saveNewPubStudy());       
           
        //check count of list
        System.assertEquals(1, pubModel.PubStudy.PubStudyList.size());
        
        PubStudyTriggerLogic.PubStudyTriggerInsertOrDeleteLogic(pubModel.PubStudy.PubStudyList);
        
        //assert trigger synchronized PASS on insert
        Publication__c pubToCheck = [Select Pass__c from Publication__c where id =:PubStudyTestPub.id];
        System.assertEquals(true,pubToCheck.Pass__c);
        
        //delete study
        pubModel.PubStudy.PubStudyList[0].isSelected__c = true;
        
        System.assertNotEquals(null, pubModel.PubStudy.deleteSelected());
        
        PubStudyTriggerLogic.PubStudyTriggerInsertOrDeleteLogic(PubStudyModel.getAllPubStudyList(PubStudyTestPub.id));
        
        //assert trigger synchronized PASS on delete
        pubToCheck = [Select Pass__c from Publication__c where id =:PubStudyTestPub.id];
        System.assertEquals(false, pubToCheck.Pass__c);
        
        Test.stopTest();
    }
}