force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <fields>
        <fullName>Assigned_FPRC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned to FPR Coordinator</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PubReviewTeam__c.object
<CustomObject>
    <fields>
        <fullName>AssignedFPRCFF__c</fullName>
        <formula>Publication__r.Assigned_FPRC__r.FirstName &amp; &quot; &quot; &amp; Publication__r.Assigned_FPRC__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AssignedFPRCFF</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DelegatedTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Publication Review Team Member this pub was delegated to</description>
        <label>Delegated To</label>
        <referenceTo>PubReviewTeam__c</referenceTo>
        <relationshipLabel>Publication Review Team Members (Delegated To)</relationshipLabel>
        <relationshipName>Publication_Review_Team_Members1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Delegation_Justification__c</fullName>
        <label>Delegation Justification</label>
        <picklist>
            <picklistValues>
                <fullName>Reviewer on travel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reviewer on vacation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reviewer on medical leave</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reviewer in office but not available</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DisplayName__c</fullName>
        <description>Display name for the team member - Currently the contact&apos;s name or the contact being proxied. If this is not displayed, The associated contact&apos;s name will be used in the view</description>
        <label>DisplayName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProxyMember__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>if user has a proxy for this pub, lookup to that proxy team member</description>
        <label>Proxy Member</label>
        <referenceTo>PubReviewTeam__c</referenceTo>
        <relationshipLabel>Publication Review Team Members (Proxy Member)</relationshipLabel>
        <relationshipName>ProxyMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PubIDLink__c</fullName>
        <formula>HYPERLINK($Setup.OrgUrl__c.VfURL__c&amp;&quot;AppearFpr?Id=&quot;&amp;Publication__r.Id&amp;&quot;&amp;param=blah&quot;, 
Publication__r.Name,  &quot;Review Pub&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PubIDLink</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipName>PubReviewTeams</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reviewer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reviewer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>PubReviewTeams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubType__c</fullName>
        <label>SubType</label>
        <picklist>
            <picklistValues>
                <fullName>Standard</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Delegate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proxy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delegate Exists</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delegate New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Triaged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Triagee</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TriageDelegatedBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TriageDelegatedBy</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>PubReviewTeams1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Triage_Justification__c</fullName>
        <label>Triage Justification</label>
        <picklist>
            <picklistValues>
                <fullName>Additional legal expertise required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Additional scientific/medical/statistical expertise required</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TriagedTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Publication Review Team Member the publication was triaged to</description>
        <label>Triaged To</label>
        <referenceTo>PubReviewTeam__c</referenceTo>
        <relationshipLabel>Publication Review Team Members</relationshipLabel>
        <relationshipName>Publication_Review_Team_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publication Review Team Member</label>
    <nameField>
        <displayFormat>PRT-{000000000}</displayFormat>
        <label>PubReviewTeamId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication Review Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/PubReviewTeamNoSharingModel.cls
public without sharing class PubReviewTeamNoSharingModel {

	public static PubReviewTeam__c loadPubReviewTeamRecord(Id pubReviewTeamId) {
		List<PubReviewTeam__c> results = [
			select PubIDLink__c, Reviewer__c, AssignedFPRCFF__c, publication__r.name, Reviewer__r.name, 
				TriageDelegatedBy__r.name, Triage_Justification__c, TriagedTo__r.Reviewer__r.name, SubType__c,
				DelegatedTo__r.Reviewer__r.name, Delegation_Justification__c, ProxyMember__c, DisplayName__c
			from PubReviewTeam__c   
			where id = :pubReviewTeamId
		];
		if ( results.size() == 1) {
			return results[0];
		} else {
			return null;
		}
	}

}