force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <fields>
        <fullName>Publication_Title__c</fullName>
        <inlineHelpText>This is a succinct but descriptive Title of the Publication</inlineHelpText>
        <label>Publication Title</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SiebelRowId__c</fullName>
        <description>Used for legacy data mapping</description>
        <externalId>true</externalId>
        <label>SiebelRowId</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/PubAttachmentSiebelIdWebService.cls
@RestResource(urlMapping='/PubAttachmentSiebelIdWebService/v1/*')
global class PubAttachmentSiebelIdWebService {

	@httpPost 
	global static Map<String, String>  post(List<string> pubSiebelIdList) {
		Map<String,String> result = new Map<String,String>();
		try {
			Long startTime = DateTime.now().getTime();
			
			Set<String> SiebelIdSet = new Set<String>();
			for(String siebelId : pubSiebelIdList) {
				SiebelIdSet.add(siebelId);
			}
	
			List<Publication__c> pubs = [
				select id, SiebelRowId__c //, name, publication_Title__c
				from publication__c
				where SiebelRowId__c in :SiebelIdSet
			];
	
			
			for(Publication__c pub : pubs) {
				result.put(pub.SiebelRowId__c, pub.id);
			}
			
			AppLogModel.LogInfo('PubAttachmentSiebelIdWebService', 'Completed processing for '+ pubSiebelIdList.size() + ' pubSiebelIdList records' );
		} catch ( Exception e ) {
			AppLogModel.LogError('PubAttachmentSiebelIdWebService', e.getMessage());
		} finally {
			AppLogModel.flushLogs();
		}
		return result;
	}
	
}