force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <fields>
        <fullName>IsSelected__c</fullName>
        <defaultValue>false</defaultValue>
        <description>for UI operation - please do not store or migrate data into this field</description>
        <label>IsSelected</label>
        <type>Checkbox</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Study__c.object
<CustomObject>
    <label>Study/Project</label>
    <nameField>
        <label>Study/Project #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Studies/Projects</pluralLabel>
    <recordTypes>
        <fullName>Study</fullName>
        <active>true</active>
        <label>Study</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/PubStudyModelTest.cls
@IsTest
public class PubStudyModelTest {
    private static void createData() {
        OrganizationModelData.createData();
        DepartmentModelData.createData();
        TherapeuticAreaModelData.createData();
        AmgenProductModelData.createData();
        StudyModelData.createData();
    }
    
    @IsTest
    private static void SelectDeselectStudies() {
        createData();
        
        
        Test.startTest();
        Publication__c pub = UnitTestData.PublicationNew('SelectDeselectStudiesTest');
        Publication__c clonePub = UnitTestData.newPublication('PubScientificStatementModelTest2');
        AppearPubModel pubModel = new AppearPubModel(pub.id);
        Study__c study = [Select Id, Name from Study__c limit 1];
          
        System.assertEquals(true,  pubModel.PubStudy.canAddDelStudies);  
        
        //fail cases        
        pubModel.PubStudy.saveNewPubStudy(); 
        pubModel.PubStudy.StudyProjectId = 'invalid';
        pubModel.PubStudy.saveNewPubStudy(); 
        
        //add a study           
        pubModel.PubStudy.StudyProjectId = study.Id;
        System.assertNotEquals(null, pubModel.PubStudy.saveNewPubStudy());        
           
        //check count of list
        System.assertEquals(1, pubModel.PubStudy.PubStudyList.size());
        
        PubStudyModel.setupMiscFromProdStudy(pub.Id); 
        
        
        //clone
        PubStudyModel.clone(pub.Id, clonePub.id);        
        System.assertEquals(1, PubStudyModel.getAllPubStudyList(clonePub.Id).size()); 
        
        //delete study
        pubModel.PubStudy.PubStudyList[0].isSelected__c = true;
        
        Test.stopTest();
        
        System.assertNotEquals(null, pubModel.PubStudy.deleteSelected());
        
        //invoke static functions
        System.assertEquals(0, PubStudyModel.getAllPubStudyList(pub.Id).size()); 
        System.assertEquals(false,  PubStudyModel.CheckDupStudyForPub(pub.Id,study.Id));
    }        
}