force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <fields>
        <fullName>Assigned_FPRC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned to FPR Coordinator</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FPR_Due_Date__c</fullName>
        <inlineHelpText>As best practice, select an FPR due date that is more than 10 business days from today. If this is a rush request, provide business justification in the Comments for FPR Coordinator section and we will try to facilitate your request.</inlineHelpText>
        <label>FPR Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FPR_Submitter__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>FPR_Submitter will record the latest person that click on the Submit to FPR button.

DO NOT USE this field to check if a pub is an FPR Only Pub</description>
        <label>FPR Submitter</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Publication (FPR Submitter)</relationshipLabel>
        <relationshipName>FPR_Submitter</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PubStatus__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Current status of this publication</description>
        <label>PubStatus</label>
        <referenceTo>PubStatus__c</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <recordTypes>
        <fullName>Execute</fullName>
        <active>true</active>
        <label>Execute</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PubReviewTeam__c.object
<CustomObject>
    <fields>
        <fullName>HasVoted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>boolean set when a team member has voted</description>
        <label>HasVoted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsCurrentFPRCycleForPub__c</fullName>
        <formula>Publication__r.Current_FPRCycle_Id_Formula__c  =  FPR_Cycle__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>IsCurrentFPRCycleForPub</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipName>PubReviewTeams</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reviewer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reviewer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>PubReviewTeams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Primary / Informed</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Primary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Notify</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Publication Review Team Member</label>
    <nameField>
        <displayFormat>PRT-{000000000}</displayFormat>
        <label>PubReviewTeamId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication Review Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PubStatus__c.object
<CustomObject>
    <description>List of Status for a Publication - Target Date / Revised Date / Actual Date
Will be used for planning</description>
    <fields>
        <fullName>IsCurrentFPRCycleForPub__c</fullName>
        <formula>Publication_id__r.Current_FPRCycle_Id_Formula__c  =  FPR_Cycle__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>IsCurrentFPRCycleForPub</label>
        <type>Checkbox</type>
    </fields>
    <label>Publication Status</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>PubStatus Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/BatchNightlyPubScan.cls
global class BatchNightlyPubScan extends BatchBase 
	implements Database.Batchable<SObject>,Database.Stateful {
   	public String SOQL = 'select id, name, Assigned_FPRC__c, FPR_Submitter__c from Publication__c where PubStatus__c IN ';
   	
   	private static Set<id> pStatusIdsToInclude = null;
   	private static Set<id> statusIdsToInclude{
   		get{
   			if (pStatusIdsToInclude == null) {
   				pStatusIdsToInclude = new Set<Id>();
				pStatusIdsToInclude.add(StatusModel.Routed.Id);
				pStatusIdsToInclude.add(StatusModel.DiscussionRequired.Id);
   			}
   			
   			return pStatusIdsToInclude; 
   		}
   	}
   	
	public BatchNightlyPubScan() { //find pubs routed or discussion required status with fpr date due today or 2 days ago
		super();
		
		SOQL = SOQL + ':statusIdsToInclude and (FPR_Due_Date__c = TODAY OR FPR_Due_Date__c =  LAST_N_DAYS:2) order by name desc';
		
    	if ( Test.isRunningTest()){
    		SOQL = SOQL + ' limit 10';
    	}
    	AddMessage(SOQL);
        system.debug(SOQL);
	}
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        batchableContext = BC;
        batchName = 'BatchNightlyPubScan';
        System.Debug(SOQL);
        return Database.getQueryLocator(SOQL);
    }

    global void execute(Database.BatchableContext BC, List<publication__c> pubs){
    	
    	/*
    	Friendly_Reminder_Email not part of 14 emails provided
    	
    	
    	EmailTemplate template = AppearSendEmailUtil.emailTemplateMap.get('Friendly_Reminder_Email');
    	if (template <> null) {
	    	Set<id> pubIds = new Set<id>();    	
	    	   	
	    	for(Publication__c pub : pubs) {  
	    		AppearSendEmailUtil.SendEmail(pub.Fpr_Submitter__c, pub.Id, template.Id, pub.id); //send email to fprc  
				AppearSendEmailUtil.SendEmail(pub.Assigned_FPRC__c, pub.Id , template.Id, pub.id); //send email to fpr submitter				
				
				pubIds.add(pub.Id);	
	    	}
	    	
	    	List<PubReviewTeam__c> ReviewersToEmail = [
	    		select id, Reviewer__c, publication__c 
	    		from PubReviewTeam__c 
	    		where HasVoted__c = False 
	    		AND Type__c = 'Primary' AND IsCurrentFPRCycleForPub__c = True AND publication__c in :pubIds
	    	]; 
	    	for(PubReviewTeam__c reviewer : ReviewersToEmail) { //send email to reviewer
	    		AppearSendEmailUtil.SendEmail(reviewer.Reviewer__c, reviewer.publication__c, template.Id, reviewer.publication__c);
	    	}
    	}
    	
    	*/
		AppLogModel.flushLogs();
    } 

    global void finish(Database.BatchableContext BC){
		SendBatchCompletionEmail();
	}
	
	//BatchNightlyPubScan.runNow();
	public static void runNow(){
    	BatchNightlyPubScan batch = new BatchNightlyPubScan();
        Database.executeBatch(batch, 200);
	}

//////////////////////////////////////////  unit test /////////////////////////////////////
	@isTest
	private static void unitTest() {
		CreateData();
		
		BatchNightlyPubScan.runNow();
	} 
	
	public static void CreateData() {
		StatusModelData.CreateData();
	}
}