force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <fields>
        <fullName>PubStatus__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Current status of this publication</description>
        <label>PubStatus</label>
        <referenceTo>PubStatus__c</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <recordTypes>
        <fullName>Execute</fullName>
        <active>true</active>
        <label>Execute</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PubStatus__c.object
<CustomObject>
    <description>List of Status for a Publication - Target Date / Revised Date / Actual Date
Will be used for planning</description>
    <fields>
        <fullName>Publication_id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication_id</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipName>PubStatus</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reason_For_Change__c</fullName>
        <label>Reason For Change</label>
        <picklist>
            <picklistValues>
                <fullName>Delay in Data Availability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delay in publication of primary manuscript</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External author requested timeline shift</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External author review delay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External Steering Committee delays</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal contributor delay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal reviewer delay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Program Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Requests for additional analyses</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resourcing constraints</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RevisedTargetDate__c</fullName>
        <label>Latest Revised Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Status</label>
        <referenceTo>Status__c</referenceTo>
        <relationshipName>PubStatuses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publication Status</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>PubStatus Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/Status__c.object
<CustomObject>
    <label>Status</label>
    <nameField>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/BatchDef541.cls
//BatchDef541- When Latest Target Submission Date [RevisedTargetDate__c] is NOT NULL on Submitted/Completed Status– create a reason forchange in 
//'Legacy Publication - Reason For Change not available".


global class BatchDef541 extends BatchBase 
	implements Database.Batchable<SObject>,Database.Stateful {
   	public String SOQL = 'select id, Reason_For_Change__c, RevisedTargetDate__c from PubStatus__c '+
		'where Status__r.name = \'Submitted/Completed\' '+
		'and RevisedTargetDate__c <> null ';
   	
	public BatchDef541() {
		super();
    	if ( Test.isRunningTest()){
    		SOQL = SOQL + ' limit 10';
    	}
    	AddMessage(SOQL);
        system.debug(SOQL);
	}
	
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        batchableContext = BC;
        batchName = 'BatchDef541';
        System.Debug(SOQL);
        return Database.getQueryLocator(SOQL);
    }

    global void execute(Database.BatchableContext BC, List<PubStatus__c> pubs){
		ActionforPubs(pubs);
    }

    global void finish(Database.BatchableContext BC){
		SendBatchCompletionEmail();
	}
	
	//BatchDef541.runNow();
	public static void runNow(){
    	BatchDef541 batch = new BatchDef541();
        Database.executeBatch(batch, 50);
	}
	
	public static void ActionforPubs(List<PubStatus__c> pubStatusList) {
		if ( pubStatusList == null) return;
		
		for (PubStatus__c pub :  pubStatusList) {
			Date RevisedTargetDate = Date.ValueOf(pub.RevisedTargetDate__c);
			pub.Reason_For_Change__c = 'Legacy Publication - Reason For Change not available. ['+ RevisedTargetDate.Format() +']';
		}
		
		AppLogModel.LogInfo('BatchDef541', 'updating reason for changes '+pubStatusList.size()+' pubStatus with latest Target_date = null');
		database.update(pubStatusList, true);
		
		AppLogModel.flushLogs();		
	}
	
	/*
	BatchDef541.ActionForOnePub('Pub-Id-037085');
	*/
	public static void ActionForOnePub(string pubName){
		List<PubStatus__c> pubStatusList = [
			select id, Reason_For_Change__c, RevisedTargetDate__c 
			from PubStatus__c 
			where Status__r.name = 'Submitted/Completed' 
			and RevisedTargetDate__c <> null 
			and publication_id__r.name = :pubName
		];
		
		ActionforPubs(pubStatusList);
		
	}
	
	
//////////////////////////////////////////  unit test /////////////////////////////////////
	@isTest
	private static void unitTest() {
		CreateData();
		
		BatchDef541.runNow();
	} 
	
	public static void CreateData() {
		Publication__c pub = UnitTestData.PublicationNew('TestBatchDef541');
		
		AppearPubModel activePub = new AppearPubModel(pub.id);
		System.assertNotEquals(null, activePub);
		
		List<PubStatus__c> pubStatusList = activePub.PubStatus.PubStatusList;
		for(PubStatus__c pubStatus : pubStatusList) {
			if ( pubStatus.Status__r.name == 'Submitted/Completed') {
				pubStatus.RevisedTargetDate__c = Date.Today();
				
				update pubStatus;
			}
		}
		
	}
}