force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <fields>
        <fullName>Current_FPRCycle_Id_Formula__c</fullName>
        <formula>PubStatus__r.FPR_Cycle__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current FPR Cycle Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Status_Id_FormulaField__c</fullName>
        <formula>PubStatus__r.Status__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current Status Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_SubmissionCycle_Id_Formula__c</fullName>
        <formula>PubStatus__r.Submission_Cycle__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current Submission Cycle Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PubStatus__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Current status of this publication</description>
        <label>PubStatus</label>
        <referenceTo>PubStatus__c</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <recordTypes>
        <fullName>Execute</fullName>
        <active>true</active>
        <label>Execute</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PubStatus__c.object
<CustomObject>
    <description>List of Status for a Publication - Target Date / Revised Date / Actual Date
Will be used for planning</description>
    <label>Publication Status</label>
    <nameField>
        <displayFormat>{000000000}</displayFormat>
        <label>PubStatus Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication Statuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/BatchDataTest.cls
global class BatchDataTest extends BatchBase 
    implements Database.Batchable<SObject>,Database.Stateful {
    public String SOQL = 'select id, name, PubStatus__c, Current_SubmissionCycle_Id_Formula__c, Current_FPRCycle_Id_Formula__c '+
                'from Publication__c ' +
                'where RecordTypeId in :recordIdsToInclude '+ 
                'AND Current_Status_Id_FormulaField__c NOT in :statusIdsToExclude '+ 
                'order by name';
    
    
    public BatchDataTest() { //find pubs routed or discussion required status with fpr date due today or 2 days ago
        super();
        
        if ( Test.isRunningTest()){
            SOQL = SOQL + ' limit 10';
            AppLogModel.appLogSizeLimit = 5;
        }
        AddMessage(SOQL);
        system.debug(SOQL);
        
    }
    
    private static Set<id> recordIdsToInclude{
        get{
            return RecordTypeModel.LegacyInProgressPubRecordIdSet;
        }
    }
    
    private static Set<id> pStatusIdsToExclude = null;
    private static Set<id> statusIdsToExclude{
        get{
            if (pStatusIdsToExclude == null) {
                pStatusIdsToExclude = new Set<id>();
                
                pStatusIdsToExclude.add(StatusModel.PublishedPresented.id);
                pStatusIdsToExclude.add(StatusModel.StatusMap.get('Accepted').id);
            }
            return pStatusIdsToExclude;
        }
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        batchableContext = BC;
        batchName = 'BatchDataTest';
        System.Debug(SOQL);
        return Database.getQueryLocator(SOQL);
    }
    
    global void execute(Database.BatchableContext BC, List<publication__c> pubs){
        AppearDataTest.checkPub(pubs);
        AppearDataTest.checkSubmissionCycle(pubs, true);
        AppearDataTest.checkFprCycle(pubs, true);
        
        for(integer x= 0; x<20;x++){
            AppLogModel.LogInfo('BatchDataTest::execute', 'This is message #'+x);
        }
        
        
        AppLogModel.flushLogs();
    }

    global void finish(Database.BatchableContext BC){
        SendBatchCompletionEmail();
    }
    
    //BatchDataTest.runNow();
    public static void runNow(){
        BatchDataTest batch = new BatchDataTest();
        Database.executeBatch(batch, 500);
    }
    
    @IsTest
    public static void UnitTest() {
        StatusModelData.createData();
        BatchDataTest.runNow();
        Set<Id> Rec = new Set<Id>();
        BatchDataTest.recordIdsToInclude = rec;
        BatchDataTest.statusIdsToExclude = rec;
    }
       
}