force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <fields>
        <fullName>Add_Meeting_Journal__c</fullName>
        <description>This field is used to enter the Target if not found using the &quot;Target&quot; component.</description>
        <inlineHelpText>If the target is not found using the Target button on the Details page, then enter the target in this field by clicking the Edit button on the top.</inlineHelpText>
        <label>Target Not Found</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Current_Target__c</fullName>
        <description>The Current Target field will also be used to populate the Target field for a new Submission Cycle.
This field should NEVER be moved to a formula</description>
        <inlineHelpText>This field is populated automatically by using the &quot;Target&quot; button on the Details tile.  If the desired target is NOT found using the Target button, please use the &quot;Target Not Found&quot; field below.</inlineHelpText>
        <label>Current Target</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <recordTypes>
        <fullName>Execute</fullName>
        <active>true</active>
        <label>Execute</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/BatchSyncTargetFields.cls
global class BatchSyncTargetFields extends BatchBase 
    implements Database.Batchable<SObject>,Database.Stateful {
    public String SOQL = 'select id,name, Current_Target__c from Publication__c ' +
        ' order by name desc';
    public BatchSyncTargetFields() {
        super();
        if ( Test.isRunningTest()){
            SOQL = SOQL + ' limit 10';
        }
        AddMessage(SOQL);
        system.debug(SOQL);
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        batchableContext = BC;
        batchName = 'BatchSyncTargetFields';
        System.Debug(SOQL);
        return Database.getQueryLocator(SOQL);
    }

    global void execute(Database.BatchableContext BC, List<publication__c> pubs){
        syncPubs(pubs);
    }
    
    public static void syncPubs(List<Publication__c> pubs) {
        List<Publication__c> pubsToUpdate = new List<Publication__c>();
        for (Publication__c pub : pubs) {
            AppearPubModel pubModel = new AppearPubModel(pub.Id);
            //if (string.IsBlank( pub.Current_Target__c )) { //update all Current_Target
                string currentTarget = pubModel.CurrentTarget;
                if (string.IsBlank(currentTarget)) {
                    currentTarget = pubModel.pubRecord.Add_Meeting_Journal__c;
                }
                if ( currentTarget <> null && currentTarget.length() > 255) {
                    pub.Current_Target__c = currentTarget.substring(254);
                } else {
                    pub.Current_Target__c = currentTarget;
                }
                pubsToUpdate.add(pub);
            //}
        }   
        
        if (pubsToUpdate.size() > 0) {
            update pubsToUpdate;
        }
        AppLogModel.flushLogs();
    }
    
    //BatchSyncTargetFields.syncOnePub('PubId-000000');
    public static void syncOnePub(string pubName){
        List<Publication__c> pubs = [
            select id,name, Current_Target__c
            from Publication__c 
            WHERE name = :pubName  
        ];
        
        syncPubs(pubs);
    }
    
    //BatchSyncTargetFields.runNow();
    public static void runNow(){
        BatchSyncTargetFields batch = new BatchSyncTargetFields();
        Database.executeBatch(batch, 20);
    }
    
    global void finish(Database.BatchableContext BC){
        SendBatchCompletionEmail();
    }

//////////////////////////////////////////  unit test /////////////////////////////////////
    @isTest
    private static void unitTest() {
        CreateData();
        
        BatchSyncTargetFields.runNow();
    } 
    
    public static void CreateData() {
        Publication__c pub = UnitTestData.PublicationNew('TestingPublication1');
        Publication__c pub1 = UnitTestData.newPublication('TestingPublication2');
        
    }
}