force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <fields>
        <fullName>Execution_Notes_Last_Mod__c</fullName>
        <label>Execution Notes Last Mod</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Execution_Notes__c</fullName>
        <label>Execution Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SiebelRowId__c</fullName>
        <description>Used for legacy data mapping</description>
        <externalId>true</externalId>
        <label>SiebelRowId</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <recordTypes>
        <fullName>Execute</fullName>
        <active>true</active>
        <label>Execute</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PubNote__c.object
<CustomObject>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipName>PubNotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SiebelRowId__c</fullName>
        <externalId>true</externalId>
        <label>SiebelRowId</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Publication Note</label>
    <nameField>
        <label>PubNotes Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Publication Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/BatchMergeNotes.cls
global class BatchMergeNotes extends BatchBase 
    implements Database.Batchable<SObject>,Database.Stateful {

    public String SOQL = 'select id,name from Publication__c ' +
        ' order by createddate';
    
    public BatchMergeNotes() {
        super();
        if ( Test.isRunningTest()){
            SOQL = SOQL + ' limit 10';
        }
        AddMessage(SOQL);
        system.debug(SOQL);
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        batchableContext = BC;
        batchName = 'BatchMergeNotes';  
        System.Debug(SOQL);
        return Database.getQueryLocator(SOQL);
    }
    

    global void execute(Database.BatchableContext BC, List<publication__c> pubs){
        for(publication__c pub : pubs) {

            list<PubNote__c> notesForPub = [
                select Notes__c
                from pubNote__c
                where publication__c = :pub.id
                order by SiebelRowId__c
            ];
    

            if ( notesForPub.size() > 0) {
                
                string mergedNotes = '';
                for(PubNote__c note : NotesForPub) {
                    mergedNotes += note.notes__c + '\r\n\r\n';
                }
                
                AppearPubModel activePub = New AppearPubModel(pub.id);
                
                activePub.pubRecord.Execution_Notes__c = mergedNotes ;
                activePub.pubRecord.Execution_Notes_Last_Mod__c = DateTime.Now();
                update activePub.pubRecord;

            }

        }

        AppLogModel.flushLogs();
    }
    
    
    global void finish(Database.BatchableContext BC){
        SendBatchCompletionEmail();
    }
    
    //BatchMergeNotes.runNow();
    public static void runNow(){
        BatchMergeNotes batch = new BatchMergeNotes();
        Database.executeBatch(batch, 10);
    }

//////////////////////////////////////////  unit test /////////////////////////////////////
    
    private static testMethod void unitTest() {
        
        CreateData();
        BatchMergeNotes.runNow();
        
    } 
    
    public static void CreateData() {
        
    }
}