force-app/main/default/staticresources/python/Disappear/src/objects/Publication__c.object
<CustomObject>
    <description>Contains the Publication Details for each Publication Record</description>
    <fields>
        <fullName>Assigned_FPRC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned to FPR Coordinator</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Publication</relationshipLabel>
        <relationshipName>Publication</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Target__c</fullName>
        <description>The Current Target field will also be used to populate the Target field for a new Submission Cycle.
This field should NEVER be moved to a formula</description>
        <inlineHelpText>This field is populated automatically by using the &quot;Target&quot; button on the Details tile.  If the desired target is NOT found using the Target button, please use the &quot;Target Not Found&quot; field below.</inlineHelpText>
        <label>Current Target</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FPR_Due_Date__c</fullName>
        <inlineHelpText>As best practice, select an FPR due date that is more than 10 business days from today. If this is a rush request, provide business justification in the Comments for FPR Coordinator section and we will try to facilitate your request.</inlineHelpText>
        <label>FPR Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FPR_Submitter__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>FPR_Submitter will record the latest person that click on the Submit to FPR button.

DO NOT USE this field to check if a pub is an FPR Only Pub</description>
        <label>FPR Submitter</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Publication (FPR Submitter)</relationshipLabel>
        <relationshipName>FPR_Submitter</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <description>Related to Pub Product Indication</description>
        <label>Primary Prod Ind Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Indication__c</fullName>
        <description>A READ ONLY string that list all product Indications for the Publication
The key product indication will be list at the first entry</description>
        <inlineHelpText>Product - Indication is a required field that is available for selection when a publication is first saved. Once saved, the Product Indication may be edited using the Product Indication button.</inlineHelpText>
        <label>Product - Indication</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publication_Title__c</fullName>
        <inlineHelpText>This is a succinct but descriptive Title of the Publication</inlineHelpText>
        <label>Publication Title</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Publication_Type__c</fullName>
        <label>Publication Type</label>
        <picklist>
            <picklistValues>
                <fullName>Abstract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ad Board Summary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMCP Dossier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Book Chapter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brief Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Case Report</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CMS/Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Editorial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GVD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HTA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Letter to Editor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manuscript</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Meeting Summary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Newsletter Article</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oral Presentation (Slide Deck)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Poster</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review Article</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supplement Article (Non English Language Only)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Translation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Publication</label>
    <nameField>
        <displayFormat>Pub-Id-{000000}</displayFormat>
        <label>Pub ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication</pluralLabel>
    <recordTypes>
        <fullName>Review</fullName>
        <active>true</active>
        <label>Review</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/objects/PubReviewTeam__c.object
<CustomObject>
    <fields>
        <fullName>Delegation_Justification__c</fullName>
        <label>Delegation Justification</label>
        <picklist>
            <picklistValues>
                <fullName>Reviewer on travel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reviewer on vacation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reviewer on medical leave</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reviewer in office but not available</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Publication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Publication</label>
        <referenceTo>Publication__c</referenceTo>
        <relationshipName>PubReviewTeams</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Publication Review Team Member</label>
    <nameField>
        <displayFormat>PRT-{000000000}</displayFormat>
        <label>PubReviewTeamId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Publication Review Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/Email_03_RoutedToDelegate.cls
public class Email_03_RoutedToDelegate extends AppearEmailBase {


	public Email_03_RoutedToDelegate( List<Id> toAddressIds, List<Id> ccAddressIds, String delegatedFromName,  
		PubReviewTeam__c reviewTeamMemberCycle, publication__c pub) {
		super(pub,'Email_03_RoutedToDelegate');
		 
		subject('FPR '+ pub.name +', Due: ' + 
			pub.fpr_Due_Date__c.format() + ', ' + pub.Primary__c + ', ' + pub.Publication_Type__c +' has been delegated to you for review.');
		ToAddresses(toAddressIds);
		CCAddresses(ccAddressIds);

		String htmlBodyStr =
			'Do not reply to this email message.<br><br>' +
			delegatedFromName + ' has delegated FPR ' + pub.name + 
			', titled ' + pub.Publication_Title__c + 
			', with a current target of ' + pub.Current_Target__c + ', ' +
			'to you for review by ' + pub.fpr_Due_Date__c.format() + '. The delegation justification is: '+ reviewTeamMemberCycle.Delegation_Justification__c +  '.<br><br>'+
			'Note: If additional Reviewers are needed, triage this assignment BEFORE voting. All new Reviewers must be trained on the FPR System. ' +
			'Contact your assigned FPR Coordinator, ' + pub.Assigned_FPRC__r.name + 
			', if you have any questions. <br><br>' + 
			'<B>Reviewers</B>: Access the FPR record using this link <a href="' + URL.getSalesforceBaseUrl().toExternalForm() + '/apex/AppearFpr?Id=' + Pub.id +'&param=blah'+'">'+Pub.Name+'</a><br>' +
			'<B>Submitters</B>: View the status of the FPR record using your bookmarked system URL or through the system launch button from the <a href="' + AppearUrlModel.GetSimpleFprPortalPath() + '" target="_blank">FPR Site</a>.<br><br>' +
			'FPR Submitter, this notification has been emailed to you for notification purposes only. No action is required from you. <br><br>' +
			'Thank you,<br>' +
			'FPR System<br>';

		htmlBody(htmlBodyStr);
		plainTextBody(htmlBodyStr.replace('<br>', '\\r\\n'));
		
		AppLogModel.LogInfo('Email_03_RoutedToDelegate', 'Created Email_03_RoutedToDelegate for pub : '+pub.name+' to '+toAddresses+' cc '+ ccAddresses, pub.id);
		AppLogModel.flushLogs();
	}
	public Email_03_RoutedToDelegate( List<Id> toAddressIds, List<Id> ccAddressIds, String delegatedFromName,  
		Id reviewTeamMemberCycleId, publication__c pub) {
		super(pub,'Email_03_RoutedToDelegate');
	
		PubReviewTeam__c reviewTeamMemberCycle = PubReviewTeamNoSharingModel.loadPubReviewTeamRecord(reviewTeamMemberCycleId);  
		if ( pub.Primary__c == null) {
			if ( pub.Product_Indication__c.contains(';'))  {
				pub.Primary__c = pub.Product_Indication__c.split(';',0)[0];
			} else {
				pub.Primary__c = pub.Product_Indication__c;
			}
		}
		 
		subject('FPR '+ reviewTeamMemberCycle.publication__r.name +', Due: ' + 
			pub.fpr_Due_Date__c.format() + ', ' + pub.Primary__c + ', ' + pub.Publication_Type__c +' has been delegated to you for review.');
		ToAddresses(toAddressIds);
		CCAddresses(ccAddressIds);

		String htmlBodyStr =
			'Do not reply to this email message.<br><br>' +
			delegatedFromName + ' has delegated FPR ' + reviewTeamMemberCycle.publication__r.name + 
			', titled ' + pub.Publication_Title__c + 
			', with a current target of ' + pub.Current_Target__c + ', ' +
			'to you for review by ' + pub.fpr_Due_Date__c.format() + '. The delegation justification is: '+ reviewTeamMemberCycle.Delegation_Justification__c +  '.<br><br>'+
			'Note: If additional Reviewers are needed, triage this assignment BEFORE voting. All new Reviewers must be trained on the FPR System. ' +
			'Contact your assigned FPR Coordinator, ' + pub.Assigned_FPRC__r.name + 
			', if you have any questions. <br><br>' + 
			'<B>Reviewers</B>: Access the FPR record using this link <a href="' + URL.getSalesforceBaseUrl().toExternalForm() + '/apex/AppearFpr?Id=' + Pub.id +'&param=blah'+'">'+Pub.Name+'</a><br>' +
			'<B>Submitters</B>: View the status of the FPR record using your bookmarked system URL or through the system launch button from the <a href="' + AppearUrlModel.GetSimpleFprPortalPath() + '" target="_blank">FPR Site</a>.<br><br>' +
			'FPR Submitter, this notification has been emailed to you for notification purposes only. No action is required from you. <br><br>' +
			'Thank you,<br>' +
			'FPR System<br>';

		htmlBody(htmlBodyStr);
		plainTextBody(htmlBodyStr.replace('<br>', '\\r\\n'));
		
		AppLogModel.LogInfo('Email_03_RoutedToDelegate', 'Created Email_03_RoutedToDelegate for pub : '+pub.name+' to '+toAddresses+' cc '+ ccAddresses, pub.id);
		AppLogModel.flushLogs();
	}

  
	//Email_03_RoutedToDelegate.testEmail();
	
	public static void testEmail() {
		AppearPubModel activePub = EmailPubReviewTeam.testPub;
		List<Id> ToAddressIds = new List<Id>();
		ToAddressIds.add(activePub.pubRecord.Assigned_FPRC__c);
		ToAddressIds.add(activePub.pubRecord.FPR_Submitter__c);

		Email_03_RoutedToDelegate email = new Email_03_RoutedToDelegate(
			ToAddressIds, ToAddressIds, activePub.pubRecord.Assigned_FPRC__c,
				activePub.PubReviewTeam.NewPubReviewTeamMembers.Id, activePub.pubRecord);
		email.sendEmail();

	}
	
	
}