force-app/main/default/staticresources/python/Disappear/src/objects/r20mig__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <picklist>
            <picklistValues>
                <fullName>Migrate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>FromProfile__c</fullName>
        <description>we cannot create a link to profile object
so copy the name of the profile in this field</description>
        <label>From Profile</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FromUser__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>From User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Rel_2_0_migration_tools</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ToFederationId__c</fullName>
        <label>ToFederationId</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ToFprPortalUser__c</fullName>
        <defaultValue>false</defaultValue>
        <label>To FPR Portal User</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ToProfile__c</fullName>
        <label>To Profile</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ToUser__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>To User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Rel_2_0_migration_tools1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>fromContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>from Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Rel 2.0 migration tools</relationshipLabel>
        <relationshipName>Rel_2_0_migration_tools</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>isSelected__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Selected</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>toContactFedId__c</fullName>
        <formula>text(toContact__r.Federation_Identifier__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>toContactFedId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>toContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>to Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Rel 2.0 migration tools (to Contact)</relationshipLabel>
        <relationshipName>Rel_2_0_migration_tools1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Rel 2.0 migration tools</label>
    <nameField>
        <displayFormat>mig-{00000}</displayFormat>
        <label>Rel 2.0 migration tools Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rel 2.0 migration tools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/BatchRelease20Migration.cls
global class BatchRelease20Migration extends BatchBase 
	implements Database.Batchable<SObject>,Database.Stateful {

	public boolean isMigrationToPortal = false;
	public boolean isMigrationToPlatform = false;
	public boolean isStep2 = false;
	
    public static String SOQL = 'select id, Action__c, FromProfile__c,  FromUser__c, FromUser__r.ProfileId, isSelected__c, fromContact__c, toContact__c, toContactFedId__c, ToFederationId__c, ' +
                	'ToFprPortalUser__c, ToProfile__c, ToUser__c, ToUser__r.profileId  ' +
                	'from r20mig__c where isSelected__c = true ' ;
    
    public BatchRelease20Migration(boolean isMigrationToPortal, boolean isStep2, 
    	boolean isMigrationToPlatform) {
		super();
		
		this.isMigrationToPortal = isMigrationToPortal;
		this.isStep2 = isStep2;
		this.isMigrationToPlatform = isMigrationToPlatform;
		
    	if ( Test.isRunningTest()){
    		SOQL = SOQL + ' limit 1';
    	}
    	AddMessage(SOQL);
        system.debug(SOQL);
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        batchableContext = BC;
        batchName = 'BatchRelease20Migration';
        System.Debug(SOQL);
        return Database.getQueryLocator(SOQL);
    }
    

    global void execute(Database.BatchableContext BC, List<r20mig__c> migList){
		if (isMigrationToPortal) {
			executeToPortal(migList, isStep2);
		} else if (isMigrationToPlatform) {
			executeToPlatform(migList, isStep2);
		}
    }
    
    global static void executeToPortal(List<r20mig__c> migList, boolean isMigrationToPortalStep2) {
    	AppLogModel.LogDebug('BatchRelease20Migration::executeToPortal', 'miglist has '+migList.size()+' record(s)');
    	Profile fprSubmitterPortalProfile = ProfileModel.AppearPortalFprOnlySubmitterProfile;
    	
    	for(r20mig__c m : migList) {
    		if (m.ToFprPortalUser__c == true) {
    			
    			if (m.fromContact__c <> null ) {
					if ( isMigrationToPortalStep2 == false) {
						//create FPR Portal User
						User portalUser = PortalUserModel.CreatePortalUser(m.fromContact__c, fprSubmitterPortalProfile);  
						MigratePubOwnershipUtil.migratePubAndJunctionOwnership(m.FromUser__c, portalUser.Id);
						AppLogModel.flushLogs();
					}
					if ( isMigrationToPortalStep2) {
						Rel20MigrationModel.DeactivateUser(m.FromUser__c);
					}
					
    			} else {
    				AppLogModel.LogError('BatchRelease20Migration::executeToPortal', 'from_contact__c == null');
    			}
			}
    	}	
    	
    }
    
    //BatchRelease20Migration.RunSingleStep1();
    global static void RunSingleStep1() {
    	List<r20mig__c> migList = Database.query(SOQL);
    	executeToPortal(migList, false);
    }

	//BatchRelease20Migration.RunSingleStep2();
    global static void RunSingleStep2() {
    	List<r20mig__c> migList = Database.query(SOQL);
    	executeToPortal(migList, true);
    }
        
    global static void executeToPlatform(List<r20mig__c> migList, boolean isStep2) {
    	for(r20mig__c m : migList) {
    		if ( m.ToFprPortalUser__c == false && m.isSelected__c && m.toContactFedId__c <> '0' && m.ToFederationId__c <> '' ) {
    			if ( !isStep2) {
	    			MigratePubOwnershipUtil.migratePubAndJunctionOwnership(m.FromUser__c, m.ToUser__c);
					ContactReplacementUtility.ReplaceContact(m.fromContact__c, m.toContact__c);
					Rel20MigrationModel.FlagContactForDelete(m.fromContact__c);
    			}
				if ( isStep2) {
					Rel20MigrationModel.DeactivateUser(m.FromUser__c);
				}
    		}
		} 
    }
    

    global void finish(Database.BatchableContext BC){
		SendBatchCompletionEmail();
	}
	
	//BatchRelease20Migration.runMigrationToPortalStep1(); 
	public static void runMigrationToPortalStep1(){
		boolean isMigrationToPortal = true;
		boolean isStep2 = false;
		boolean isMigrationToPlatform = false;
		 
    	BatchRelease20Migration batch = new BatchRelease20Migration(isMigrationToPortal, isStep2, isMigrationToPlatform);
        Database.executeBatch(batch, 1);
	}
 
 	//BatchRelease20Migration.runMigrationToPortalStep2(); 
	public static void runMigrationToPortalStep2(){
		boolean isMigrationToPortal = true;
		boolean isStep2 = true;
		boolean isMigrationToPlatform = false;
		 
    	BatchRelease20Migration batch = new BatchRelease20Migration(isMigrationToPortal, isStep2, isMigrationToPlatform);
        Database.executeBatch(batch, 1);
	}
 
	//BatchRelease20Migration.runMigrationToPlatformStep1();
	public static void runMigrationToPlatformStep1(){
		boolean isMigrationToPortal = false;
		boolean isMigrationToPlatform = true;
		boolean isStep2 = false;
		
    	BatchRelease20Migration batch = new BatchRelease20Migration(isMigrationToPortal, isStep2, isMigrationToPlatform);
        Database.executeBatch(batch, 1);
	}

	//BatchRelease20Migration.runMigrationToPlatformStep2();
	public static void runMigrationToPlatformStep2(){
		boolean isMigrationToPortal = false;
		boolean isMigrationToPlatform = true;
		boolean isStep2 = true;
		
    	BatchRelease20Migration batch = new BatchRelease20Migration(isMigrationToPortal, isStep2, isMigrationToPlatform);
        Database.executeBatch(batch, 1);
	}

//////////////////////////////////////////  unit test /////////////////////////////////////
	
	private static testMethod void unitTest() {
		CreateData();
		
		BatchRelease20Migration.runMigrationToPortalStep1();
	}   
	
	public static void CreateData() {
		
	}
}