force-app/main/default/staticresources/python/Disappear/src/objects/Status__c.object
<CustomObject>
    <fields>
        <fullName>Stage__c</fullName>
        <description>Stage of a publication - 
Each status belongs to a stage
the stage will decide which chevron get highlighted.</description>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Suggest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Execute</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FPR Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>displayOrder__c</fullName>
        <description>display order</description>
        <label>displayOrder</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Status</label>
    <nameField>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Statuses</pluralLabel>
    <recordTypes>
        <fullName>AutoInsert</fullName>
        <active>true</active>
        <label>AutoInsert</label>
    </recordTypes>
    <recordTypes>
        <fullName>Department_Status</fullName>
        <active>true</active>
        <label>Department Status</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/AppearDataScriptController.cls
public class AppearDataScriptController {
	
	public string dataScriptValues { get; private set; }
	
	RecordType departmentStatusRecType = RecordTypeModel.LookupRecordType('Status__c','Department_Status');
	RecordType globalStatusRecType = RecordTypeModel.LookupRecordType('Status__c','Global Status');
	RecordType autoInsertRecType = RecordTypeModel.LookupRecordType('Status__c','AutoInsert');
	
	public void StatusDataScript() {
		string result = '';
		for( Status__c status : StatusModel.StatusList) {
			result = result + genStatus(status) + '<br/>';
		}
		
		dataScriptValues = result;
	}
	
	private string genStatus(Status__c status){
		string result = 'statusList.add( new status__c(' +
			'name= \''+status.Name+'\', '+
			'displayOrder__c='+status.displayOrder__c+', '+
			'Stage__c = \''+status.Stage__c+'\', ';
			
			
		if ( status.RecordTypeId == departmentStatusRecType.id ) {	
			result += 'RecordTypeId = departmentStatusRecType.id));';		
		} else if ( status.RecordTypeId == globalStatusRecType.id ) {	
			result += 'RecordTypeId = globalStatusRecType.id));';	
		} else if ( status.RecordTypeId == autoInsertRecType.id ) {	
			result += 'RecordTypeId = autoInsertRecType.id));';	
		}
		
		return result;
	}

}