force-app/main/default/staticresources/python/Disappear/src/objects/Study__c.object
<CustomObject>
    <fields>
        <fullName>Acronym__c</fullName>
        <label>Acronym</label>
        <length>300</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Amgen_Ind__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Amgen Indicator</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Investigator__c</fullName>
        <label>Investigator</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsLogicallyDeleted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Expired</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Latest_Study_status__c</fullName>
        <label>Latest Study/Project Status</label>
        <picklist>
            <picklistValues>
                <fullName>Accrued</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSR Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proposed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>NCT__c</fullName>
        <label>NCT#</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>N__c</fullName>
        <description>Number of subjects</description>
        <inlineHelpText>Number of subjects</inlineHelpText>
        <label>N</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PASS__c</fullName>
        <defaultValue>false</defaultValue>
        <description>PASS field/flag for tracking.</description>
        <label>PASS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Posted_on_ClinTrials__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Posted on Clinical Trials</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project_Sponsor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Department that sponsor this Project</description>
        <label>Project Sponsor</label>
        <referenceTo>Department__c</referenceTo>
        <relationshipName>Studies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Published_Date__c</fullName>
        <label>Published Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SiebelRowId__c</fullName>
        <externalId>true</externalId>
        <label>SiebelRowId</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StudySponsor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sponsor Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Studies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Study_Phase__c</fullName>
        <label>Study/Project Phase</label>
        <picklist>
            <picklistValues>
                <fullName>Investigator Initiated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phase 0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phase 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phase 1a</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phase 1b</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phase 1b/2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phase 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phase 2/3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phase 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phase 3b</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phase 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PreClinical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phase 1/2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Study_TA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Study/Project TA</label>
        <referenceTo>TherapeuticArea__c</referenceTo>
        <relationshipLabel>Studies/Projects</relationshipLabel>
        <relationshipName>Studies</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Study_Type__c</fullName>
        <label>Study/Project Type</label>
        <picklist>
            <picklistValues>
                <fullName>Analysis of existing Data</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chart Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clinical Trial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cross-sectional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Epidemiology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Follow-up Study</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health Econ Study</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Vitro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MUE/DUE Study</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PK-PD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PreClinical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registry Study</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registry/Observational</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <type>TextArea</type>
    </fields>
    <label>Study/Project</label>
    <nameField>
        <label>Study/Project #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Studies/Projects</pluralLabel>
    <recordTypes>
        <fullName>Project</fullName>
        <active>true</active>
        <label>Project</label>
    </recordTypes>
    <recordTypes>
        <fullName>Study</fullName>
        <active>true</active>
        <label>Study</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/StudyModel.cls
public class StudyModel {
    
    private static RecordType pStudyRecType = null;
    public static RecordType StudyRecType {
        get {
            if (pStudyRecType == null){
                pStudyRecType = RecordTypeModel.LookupRecordType('Study__c', 'Study');
                System.AssertNotEquals(null, pStudyRecType);
            }
            return pStudyRecType;
        }
    }

    private static RecordType pProjectRecType = null;
    public static RecordType ProjectRecType {
        get {
            if (pProjectRecType == null){
                pProjectRecType = RecordTypeModel.LookupRecordType('Study__c', 'Project');
                System.AssertNotEquals(null, pProjectRecType);
            }
            return pProjectRecType;
        }
    }


    private static Map<string, Study__c> pProjectMapByTitle = null;
    public static Map<string, Study__c> ProjectMapByTitle {
        get {
            if ( pProjectMapByTitle == null){
                pProjectMapByTitle = new Map<string, Study__c>();
                for(Study__c study : ProjectStudyList){
                    pProjectMapByTitle.put(study.title__c, study);
                }
            }
            return pProjectMapByTitle;
        }
    }
    
    private static List<Study__c> pProjectStudyList = null;
    public static List<Study__c> ProjectStudyList {
        get {
            if ( pProjectStudyList == null) {
                pProjectStudyList = getStudyByRecordType('Project');
            }
            return pProjectStudyList;
        }
    }


    private static Map<string, Study__c> pStudyMapByName = null;
    public static Map<string, Study__c> StudyMapByName {
        get {
            if ( pStudyMapByName == null){
                pStudyMapByName = new Map<string, Study__c>();
                for(Study__c study : StudyStudyList){
                    pStudyMapByName.put(study.name, study);
                }
            }
            return pStudyMapByName;
        }
    }    
    
    private static Map<string, Study__c> pStudyMapByTitle = null;
    public static Map<string, Study__c> StudyMapByTitle {
        get {
            if ( pStudyMapByTitle == null){
                pStudyMapByTitle = new Map<string, Study__c>();
                for(Study__c study : StudyStudyList){
                    pStudyMapByTitle.put(study.title__c, study);
                }
            }
            return pStudyMapByTitle;
        }
    }
    
    private static List<Study__c> pStudyStudyList = null;
    public static List<Study__c> StudyStudyList {
        get {
            if ( pStudyStudyList == null) {
                pStudyStudyList = getStudyByRecordType('Study');
            }
            return pStudyStudyList;
        }
    }

    
    public static List<Study__c> getStudyByRecordType(string recordTypeName) {
        RecordType recType = RecordTypeModel.LookupRecordType('Study__c', recordTypeName);
        if(recType == null){
            return new List<Study__c>();
        }
        
        List<Study__c> study = [
              Select Id, Name, RecordTypeId, RecordType.Name, Acronym__c,
               Amgen_Ind__c, Description__c, Investigator__c, 
              Latest_Study_status__c, N__c, NCT__c,
              Posted_on_ClinTrials__c, Project_Sponsor__c,
              Published_Date__c, SiebelRowId__c, StudySponsor__c,
              Study_Phase__c, Study_TA__c, Study_Type__c, Title__c, isLogicallyDeleted__c
              From Study__c 
              where RecordTypeId = :recType.id
              and isLogicallyDeleted__c = false
              order by Name
        ];
        return study;
    }
    
    //
    
    public static Study__c findStudyById(string studyId){
        list<study__c> studies = [
            select id, Pass__c 
            from Study__c
            where id = :studyId
        ];
        if ( studies.size() == 1){
            return studies[0];
        } else {
            return null;
        }
    }
    

    
    
    ///////////////  JS Remote support //////////////////
    public static List<Study__c> findStudyByName(string startWith){
        
        string startWithParam = startWith + '%';
        
        List<Study__c> nameResults = [
            select id, name, Title__c
            From Study__c 
            where Name like :startWithParam 
            and RecordTypeId = :StudyRecType.id
            order by Name
            limit 25
        ];
        List<Study__c> titleResults = [
            select id, name, Title__c
            From Study__c 
            where Title__c like :startWithParam
            and RecordTypeId = :StudyRecType.id
            order by Title__c
            limit 25
        ];
        titleResults.addAll(nameResults);     
        return titleResults;   
    }
    
    public static List<Study__c> findProjectByName(string startWith){
        
        string startWithParam = startWith + '%';
        
        List<Study__c> nameResults = [
            select id, name, Title__c
            From Study__c 
            where Name like :startWithParam 
            and RecordTypeId = :ProjectRecType.id
            order by Name
            limit 25
        ];
        List<Study__c> titleResults = [
            select id, name, Title__c
            From Study__c 
            where Title__c like :startWithParam
            and RecordTypeId = :ProjectRecType.id
            order by Title__c
            limit 25
        ];
        titleResults.addAll(nameResults);     
        return titleResults;        
    }
}