force-app/main/default/staticresources/python/Disappear/src/objects/StudyNote__c.object
<CustomObject>
    <fields>
        <fullName>Note__c</fullName>
        <label>Note</label>
        <length>4095</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>StudyId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Study</label>
        <referenceTo>Study__c</referenceTo>
        <relationshipName>StudyNotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Study/Project Note</label>
    <nameField>
        <label>StudyNote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Study/Project Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/staticresources/python/Disappear/src/classes/StudyNoteModel.cls
public class StudyNoteModel {
  
   private static Map<string,StudyNote__c> pStudyNoteMap = null;
   public static Map<string,StudyNote__c> StudyNoteMap {
    get {
      if ( pStudyNoteMap == null) {
        pStudyNoteMap = new Map<string,StudyNote__c>();
        for(StudyNote__c studyNote : StudyNoteList ) {
          pStudyNoteMap.put(studyNote.name, studyNote);
        }
      }
      return pStudyNoteMap;
    }
   }
    private static List<StudyNote__c> pStudyNoteList = null;
    public static List<StudyNote__c> StudyNoteList {
        get {
            if ( pStudyNoteList == null) {
                pStudyNoteList = getAllStudyNotes();
            }
            return pStudyNoteList;
        }
    }
    
    public static List<StudyNote__c> getAllStudyNotes() {
         List<StudyNote__c> studyNote= [
      Select Id, Name, StudyId__c, Note__c
      From StudyNote__c 
      order by Name
    ];
    return studyNote;
    
    }
 
}